### ISSUE TITLE
Online library does not showing anything on API level 24, and showing (Trust anchor for certification path not found) error.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3772] opened 2024-03-29 09:55 UTC
**Describe the bug**
OnlineLibrary does not show any content in API level 24 from yesterday(28 March 2024). before yesterday it was showing the online content at this API level. Due to this, our test cases are also failing on CI. Above the API level 24 the online content is showing properly.

**Expected behavior**
It should show the online content on this API level as well.

**Steps to reproduce the behavior:**
1. Run the application on API level 24(Android 7) device or emualtor.
2. Go to the `Download` screen. You will see the error.

**Screenshots**
![Screenshot from 2024-03-29 15-13-20](https://github.com/kiwix/kiwix-android/assets/34593983/00b53b78-5a58-47da-9336-4c7833722cf9)

**Environment**
- Version of Kiwix Android: 3.9.1
- Device: Emulator and CI.
- OS version: Android 7(API level 24)

**Logs**
```kotlin
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2024-03-29 15:09:05.165 14937-15016 System.err              pid-14937                            W  	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:361)
2024-03-29 15:09:05.165 14937-15016 System.err              pid-14937                            W  	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
2024-03-29 15:09:05.165 14937-15016 System.err              pid-14937                            W  	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
2024-03-29 15:09:05.165 14937-15016 System.err              pid-14937                            W  	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
2024-03-29 15:09:05.165 14937-15016 System.err              pid-14937                            W  	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
2024-03-29 15:09:05.165 14937-15016 System.err              pid-14937                            W  	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
2024-03-29 15:09:05.165 14937-15016 System.err              pid-14937                            W  	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
2024-03-29 15:09:05.165 14937-15016 System.err              pid-14937                            W  	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
2024-03-29 15:09:05.165 14937-15016 System.err              pid-14937                            W  	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
2024-03-29 15:09:05.165 14937-15016 System.err              pid-14937                            W  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-03-29 15:09:05.165 14937-15016 System.err              pid-14937                            W  	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
2024-03-29 15:09:05.165 14937-15016 System.err              pid-14937                            W  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-03-29 15:09:05.165 14937-15016 System.err              pid-14937                            W  	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
2024-03-29 15:09:05.165 14937-15016 System.err              pid-14937                            W  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-03-29 15:09:05.165 14937-15016 System.err              pid-14937                            W  	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:46)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at io.reactivex.Observable.subscribe(Observable.java:12284)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at io.reactivex.Observable.subscribe(Observable.java:12284)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at java.lang.Thread.run(Thread.java:761)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:549)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:508)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:401)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:375)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:304)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:178)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:596)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	... 31 more
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
2024-03-29 15:09:05.166 14937-15016 System.err              pid-14937                            W  	... 42 more
```

**Comment by MohitMaliFtechiz** [comment] 2024-03-29 10:51
It is an SSL issue, probably we have changed the SSL or the current SSL is expired. Since it is working with `http` but giving an error with `https`. @kelson42 Do you confirm?

![Screenshot from 2024-03-29 15-57-55](https://github.com/kiwix/kiwix-android/assets/34593983/c8417d6f-b1b8-4874-8732-2be53fbfa997)

![Screenshot from 2024-03-29 16-20-13](https://github.com/kiwix/kiwix-android/assets/34593983/52c893d9-c4c8-446d-a85d-ab3c0c067eae)

**Comment by kelson42** [comment] 2024-03-29 16:22
SSL is OK https://www.ssllabs.com/ssltest/analyze.html?d=mirror.download.kiwix.org so the question is why it is not OK for this device?

**Comment by kelson42** [comment] 2024-03-29 16:32
Actually SSL server confog is maybe not OK, see https://github.com/kiwix/k8s/issues/175

**Comment by rgaudin** [comment] 2024-04-02 09:58
I can reproduce, indeed, on API 24 only

```
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
    at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:361)
    at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
    at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
    at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
    at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
    at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
    at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
    at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
    at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
    at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
    at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:46)
    at io.reactivex.Observable.subscribe(Observable.java:12284)
    at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
    at io.reactivex.Observable.subscribe(Observable.java:12284)
    at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
    at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
    at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
    at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:761)
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
    at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:549)
    at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:508)
    at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:401)
    at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:375)
    at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:304)
    at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
    at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
    at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:178)
    at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:596)
    at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
    at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
    ... 31 more
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
    ... 42 more

```

According to [doc](https://developer.android.com/privacy-and-security/security-ssl#CommonProblems)

> This can happen for several reasons, including:
> 
>     The CA that issued the server certificate was unknown.
>     The server certificate wasn't signed by a CA, but was self signed.
>     The server configuration is missing an intermediate CA.

## Missing intermediate CA

This doesn't seem to be the case. We can see that there's an intermediate cert from Let's Encrypt and that it is properly included. Root CA is `ISRG Root X1`

```
❯ openssl s_client -connect mirror.download.kiwix.org:443 -showcerts
Connecting to 51.159.108.60
CONNECTED(00000005)
depth=2 C=US, O=Internet Security Research Group, CN=ISRG Root X1
verify return:1
depth=1 C=US, O=Let's Encrypt, CN=R3
verify return:1
depth=0 CN=mirror.download.kiwix.org
verify return:1
---
Certificate chain
 0 s:CN=mirror.download.kiwix.org
   i:C=US, O=Let's Encrypt, CN=R3
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Mar 26 20:05:05 2024 GMT; NotAfter: Jun 24 20:05:04 2024 GMT
-----BEGIN CERTIFICATE-----
MIIE/jCCA+agAwIBAgISBAdt/zoNMlP6qJH613l30NuzMA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yNDAzMjYyMDA1MDVaFw0yNDA2MjQyMDA1MDRaMCQxIjAgBgNVBAMT
GW1pcnJvci5kb3dubG9hZC5raXdpeC5vcmcwggEiMA0GCSqGSIb3DQEBAQUAA4IB
DwAwggEKAoIBAQC/iSzNshZk4w/i9SPu4ZD87adajQYgaOG5lXkO/gfXHRP13fa/
1FALHVaAwH0935yMo0R8KRtWGS3PxNgjFr0ru+QkRVUyWzNfZUcVDcmgVtNLIxnF
osJhGVe/rwmTqNFRyzstsgk1toUEiezwhJPV+00hSGlLLru5W3wgQivPoVGJgqOO
SFFiBvquMQULp15IGjTMRlFW5U3pupyuJh47VPf/CKu9t9r/0hTTqN/GbdEWL0GV
oZrNjyU30WyhZKQoXZjQ1IOdGAh3diLGF45ahsWNm4MzchgRlo+bCilRVuTVvByX
YI85ja8PnpRGLJXiPB5UAUScOkjPOk76g5oxAgMBAAGjggIaMIICFjAOBgNVHQ8B
Af8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB
/wQCMAAwHQYDVR0OBBYEFFTASGD4/8//mHIXQCjuRAZu0TouMB8GA1UdIwQYMBaA
FBQusxe3WFbLrlAJQOYfr52LFMLGMFUGCCsGAQUFBwEBBEkwRzAhBggrBgEFBQcw
AYYVaHR0cDovL3IzLm8ubGVuY3Iub3JnMCIGCCsGAQUFBzAChhZodHRwOi8vcjMu
aS5sZW5jci5vcmcvMCQGA1UdEQQdMBuCGW1pcnJvci5kb3dubG9hZC5raXdpeC5v
cmcwEwYDVR0gBAwwCjAIBgZngQwBAgEwggEDBgorBgEEAdZ5AgQCBIH0BIHxAO8A
dgDuzdBk1dsazsVct520zROiModGfLzs3sNRSFlGcR+1mwAAAY58lLqDAAAEAwBH
MEUCIAv+UeVZnUSeh31hQkMcOy1iULPk/rrOr9T7rdFCWoh9AiEAgi8arXOBKTT8
ZvAWJylj4cfA2Q3Yd9qY9f0/L0tEURsAdQCi4r/WHt4vLweg1k5tN6fcZUOwxrUu
otq3iviabfUX2AAAAY58lLr8AAAEAwBGMEQCIA1j4bvIuG2GjRxzNDB85XAntWSK
swPASJp6rw6O5a/0AiAakLieE1Rr2rv5L2N+HRrKasUSw9u97pTnDZZm1gqqZzAN
BgkqhkiG9w0BAQsFAAOCAQEActlrwvd+nplYkAHv04VSzUXyiqvJJv9ln9pJZen0
SKS+3cX7z7/FBE4v01n2Yg8aI+HP2g5aGT9rKdcKJ3KwkSmFEUeqi2xaIztzltV/
CuQTtX/g9ei0d8BbWMtctVXfN4UfA1ZCNmad7h77FG+nKKjCTbOptZ8dTuy4E8Fi
v2VdAb1s8eSA5dthtG5Wjp5AHPi3aCFwfnBhMUH6P7TApT4MfHrVSealMBXB8JUv
zRzCTQmPd7LCft8JnKJPj4yPl4ONXmipCnp/L2MHuboXc2ImFaBDdd11STBYtQyF
nzcXL5Uu8wba9qjjMqDn25WgP2jsOkG4alLsHoiDl607kQ==
-----END CERTIFICATE-----
 1 s:C=US, O=Let's Encrypt, CN=R3
   i:C=US, O=Internet Security Research Group, CN=ISRG Root X1
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Sep  4 00:00:00 2020 GMT; NotAfter: Sep 15 16:00:00 2025 GMT
-----BEGIN CERTIFICATE-----
MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
/kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
nLRbwHOoq7hHwg==
-----END CERTIFICATE-----
---
Server certificate
subject=CN=mirror.download.kiwix.org
issuer=C=US, O=Let's Encrypt, CN=R3
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3153 bytes and written 413 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
This TLS version forbids renegotiation.
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: E37F8495CF0684345DFFC01DD5FDBD38C69A5CDE765E1778AA32E71DFED15F59
    Session-ID-ctx:
    Resumption PSK: D21A7421D21B6145D7368F23E570ED238E28E387B4D9CF4FC6A8DDE590C4AB54A3C0AFCE4CFBE58FCAA455144A5260BF
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 600 (seconds)
    TLS session ticket:
    0000 - a2 09 94 cf 51 6b 4e 49-58 af 0c 4a 50 27 ca 52   ....QkNIX..JP'.R
    0010 - 9f 40 e7 f3 fe 96 9d 86-a2 b7 af e3 92 c1 d3 57   .@.............W

    Start Time: 1712049404
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: 1313203E69D6111B207BE4EA24686DE36DEFF7D7071F9ED5C5FC36D22BF5A89D
    Session-ID-ctx:
    Resumption PSK: 782869F7B080105363C68ACB2A4398D6DEA8B5D30DFBC0277E5EBC84B38C131DF05F94B84988A88747DA4FB4C9F4911A
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 600 (seconds)
    TLS session ticket:
    0000 - ee 90 7e 38 d0 4c 33 8d-58 ff 51 5e 50 04 36 c1   ..~8.L3.X.Q^P.6.
    0010 - 15 01 f9 ac cc a8 d3 97-ea 34 3a 29 76 15 2b 8a   .........4:)v.+.

    Start Time: 1712049404
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
closed
```

## The server certificate wasn't signed by a CA, but was self signed.

As visible in output above, no sign of self-signed certificate.

## The CA that issued the server certificate was unknown.

According to [Let's Encrypt](https://letsencrypt.org/docs/certificate-compatibility/), `ISRG Root X1` is trusted on `Android >= 7.1.1`. `7.1` [is API 25](https://apilevels.com/) while we're having the problem on API 24 only…

According to [this Let's Encrypt post](https://letsencrypt.org/2020/12/21/extending-android-compatibility), dated December 21st 2020 (its important):

> IdenTrust has agreed to issue a 3-year cross-sign for our ISRG Root X1 from their DST Root CA X3.

> **What happens when the new cross-sign expires?** This new cross-sign will expire in early 2024. Prior to that, perhaps as early as June 2021, we will be making a similar change to what we intended to make this January. When we make that change, subscribers will have the option to continue using DST Root CA X3 by configuring their ACME client to specifically request it. If you are a Let’s Encrypt subscriber who is already working to mitigate the chain switch (e.g. by configuring alternate chains or encouraging your users on old Android devices to install Firefox), continue that work so you’ll be well-positioned in the future.

So this is what happened: our previous cert was renewed just before the end of expiry so we got this far with the cross-signed CA but latest renewal meant we're on `ISG Root X1` now which is not supported by Android 7.

I need to dig a bit to understand whether and how we can request a cert that's still cross-signed by IdenTrust. [this](https://letsencrypt.org/certificates/) is not perfectly clear.

I'll come back to you.

**Comment by rgaudin** [comment] 2024-04-02 11:08
Now fixed for both `mirror.download.kiwix.org` and `download.kiwix.org` (referenced in `library_zim.xml`)

<img width="574" alt="Screenshot 2024-04-02 at 11 07 40" src="https://github.com/kiwix/kiwix-android/assets/57929/f6e61f21-2aa5-438d-a14f-814cbc2add57">

**Comment by MohitMaliFtechiz** [comment] 2024-04-02 11:18
@rgaudin Thanks for the fix, I confirm that the issue is resolved on API level 24.

**Comment by kelson42** [comment] 2024-04-02 15:31
This fix is not really substainable. What about tequestion API25 in 3.10.0?

**Comment by rgaudin** [comment] 2024-04-02 15:35
@kelson42 you should open a separate ticket. This issue is fixed.

**Comment by MohitMaliFtechiz** [comment] 2024-04-03 07:15
@kelson42, @rgaudin We can do this on the Android side as well for this specific API level, see the [okhttp issue](https://github.com/square/okhttp/issues/6403) and [this article](https://stackoverflow.com/questions/64844311/certpathvalidatorexception-connecting-to-a-lets-encrypt-host-on-android-m-or-ea).

**Comment by rgaudin** [comment] 2024-04-03 07:38
I don't care for this because we'll have different scenarios in-app and in-browser. So a user will not be able to download a ZIM from his browser but could from within the App.
Also, adding a specific CA in the app feels more like a hack than what we are doing now.

**Comment by MohitMaliFtechiz** [comment] 2024-04-03 08:47
Makes sense to me.

> What about tequestion API25 in 3.10.0?

@kelson42 Which question?

**Comment by MohitMaliFtechiz** [comment] 2024-04-04 06:03
@kelson42 If we upgrade our minimum SDK version to API level 25 then `2.0%` of [devices](https://www.composables.com/tools/distribution-chart) will stop getting updates.

![Screenshot from 2024-04-04 11-25-46](https://github.com/kiwix/kiwix-android/assets/34593983/3674642d-226c-4620-a8aa-a67e181807e2)

**Comment by kelson42** [comment] 2024-04-04 06:20
@MohitMaliFtechiz If there is no other consequence,I propose we do so in 3.11.0. Please open a dedicated ticket and I close this one.

**Closed** 2024-04-04 06:20 UTC
Labels: bug, question
