### ISSUE TITLE
Download keeps restarting

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#860] opened 2018-09-18 12:43 UTC
From OTRS

"I can't download Wikipedia (wikipedia_en_all_novid_2018-06) using Android Kiwix because it keeps restarting the download. So Kiwix will download say zimaa to zimad and a bit of zimae, then start again with zimaa.

I'm using a Samsung Galaxy 7 with Android 8.0.0 and the latest Kiwix, using WiFi only."

**Comment by MidUK** [comment] 2018-09-24 12:07
I have this problem as well.

I'm trying to make it reproducible but it's slow to test.

It might be caused by a change of wifi.

I left it downloading all night last night and it was fine this morning when I checked it. I drove to the office and then checked on the status (in the same way that I did when I woke up this morning) and then it restarted - the only change being the wifi.

It's a serious waste of bandwidth too as I've downloaded around 60GB since I started and I'm back to downloading the first 2GB chunk again (zimaa). Whichever server the data is coming from must be getting hammered.

This could be worked around by downloading in one session but there's no way for me to download 77GB overnight - I would need to do it over at least 2 days and I can't do that without changing wifi.

Might I make a recommendation of how this could be fixed?
When the download starts, can the app:

1) Check for a file of MD5 sums for each of the 2GB chunks. If it doesn't exist, download it.
2) Check local storage for each entry in the MD5 file. If that file exists, compare it's hash and if it's the same, move onto the next entry. In all other cases, download a fresh copy.

This will ensure that wastage will be quantised into 2GB chunks rather than (potentially) 77GB.

Also, why isn't there a location where the 2GB chunks can be dowloaded? I appreciate you can download the full 77GB file and split it yourself but if you have any corruption, you need to download the entire file again. Also, not everyone will have the confidence to split the file themselves.

I'm on a Samsung S9+ with stock Android 8.0.0

**Comment by kelson42** [comment] 2018-09-30 14:41
@MidUK Plan is to secure download using metalink... but we are not so far on Android... but this has nothing to do with your problem of "restart". Please wait 2.5 release and let us know.

**Comment by macgills** [comment] 2019-05-27 10:50
Fixed in #1170

**Closed by macgills** 2019-05-27 10:50 UTC
Labels: bug
