### ISSUE TITLE
Language Section Enhancement

### ISSUE THREAD

**Issue by savannahar68** [kiwix/kiwix-android#549] opened 2018-03-02 10:18 UTC
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request

### Step 1: Are you ready to report?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - [x] I have tested with the last (dev) version of the software.  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2: What is your environment?
  * version of the software you use : #__3.0.1__
  * device / operating system : __MotoG 5+/7.0___
  
### Step 3: Describe the problem:

  * What do you obtain? A copy of the error message or a screenshot is always useful.

  * When does this occur? 
  1- When we click on the globe to open the language section, there is no scroll bar(fastscroll) which can be touched and scrolled around the list,it is quite difficult without it as the list is long,this problem is everywhere where lists are used in the application
 2 - In night mode the language section checkbox to select language are almost invisible because of its color,we can change it to white color in night mode
#### Steps to reproduce:

  1. __In library click on Globe symbol(language section)___
  2. _ We cannot move through the list with help of scrollbar like in fastscroll___

  1. __Turn on the night mode___
  2. Go to the language Section[same steps as above] the check box are not that visible becuase of its color
  
  * What should be the behaviour from your point of view? How do you expect the service to work?
FastScroll should be enabled wherever listviews are used 
and the color of checkbox should be changed in night mode

### Step 4 (optional) : Other Comments:
  * What is the context of this ticket? If not obvious, explain why you need to do this.
 
  * If you have an idea about the technical background of the ticket, please share it.
  
  
![whatsapp image 2018-03-02 at 3 44 53 pm](https://user-images.githubusercontent.com/20986069/36894313-f0a5d560-1e30-11e8-81b8-1d21c6ec1bd4.jpeg)
![whatsapp image 2018-03-02 at 3 45 16 pm](https://user-images.githubusercontent.com/20986069/36894319-f21ba08c-1e30-11e8-8433-78afcd30a3e2.jpeg)

#### Feature Description

Please describe the feature you want to add to the project.

I would like to work on it,Ill add the scroller on all the list views and change the color of the checkbox

**Comment by RajaVamsi11** [comment] 2018-03-02 14:35
@savannahar68 The feature request is good to add.
what do you say @srv-twry @abdulwd @brijeshshah13

**Comment by srv-twry** [comment] 2018-03-02 14:38
@savannahar68 LGTM.

**Comment by srv-twry** [comment] 2018-03-02 14:44
@savannahar68 Please don't call me sir :smile: 
I would wait for @mhutti1 to suggest what to do in this issue and also in the RecyclerView issue. I created that issue and the plan if accepted would be to change all the ListViews to RecyclerView or atleast the performance intensive ones. If we indeed decide to change to RecyclerView then it would be better to hold this one up.

**Comment by mhutti1** [comment] 2018-03-02 23:47
I don't believe fastbar is needed at the moment and we have another issue open looking into that. As for nightmode you have created another issue so closing as duplicate of #552.

**Closed by mhutti1** 2018-03-02 23:47 UTC
Labels: enhancement, good first issue
