### ISSUE TITLE
Error: "Loading article failed"

### ISSUE THREAD

**Issue by RaiLokesh** [kiwix/kiwix-android#2595] opened 2021-02-14 03:50 UTC
Describe the bug:
Error saying "Loading article failed" when we try to go to the Reader Section after opening the book from Library.

Expected behavior:
The last opened book should open.

    1. Open the Kiwix android app
    2. Open a book from Library
    3. Switch to the Reader section
    4. See the error 
    

https://user-images.githubusercontent.com/70928573/107867955-b6c5af00-6ea5-11eb-818f-ceb58b39d87a.MP4

Environment
- Version of Kiwix Android : 3.4.3
- Device : MI
- OS version : Android 8.1.0

**Comment by kelson42** [comment] 2021-02-14 07:02
@RaiLokesh This happens with all contents? You are basically unable to use Kiwix?

**Comment by RaiLokesh** [comment] 2021-02-14 07:38
@kelson42 I experienced this with other books too. We can read books from the library but when we switch to the "Reader" section, it fails to load the article.
However, if we close the app and reopen from the background, it works fine.

**Comment by kelson42** [comment] 2021-02-14 08:58
@RaiLokesh So it always happen after a cold start? Or it just happens sporadicaly?

**Comment by RaiLokesh** [comment] 2021-02-14 10:58
@kelson42 it always happens after a cold start.

**Comment by Pawanupadhyay10** [comment] 2021-03-29 05:01
hello, can you assign me this issue and also guide me from where to start .

**Comment by kelson42** [comment] 2021-03-29 05:31
@Pawanupadhyay10 what is the root cause of the problem and how do you plan to fix it?

**Comment by kelson42** [comment] 2022-08-26 05:02
@MohitMaliFtechiz Transfering the ticket to you

**Comment by MohitMaliFtechiz** [comment] 2022-10-03 12:10
> @MohitMaliFtechiz Transfering the ticket to you

hi @kelson42 ,

Unable to reproduce the error, i think this is already fixed.
  * Version of Kiwix Android : 3.6.0
  * Device : MI Redmi Note 9
  * OS version : Android 11

**Comment by kelson42** [comment] 2022-10-03 12:13
@RaiLokesh We beliwve this bug is fixed in kiwix for android 3.6.0. Please tey with it or a nigthlt https://download.kiwix.org/nightly/. If you still have a problem, please reopen this ticket.

**Closed by kelson42** 2022-10-03 12:13 UTC
Labels: bug, question
