### ISSUE TITLE
Night mode cause some pictures to fail to display in wikipedia all maxi ZIM package

### ISSUE THREAD

**Issue by remyroy** [kiwix/kiwix-android#2380] opened 2020-09-17 14:16 UTC
I downloaded the wikipedia_en_all_maxi_2020-08.zim ZIM package for use with my Android phone with Kiwix from https://wiki.kiwix.org/wiki/Content_in_all_languages . I browsed some articles. I noticed that some pages are missing pictures.

Take the [Morse Code](https://en.wikipedia.org/wiki/Morse_code) page for instance.

Here is how it looks on my phone:

![Screenshot_20200917-085947_Kiwix](https://user-images.githubusercontent.com/303593/93482068-48b49600-f8cd-11ea-9618-7c059a759a20.png)

It is missing the main picture that shows the *Chart of the Morse code* which in this case can be quite important to the whole article.

Here is the diagnostic details:

```
Hi Kiwix Developers,
I am having an issue with the app and would like you to check these details
Curent Zim File:
/storage/9C33-6BBD/Download/wikipedia_en_all_maxi_2020-08.zim

All Zim Files in DB:
Wikipedia:
Articles: [6140943]
Creator: [Wikipedia]


Current Locale:
en_CA

Device Details:
Device:[crownqltecs]
Model:[SM-N960W]
Manufacturer:[samsung]
Time:[1597027688000]
Android Version:[10]
App Version:[3.3.4 6230304]

Mount Points
MountInfo(device=/dev/block/dm-0, mountPoint=/, fileSystem=ext4)
MountInfo(device=tmpfs, mountPoint=/dev, fileSystem=tmpfs)
MountInfo(device=devpts, mountPoint=/dev/pts, fileSystem=devpts)
MountInfo(device=none, mountPoint=/dev/cg2_bpf, fileSystem=cgroup2)
MountInfo(device=none, mountPoint=/dev/cpuctl, fileSystem=cgroup)
MountInfo(device=none, mountPoint=/dev/cpuset, fileSystem=cgroup)
MountInfo(device=none, mountPoint=/dev/memcg, fileSystem=cgroup)
MountInfo(device=none, mountPoint=/dev/stune, fileSystem=cgroup)
MountInfo(device=none, mountPoint=/dev/freezer, fileSystem=cgroup)
MountInfo(device=adb, mountPoint=/dev/usb-ffs/adb, fileSystem=functionfs)
MountInfo(device=proc, mountPoint=/proc, fileSystem=proc)
MountInfo(device=sysfs, mountPoint=/sys, fileSystem=sysfs)
MountInfo(device=selinuxfs, mountPoint=/sys/fs/selinux, fileSystem=selinuxfs)
MountInfo(device=debugfs, mountPoint=/sys/kernel/debug, fileSystem=debugfs)
MountInfo(device=tracefs, mountPoint=/sys/kernel/debug/tracing, fileSystem=tracefs)
MountInfo(device=bpf, mountPoint=/sys/fs/bpf, fileSystem=bpf)
MountInfo(device=pstore, mountPoint=/sys/fs/pstore, fileSystem=pstore)
MountInfo(device=tmpfs, mountPoint=/mnt, fileSystem=tmpfs)
MountInfo(device=tmpfs, mountPoint=/mnt/sde, fileSystem=tmpfs)
MountInfo(device=/dev/block/bootdevice/by-name/persist, mountPoint=/mnt/vendor/persist, fileSystem=ext4)
MountInfo(device=/dev/block/bootdevice/by-name/efs, mountPoint=/mnt/vendor/efs, fileSystem=ext4)
MountInfo(device=/dev/block/bootdevice/by-name/dqmdbg, mountPoint=/mnt/vendor/dqmdbg, fileSystem=ext4)
MountInfo(device=/data/knox/sdcard/150, mountPoint=/mnt/knox/default/emulated/150, fileSystem=sdcardfs)
MountInfo(device=/data/knox/sdcard/150, mountPoint=/mnt/knox/read/emulated/150, fileSystem=sdcardfs)
MountInfo(device=/data/knox/sdcard/150, mountPoint=/mnt/knox/write/emulated/150, fileSystem=sdcardfs)
MountInfo(device=/data/knox/sdcard/150, mountPoint=/mnt/knox/full/emulated/150, fileSystem=sdcardfs)
MountInfo(device=/data/knox/secure_fs/enc_media, mountPoint=/mnt/shell/enc_emulated, fileSystem=sdcardfs)
MountInfo(device=/data/media, mountPoint=/mnt/runtime/default/emulated, fileSystem=sdcardfs)
MountInfo(device=/data/media, mountPoint=/mnt/runtime/read/emulated, fileSystem=sdcardfs)
MountInfo(device=/data/media, mountPoint=/mnt/runtime/write/emulated, fileSystem=sdcardfs)
MountInfo(device=/data/media, mountPoint=/mnt/runtime/full/emulated, fileSystem=sdcardfs)
MountInfo(device=tmpfs, mountPoint=/apex, fileSystem=tmpfs)
MountInfo(device=/dev/block/dm-0, mountPoint=/apex/com.android.runtime@1, fileSystem=ext4)
MountInfo(device=/dev/block/dm-0, mountPoint=/apex/com.android.runtime, fileSystem=ext4)
MountInfo(device=/dev/block/dm-0, mountPoint=/apex/com.android.tzdata@290000000, fileSystem=ext4)
MountInfo(device=/dev/block/dm-0, mountPoint=/apex/com.android.tzdata, fileSystem=ext4)
MountInfo(device=/dev/block/dm-0, mountPoint=/apex/com.android.conscrypt@290000000, fileSystem=ext4)
MountInfo(device=/dev/block/dm-0, mountPoint=/apex/com.android.conscrypt, fileSystem=ext4)
MountInfo(device=/dev/block/dm-0, mountPoint=/apex/com.android.media.swcodec@290000000, fileSystem=ext4)
MountInfo(device=/dev/block/dm-0, mountPoint=/apex/com.android.media.swcodec, fileSystem=ext4)
MountInfo(device=/dev/block/dm-0, mountPoint=/apex/com.android.media@290000000, fileSystem=ext4)
MountInfo(device=/dev/block/dm-0, mountPoint=/apex/com.android.media, fileSystem=ext4)
MountInfo(device=/dev/block/dm-0, mountPoint=/apex/com.android.resolv@290000000, fileSystem=ext4)
MountInfo(device=/dev/block/dm-0, mountPoint=/apex/com.android.resolv, fileSystem=ext4)
MountInfo(device=/dev/block/dm-1, mountPoint=/odm, fileSystem=ext4)
MountInfo(device=/dev/block/dm-2, mountPoint=/vendor, fileSystem=ext4)
MountInfo(device=/dev/block/bootdevice/by-name/apnhlos, mountPoint=/vendor/firmware_mnt, fileSystem=vfat)
MountInfo(device=/dev/block/bootdevice/by-name/modem, mountPoint=/vendor/firmware-modem, fileSystem=vfat)
MountInfo(device=/dev/block/bootdevice/by-name/dsp, mountPoint=/vendor/dsp, fileSystem=ext4)
MountInfo(device=none, mountPoint=/acct, fileSystem=cgroup)
MountInfo(device=none, mountPoint=/config, fileSystem=configfs)
MountInfo(device=/dev/block/bootdevice/by-name/cache, mountPoint=/cache, fileSystem=ext4)
MountInfo(device=/dev/block/bootdevice/by-name/carrier, mountPoint=/carrier, fileSystem=ext4)
MountInfo(device=/dev/block/bootdevice/by-name/efs, mountPoint=/efs, fileSystem=ext4)
MountInfo(device=/dev/block/bootdevice/by-name/dqmdbg, mountPoint=/dqmdbg, fileSystem=ext4)
MountInfo(device=/dev/block/bootdevice/by-name/omr, mountPoint=/omr, fileSystem=ext4)
MountInfo(device=/dev/block/dm-3, mountPoint=/data, fileSystem=ext4)
MountInfo(device=/data/knox/data_de/150, mountPoint=/data/user_de/150, fileSystem=ecryptfs)
MountInfo(device=/data/knox/misc_de/150, mountPoint=/data/misc_de/150, fileSystem=ecryptfs)
MountInfo(device=/data/knox/system_de/150, mountPoint=/data/system_de/150, fileSystem=ecryptfs)
MountInfo(device=/data/knox/data/150, mountPoint=/data/user/150, fileSystem=ecryptfs)
MountInfo(device=/data/knox/sdcard/150, mountPoint=/data/knox/sdcard/150, fileSystem=ecryptfs)
MountInfo(device=/data/knox/misc_ce/150, mountPoint=/data/misc_ce/150, fileSystem=ecryptfs)
MountInfo(device=/data/knox/system_ce/150, mountPoint=/data/system_ce/150, fileSystem=ecryptfs)
MountInfo(device=/data/knox/secure_fs/enc_user, mountPoint=/data/enc_user, fileSystem=ecryptfs)
MountInfo(device=/data/knox/secure_fs/enc_media, mountPoint=/data/knox/secure_fs/enc_media, fileSystem=ecryptfs)
MountInfo(device=tmpfs, mountPoint=/storage, fileSystem=tmpfs)
MountInfo(device=/data/media, mountPoint=/storage/emulated, fileSystem=sdcardfs)
MountInfo(device=/data/knox/sdcard/150, mountPoint=/storage/emulated/150, fileSystem=sdcardfs)
MountInfo(device=tmpfs, mountPoint=/storage/self, fileSystem=tmpfs)
MountInfo(device=/dev/block/vold/public:179,1, mountPoint=/mnt/media_rw/9C33-6BBD, fileSystem=sdfat)
MountInfo(device=/dev/block/vold/public:179,1, mountPoint=/mnt/secure/asec, fileSystem=sdfat)
MountInfo(device=/mnt/media_rw/9C33-6BBD, mountPoint=/mnt/runtime/default/9C33-6BBD, fileSystem=sdcardfs)
MountInfo(device=/mnt/media_rw/9C33-6BBD, mountPoint=/storage/9C33-6BBD, fileSystem=sdcardfs)
MountInfo(device=/mnt/media_rw/9C33-6BBD, mountPoint=/mnt/runtime/read/9C33-6BBD, fileSystem=sdcardfs)
MountInfo(device=/mnt/media_rw/9C33-6BBD, mountPoint=/mnt/runtime/write/9C33-6BBD, fileSystem=sdcardfs)
MountInfo(device=/mnt/media_rw/9C33-6BBD, mountPoint=/mnt/runtime/full/9C33-6BBD, fileSystem=sdcardfs)

External Directories
/storage/emulated/0/Android/data/org.kiwix.kiwixmobile/files
/storage/9C33-6BBD/Android/data/org.kiwix.kiwixmobile/files
```

**Comment by remyroy** [comment] 2020-09-17 14:48
If the picture is in the ZIM package, I'm wondering why it does not show when I browse this article.

**Comment by remyroy** [comment] 2020-09-17 19:10
It feels like the rendering of the article might be wrong on the Kiwix app on Android even if the picture is in the ZIM package

**Comment by macgills** [comment] 2020-09-18 08:23
@remyroy Have you tried this not in night mode? We have an open ticket about adding backgrounds to all images so they will have a contrast that will be visible in night mode

**Comment by remyroy** [comment] 2020-09-18 10:07
Night mode seems to be what cause this issue. By disabling night mode, I
can see the Morse Code chart in the Morse Code article and the other
missing pictures.

**Comment by kelson42** [comment] 2020-09-19 09:55
@remyroy @macgills Duplicate of https://github.com/openzim/mwoffliner/issues/1026 ?

**Comment by macgills** [comment] 2020-09-21 07:30
yup, closing. Thank you for the report

**Closed** 2020-09-28 11:51 UTC
Labels: bug, question
