### ISSUE TITLE
"Find in page" stopped working

### ISSUE THREAD

**Issue by binyominzeev** [kiwix/kiwix-android#1876] opened 2020-03-10 05:25 UTC
With the most recent update, I have no longer the option to find text inside an opened page. The button is grey, disabled, impossible to click on it (although it appears).

I tried this with two different ZIMs I am using, and both of them are producing the same behavior. Before the update, I was able to use them both, without any problems.

**Screenshots**
![Screenshot_2020-03-10-06-21-08](https://user-images.githubusercontent.com/4866177/76282240-758d4e00-6297-11ea-8344-39c1172c26c1.png)

**Environment**
- Version of Kiwix Android : 3.2.1, Build: 5230201
- Device : Samsung Galaxy Tab E SM-T560
- OS version : Android 4.4.4

**Comment by kelson42** [comment] 2020-03-10 06:07
@binyominzeev type your search pattern and the “find in page” should become a tive.

**Comment by macgills** [comment] 2020-04-02 10:16
@kelson42 do we want to make it so `Find in Page` is always enabled? Otherwise this is a `won't fix`

**Comment by kelson42** [comment] 2020-04-04 14:51
Seems to work as intended.

**Closed by kelson42** 2020-04-04 14:51 UTC
Labels: question
