### ISSUE TITLE
Enhancement: The current "Online" ZIM list always downloaded

### ISSUE THREAD

**Issue by Raghav-intrigue** [kiwix/kiwix-android#1144] opened 2019-04-03 14:23 UTC
**Checklist for requesting a feature:**
- Check the issue tracker. The feature you are requesting may have already been requested. [✓] 
- Check if the feature does not exists on the latest developers version. [✓] 

**Is your feature request related to a problem? Please describe.**
1. The "Online" ZIM list is always downloaded whenever the library activity is opened. 
2. The full list (instead of only a few buffered items) is downloaded every time.
Both these combined lead to a long wait time, high data usage and unnecessary server load.

**Describe the solution you'd like**
1. Instead of downloading the full list only the first 30-40 items are loaded, reducing the server load and the cutting down the loading time to a fraction.

**Describe alternatives you've considered**
1. A cached version of the list on the device can be used to populate the list while the differences are asynchronously updated in the background.

**Comment by kelson42** [comment] 2019-04-03 14:24
We have meanwhile an OPDS end-point https://wiki.kiwix.org/wiki/OPDS. This should be used instead of the XML file.

**Comment by mhutti1** [comment] 2019-04-03 18:48
Relates to #57

**Comment by Raghav-intrigue** [comment] 2019-04-03 19:17
I am referring to the download and update of this list.
![Screenshot_2019-04-02-00-42-43-10](https://user-images.githubusercontent.com/12858001/55506454-14b2ca00-5673-11e9-8240-3acf62b65da8.png)
 @mhutti1.
Not updates to the currently active ZIM file as mentioned in #57 .

**Comment by Raghav-intrigue** [comment] 2019-04-03 19:30
Although since the OPDS backend is ready (https://github.com/kiwix/kiwix-android/issues/57#issuecomment-396044823) we could implement it on the app.
Even considering a conservative amount of usage, downloading a 6mb file multiple times a session every other day amounts to quite a lot. 6mb * 2 * 366 / 2 = ~2gb.

**Comment by Raghav-intrigue** [comment] 2019-04-03 19:45
I was thinking, for this solution:
> Instead of downloading the full list only the first 30-40 items are loaded, reducing the server load and the cutting down the loading time to a fraction.
Since the library.xml file is essentially flat, we can just stream the XML file rather than downloading it fully. We can parse on the go and display the result. 
This can be performed using XmlPullParser (currently used), so no extra dependencies needed.

**Comment by sonusourav** [comment] 2019-04-04 03:06
Duplicate of #992 . Related to #683

**Comment by Raghav-intrigue** [comment] 2019-04-04 12:40
> 2. The full list (instead of only a few buffered items) is downloaded every time.
Both these combined lead to a long wait time, high data usage and unnecessary server load.

is a duplicate of #683 
> 1. The "Online" ZIM list is always downloaded whenever the library activity is opened.

is new, as far as I know.

I am not aware of the approach in this situation @kelson42 @mhutti1 .
I would like to be assigned to this.

For now, a caching system can be implemented very easily that would only download the library when the date at http://download.kiwix.org/library/library.xml is newer than the currently downloaded version.
As for implimenting the pagination we can implement OPDS or stream the XML file depending upon preferenece.

**Comment by kelson42** [comment] 2019-06-16 16:37
I would not invest any more energy on this as using our OPDS backend in place of the `library.xml` will solve the problem.

**Closed** 2019-06-17 05:03 UTC
