### ISSUE TITLE
Update the readme.

### ISSUE THREAD

**Issue by yashk2000** [kiwix/kiwix-android#1803] opened 2020-02-24 12:38 UTC
**Describe the bug**

The section in the readme which specifies that the project must be imported should be highlighted for better visibility.

**Addition Context**

I would like to work on this.

**Comment by kelson42** [comment] 2020-02-24 12:43
Basically a duplicate of #1794

**Comment by yashk2000** [comment] 2020-02-24 12:44
@kelson42, I was told to open a separate ticket for this issue by @macgills

**Closed by kelson42** 2020-02-24 12:43 UTC
