### ISSUE TITLE
My status bar turns white when i open the kiwix app in my mobile

### ISSUE THREAD

**Issue by Nair18** [kiwix/kiwix-android#451] opened 2018-02-18 06:58 UTC
**Is it a ?**

-  Bug Report

### Step 1: Are you ready to report ?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - [ ] I have test with the last (dev) version of the software?  ( If not, and if possible, run your test again with the most recent version available.)

  
### Step 3: Describe the problem:

  * What do you obtain? A copy of the error message or a screenshot is always useful
     

![](https://media.giphy.com/media/X7hOUCIOwqpA88iHyq/giphy.gif)

  * When does this occur? 
      It occurs when I open the app in  my mobile.

  * What should be the behaviour from your point of view? How do you expect the service to work?
    The status bar shouldnt change its colour

**Comment by kelson42** [comment] 2018-02-18 08:03
@Nair18 Would you be able to fix it? It works for me, so I suspect a bug with your particular version of Android

**Comment by brijeshshah13** [comment] 2018-02-18 10:45
@Nair18 Coud please confirm the same by running in Android Emulator for the same Android Version?

**Comment by siddharth2010** [comment] 2018-02-18 12:31
@Nair18 , @kelson42 , I guess the problem is with the Xiaomi UI that your phone is using and not with the app. A similar set of issues are also there in the Samsung UI (#442 )

**Comment by brijeshshah13** [comment] 2018-02-18 15:22
@mhutti1 Please take a note of the same and suggest the steps that should be taken to deal with the issue.

**Comment by Nair18** [comment] 2018-02-18 19:40
In #432 the guy uses the same phone that I use, with same android version(4.4)

**Comment by mhutti1** [comment] 2018-02-18 23:35
If this is an issue on your phone then go ahead and try fix it but be careful not to mess up other versions.

**Comment by suyash0103** [comment] 2018-02-20 16:44
Has the issue been resolved? If not, can I try working on it?

**Comment by brijeshshah13** [comment] 2018-02-21 12:50
@suyash0103 Sure. Please go ahead and try to fix it.

**Comment by kelson42** [comment] 2019-08-24 10:50
@Nair18 @abdulwd @mhutti1 Do you think or can confirm that the problem is fixed in versions 2.5.3 or 3.0.0?

**Comment by mhutti1** [comment] 2019-08-26 22:28
I am not sure it is fixed. I would assume it might not be.

**Comment by macgills** [comment] 2019-09-05 14:31
Coloring the status bar is not supported pre 5.0. Any solution is a dirty hack eg requesting translucent status bar and making toolbar fit system windows. Also dirty hacks that don't work because I just tried that.
I am going to close and label as `won't fix`. If somebody who was able to reproduce champions this then more power to you

**Closed by macgills** 2019-09-05 14:31 UTC
Labels: bug
