### ISSUE TITLE
Multiple copies of same book are appearing in downloads section

### ISSUE THREAD

**Issue by utkarsh006** [kiwix/kiwix-android#3253] opened 2023-02-26 15:34 UTC
**Describe the bug**

https://user-images.githubusercontent.com/94545831/221420206-0cc261b0-6c70-4d9c-b6e2-1b9f24fac784.mp4

<br>

**Expected behavior**
Single copy of a book must appear in downloads section

**Steps to reproduce the behavior:**
1. 

**Screenshots**

**Environment**
- Version of Kiwix Android : 3.6.0
- Device : Samsung SM-A127F
- OS version :  12

**Logs**

**Comment by kelson42** [comment] 2023-03-02 15:46
This is a problem with the library, not the reader. Basically a duplicate of https://github.com/openzim/zim-requests/issues/575

**Closed by kelson42** 2023-03-02 15:46 UTC
