### ISSUE TITLE
No network connection

### ISSUE THREAD

**Issue by Albert221** [kiwix/kiwix-android#340] opened 2018-01-14 17:43 UTC
I see "No network connection" all the time on Online tab of Content Management although I'm connected to Internet all the time, no matter if it's WiFi or data. Logs give me this:

> W/kiwixLibrary: Error loading books:Permission denied (missing INTERNET permission?)

And it looks like this: 

![image](https://user-images.githubusercontent.com/4085280/34918883-c74390b8-f95a-11e7-9ceb-2a844320efb8.png)

**Comment by kelson42** [comment] 2018-01-14 17:48
Seems similar to #263

**Comment by Albert221** [comment] 2018-01-14 18:08
The device is Xiaomi Redmi 4 Pro

**Comment by kelson42** [comment] 2018-01-20 22:11
@julianharty @mhutti1 @divadsn I would like your feedback about that issue please. Does the fixes done since the opening (in particular #323 fixing) should let us consider this ticket to as "fixed"?

**Comment by mhutti1** [comment] 2018-01-20 22:28
It shouldn't do as imo it has no relation to the log item in this issue.

**Comment by divadsn** [comment] 2018-01-21 00:21
As far as I know for Xiaomi devices running MIUI, they can restrict access to the Internet, it's not reproducable for me as Android 6.0 and higher do not allow restricting such permissions yet.

**Comment by divadsn** [comment] 2018-01-21 00:23
Also another thing I suspect is missing storage permissions maybe, as those are requested on first time when the library view is opened by the user.

**Comment by julianharty** [comment] 2018-01-22 23:58
I agree this seems to be a distinct issue from #263 

@Albert221 are you compiling & building Kiwix Android yourself or is this problem happening in the released version? If you're working with the source code please could you run `git status` to see if something's accidentally affected any of the build files such as the gradle files or AndroidManifest.xml. If you're able to post the output from `git status` that might help us too.

**Comment by Albert221** [comment] 2018-01-23 07:30
I was running application compiled by myself, but I'm 100% sure that I
hadn't touched AndroidManifest.xml. I was hardly checking out master
several times and this issue was happening from the beginning. I'll be
happy to help debug this problem but I need to know what steps to follow
since I've already tried to find solution for that but failed on that

wt., 23.01.2018, 00:58 użytkownik Julian Harty <notifications@github.com>
napisał:

**Comment by julianharty** [comment] 2018-01-23 09:31
@Albert221 running `git diff` will help confirm whether the file was touched (or any other files related to the config and permissions). So as a place to start the debugging please could you run that command. 

It's also possible to extract the AndroidManifest.xml from the app's binary and check that & I'm pretty sure there'll be tools available both to run locally and online that'll check what permissions the binary has set. So you could try one of these tools/utilities to check the binary too. 

BTW: I expect that they'll confirm the permissions are correctly set (to include the Internet permission) the reason I'm suggesting these 2 steps first is so we can discard possible causes. They're also both easy to do and low risk.

**Comment by divadsn** [comment] 2018-01-23 14:39
@Albert221 have you checked the firewall which is built-in MIUI?

**Comment by Albert221** [comment] 2018-01-23 16:33
@julianharty 

> PS E:\AndroidStudioProjects\kiwix-android> git diff upstream/master --cached
> PS E:\AndroidStudioProjects\kiwix-android> git diff upstream/master
> PS E:\AndroidStudioProjects\kiwix-android>

No changes on AndroidManifest.xml as well as anything other. `upstream` is this repo.

@divadsn yes, there were no permissions (not that it was denied) related to Internet connection and every existing permission was allowed. I checked for example Messenger and it had no Internet permission either, so that's not the cause of it.

**Comment by macgills** [comment] 2019-05-27 10:59
Fixed in #1170

**Closed by macgills** 2019-05-27 10:59 UTC
Labels: bug
