### ISSUE TITLE
Many pictures of German Wikipedia (no video, 33GB) are not displayed

### ISSUE THREAD

**Issue by JuLuers** [kiwix/kiwix-android#1309] opened 2019-07-25 06:26 UTC
Many pictures of German Wikipedia (no video, 33GB) are not displayed on Huawei P30 Pro. 
For example in "Albert Einstein" there are empty picture rectangles, but "Through Hole Technology" shows pictures.
Kiwix 2.5.1, Build 220501, Google Play Store
Wikipedia, German, 2018-11-06, MO Videos
Huawei P30 Pro, VOG-L29, EMUI 9.1.0, Android 9, buyed some days ago
All software is up-to-date

Is there a way here in Github to paste screenshots on a mobile device?

**Comment by Bernhardino** [comment] 2019-07-25 07:00
> Is there a way here in Github to paste screenshots on a mobile device?

Yes, just drag & drop

**Comment by macgills** [comment] 2019-07-25 08:20
duplicate of #1014 , thank you for the report

**Closed by macgills** 2019-07-25 08:20 UTC

**Comment by kelson42** [comment] 2019-07-25 08:45
@JuLuers The problem is in the ZIM file itself. No problem with the reader here. We have fixed many things related to image retrieval in the Wikipedia scraper. Next one should have far less missing pictures. Thank you again for reporting it.

**Comment by JuLuers** [comment] 2019-07-25 09:58
@kelson42 The ZIM file has been downloaded by Kiwix App. If the problem is in the ZIM file itself, it must be updated on the server accessed by Kiwix. Don't know, were to get a correct ZIM file.

**Comment by kelson42** [comment] 2019-07-25 10:00
@JuLuers Yes, it will.
