### ISSUE TITLE
Cannot open ZIM files from phone download folder

### ISSUE THREAD

**Issue by benoit74** [kiwix/kiwix-android#4082] opened 2024-11-14 13:16 UTC
**Describe the bug**
When I try to load a ZIM which I just downloaded from Firefox (and is hence placed in standard "Download" folder of the phone), the app does not achieve to load the ZIM. If I move the ZIM somewhere else, everything works OK.

**Expected behavior**
Opening the file works

**Screenshots**

![Image](https://github.com/user-attachments/assets/759b96c2-1041-48e4-8da7-43c6da02851a)

**Environment**
- Version of Kiwix Android : Nightly (https://download.kiwix.org/nightly/2024-10-14/kiwix-universal-2024-10-14.apk)
- Device : Fairphone 4
- OS version : Android 13

**Logs**

[logs1731590064500.txt](https://github.com/user-attachments/files/17749063/logs1731590064500.txt)

**Comment by kelson42** [comment] 2024-11-14 13:24
Strongly suspect this is fixed in test version to be released in the next hour. @MohitMaliFtechiz You confirm?

**Comment by MohitMaliFtechiz** [comment] 2024-11-15 05:48
@kelson42, @benoit74 is talking about nightly APK(our website APK), not for the PS variant. @benoit74 Thanks for the logs, I am checking the logs.

**Comment by MohitMaliFtechiz** [comment] 2024-11-16 06:40
@benoit74 I am not able to reproduce the error in all my devices as well as on different emulators, can you please try [this APK](https://drive.google.com/file/d/1x4aIJ7BlYBAfzEH_KtxhWxmiSg83vJYm/view?usp=sharing) and share the device logs with us. It will be helpful in debugging the problem. Also, can you please tell me if opening the file from the "Download" folder via file picker works for you?

**Comment by benoit74** [comment] 2024-11-16 16:39
The test version from Google Play Store is indeed not suffering from the problem, so I assume @kelson42 was right.  And I just realize that I did not tested the latest nightly but the oldest one 🤦🏻‍♂️ Using the real latest one (from 2024-11-16) I do not have the bug either. I propose to simply close this. Sorry for the noise.

**Closed** 2024-11-16 16:47 UTC
Labels: bug, question
