### ISSUE TITLE
Warning:BuildType(local_download_server): buildConfigField 'KIWIX_DOWNLOAD_URL' value is being replaced: "http://download.kiwix.org/" -> "http://kiwix-download-server/"

### ISSUE THREAD

**Issue by pprathameshmore** [kiwix/kiwix-android#402] opened 2018-02-15 15:34 UTC
What is this warning in Android Studio?

**Comment by pprathameshmore** [comment] 2018-02-15 15:34
I can not understand this warning!

**Comment by Koundinyalanka** [comment] 2018-02-15 16:20
I can help @mhutti1 @kelson42

**Comment by pprathameshmore** [comment] 2018-02-15 16:59
What I do?

**Comment by Shashwat-Garg** [comment] 2018-02-15 17:49
@Koundinyalanka can we do it by just removing the "bulildConfigField" from local_download_server ?
Or will there be some wrong effects of it ?
I'm sorry, actually I'm a newbiew to open source, so please don't mind if I said something absurd. :)

**Comment by mhutti1** [comment] 2018-02-15 18:59
@Shashwat-Garg well it is mean tot be replaced in certain conditions.

**Comment by RajaVamsi11** [comment] 2018-02-17 09:16
@mhutti1 @srv-twry  I am facing this problem now.Anyone know  how to solve it??

**Comment by mhutti1** [comment] 2018-02-17 21:10
@RajaVamsi11 it is not an error only a warning it has no consequential effects on anything.

**Comment by RajaVamsi11** [comment] 2018-03-10 21:41
@mhutti1 Asthis warning is not harmful and it has no consequential effects on anything.Why is this still open? we can close it because it was just increasing the no of issues i think.

**Comment by mhutti1** [comment] 2018-03-11 00:03
10+ people have thought incorrectly this was the cause of a build failing. This is why we should fix it.

**Comment by brijeshshah13** [comment] 2018-03-23 13:30
What is this purpose of the following block in the `app` level `build.gradle` file?

```
local_download_server {
      initWith(buildTypes.debug)
      buildConfigField "String", "KIWIX_DOWNLOAD_URL", "\"http://kiwix-download-server/\""
      matchingFallbacks = ['debug', 'release']
}
```

**Comment by RohanBh** [comment] 2018-03-23 17:21
[This](https://stackoverflow.com/a/47547753/7263373) explains the warning. But the answer doesn't mention how to turn it off. A workaround is to manually copy the buildConfigFIeld initializations from debug build type to local_download_server build type.
But I think current code makes more sense. It's more readable. It says to do everything same as in debug build type but with one change only.

**Comment by brijeshshah13** [comment] 2018-03-23 18:36
@mhutti1 We can store the `KIWIX_DOWNLOAD_URL` in the `gradle.properties` file and fetch it using the `signingConfig signingConfigs.debug` which will use the default keystore file to sign the debug version of the apk. However, I strongly believe that the current implementation is to-the-point and we should not try to make things complex unnecessarily over this warning. To acknowledge the developers about the same, we can simply mention it in the README.md file.

**Comment by julianharty** [comment] 2018-03-23 20:51
All,
I'm the person who created this concept. Let me at least explain the intention then we can made an informed decision on what to do about the warning, placement, etc. of this parameter. I'll start with the basic context first:

We want to be able to test the kiwix-android app before we ship it. Our testing consists of a mix of automated tests (generally written in Espresso) and interactive testing done  - often - just by the person who's been modifying the app. The espresso tests often rely on external services, in particular the download.kiwix.org web site where the tests download the catalog of ZIM files and then several smaller ZIM files to assess the download functionality, etc.

We were kindly provided with a testing service by BitBar who run a service called TestDroid. This enables the project to run these automated tests on various devices and is a real help for some of the developers. However we found that one or more of the automated tests often failed, particularly on devices in TestDroid's device 'cloud'. The test failures caused us problems building the code using the CI as we didn't know whether the failure(s) were related to recent changes to our code or automated tests or problems in the environment. We ended up reducing the range of devices we ran the tests on to reduce the chances of the tests failing in the CI (which is run on travis-ci). This isn't the best approach to improving the quality of the app, or the tests.

Just under a year ago I decided to try adding support for a local equivalent of a download server that could provide sufficient functionality to support the automated tests. This download server could then be installed and used locally by developers, in the CI environment, etc. I use a raspberry pi as my download server and configure the hostname so it matches this value. I then use the relevant gradle option to run the tests against the local download server. 

If you'd like to know how to create a local download server try here https://github.com/kiwix/kiwix-android/wiki/Creating-a-local-kiwix-download-server and let me know where the instructions and process can be improved.

Since I added support for the local download server Google has released build flavors. We haven't yet polished the build options to still support the local download server option. I'm open to suggestions and/or pull requests to improve both this aspect and also the automated tests. We'd like these tests to be comprehensive, useful and reliable on many devices and environments (including on TestDroid devices).

**Comment by RohanBh** [comment] 2018-03-23 23:16
@julianharty is it possible for us to see the error logs testdroid's devices generated when they frequently crashed?

**Comment by julianharty** [comment] 2018-03-28 07:36
The error logs are available. I'll see if we can find a way to get you
access to them.

**Comment by faith-hb** [comment] 2018-10-16 03:29
> 10+ people have thought incorrectly this was the cause of a build failing. This is why we should fix it.

The result?

**Comment by kelson42** [comment] 2019-06-18 05:16
@mhutti1 @mhutti1 @julianharty What should we do with this. It seems quite unmaintained. I believe it is still not fully running (the mock network/download server)... and to me this seems really overcomplex (and I don't understand why we don't deal with the standard infrastructure). Could we remove this?

**Comment by julianharty** [comment] 2019-06-18 07:39
@mhutti1 @macgills @kelson42 I agree we shouldn't leave this code languishing, we have a couple of options I think. The choice depends on whether we would like to be able to setup a controlled environment for testing downloads by the app(s). 

- We could remove the build target and the few lines of code from the Android app. This is easy to do and leaves the project's codebase relatively clean. It's feasible to perform the testing by other means e.g. proxies and/or local DNS entries that point to a local server, albeit these configurations may be fairly involved and few people are ever going to do so (if anyone).
-  We could tidy up the build so this is easy to configure when we want to use this option and so it's transparent and does not confuse people otherwise. 
- We could alter the Android app so the download server is a parameter in the app's settings, perhaps under an advanced setting menu option. 
   - We could also configure only enabling this feature in debug builds if we didn't want the risk of 'breaking' the app for end users.
   - Or we could make this available so that the app could be used to download content from a local server on WiFi which may be particularly useful in refugee camps, etc. where connection to the internet is expensive, slow and unreliable -  local Kiwix servers could host the content and enable users to download it easily (I envisage this as a parallel alternative to peer-to-peer downloads)

From a testing perspective, having a local download server enables us to inject faults in the download process so we can test how well the app detects and deals with the faults. Does the app crash (surely not! :) does it notify the user and allow them to make alternative choices, etc. etc.

**Comment by macgills** [comment] 2019-06-18 09:21
I would propose the usage of MockWebServer from the fine folks at square, there however is - I believe - no reason for this to be a build type.
We can just create a suite of tests via subclassing that inject a different retrofit service targeting our mockwebserver and expect all the responses.
I have a personal axe to grind against any ui test that talks to a backend, prime source of intermittent failure and slowness. If we want to test that our app integrates with a backend that should be a different classification of test that invokes our net code without a ui.

**Comment by macgills** [comment] 2019-06-18 15:08
Not currently no, I am hoping for some time for a more comprehensive automation strategy in 3.0/3.1. I have regrettably broken some tests that have been ignored and flagged as due for repair. Espresso Idling resources are another source of irritation, automation code have internal knowledge of the source code under test grinds my gears.
The unit test expansion - now that coverage is implemented - should also give us a hefty confidence boost in these areas.
It should also be mentioned that we don't "in app" download these files anymore as it is handled by the downloadManager and I don't feel a pressing urge to test the android framework. Maybe in a very isolated test case.

**Comment by kelson42** [comment] 2019-06-23 09:46
@macgills @mhutti1 @julianharty Putting to 3.0 milestone

**Comment by kelson42** [comment] 2019-07-01 10:27
local_download_server buildType has been removed.

**Comment by macgills** [comment] 2019-07-01 10:28
closing

**Closed by macgills** 2019-07-01 10:28 UTC
Labels: build tools, good first issue
