### ISSUE TITLE
Scrolling Issue in the initial landing screen

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#798] opened 2018-07-08 19:08 UTC
**Describe the bug**

- on scrolling down on the kiwix image on the initial landing screen, the image moves up

**Expected behavior**

- The image should remain stationary.

**Steps to reproduce the behavior:**
1. open the app (for the first time after installing the apk, so that it opens the intial landing screen)
2. try to scroll down by swiping up on the kiwix image

**Screenshots**

<img width="341" alt="zxc" src="https://user-images.githubusercontent.com/32238400/42423019-60a020e8-8310-11e8-9591-9d237654c7b6.png">

**Environment**
- Version of Kiwix Android : 3.0
- Device : Samsung S6
- OS version : Android 7.0

**Comment by abdulwd** [comment] 2018-07-10 16:16
@siddharth2010 You can go to settings and enable **Keep Toolbar Visible** that will make the banner stationary. I think I have found an issue while trying to reproduce this one. When **Keep Toolbar Visible** is disabled, I'm not able to scroll to the last item of the recycler view unless I scroll the banner.
@mhutti1 Should we make the banner stationary for the home screen? i.e. the scrolling behavior of the app bar of the home will not depend on **Keep Toolbar Visible** in the settings.

**Comment by siddharth2010** [comment] 2018-07-10 17:30
@abdulwd , I saw the **Keep Toolbar Visible** option in the settings, and its working fine, however, I think you are right, making the banner stationary for the home screen will probably be a good idea.

**Comment by mhutti1** [comment] 2018-07-11 22:30
The banner should not be kept stationary imo it should scroll. If there are issues due to this they should be fixed.

**Comment by macgills** [comment] 2019-06-21 11:53
![image](https://user-images.githubusercontent.com/3358282/59920133-75a3a000-9421-11e9-94f1-2b87c952f4d1.png)
You can also scroll it to the side once you start scrolling, not a fan of this behaviour at all.
The only way I am seeing of doing it right now is disabling scrolling on the entire webview but then we have to reenable it when a user selects a file

**Comment by kelson42** [comment] 2019-09-17 08:54
Fixed in #1427

**Closed by kelson42** 2019-09-17 08:54 UTC
Labels: UI, bug
