### ISSUE TITLE
Crash Report 3.3.3: Dagger component not initialised in activity creation

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2198] opened 2020-07-10 10:33 UTC
```
Caused by: kotlin.UninitializedPropertyAccessException: 
  at org.kiwix.kiwixmobile.core.CoreApp$Companion.getCoreComponent (CoreApp.java:44)
  at org.kiwix.kiwixmobile.core.base.BaseActivity.onCreate (BaseActivity.java:43)
  at org.kiwix.kiwixmobile.core.splash.CoreSplashActivity.onCreate (CoreSplashActivity.java:30)
```

This seems like a device bug, the CoreComponent is created in the `onCreate` of the Application class which happens on the main thread, is one of the leading causes of slow startup times in apps and absolutely should happen before *any* activity's `onCreate`.

The only thing I can really think of here is just not using the component here, perhaps reparenting away from BaseActivity and manually constructing some objects for the SplashActivity only. Then also praying the component is initialised before the next screen.

**Comment by kelson42** [comment] 2020-08-16 06:22
@macgills What should we do with that one?

**Comment by macgills** [comment] 2020-08-17 08:50
This might go away with SplashActivity not really existing as the Single Activity Architecture is being migrated to by Frans.

We could also attempt to migrate to Hilt, the newest Dagger library from the jetpack team. I haven't seen any explicit mention of how it works in a multi module scenario but maybe it is just fine

**Comment by kelson42** [comment] 2022-09-21 05:58
@MohitMaliFtechiz An update here would be welcome

**Comment by MohitMaliFtechiz** [comment] 2022-11-23 13:42
hi @kelson42 @macgills ,

I am unable to reproduce this bug on latest develop build.

**Comment by kelson42** [comment] 2022-11-23 13:47
@MohitMaliFtechiz Please check in Google Play store reports if this still happen

**Comment by MohitMaliFtechiz** [comment] 2022-11-25 13:05
hi @kelson42 ,

The reports suggest it is occurring on version 3.4.5 , but last playstore build was 3.4.4 but no crash report for 3.5.0 and 3.6.0.

**Comment by kelson42** [comment] 2022-11-25 13:07
Ok for closing rhen.

**Closed** 2022-11-25 13:07 UTC
Labels: bug, question
