### ISSUE TITLE
Host Books don't  update on Application

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#2537] opened 2020-12-03 09:07 UTC
**Describe the bug**
UnSelected Host books are showing on Hosting.

**Expected behavior**
Only Selected Host books should show.

**Steps to reproduce the behavior:**
1. Start the server on HostFragment
2. Unselect one or more zim files
3. See the unselected books are showing (On Mobile device)

**Environment**
- Version of Kiwix Android : develop
- Device : 10
- OS version : pixel

**Comment by macgills** [comment] 2020-12-03 11:11
Is this a dupe of https://github.com/kiwix/kiwix-android/issues/2447 ?

**Comment by gouri-panda** [comment] 2020-12-03 11:14
@macgills #2447 that is showing on the browser and this issue is related to mobile application

**Comment by kelson42** [comment] 2023-01-26 19:13
@MohitMaliFtechiz Is that still a valid bug?

**Comment by MohitMaliFtechiz** [comment] 2023-01-27 05:26
> @MohitMaliFtechiz Is that still a valid bug?

ok @kelson42  I will check this bug.

**Comment by MohitMaliFtechiz** [comment] 2023-01-27 09:05
@kelson42 ,
i have tested this. i found when i select only 2-3 books and un-select all other book. then all books are showing in hosting, i'm attaching a video.

https://user-images.githubusercontent.com/34593983/215048456-de01da84-a61f-4f20-aac6-affe42f2c5a3.mp4

**Comment by kelson42** [comment] 2023-01-27 09:21
@MohitMaliDeveloper Thank you for testing. I don't really understand why the checkbox disappear when server is running. I propose to just keep them always visible and if someone change (adding or removing a book) while service is running, then service is restarted.

**Comment by MohitMaliFtechiz** [comment] 2023-01-27 10:00
@kelson42 ,

> I propose to just keep them always visible and if someone change (adding or removing a book) while service is running, then service is restarted

i'm creating a separate ticket for this 

> i have tested this. i found when i select only 2-3 books and un-select all other book. then all books are showing in hosting
 
For this, i have placed a fix https://github.com/kiwix/kiwix-android/pull/3218

**Comment by kelson42** [comment] 2023-09-21 14:43
@MohitMaliFtechiz @gouri-panda What the status of this bug? Does it still occurs?

**Comment by kelson42** [comment] 2023-09-26 10:22
It seems it works now, although mabe memory leak occur on api24. An otjer ticket should be open for that.

**Closed** 2023-11-12 17:00 UTC
Labels: bug
