### ISSUE TITLE
In app language selection doesn't work on 7.0+

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-android#207] opened 2017-07-18 15:00 UTC
On a android 7.0 configured in French.

Using the last alpha version of wikimed (`2017-07 Build: 171990`), the (top right) menu is sometime in english and sometime in french.

It seems that the language doesn't change during a run of the application.
But if you close the application (and remove it from "opened applications") and relaunch the application, the menu language can change.

Reproducer is not easy, you may have to try those actions to reproduce it:
- Open/close application
- Search
- Change settings
- ...

**Comment by mgautierfr** [comment] 2017-07-18 15:11
A reproducer :
- Start wikimed (from fresh start) => menu is in french
- Go to settings (options) and change the Night mode (Mode nocturne)
- Go back => menu is in english

**Comment by kelson42** [comment] 2017-07-18 18:25
@mhutti1 A clue about what is going on? Not really a blocker for new Wikimed release, but would be better to have it working properly.

**Comment by mhutti1** [comment] 2017-07-18 19:37
So this is an intended feature as `  "enforced_lang": "en"
` is set. I am not sure why it starts out in french though.

**Comment by kelson42** [comment] 2017-07-19 04:52
This seems to impact only the custom apps. Probably something is a bit wrong and makes the app mixing Android language=default Kiwix language and the enforced_lang (only for custom apps). Not a blocker for Wikimed release but would be nice to have it fixed to avoid confusing users. We still have a few days before Wikimed public release.

**Comment by mhutti1** [comment] 2017-07-19 22:01
Ok. I think I can reproduce in Kiwix. I set language to french and restart app and it is in english. Can you reproduce?

**Comment by mhutti1** [comment] 2017-07-19 22:09
I think the whole locale selection logic might need reviewing. I can see if I can find the bug tommorow.

**Comment by kelson42** [comment] 2017-07-20 06:20
@mhutti1 Perfect, yes please have a look. I do not have tried to reproduce the pb but of course @mgautierfr can.

**Comment by mhutti1** [comment] 2017-07-20 20:31
This is a much bigger task than I anticipated. Google depreciated the API we use and didn't replace it so work arounds require some creativity. We need to add a whole new set of language selection logic for 7.0+

**Comment by kelson42** [comment] 2017-07-21 05:58
@mhutti1 ok :( Thank you very much for the investigation. In a sense, this is good to hear that this is a 7.0 specific bug. As 7.0 is only a few % of our audience, this confirm we can release Wikimed with that bug. That said, I tend to think, we should have fixed this 2.4? What do you think about the priority?

**Comment by kelson42** [comment] 2019-06-24 19:35
@mhutti1 @macgills What is the status on this as this selection has been quite seriously revamped for 2.5?

**Comment by macgills** [comment] 2019-06-25 08:09
In another ticket I was asking for our language selection in Settings to be totally removed because I did not like it and if we want the app to render in another language we should just respect the android device's settings. 
That was not revamped in 2.5, the dialog for choosing your selected languages was.

**Comment by kelson42** [comment] 2019-06-25 08:14
@macgills thx for the clarification. I'm not really ready to remove that feature, I see a few valid use cases like:
* Android does not support the language the user wants
* someone wants to use the app but is not the device owner.

@macgills Please open a dedicated ticket to propose this feature removal and we will discuss it openly ;)

**Comment by macgills** [comment] 2020-01-31 10:32
I would say this will be resolved in #1738

**Closed** 2020-02-04 10:33 UTC
Labels: bug
