### ISSUE TITLE
Main entry is not displayed

### ISSUE THREAD

**Issue by benoit74** [kiwix/kiwix-android#3480] opened 2023-09-15 13:59 UTC
**Describe the bug**

When I go to Library to select a ZIM and open it, it opens a blank page. 

The issue happens with:
- `disledansmalangue_fr_2023-05` (created with nautilus scraper)
- a private ZIM from DWDS project (created with zimwriterfs)

Issue does not happen with `ted_en_playlist-let-s-talk-crap_2021-01` (created with ted scraper)

Both ZIM with issues seems to have a valid main entry (entry exist and is an HTML page).

**Expected behavior**

Main entry is displayed

**Steps to reproduce the behavior:**
1. Click on 'Library' at the bottom of the screen
2. Search for 'disledansmalangue'
3. Download the ZIM
4. Open the ZIM once download completes
5. See error 

**Environment**
- Version of Kiwix Android : 3.7.1 and 2023-09-14 nightly 
- Device : Fairphone 4 5G 
- OS version : Android 12

**Comment by kelson42** [comment] 2023-09-18 17:36
@benoit74 @MohitMaliDeveloper I guess this has been fixed today.

**Comment by MohitMaliFtechiz** [comment] 2023-09-19 05:12
@benoit74, @kelson42 I have tested this with [disledansmalangue_fr_2023-05.zim](https://download.kiwix.org/zim/other/disledansmalangue_fr_2023-05.zim) and i am unable to reproduce the error. Since we have adapted the new wrapper this error is automatically fixed, can you please try with our [latest nightly APK](https://download.kiwix.org/nightly/2023-09-19/kiwix-universal-2023-09-19.apk) or with the develop branch is this issue still exists at your end?


https://github.com/kiwix/kiwix-android/assets/34593983/c17979ba-612e-431e-a280-ed84bcf101cd

**Comment by kelson42** [comment] 2023-09-19 05:39
@benoit74 99% sure its fixed in 3.8.0 (to be released)

**Closed** 2023-09-19 05:39 UTC
Labels: bug, duplicate, question

**Comment by benoit74** [comment] 2023-09-19 09:19
Yes it is, latest nightly is ok.
