### ISSUE TITLE
Content list unreadable in dark mode

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#1531] opened 2019-09-28 08:49 UTC
Version 3.0.3
Funnily enough, the issue is only with the online catalogue, not the local library.
![Dark Mode enabled](https://user-images.githubusercontent.com/21675885/65814067-95472300-e1dd-11e9-903b-f407bbdd8a89.png)

**Comment by kelson42** [comment] 2019-09-28 08:51
Pretty much a duplicate of #1301, even if the symptom seems now slightly different. Problems around Night-mode are known and need a revamping in 3.1

**Closed** 2019-10-17 09:45 UTC
Labels: UI, bug
