### ISSUE TITLE
Recent tabs are not gray in night mode.

### ISSUE THREAD

**Issue by KushagraK123** [kiwix/kiwix-android#1823] opened 2020-02-26 17:05 UTC
**Describe the bug**
Recent tabs appear white in Night Mode

**Expected behavior**
They should be of dark color

**Screenshots**
![Screenshot_2020-02-26-22-20-12-651_org kiwix kiwixmobile](https://user-images.githubusercontent.com/35377313/75368501-e1f76d00-58e7-11ea-969c-23b3e62bd1e1.jpg)

**Environment**
- Version of Kiwix Android : 3.2.0

**Comment by mhutti1** [comment] 2020-03-01 13:47
Yes this looks like a bug. The images are still inverted for me so I think the filter we use isn't being applied in the tab menu.

**Comment by kelson42** [comment] 2020-03-02 07:31
To me basically a duplicate of #1411 and #1476, should be tacle in milestone 3.4 IMO.

**Closed** 2020-04-02 11:08 UTC
Labels: bug, good first issue
