### ISSUE TITLE
Kiwix 3.9.1 and Wikivoyage 2023-12 apps crashing when opening zim files on Fire OS 7.3.2.9

### ISSUE THREAD

**Issue by Otmooron** [kiwix/kiwix-android#3692] opened 2024-02-03 21:46 UTC
Whether I try and open the largest or smallest Wikivoyage zim files (or the Wikimedia Top 100 in the case of Kiwix), the apps crash to the home screen.  Zim files download but do not open.

iOS Kiwix app works fine with same content and Wikivoyage app worked brilliantly on Kindle until recently, so I assume bug is in latest versions of apps.

Device is Kindle Fire HD8 (8th generation) running Fire OS 7.3.2.9 (latest available for device, equivalent of Android 9 Pie). Apps were installed from Play Store.

**Comment by kelson42** [comment] 2024-02-05 20:06
@MohitMaliFtechiz Can you please help @Otmooron ?

**Comment by MohitMaliFtechiz** [comment] 2024-02-06 13:36
@Otmooron is this behavior is same for other ZIM files too? or you are only facing this issue with `Wikivoyage` and `Wikimedia Top 100` ZIM files.

> I sideloaded Kiwix 3.7.1 and it’s working fine, so it’s something between 3.7.1 and 3.9.1. Hope this helps.

Thanks for the additional information it would be helpful.

**Comment by Otmooron** [comment] 2024-02-06 13:41
I was only interested in getting access to Wikivoyage, but thought I should try the Wikipedia file to make sure it wasn’t just a Wikivoyage issue. 

If you would like to suggest some other files I can go back to 3.9.1 and try them?

**Comment by MohitMaliFtechiz** [comment] 2024-02-06 13:48
Can you please try with these two small ZIM files?
1. [beer.stackexchange.com_en_all_2023-05.zim](https://download.kiwix.org/zim/stack_exchange/beer.stackexchange.com_en_all_2023-05.zim)
2. [alpinelinux_en_all_maxi_2022-12.zim](https://download.kiwix.org/zim/other/alpinelinux_en_all_maxi_2022-12.zim)

**Comment by Otmooron** [comment] 2024-02-06 16:32
OK. those two crash on 3.8.0 and 3.9.1, but everything works again when I revert back to 3.7.1.  I think that ties in with when the problems started.

**Comment by MohitMaliFtechiz** [comment] 2024-02-07 05:50
@Otmooron Thanks for your testing. So it means every ZIM file is crashing on your device when you try to open them in the recent version of Kiwix. We are investigation this bug.

**Comment by kelson42** [comment] 2024-02-07 06:57
@MohitMaliFtechiz I guess a log file would be helpful at this stage... or do you have another approach to try to identify where the crash comes from?

**Comment by MohitMaliFtechiz** [comment] 2024-02-07 07:23
@kelson42 I was thinking of creating an emulator with Fire OS but they are [discontinued](https://stackoverflow.com/questions/28288168/amazon-kindle-fire-avd) now, and another approach I have just tried which is mentioned on the [official amazon docs](https://developer.amazon.com/docs/fire-tablets/ft-testing-without-an-amazon-device.html) but on this I am not able to reproduce this issue. 

Version `3.7.1` is working fine in the user's device(that uses the older libkiwix), and we recently started using the libkiwix `2.0.0` which has the debug symbol. @Otmooron can you please try with this APK https://drive.google.com/file/d/11JYfBfYf3H4dIUibZ0tuMlT_vtOEm0xn/view?usp=sharing, and when it will crash while opening the ZIM file it ask for send the crash report, please put that crash report here, it would be very helpful here.

**Comment by Otmooron** [comment] 2024-02-07 08:58
@MohitMaliFtechiz I trust this is what you are looking for?

[logs1707295495925.txt](https://github.com/kiwix/kiwix-android/files/14191225/logs1707295495925.txt)

**Comment by Otmooron** [comment] 2024-02-07 17:05
@MohitMaliFtechiz Sorry, that hasn't worked.  ZIM Files downloaded from the online repository into my library crash as before.  The two files you sent above now come up with the error message "The selected ZIM file could not be found" when I try and load them from the file picker in Kiwix or I double-click them from the Files app. There is a Leaks icon on the home screen with 2 distinct leaks, but I'm not sure what you might want for debugging.

**Comment by MohitMaliFtechiz** [comment] 2024-02-08 06:41
@Otmooron Thanks for your testing. We only placed a fix in the above APK on behalf of the logs you have provided. Both crashing scenarios are different.

> The two files you sent above now come up with the error message "The selected ZIM file could not be found" when I try and load them from the file picker in Kiwix or I double-click them from the Files app.

Ok so now it is not crashing while you are selecting the ZIM file via file picker, but it should open the ZIM file we have added some more paths to get the actual path from the uri. Unfortunately, it is not getting the actual path so it means the URI content prefix is different and we need that prefix.

> ZIM Files downloaded from the online repository into my library crash as before.

We have not placed a fix for this issue as we don't have logs of the crash of this scenario. but in the below APK, It will ask you to send the crash report.

Can you please help us to diagnose the actual problem in both scenarios?

First, try this APK https://drive.google.com/file/d/11JYfBfYf3H4dIUibZ0tuMlT_vtOEm0xn/view?usp=sharing.

First step:
1. Open the ZIM file via the file picker.
2. It will show you the "The selected ZIM file could not be found" error message.
3. Go to the help screen from the bar.
4. Click on "Send diagnostic report". attracted that file here.
It will be helpful to address why the ZIM file is not opening on your device. Since it will attach the created URI by your system in logs.

Second step:
1. Click on any ZIM file showing in the "Library screen". The application will crash as you described above.
2. It will ask you to send the crash report.
3. Please Attached that report here.

**Comment by Otmooron** [comment] 2024-02-08 08:55
OK

Here is the diagnostic report for the first step - 
[logs1707380316096.txt](https://github.com/kiwix/kiwix-android/files/14206275/logs1707380316096.txt)

In the second step it didn't properly crash out to the home screen - the screen went out to Home but the app was still running.  I also didn't get asked to send the crash report, but I created a diagnostic report here - 
[logs1707380868923.txt](https://github.com/kiwix/kiwix-android/files/14206490/logs1707380868923.txt)

Hope you understand - I'm just a layman!

**Comment by kelson42** [comment] 2024-03-05 13:33
@MohitMaliFtechiz What is the status here on this issue?

**Comment by MohitMaliFtechiz** [comment] 2024-03-05 15:00
@kelson42 The user faces the same issue as we are in https://github.com/kiwix/kiwix-android/issues/3661 on the `armeabi-v7a`. I have shared all the logs with @mgautierfr of the error.

**Comment by kelson42** [comment] 2024-03-11 06:49
@MohitMaliFtechiz Any reason to not merge the tickets?

**Comment by MohitMaliFtechiz** [comment] 2024-03-11 07:11
@kelson42 I kept this ticket to take user feedback But now we can merge this ticket with https://github.com/kiwix/kiwix-android/issues/3661 as we have better logs documented in #3661 for the error and now we are able to reproduce the error.

**Closed** 2024-03-11 07:14 UTC
Labels: bug, duplicate, question
