### ISSUE TITLE
Remove requirement to grant photo and media permission

### ISSUE THREAD

**Issue by wbillan** [kiwix/kiwix-android#2808] opened 2022-04-26 22:37 UTC
**Is your feature request related to a problem? Please describe.**
Currently Kiwix requires users to grant grant photo and media permission, which gives it access to all of the user's photos and videos, which has privacy implications.  The app doesn't actually need this permission as per Android scoped storage  (https://source.android.com/devices/storage/scoped) in Android 11+, as an app does not require permissions to create files and access those created files.

**Describe the solution you'd like**
Remove requests for and and the requirement for photos and media permission.

**Describe alternatives you've considered**
Not applicable, requiring the described permission in unnecessary.

**Comment by kelson42** [comment] 2022-06-21 14:51
@wbillan I agree on the principle, I guess this ticket is a duplicate of #2062

**Closed by kelson42** 2022-06-21 14:51 UTC
Labels: enhancement, question

**Comment by gouri-panda** [comment] 2022-06-21 15:34
>@wbillan I agree on the principle, I guess this ticket is a duplicate of https://github.com/kiwix/kiwix-android/issues/2062

+1
