### ISSUE TITLE
Display ongoing downloads on top(download tab)

### ISSUE THREAD

**Issue by Mitia99** [kiwix/kiwix-android#2564] opened 2020-12-26 09:52 UTC
**Is your feature request related to a problem? Please describe.**
The issue is that I do multiples library download but it is not really convenient to check the download status from notification pannel.

**Describe the solution you'd like**
Display ongoing dowbloads on top in "download tab".

**Comment by kelson42** [comment] 2020-12-26 10:00
Duplicate of #2496

**Closed by kelson42** 2020-12-26 10:00 UTC
Labels: duplicate, enhancement
