### ISSUE TITLE
Add manual selection for ZIM files to the library

### ISSUE THREAD

**Issue by banane4711** [kiwix/kiwix-android#2405] opened 2020-09-28 10:37 UTC
Actually Kiwix uses an automated search for libraries on the mobile phone. This takes a lot of time (especially on large SD cards) and blocks the phone. As in most cases the user knows, where the ZIM files have been stored it would be very helpful and more efficient to have the choice between an automated search and the manual selection of a folder or a file.

**Comment by kelson42** [comment] 2020-09-28 11:04
@banane4711 What do you mean exactly with " blocks the phone"?

**Comment by kelson42** [comment] 2020-10-12 07:36
Without answer and clarification about this ticket, I plan to close it.

**Comment by banane4711** [comment] 2020-10-12 07:40
Hi Kelson,

find the reply from September below.

Sven



-------- Weitergeleitete Nachricht --------
Betreff: 	Re: [kiwix/kiwix-android] Add manual selection forZIM files to 
the library (#2405)
Datum: 	Mon, 28 Sep 2020 21:00:04 +0800
Von: 	nextcloud@sbecher.de
An: 	Kelson <notifications@github.com>



Hi Kelson,

it means, that the screen is shown a pretty long time and I cannot leave 
it as otherwise the search for the libraries will stop. If I open Kiwix 
again the search starts from scratch. Therefore I'm stuck with the 
search screen.

Sorry if I didn't express clearly

Sven


Am 28.09.2020 um 19:04 schrieb Kelson:

**Comment by banane4711** [comment] 2020-10-12 07:44
Hi Kelson,
seems my reply hasn't been filed :-(

it means, that the search screen is shown a pretty long time while searching through the whole phone / SD-card and I cannot leave the search screen as otherwise the search for the libraries will stop. Opening Kiwix again next time the search starts searching libraries from scratch. Therefore, I'm stuck with the search screen and have to wait until a library is found as otherwise I cannot start Kiwix without repeated search

Sorry if I didn't express clearly

Sven

**Comment by kelson42** [comment] 2020-10-12 07:49
@abdulwd @mhutti1 @siddharth2010 @Frans-Lukas @macgills I'm not really in favour of adding a manual way to add a file because the automatic way should work fine. @banane4711 seemsto say that it does not. This needs to be first confirmed/analysed/understood properly I believe.

**Comment by banane4711** [comment] 2020-10-12 07:57
> @abdulwd @mhutti1 @siddharth2010 @Frans-Lukas @macgills I'm not really in favour of adding a manual way to add a file because the automatic way should work fine. @banane4711 seems to say that it does not. This needs to be first confirmed/analysed/understood properly I believe.

In general, the automatic way works, but due to the increased size of memory (E.g. I'm using a 512MB SD-card) it needs a lot of time to dive through all folders. and sub-folders If the search could be done in the background it also may solve the issue. (Allthough I still think the manual option is more convenient for many users ;-):
Sven

**Comment by abdulwd** [comment] 2020-10-12 08:21
IMO we can consider this. Although this will have a very low adoption.
We can also think of scanning selected folder(s) instead of the full file-system.

**Comment by banane4711** [comment] 2020-10-12 08:23
> IMO we can consider this. Although this will have a very low adoption.
> We can also think of scanning selected folder(s) instead of the full file-system.

Scanning selected folder would also be fine as this avoids checking the whole file system and shortens the search time significantly

**Comment by macgills** [comment] 2020-10-12 11:07
@banane4711 is your device 2 core by any chance? The scan does occur in the background. Much like our recent issues around search we could pursue a coroutine based implementation and see if we achieve any speed gains.

If we go the custom directory route we need to communicate very cleary that this overrides automatic detection. A simpler system might be a toggle to disable auto detection and only utilise the app folders. The user would then be responsible for moving files into the kiwix specific directories

**Comment by banane4711** [comment] 2020-10-12 11:47
> @banane4711 is your device 2 core by any chance? The scan does occur in the background. Much like our recent issues around search we could pursue a coroutine based implementation and see if we achieve any speed gains.

My device is 4-core bit.LITTLE in 2 clusters.
 
> If we go the custom directory route we need to communicate very cleary that this overrides automatic detection. A simpler system might be a toggle to disable auto detection and only utilise the app folders. The user would then be responsible for moving files into the kiwix specific directories

I understand the idea, but I'd have concerns on that as we are partly talking about really large files (up to30GB). The solution putting them in the App directory would limit the user in choosing the appropriatenadn sufficient memory. (E.g. my tablet has 32G internal but 512G SD-card)

**Comment by macgills** [comment] 2020-10-12 11:49
The app has folders on sd card and on internal

**Comment by banane4711** [comment] 2020-10-12 11:51
If both can be used according to users needs that would be sufficient I guess

**Comment by kelson42** [comment] 2022-04-11 08:15
@MohitMaliFtechiz Can you explain here what you plan to do?

**Comment by MohitMaliFtechiz** [comment] 2022-04-11 13:33
hi @kelson42 ,

I will try to optimise the search time. so that result will prompt relatively fast if that doe's resolve the issue then last solution is to add file chooser.

**Comment by MohitMaliFtechiz** [comment] 2022-04-15 09:57
hi @kelson42 ,

We have to add file picker to fix this problem , it won't take long few lines of code will resolve this issue. We can options in menu item to open file. Let me know if that solutions works for you ?

**Comment by kelson42** [comment] 2022-04-18 12:25
@MohitMaliFtechiz Please do ao with a PR if there is no alternative. We will discuss the details and rationals asap.

**Closed** 2022-04-30 06:24 UTC
Labels: enhancement, question
