### ISSUE TITLE
Make the search button onclick action more precise.

### ISSUE THREAD

**Issue by moksh-mahajan** [kiwix/kiwix-android#429] opened 2018-02-16 11:00 UTC
The search bar pops up even if we click on the space between the actual search button and the 3 bar icon. Make appropriate changes in the code so that it will open search bar only when search button is clicked.

**Comment by moksh-mahajan** [comment] 2018-02-16 11:01
Kindly review this issue @mhutti1  @kelson42

**Comment by srv-twry** [comment] 2018-02-16 11:15
@moksh-mahajan can you attach a GIF ?

**Comment by arpank10** [comment] 2018-02-16 11:29
@moksh-mahajan I think @mhutti1 already closed your previous issue saying that it is not a bug. This issue is the same. Please check and close the issue.

**Comment by srv-twry** [comment] 2018-02-16 11:34
@moksh-mahajan Please avoid doing this. You were already told that it isn't a bug. Creating the same issue multiple times won't make it any relevant.
It is strictly advised not to repeat this.

**Closed by srv-twry** 2018-02-16 11:34 UTC

**Comment by moksh-mahajan** [comment] 2018-02-16 12:15
@srv-twry  sorry my bad, I am new to github :(
