### ISSUE TITLE
When you add new tab pervious tab and article disappear

### ISSUE THREAD

**Issue by abhijeetsinghcode** [kiwix/kiwix-android#2388] opened 2020-09-21 14:17 UTC
Tab -1 is open with an article.
When I add Tab - 2  and open an article  it opens and  tab - 2 becomes tab - 1 . The pervious article disappear. 
You can watch the video  given below.

**Kiwiz , WIkipedia offline**

Video - Open tab in background (OFF) ->
https://drive.google.com/file/d/1-JzrhVXgzONKUzZFCfHxH8yoyOkBBorO/view?usp=sharing

Video - Open tab in background (ON) ->
https://drive.google.com/file/d/1-DZyyz1--CJogSNh1KGvRW542L3IZBEs/view?usp=sharing

**Kiwiz , WIkipedia offline(Beta)**
 There is difference ->
In the Reader section 
An Article  is open Tab -1 .
Now when I add tab - 2 ,same  article appear on  tab - 1 and in tab - 2.
Now I have one article in two tab.

Now I click on Library and open new article tab it become tab -1  with different article which I opened.
Now I click on Reader section it has same pervious article on both tab - 1 and tab - 2

Video - Open tab in background (OFF) ->
https://drive.google.com/file/d/1-Jcal8Ct4yNegygBN2-fepBBnGk4ym2b/view?usp=sharing

Video - Open tab in background (ON) ->
https://drive.google.com/file/d/1-HvxK3qjK4S1jq-NqnPmBu863xo6j5eB/view?usp=sharing

Device -> Redmi Go
Android version -> 8.1.0

**Comment by macgills** [comment] 2020-09-22 09:08
Could you try to reproduce this on our beta release to google play? You can signup through the play store

**Comment by abhijeetsinghcode** [comment] 2020-09-22 09:18
> Could you try to reproduce this on our beta release to google play? You can signup through the play store

Ok sir, I will try to replicate this .

**Comment by abhijeetsinghcode** [comment] 2020-09-22 10:22
> Could you try to reproduce this on our beta release to google play? You can signup through the play store



> Could you try to reproduce this on our beta release to google play? You can signup through the play store

**Kiwiz , WIkipedia offline(Beta)**
 There is difference ->
In the Reader section 
An Article  is open Tab -1 .
Now when I add tab - 2 ,same  article appear on  tab - 1 and in tab - 2.
Now I have one article in two tab.

Now I click on Library and open new article tab it become tab -1  with different article which I opened.
Now I click on Reader section it has same pervious article on both tab - 1 and tab - 2

Video - Open tab in background (OFF) ->
https://drive.google.com/file/d/1-Jcal8Ct4yNegygBN2-fepBBnGk4ym2b/view?usp=sharing

Video - Open tab in background (ON) ->
https://drive.google.com/file/d/1-HvxK3qjK4S1jq-NqnPmBu863xo6j5eB/view?usp=sharing

Device -> Redmi Go
Android version -> 8.1.0

**Comment by gouri-panda** [comment] 2020-12-01 09:20
@macgills  I want to work on this issue ;)

**Comment by gouri-panda** [comment] 2020-12-03 11:58
@kelson42 I discussed with @macgills. It's not a bug. We don't support Multizim tabs yet. @macgills @kelson42 What should we do with this issue? Should we wait for #2168 to complete or close this?

**Comment by macgills** [comment] 2020-12-03 12:00
closing as dupe

**Closed by macgills** 2020-12-03 12:00 UTC
Labels: bug
