### ISSUE TITLE
kiwix isn't usable any more after downloading wp-de (40GB) to a fat32 sd card on arm64

### ISSUE THREAD

**Issue by JensKorte** [kiwix/kiwix-android#3457] opened 2023-07-22 10:04 UTC
I know that fat32 and splitting zims isn't supported any more, see #2085 https://github.com/kiwix/kiwix-tools/issues/287 .

I post an extra bug report for the FP3, kiwix 3.6 doesn't get beyond "Please grant access to all files".

## Using a Fairphone 3 (arm64), kiwix 2.4

kiwix does offer to download the wp-de 40GB file and saves it splitted into zimaa and so on. After finishing the download I get the "Get content" screen (translated from german) and I can start a new download but after a minute the app seems to crash partly and I get back to "Get content".

To me it seems like kiwix tries to analyze the splitted zim file and crashes.

## Fairphone 3, kiwix 3.6

Using kiwix I finally get the message "To use content offline you need to grant access to the storage" (translated from "Um auf Offlineinhalt zuzugreifen, müssen wir auf Ihren Speicher zugreifen"). I granted all the rights: 1. Android preferences -> Apps -> Kiwix -> Permissions (allowed all) 2. Android preferences -> Apps -> Special App-access -> Access on all files (kiwix allowed).

Rebooting doesn't change anything.

## Fairphone 2, kiwix 3.6

Using a Fairphone 2 (arm32) kiwix works without problems with the same sd card and the splitting zim file.

**Expected behavior**

Post a warning "ZIM files >4GB are not supported any more on fat32 filesystems. You may continue but may experience problems. In case of problems delete the files in a file manager." 

## Environments

- Version of Kiwix Android : 2.4 from F-Droid
- Device : Fairphone 3
- OS version : LineageOS 20-20230704-microG-FP3 (this is the LOS from microG, not the original one!)

- Version of Kiwix Android : 3.6 from IzzyOnDroid
- Device : Fairphone 3
- OS version : LineageOS 20-20230704-microG-FP3 (this is the LOS from microG, not the original one!)

- Version of Kiwix Android : 3.6 from IzzyOnDroid
- Device : Fairphone 2
- OS version : lineage_FP2-userdebug 11 RQ3A.211001.0018b341da986

**Comment by MohitMaliFtechiz** [comment] 2023-08-05 12:35
@JensKorte Thanks for reporting the issue.

> kiwix does offer to download the wp-de 40GB file and saves it splitted into zimaa and so on. After finishing the download I get the "Get content" screen (translated from german) and I can start a new download but after a minute the app seems to crash partly and I get back to "Get content".
To me it seems like kiwix tries to analyze the splitted zim file and crashes.

It 

> Using kiwix I finally get the message "To use content offline you need to grant access to the storage" (translated from "Um auf Offlineinhalt zuzugreifen, müssen wir auf Ihren Speicher zugreifen"). I granted all the rights: 1. Android preferences -> Apps -> Kiwix -> Permissions (allowed all) 2. Android preferences -> Apps -> Special App-access -> Access on all files (kiwix allowed).
Rebooting doesn't change anything.

Have you try this with 3.7.1 .

> Using a Fairphone 2 (arm32) kiwix works without problems with the same sd card and the splitting zim file.

This indicates that the issue is not related to the code since both devices run on different API levels. The Fairphone 2 runs on [Android 5.1](https://www.gadgets360.com/fairphone-2-3058), and Fairphone 3 runs on [Android 9 to Android 13](https://www.gsmarena.com/fairphone_3-10397.php). It seems to be a permission issue (which is already fixed in 3.7.1) as discussed in https://github.com/kiwix/kiwix-android/issues/3458. Please try version 3.7.1 and let us know if you encounter any further problems.

> Expected behavior
Post a warning "ZIM files >4GB are not supported any more on fat32 filesystems. You may continue but may experience problems. In case of problems delete the files in a file manager."

We are showing the error message to user if the filesystem is not supported files over 4GB as discussed in #3458.

**Comment by kelson42** [comment] 2023-08-27 05:03
@JensKorte Can you please give feedback and test with latest nightly https://download.kiwix.org/nightly/

**Comment by JensKorte** [comment] 2023-08-28 12:41
On a FP2, filesystem created with "mkfs.fat  /dev/sdX" and a 10GB download I get (translated from german) "Your filesystem doesn't support files bigger then 4GB".  Version: kiwix-universal-2023-08-27.apk

**Comment by kelson42** [comment] 2023-08-29 02:40
@JensKorte Seems appropriate error message to me!

**Closed** 2023-08-29 02:42 UTC
Labels: question
