### ISSUE TITLE
disabled videojs widget with youscribe_audiobooks

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-android#1769] opened 2020-02-13 13:01 UTC
**Describe the bug**
Using [youscribe_audiobooks ZIM](download.kiwix.org/zim/other/youscribe_fr_audiobooks_2020-01.zim), both @kelson42 and @Popolechien reported frequently facing _disabled videojs widgets_.

This renders the the ZIM file unusable on android.

**Steps to reproduce the behavior:**
1. Open ZIM
2. Try various titles and check that the widget is enabled/usable

Reports were on the following titles (use search): `albatros` and `Chat et souris`, `Frankenstein`.

Please note that:

* Regular chrome accessing a kiwix-serve serving same ZIM on the same device is not affected.
* kiwix for macOS is not affected.
* kiwix iOS is not affected.
* screenshot-mentioned files have been compared with working ones and are using very same codec and properties.

**Screenshots**
![73929019-fc7f8d00-48cb-11ea-85ea-8187b0439cbb](https://user-images.githubusercontent.com/57929/74437219-b001f780-4e5f-11ea-8140-6b8ce50fb27c.png)
![Screenshot_20200203_090354_org kiwix kiwixmobile](https://user-images.githubusercontent.com/57929/74437226-b1cbbb00-4e5f-11ea-9efc-f760724166d7.jpg)
![Screenshot_20200207-093222](https://user-images.githubusercontent.com/57929/74437231-b3957e80-4e5f-11ea-8060-39d66a1a79cc.png)

**Environment**
@kelson42 @Popolechien can you please share your device/env information ?
- Version of Kiwix Android : 
- Device : 
- OS version :

**Comment by Popolechien** [comment] 2020-02-13 13:15
Kiwix Android : 3.1.3 build 6230103

 Huawei P20 lite

 Android 9

**Comment by macgills** [comment] 2020-02-13 17:18
So how video reading works is like so 
```
  private fun loadVideo(uri: Uri): ParcelFileDescriptor {
    val infoPair = jniKiwixReader.getDirectAccessInformation(uri.filePath)
    if (infoPair == null || !File(infoPair.filename).exists()) {
      return loadVideoFromCache(uri)
    }
    Log.e("OFFSETS", "$uri ${infoPair.offset}")
    return dup(infoPair.fileDescriptor)
```

The issue is arising in the `dup(infoPair.fileDescritor)` which creates a file pointing to the zim file but with an offset(start location of content) that it gets from infoPair. The offset in infoPair is negative causing an exception to be thrown
```
    java.io.IOException: offset < 0: -42882599
        at java.io.RandomAccessFile.seek(RandomAccessFile.java:584)
        at org.kiwix.kiwixmobile.core.reader.ZimFileReaderKt.getFileDescriptor(ZimFileReader.kt:262)
```

It seems to me that negative offsets in the infoPair should be invalid. @mgautierfr may be able to shed more light more here

**Comment by kelson42** [comment] 2020-02-13 17:42
@macgills Might that be that we have here simply a typing problem (unsigned versus signed) for example?

**Comment by macgills** [comment] 2020-02-14 08:20
```
package org.kiwix.kiwixlib;

public class Pair {
  public String filename;
  public int offset;

  public Pair() {
  }
}
```
there is no possible way for this information to cross the JNI bridge, an int in java is 32 bits. Even still we would be in a lot of trouble if an unsigned 64 bit long came across. Would probably have to represent it via `BigNumber`

**Comment by kelson42** [comment] 2020-02-14 11:19
@macgills @mgautierfr Nice we have identified the root cause. I let you discuss the solution. Obviously this is a quite serious/urgent problem.

Remark: For good or bad reasons, I would not be surprised if we the root cause of #1659 is the same or a similar problem.

**Comment by macgills** [comment] 2020-02-14 11:32
The current theory on #1659 is that some videofiles are stored adjacent within the zim file, the android api does not currently give us a way of specifying the length of the content we pass as a file descriptor to the webview to get played so it happily continues parsing video bytes until it encounters an error. That is the theory anyways.

**Comment by macgills** [comment] 2020-02-14 11:42
On the topic of a solution: just using Long in the JNI should be fine because we will have a positive range of 0-9,223,372,036,854,775,807 bytes for an offset before hitting negative values which is quite a lot
![image](https://user-images.githubusercontent.com/3358282/74527971-fb2f0f80-4f1e-11ea-9837-78a4a8a07a1d.png)

**Comment by kelson42** [comment] 2020-02-18 13:24
@mgautierfr Could you please fix this typing problem and release a test kiwixlib for @macgills ?

**Comment by macgills** [comment] 2020-02-19 09:13
We have some partial success
![image](https://user-images.githubusercontent.com/3358282/74819188-e9bb7e00-52f7-11ea-9f08-9f2ccaaaa184.png)

```
E/chromium: [ERROR:batching_media_log.cc(26)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"FFmpegDemuxer: open context failed"}
E/chromium: [ERROR:batching_media_log.cc(26)] MediaEvent: PIPELINE_ERROR DEMUXER_ERROR_COULD_NOT_OPEN
```

I will investigate these errors that are affecting the disabled audio files

**Comment by macgills** [comment] 2020-02-19 09:58
I am unsure how to progress as this seems to be a chromium error? My WebView implementation is supplied by Chrome 80.0.3987.99 . This answer doesn't fill me with confidence as in the description it says it was working fine on kiwix-serve.

All I can find when googling is people complaining about chrome 67.

If @rgaudin or @kelson42 want to contact me on slack I can share an apk so they can test with their webviews as hopefully this is just somehow a me problem.

Or [this](https://phabricator.wikimedia.org/T164520) could form a basis of a solution? I am a bit skeptical

**Comment by macgills** [comment] 2020-02-25 14:01
Closing as duplicate of #1659

**Closed by macgills** 2020-02-25 14:01 UTC
Labels: bug
