### ISSUE TITLE
EmptyView overlaps with the content

### ISSUE THREAD

**Issue by harshvardhan-takawale** [kiwix/kiwix-android#684] opened 2018-04-01 12:34 UTC
### Environment
  * version of the software you use: 2.3 Build: 55
  * device / operating system: Moto G4 Plus
  
### The Bug:

The Empty View overlaps with the content in the ZimManagerActivity.

There are no proper steps to reproduce it, although I did it by loading the content, turning off and on the data and refreshing the list.

### ScreenShot

![kiwix_overlap1](https://user-images.githubusercontent.com/28982436/38173172-f745f248-35d6-11e8-812e-e3fb73214ee2.png)
![kiwix_overlap2](https://user-images.githubusercontent.com/28982436/38173175-07c3e206-35d7-11e8-9ac2-12b019585722.png)

**Comment by Rahul5758** [comment] 2018-04-01 17:57
@harshvardhan-takawale I also faced the same issue on Moto G4 Plus mobile.
![shared1](https://user-images.githubusercontent.com/26683036/38175996-18c643f0-3604-11e8-84e9-e2326157d11c.jpg)

**Comment by brijeshshah13** [comment] 2018-04-02 03:21
@mhutti1 I confirm the existence of this bug. @harshvardhan-takawale Would you like to resolve this?

**Comment by harshvardhan-takawale** [comment] 2018-04-02 06:18
@brijeshshah13 I wish to work on the issue but I am unable to reproduce the bug reliably so testing whether it is solved or not is difficult.

**Comment by brijeshshah13** [comment] 2018-04-02 09:01
@harshvardhan-takawale I will try to reproduce the bug and update this comment when I find do.

**Comment by hjoshi123** [comment] 2018-04-02 13:16
@harshvardhan-takawale How did you get the bug? I am not able to reproduce it. I want to work on this.

**Comment by harshvardhan-takawale** [comment] 2018-04-03 04:37
@hjoshi123 As I said, I get this bug sometimes when I follow the steps mentioned above but it is not a completely reliable method to reproduce the bug

**Comment by Rahul5758** [comment] 2018-04-03 14:31
@harshvardhan-takawale Please share the apk you are using.

**Comment by iadeelzafar** [comment] 2019-03-11 08:53
@abdulwd This bug is still present. I think we should label it as a 'good first issue' for new contributors.

**Comment by ChandanNaik999** [comment] 2019-04-07 19:21
I would like to take upon this issue as no one is working on it.

**Comment by ChandanNaik999** [comment] 2019-04-14 13:19
can I take this issue?

**Comment by prajurock** [comment] 2019-04-14 13:21
Yes I think.

**Comment by jhbiggs** [comment] 2019-06-10 15:24
I'd like to have a look.  Is there a reliable way to reproduce it yet?

**Comment by kelson42** [comment] 2019-06-10 16:03
@jhbiggs Looks like this is not straight to reproduce
@macgills Might that be that this bug is already fixed in 2.5?

**Comment by macgills** [comment] 2019-06-13 09:36
This is already fixed in 2.5. I will close this ticket accordingly

**Closed by macgills** 2019-06-13 09:36 UTC
Labels: bug, good first issue
