### ISSUE TITLE
App crashes on clicking pause button for download in Landscape mode.

### ISSUE THREAD

**Issue by rohap97** [kiwix/kiwix-android#990] opened 2019-02-15 21:38 UTC
**Describe the bug**

App crashes when we click pause button for download in Landscape mode.

**Steps to reproduce the behavior:**
1. Start Downloading a .zim file
2. Go to Downloading tab.
3. Rotate the screen to Landscape mode.
4. Click the pause button for ongoing download.
5. App crashes

**Environment**
- Version of Kiwix Android : 2.4 Build: 55
- Device :  Lenovo Vibe K5 Note
- OS version : Android 6.0

**Comment by MisterAwesome23** [comment] 2019-02-21 17:39
It seems like downloadFragment.listView.invalidateViews();
doesn't know which orientation to move into. I'd like to work on this can anyone guide me? I am sort of a beginner to android.

**Comment by mhutti1** [comment] 2019-02-21 20:26
@MisterAwesome23 The general way to go about fixing something like this is to first reproduce it on a device you have. Then get a stacktrace for it. Using this work out where the code is incorrect and attempt to change it so you no longer crash.

**Comment by MisterAwesome23** [comment] 2019-02-21 20:28
What exactly is stack tracing. I performed the crash and noted the log cat for reason for crash that is from where I got the list view fragment function. Is there better ways to debug/stack trace or log cat is the right way.
I am pretty new to debugging too, any idea how to grap onto debugging quickly, like any course or resources?

**Comment by mhutti1** [comment] 2019-02-22 00:47
@MisterAwesome23 RE stacktracing yeah use you can use logcat. RE debugging its mostly something you just need to practise imo but there might be some good tutorials on Google.

**Comment by ShridharGoel** [comment] 2019-03-07 10:39
Can I take this up?

**Comment by abdulwd** [comment] 2019-03-07 17:39
@ShridharGoel You can work on it. I think @MisterAwesome23 is not working on this.

**Comment by iadeelzafar** [comment] 2019-03-07 17:43
I tried to reproduce this today but i couldn't reproduce this. 
@abdulwd @shridharghoel can you?

**Comment by ShridharGoel** [comment] 2019-03-07 18:02
Yes I'm able to reproduce it.

**Comment by iadeelzafar** [comment] 2019-03-07 19:08
@ShridharGoel Alright. Good Luck.

**Comment by ShridharGoel** [comment] 2019-03-07 21:10
@iadeelzafar Thanks.

**Comment by macgills** [comment] 2019-05-27 10:51
Fixed in #1170

**Closed by macgills** 2019-05-27 10:51 UTC
Labels: bug
