### ISSUE TITLE
Empty UI of Bookmarks and History

### ISSUE THREAD

**Issue by yashk2000** [kiwix/kiwix-android#1708] opened 2020-01-22 18:51 UTC
**Describe the solution you'd like**
Currently, if there are no bookmarks or no history, the activities are just blank white screens which don't look very good. Instead, a small message such as "No bookmarks yet" and "No history yet" could be displayed in case there aren't any.

**Describe alternatives you've considered**
Whenever the history or bookmark activity is opened or refreshed, check whether the list is empty. If empty, display an appropriate message. 

**Additional context**

A screenshot of the proposed change is:
![screencap](https://user-images.githubusercontent.com/41234408/72923849-d4dde000-3d75-11ea-85e5-6459068e56fb.png)

I would like to work on this issue.

**Comment by kelson42** [comment] 2020-01-22 18:56
This is to a large extend a duplicate of #1058

**Comment by yashk2000** [comment] 2020-01-22 19:01
@kelson42 thanks for pointing out. Once I am done with this issue, I'll work on #1058 too.

**Comment by kelson42** [comment] 2020-01-22 19:38
@yashk2000 thx

**Closed** 2020-01-27 13:41 UTC
Labels: UI, enhancement, good first issue
