### ISSUE TITLE
Kiwix-android 3.3.1 does not pick up zim file

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#2163] opened 2020-06-25 06:27 UTC
From freshdesk with a disposable email address, so feel free to close if there is not enough info:

"My mobile is Sony Xperia XZ1compact (Android 9, Ver. 47.2.A.11.228), using kiwix Ver. 3.3.1 Build: 6230301.
The problem: the file wikipedia_de_all_maxi_2020-06.zim,
(downloaded from https://download.kiwix.org/zim/wikipedia/, md5sum 75ed07bf09c45d54e6af3628906f702f),
is not picked up by kiwix (in ->Settings->Library->Device, persistent rotating circle).
Same problem with wikipedia_de_all_nopic_2020-06.zim.
I checked the md5sum to make sure the zim-file was copied correctly onto the sdcard.
wikipedia_de_all_maxi_2020-05.zim is working as intended, a fresh install of kiwix did not help.
I would gladly hear about any solution or progress to this problem."

**Comment by macgills** [comment] 2020-06-25 14:33
The neverending circle says to me that we are trying to determine their filesystem using our fallback of writing a 4GB test file.

If you can ask the user to send a Diagnostic Report from the Help screen I might be able to do something.

**Comment by florian29** [comment] 2020-06-29 17:38
I confirm the issue for wikipedia_es_all_maxi_2020-06.zim. The problem is with the new ZIM files from June 2020, there was changed something in the format of the ZIM. Also Kiwix Desktop for Win64 can't open these files anymore. Read this: https://github.com/kiwix/kiwix-desktop/issues/458 and this: https://github.com/kiwix/kiwix-js/issues/629
Jaifroid made a fix yet for Kiwix JS, but obviously someone has to care about fixing this issue for the other platforms too, including for Android.

**Comment by kelson42** [comment] 2020-06-29 17:42
@florian29 Thank you for going through all the ports and checking the problem/solution. We will release a new maintenance release (planned anyway in the next few days). Hope you will able to subscribe to the beta tester group and tell us if this is fixed.

**Comment by kelson42** [comment] 2020-06-29 17:42
Seems a duplicate of https://github.com/openzim/libzim/issues/353

**Comment by Popolechien** [comment] 2020-07-02 05:52
In the meantime the original user has replied:

"Ok, if I wait about 10 mins, the file finally shows up on Library screen, but the circe is still rotating.
Selecting the file freezes the app and everything completely, until Android kicks in and let me finish the app.
Since wikipedia_de_all_maxi_2020-05.zim does not show an neverending circle, but works entirely as intended, I do not think that has anything to do with the 4GB boundary."

**Comment by kelson42** [comment] 2020-07-02 08:48
@Popolechien Thx for your feedback, to me this confirme that this is a duplicate of https://github.com/openzim/libzim/issues/353. Fixed in 3.3.2 to come in beta today or tomorrow.

**Closed by kelson42** 2020-07-02 08:48 UTC
Labels: bug

**Comment by florian29** [comment] 2020-07-02 19:08
>  Fixed in 3.3.2 to come in beta today or tomorrow.

3.3.2 doesn't work for me. App crashes on opening. (Android 4.4.4, tested with Samsung S4 mini and also with Bluestacks App Player Android 4.4.4)
