### ISSUE TITLE
Broken downloads, incompatibility with Blokada

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#1304] opened 2019-07-22 08:50 UTC
From @bernhardino

>  I had the same issue a week ago. I've tried four times to download the whole german content of wikipedia (33GB), and each time the download stopped after about 12GB (Galaxy S9, 254GB, with Android 9, not rooted). As I'm also a android app dev in my spare time, maybe I can give you some more informations if you tell me which one you need. 

<s>
A user reported the following scenario:
- tried to download a zim file;
- Download window indicates "pending";
- Nothing more happens.

Kiwix Version 2.5.1  Build 220501
Sony Xperia XA   F3113
Android version 7.0 Build number 33.3.A.1.126
</s>
Original ticket (because this one has been highjacked by the Blokada incompatibility) moved to #459

**Comment by kelson42** [comment] 2019-07-22 09:13
@macgills We need here a bit more error reporting probably.

**Comment by Bernhardino** [comment] 2019-07-22 13:43
I had the same issue a week ago. I've tried four times to download the whole german content of wikipedia (33GB), and each time the download stopped after about 12GB (Galaxy S9, 254GB, with Android 9, not rooted). As I'm also a android app dev in my spare time, maybe I can give you some more informations if you tell me which one you need.

**Comment by kelson42** [comment] 2019-07-22 14:31
@Bernhardino Thank you for your feedback and your offer. Do you see anything special in the Android log when this happens?

**Comment by Bernhardino** [comment] 2019-07-22 15:14
@kelson42 Actually, in this moment I'm trying to download within Kiwix a 24GB zim file to see if the action stopps again. But if I remember properly, my error message wasn't "pending" like above but something like "Can't be downloaded". Anyway, in one hour, I'll know more ...

**Comment by Bernhardino** [comment] 2019-07-22 15:26
Bingo, my download failed ("HTTP data error"). In the log, i found only these two lines:

2019-07-22 17:15:05.991 6860-15915/? D/DownloadManager: [3795] Starting org.kiwix.kiwixmobile
2019-07-22 17:15:06.113 6860-15383/? W/DownloadManager: [3795] Stop requested with status HTTP_DATA_ERROR: Local halt requested; job probably timed out

If it is of use, I can send to you the last minutes of the log. But it seems to me that it's rather a problem of communication than of Kiwix, isn't it?

**Comment by Bernhardino** [comment] 2019-07-23 00:36
@kelson42 I did some further tests and found that Kiwix has (at least on my smartphone) a problem with Blokada, a popular ad blocker (not in App Store, Google won't allow that). If Blockada is activ, the download window of Kiwix shows "pending", and nothing happens, as described in the first post. I use Blockade for half a year and had absolutly no problems 'till now with it, that's the very first negative impact of Blockada. Mayby the user in posting #1 also had Blockad installed?

**Comment by macgills** [comment] 2019-07-23 09:27
https://github.com/kiwix/kiwix-android/blob/develop/app/src/main/java/org/kiwix/kiwixmobile/downloader/model/DownloadStatus.kt We just report the errors the [DownloadManager](https://developer.android.com/reference/android/app/DownloadManager) reports to us. We could show a retry button when we enter the FAILED state and encourage the user to turn on wifi only downloading as that might have an easier time of guaranteeing a successful download

**Comment by kelson42** [comment] 2019-07-24 11:18
@Bernhardino Thank you for the report, so deactivating Blockada and everything works fine?
@macgills Two remarks:
* It should autoretry
* Error should be printed (seems not to be the case in the first report of @Popolechien).

**Comment by macgills** [comment] 2019-07-24 11:24
@kelson42 Errors are always printed, I give as much information as I get. If it was Pending then the downloadManager was telling me that the download was pending.

Re retry: then we need to define auto retry logic.
How many times do we retry?
What is the backoff between retries?
How do we alert the user that a retry is now being attempted?

The easiest solution is just to show a retry button on failure to give the user control, they might be able to figure out why it errored better than I can eg they connected to a poor connection, there was a mobile data outage, firewall problem, adblocker installed etc

**Comment by kelson42** [comment] 2019-07-24 11:27
@macgills Does a retry will reastart from offset 0?

**Comment by macgills** [comment] 2019-07-24 11:34
Yes, if it has gone to failed the downloadManager will have deleted the file it was downloading, there is no retry functionality for it

**Comment by macgills** [comment] 2019-07-24 11:40
Ahhh a thought: blockada might not play well with http traffic, we really should be using https only, the android ecosystem gets ever more insistent on it

**Comment by Bernhardino** [comment] 2019-07-24 21:58
@kelson42 Sorry to answer so late. Yes, on my Galaxy S9 with Android 9 I've able to reproduce this effect (5x): With Blockada the error "Pending" in the download window of Kiwix from the very first second on, and then for 2 hours nothing happens (then I stopped the "download"); without Blockada, no problems with the desired download. But to be honest, I don't understand this, because Blockada has a log file at its own, and there I see, that kiwix.org is NOT blocked (see screenshot).
![Screenshot_Blokada](https://user-images.githubusercontent.com/44344692/61830743-3925f280-ae6c-11e9-8146-3613907d931e.png)

So I look at the Android catlog. There is a interesting line with the first difference, each time the fourth date ("networkInfo: type:WIFI" vs. "VPN"). Maybe that will help you:

************* without Blockada, working:
2019-07-24 23:28:14.692 18726-28514/? D/OkHttp: <-- 200 OK http://download.kiwix.org/zim/wikisource/wikisource_de_all_novid_2018-10.zim.meta4 (123ms, unknown-length body)
2019-07-24 23:28:14.901 6560-8652/? W/DownloadManager: Path appears to be invalid: /storage/emulated/0/Kiwix/wikisource_de_all_novid_2018-10.zim
2019-07-24 23:28:14.970 4860-16350/? D/ConnectivityService: filterNetworkStateForUid() uid: 10745, pid: 4860
2019-07-24 23:28:14.970 4860-16350/? D/ConnectivityService: filterNetworkStateForUid() uid: 10745, pid: 4860, networkInfo: [type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: (none), failover: false, available: true, roaming: false]
2019-07-24 23:28:15.044 4860-5063/? D/WifiTrafficPoller: TrafficStats TxPkts=197536 RxPkts=429848 TxBytes=16394962 RxBytes=572039781 , Foreground uid=10745 pkgName=org.kiwix.kiwixmobile TxPackets=97314 RxPackets=243757 TxBytes=5304741 RxBytes=355721335
2019-07-24 23:28:15.046 5163-5163/? D/SecStatusBarWifiView: updateState: WifiIconState(resId=2131232588, visible=true, activityId=2131232594)
2019-07-24 23:28:15.048 6560-28572/? D/DownloadManager: [3885] Starting org.kiwix.kiwixmobile

************* with Blockada, NOT working:
2019-07-24 22:52:07.838 18726-24738/? D/OkHttp: <-- 200 OK http://download.kiwix.org/zim/wikiquote/wikiquote_de_all_nopic_2019-06.zim.meta4 (147ms, 3082-byte body)
2019-07-24 22:52:07.868 6560-21791/? W/DownloadManager: Path appears to be invalid: /storage/emulated/0/Kiwix/wikiquote_de_all_nopic_2019-06.zim
2019-07-24 22:52:07.915 4860-4888/? D/ConnectivityService: filterNetworkStateForUid() uid: 10745, pid: 4860
2019-07-24 22:52:07.915 4860-4888/? D/ConnectivityService: filterNetworkStateForUid() uid: 10745, pid: 4860, networkInfo: [type: VPN[], state: CONNECTED/CONNECTED, reason: agentConnect, extra: (none), failover: false, available: true, roaming: false]
2019-07-24 22:52:08.053 4860-24796/? D/WifiConnectivityMonitor.DnsPingerHandler: setCurrentLinkProperties: lp={InterfaceName: wlan0 LinkAddresses: [fe80::4a56:2e87:6e75:4cc4/64,192.168.0.108/24,]  Routes: [fe80::/64 -> :: wlan0,192.168.0.0/24 -> 0.0.0.0 wlan0,0.0.0.0/0 -> 192.168.0.1 wlan0,] DnsAddresses: [62.2.24.158,62.2.17.60,62.2.24.162,62.2.17.61,] UsePrivateDns: false PrivateDnsServerName: null Domains: home MTU: 0 TcpBufferSizes: 524288,1048576,4194304,524288,1048576,4194304}
2019-07-24 22:52:08.158 4860-24797/? D/WifiPermissionsUtil: canAccessScanResults: pkgName = android, uid = 1000
2019-07-24 22:52:08.161 4860-24797/? D/WifiConnectivityMonitor.DnsPingerHandler: #1 GW MAC address found in ARP table.1 msec.
2019-07-24 22:52:08.414 4860-24797/? D/WifiConnectivityMonitor.DnsThread:  [|245] [] [] []
2019-07-24 22:52:08.415 4860-5115/? D/WifiConnectivityMonitor: DNS resultType : 0, responseTime : 245
2019-07-24 22:52:08.502 4860-5063/? D/WifiTrafficPoller: TrafficStats TxPkts=177847 RxPkts=378581 TxBytes=15218254 RxBytes=499122809 , Foreground uid=10745 pkgName=org.kiwix.kiwixmobile TxPackets=78724 RxPackets=194072 TxBytes=4293273 RxBytes=283232285

**Comment by kelson42** [comment] 2019-07-27 07:40
download.kiwix.org is only a redirecting solution, then the download is routed to a mirror, here mirror.download.kiwix.org. But it can be an other download mirror. So it can also happen than an other mirror was needed. FYI, AFAIK mirror.download.kiwix.org is the only HTTP mirror, all the other ones are HTTPs.

@macgills I wonder what we can do here... to me the main problem is only that we have no feedabck on the Kiwix screen, it just says "Pending"  although in the log an error seems to happen (@Bernhardino you confirm?).

**Comment by macgills** [comment] 2019-07-29 08:31
We could add some text somewhere? A one time message that pops up on first download? "You may have to disable ad blockers to download zim files".
I am showing as much information as is provided to me by downloadmanager

**Comment by kelson42** [comment] 2019-07-29 08:35
@macgills I wonder why the downloader/Kiwix does not already report and error. Do you know why?

**Comment by macgills** [comment] 2019-07-29 09:17
https://github.com/blokadaorg/blokada/issues/324 found it

**Comment by kelson42** [comment] 2019-07-29 09:32
So, what I see here is that the whole thread is about Blokada... but this does not fit or give a response to the original but report from @Popolechien. I'll open a new ticket #459

**Comment by julianharty** [comment] 2019-08-09 10:23
> download.kiwix.org is only a redirecting solution, then the download is routed to a mirror, here mirror.download.kiwix.org. But it can be an other download mirror. So it can also happen than an other mirror was needed. FYI, AFAIK mirror.download.kiwix.org is the only HTTP mirror, all the other ones are HTTPs.
> 
> @macgills I wonder what we can do here... to me the main problem is only that we have no feedabck on the Kiwix screen, it just says "Pending" although in the log an error seems to happen (@Bernhardino you confirm?).

@kelson42 @macgills FYI a year or so ago we had issues reported on the download mirror used for users in India. IIRC there were issues downloading the content using HTTPS (on older Android OS Releases) see #510 for the background. Perhaps it's worth testing any changes on old, mid-range devices (I have several and can test changes when you ask me).

**Comment by kelson42** [comment] 2019-08-23 16:01
@macgills Does moving to Fetch would help here?

**Comment by macgills** [comment] 2019-08-26 08:20
Yes, users would be able to whitelist our app through blokada

**Closed** 2019-09-11 08:57 UTC
Labels: bug
