### ISSUE TITLE
Clicking Sub topics in right drawer doesn't work

### ISSUE THREAD

**Issue by yash1ts** [kiwix/kiwix-android#1969] opened 2020-03-26 17:39 UTC
**Describe the bug**
Clicking subtopics in the right drawer should scroll the current page to that topic as clicking topics does. It just closes the drawer.

**Expected behavior**
On clicking the subtopic the page should scroll to that topic.

**Steps to reproduce the behavior:**
1. Open any book.
2. Open right drawer from bottom nav bar.
3. Click on any sub-topic.
bug- Closes the drawer but no page scrolled.

**Comment by 4shutosh** [comment] 2020-03-27 05:02
The issue is not described well.
It happens when the main parent heading view is collapsed and is required to be expanded for the suptopic drawer item to work.
I think the drawer works fine in other cases.

**Comment by yash1ts** [comment] 2020-03-27 09:16
@4shutosh I agree with you, I didn't see that at first. The clicking doesn't work because the heading is collapsed. As a result, the page is not scrolled on clicking subtopics.

**Comment by macgills** [comment] 2020-03-27 15:49
duplicate of #309 closing

**Closed by macgills** 2020-03-27 15:49 UTC
