### ISSUE TITLE
Mobile Network permission dialog doesn't show

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#2839] opened 2022-05-17 19:30 UTC
**Describe the bug**
The network permission dialog doesn't show if we re-click the download section.
**Expected behavior**
It should show permission dialog.

**Steps to reproduce the behavior:**
1. Fresh install the app or remove network permission from the settings
2. Open the app and go to the download section (you can see the network permission dialog)
3. click the 'no' option
4. click the download tab again
5. Observe there will be no permission dialog

**Environment**
- Version of Kiwix Android: 3.4.6
- Device: Pixel
- OS version: 11

**Comment by kelson42** [comment] 2022-05-18 04:39
@MohitMaliFtechiz @gouri-panda This seems quite critical to me because in such a scenario user can not download at all and there is nothing in the app he ca do. Right?

**Comment by MohitMaliFtechiz** [comment] 2022-05-18 04:48
> @MohitMaliFtechiz @gouri-panda This seems quite critical to me because in such a scenario user can not download at all and there is nothing in the app he ca do. Right?

Ok @kelson , i will place fix for this bug.

**Comment by gouri-panda** [comment] 2022-05-18 04:51
@kelson42 Yes, but if it relaunchs again, then it will show the network dialogue.

**Comment by kelson42** [comment] 2022-05-18 05:19
@gouri-panda Ok, but considering that ending/starting an app in Android is pretty unclear. I already see the bug reports. I think we should still fix it in `3.5.0`. Is that a regression?

**Comment by gouri-panda** [comment] 2022-05-18 07:37
No, I don't think it's not a regression. Yes, we should fix in 3.5.

**Closed** 2022-05-19 13:18 UTC
Labels: bug
