### ISSUE TITLE
Release 2.4 on F-Droid

### ISSUE THREAD

**Issue by tbertels** [kiwix/kiwix-android#730] opened 2018-05-06 07:51 UTC
### Environment
  * version of the software you use : Kiwix 2.2 (53)
  * device / operating system : 6.0.1
  
### The Bug:
Based on the [CHANGELOG](https://github.com/kiwix/kiwix-android/blob/master/CHANGELOG), the latest version is 2.3.
From #247 it seems at least some users have the version 2.3

**Comment by tbertels** [comment] 2018-05-06 08:03
You may also want to [publish a more recent version on open beta](https://support.google.com/googleplay/android-developer/answer/3131213).

**Comment by tbertels** [comment] 2018-05-06 08:17
With version 2.3 adding improvements like remaining time and full interface translation, you may want to release it before 3.0.
While some apps get updates without noticeable changes, this is really not the case of Kiwix, which could use a little more frequent updates.

**Comment by mhutti1** [comment] 2018-05-09 11:44
2.3 started to be rolled out however it caused crashes on a small but significant proportion of devices that took a very long time to track down. As such we didn't continue with the roll out and have been working on fixing these issues. (They should all now be fixed on master). We will hopefully release 2.4 soon and will ensure it is on fdroid.

**Comment by tbertels** [comment] 2018-05-10 09:37
Thanks for the info! I'm looking forward to 2.4!

**Comment by kelson42** [comment] 2018-08-05 09:45
2.4 is currently being rolled out on Google Play.

**Comment by kelson42** [comment] 2018-09-19 10:49
Seems to be a duplicate of https://github.com/kiwix/kiwix-android/issues/61

**Closed by kelson42** 2018-09-19 10:49 UTC
Labels: release
