### ISSUE TITLE
Bookmarked articles indicate path instead of article name (if missing "title" node)

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#214] opened 2017-07-24 15:11 UTC
See screenshot
![screenshot_2017-07-24-17-03-05](https://user-images.githubusercontent.com/21675885/28530157-1d769878-7093-11e7-8af9-f38b935fbf44.png)

**Comment by kelson42** [comment] 2017-07-24 15:32
@mhutti1 Unfortunately, we have found an other blocker for our custom app updates... Hope this is nothing big.

**Comment by kelson42** [comment] 2017-07-24 16:00
@EladKeyshawn Any idea? Maybe have you introduced that regressiong with on of your last commits?

**Comment by EladKeyshawn** [comment] 2017-07-24 18:21
@kelson42 I haven't merged any changes so it shouldn't be the problem.

**Comment by kelson42** [comment] 2017-07-24 18:29
@EladKeyshawn I mean this bug might be as old as April/hackathon.

**Comment by mhutti1** [comment] 2017-07-24 22:53
This is a content issue. It is fine for old ZIM files, I am looking into it now.

**Comment by mhutti1** [comment] 2017-07-24 22:58
@kelson42 The title tag of the new ZIM files is empty. I could hack a work around but it would be very messy. Is it possible to have the title tag set correctly?

**Comment by kelson42** [comment] 2017-07-25 04:15
@mhutti1 mhm,,, this is indeed a bug in the ZIM file. This is not a normal situation, but might be good to have a better handling of that case. Need to check how looks the title in the ZIM file index itself. I would try to use it here if the DOM node "title" is missing.

**Comment by kelson42** [comment] 2017-07-25 04:25
I have open that bug on mwoffliner side https://github.com/openzim/mwoffliner/issues/99

**Comment by mhutti1** [comment] 2017-07-25 12:59
@kelson42 There is also title in a header I could probably extract rather than make JNI changes. Trouble is i'm going to need to parse every page before it loads to make this change. The other solution is to rework how titles are handled across the app but this would be a lot of work. Can I confirm if you want me to go ahead with this hack?

**Comment by mgautierfr** [comment] 2017-07-25 13:39
> The title tag of the new ZIM files is empty

Sorry but I don't get it. Of which title tag we are speaking about ?

Are you speaking of the article of the zim itself ? The title of the article in the dirent ? The title in the html head ?

**Comment by mhutti1** [comment] 2017-07-25 13:51
The title in the html head. <title>

**Comment by mgautierfr** [comment] 2017-07-25 14:05
Ok, so of which title you're are speaking about here ? :)

> There is also title in a header I could probably extract rather than make JNI changes. 

I was thinking this sentence was about the html title.

---

The JNI API is pretty poor to be honest. I plan to rewrite it [*].
I could do a small API change to extend
`byte[] getContent(String url, JNIKiwixString mimeType, JNIKiwixInt size);`
to
`byte[] getContent(String url, JNIKiwixString title, JNIKiwixString mimeType, JNIKiwixInt size);`.
This would allow you to get the title from what is in the zim structure directly and not parse the html.

In any case, I suggest to do as minimal changes as possible because big changes will come later for sure.

[*] This is necessary to multi-zim search. And I've already mostly done this rewrite but not committed it  as it would broke android code.

**Comment by mhutti1** [comment] 2017-07-25 14:11
That would be one way of solving the issue and would be better than just
parsing it from the html.

**Comment by mhutti1** [comment] 2017-07-25 14:12
The title I am speaking of there is in a <h> tag I might be able to parse.

**Comment by kelson42** [comment] 2017-07-25 15:51
@mhutti1 Please don't this is Mediawiki specific. What propose @mgautierfr is probably the only solution to that ticket.

**Comment by mhutti1** [comment] 2017-07-25 16:11
Cool. Even that is likely going to be very hacky on the Java side though.
While I can override the getTitle() method. I doubt it's a good idea long
term. Especially with our reliance on content providers.

**Comment by mhutti1** [comment] 2017-07-25 16:13
In fact it would be easier to edit the html while parsing it anyway. So I
guess the solution is too hard set the title to a value returned by the JNI
as specified above.

**Comment by mgautierfr** [comment] 2017-07-26 09:08
@mhutti1, I've updated the API as I've proposed in this PR kiwix/kiwix-lib#74
You can start to update the code on your side. I will merge the PR in kiwix-lib when you want to.

**Comment by mhutti1** [comment] 2017-07-27 23:01
@mgautierfr My changes are ready to merge. They will likely break kiwix-build until kiwix-lib is merged. I have tested them and they seem to integrate well. If you want to go ahead and merge both when you are ready.

**Comment by kelson42** [comment] 2017-08-02 19:05
mwofliner has been fixed and now Mediawiki ZIM files will be generated with HTML pages without title. Fixing the java to deal with such a use case seems (1) almost useless (2) not trivial to do easily. Nothing will be done further here. That said, thx to @mgautierfr to improve JNI in kiwix-lib.

**Closed by kelson42** 2017-08-02 19:05 UTC
Labels: enhancement
