### ISSUE TITLE
Migrate Kiwix Android App to Jetpack Compose

### ISSUE THREAD

**Issue by itsPronay** [kiwix/kiwix-android#3872] opened 2024-06-07 15:31 UTC
[Jetpack Compose](https://developer.android.com/develop/ui/compose) is the modern toolkit for building native Android UIs. By adopting Compose, Kiwix can simplify UI development, improve maintainability, and ensure the app aligns with the latest Android development practices.

Benefits of Jetpack Compose

- **Simplified UI Development**: Compose allows developers to write less code, reducing boilerplate and making the UI code more intuitive and easier to maintain.

- **Improved Performance**: Compose is designed to be more efficient, which can result in better app performance and responsiveness.
- **Better Integration with Kotlin**: Compose is fully Kotlin-based, providing a seamless development experience with Kotlin features like coroutines and flows.
- **Future-Proof**: Google is actively developing and promoting Compose as the future of Android development, ensuring long-term support and innovation.

## Migration can be carried out in 2 phrases, 
In the first migration, we can migrate screens, and then use them with views 
In the second migration, we can remove Fragments and Navigation components 

To get a full idea of how the migration will take place please view official docs on  [Migration strategy](https://developer.android.com/develop/ui/compose/migrate/strategy)

![image](https://github.com/kiwix/kiwix-android/assets/78101731/e64dc95c-70fb-4cb7-99b7-2a4d6647e59f)

**Comment by kelson42** [comment] 2024-06-15 11:20
Duplicate of #2669, we will continue there the discussion.

**Closed by kelson42** 2024-06-15 11:20 UTC
