### ISSUE TITLE
Suggestion search fails on cutting-edge Wikispecies custom app

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#2580] opened 2021-01-15 13:46 UTC
A few hours ago I have released a new Wikispecies custom app:
https://play.google.com/store/apps/details?id=org.kiwix.kiwixcustomwikispecies

Yesterday I failed because of #2578 but this has been fixed and I change the CI of the Kiwix Android Custom Apps to deal with the `develop` branch instead of the usual official release branch `master`. See:
https://github.com/kiwix/kiwix-android-custom/commit/b73f0b5c07b8775d84238b8c217e7b267a83362e

First all seemed first OK and I have put the Wikispecies app in production. Unfortunately I missed an important regression. The problem is that what ever the suggestion I choose in the proposed suggestions, it always load the welcome page. Which make the search/suggestion system useless.

Would be great to identify quickly the problem so I can fix the production release of the Wikispecies custom app (and later updated other app with 3.4.3+ code base).

**Comment by gouri-panda** [comment] 2021-01-19 09:20
I think this is a flaw in PipedInputStream and PipedOutputStream. Once it closes one of the two, the other one is immediately useless. I would have preferred at least that the PipedInputStream would still be able to read what was written up to the point of closing the PipedOutputStream.

**Comment by kelson42** [comment] 2021-01-19 09:29
@gouri-panda Thank you for having a look to that. What is really strange is why this impact only the custom app?

**Comment by gouri-panda** [comment] 2021-01-19 09:53
@kelson42 I just digged the surface. It closes the inputStrreamReader.If one closes the other one will close while throwing  exception. I will definitely check out why this is happening what's the root cause of this problem.

**Comment by kelson42** [comment] 2021-03-05 06:14
@gouri-panda Hi, do you still plan to work on this ticket?

**Comment by gouri-panda** [comment] 2021-03-05 06:43
Yes! @kelson42 Now I'm totally available. Thank you!

**Comment by gouri-panda** [comment] 2021-03-09 13:28
@kelson42 I think the regression was here https://github.com/kiwix/kiwix-android/commit/f3ce4f9916d09178a238de8723e44807f01aa2fc.

**Comment by gouri-panda** [comment] 2021-03-09 13:37
Since the commit is reverted now. It is no longer issue now.

**Comment by kelson42** [comment] 2021-03-09 13:38
@gouri-panda Great news, when was this reverted?

**Comment by gouri-panda** [comment] 2021-03-09 13:45
January 17 https://github.com/kiwix/kiwix-android/commit/24b052e27dfa60423422a4401bc41fc09ea49362. Thanks to @s-ayush2903

**Comment by kelson42** [comment] 2021-03-09 13:57
Argh.... Two days after the Wikispecies app release... Will make a new release and check.

**Closed** 2021-03-10 12:46 UTC
Labels: bug, question
