### ISSUE TITLE
BUG:Error on Rotation of screen on new tabs feature

### ISSUE THREAD

**Issue by gptshubham595** [kiwix/kiwix-android#1152] opened 2019-04-07 15:52 UTC
on turninig screen rotation and once going back this shows unknow rotations and any tabs opened gets it rotation changed on random

**Comment by gptshubham595** [comment] 2019-04-07 16:06
https://vimeo.com/328952168

**Comment by gptshubham595** [comment] 2019-04-07 17:02
@mhutti1 @abdulwd @kelson42 @sonusourav

**Comment by sonusourav** [comment] 2019-04-07 19:14
Duplicate of #948 . If you want you can work on this, however.

**Closed** 2019-04-15 20:34 UTC
