### ISSUE TITLE
Deleting from library does not free up storage

### ISSUE THREAD

**Issue by sunsero** [kiwix/kiwix-android#3767] opened 2024-03-26 01:51 UTC
**After deleting from the library view the storage is not freed up.**

**When deleting a file from the library the storage should be freed up**

**Steps to reproduce the behavior:**
1. Download a file from Download tab, e. g. Wikipedia with 40 GB
2. Check disk space
3. Delete the file from the library
4. Check disk space again

**Screenshots**

**Environment**
- Version of Kiwix Android : 3.9.1
- Device : Zenfone 9
- OS version : Android 14

**Logs**

**Comment by MohitMaliFtechiz** [comment] 2024-03-26 06:37
@sunsero Thanks for opening the issue, Most of the new Android devices have the trash feature in them, and whenever we delete something from the device it moves to the trash to give one more chance to retrieve back that item. Can you please check if the deleted item is stored in the trash?

**Comment by sunsero** [comment] 2024-03-26 07:14
Unfortunately I already deleted Kiwix data in App Info which freed up the storage. However I'm not aware where to find the trash on my phone. Never came across it.

On the other hand I noticed when canceling a download within Kiwix the used storage is freed up immediately.

**Comment by MohitMaliFtechiz** [comment] 2024-03-26 07:42
> Unfortunately I already deleted Kiwix data in App Info which freed up the storage.

@sunsero It clears the application data(Bookmarks, Notes, and other application configurations) which frees up space from your device.

> However I'm not aware where to find the trash on my phone. Never came across it.

In most of the devices It is located inside your file explorer you can find it there.

> On the other hand I noticed when canceling a download within Kiwix the used storage is freed up immediately.

It is because it is held by the Kiwix app until it is completely downloaded, and whenever you cancel the download it deletes that temp file.

**Comment by sunsero** [comment] 2024-03-26 17:34
I had been aware that deleting the app data (>100Gb) would delete everything. But as there were only about 50 GB ZIM files in the library, I did this anyway.

Thanks to your hint I found the trash bin inside the file explorer that came with the phone (normally using another one). However the trash bin there is empty even after deleting a small ZIM file from the Kiwix library.

If possible Kiwix should actually delete the file without moving it to the trash bin. Even on latest Android versions Kiwix has full access to the files stored in its data directory, doesn't it?

**Comment by MohitMaliFtechiz** [comment] 2024-03-27 11:52
> Thanks to your hint I found the trash bin inside the file explorer that came with the phone (normally using another one). However the trash bin there is empty even after deleting a small ZIM file from the Kiwix library.
> If possible Kiwix should actually delete the file without moving it to the trash bin. Even on latest Android versions Kiwix has full access to the files stored in its data directory, doesn't it?

Thanks for providing this additional information that it is not in the trash folder. We are permanently deleting the file from the storage like when canceling the download deletes from the storage. As you said, it is not going to the trash folder so it is permanently deleted from the storage. However, I also tried to reproduce this behavior on my Android 14 device, and it freed up the storage immediately after deleting the file (with kiwix version 3.10.0).

Can you please try this APK [kiwix.apk](https://download.kiwix.org/nightly/2024-03-27/kiwix-universal-2024-03-27.apk), and give your feedback is the problem still exist at your end?

**Comment by MohitMaliFtechiz** [comment] 2024-04-01 12:44
@sunsero Any feedback about the latest APK?

**Comment by sunsero** [comment] 2024-04-01 12:50
Sorry, I cannot install it over the current one because of different signatures. And if I uninstalled the installed Kiwix before I would lose the 40 GB offline Wikipedia download during holidays. ;(

**Comment by MohitMaliFtechiz** [comment] 2024-04-01 13:58
@sunsero To not lose the current downloaded Wikipedia ZIM file you can do the following things.
* You can copy that ZIM file from the app-specific(`Android/data/org.kiwix.kiwixmobile/files/kiwix/`) directory to any other location of your phone e.g. in the download folder by using any third-party file manager which allows copying the file from the app-specific directory, since most of the device's file managers does show the content inside the `Android/data` directory.
* You can copy it to your computer since the computer can easily copy the data from the app-specific directory.
* Or you can wait for the `3.10.0` which will be released soon.

**Comment by sunsero** [comment] 2024-04-01 15:21
OK, I could copy the downloaded files to the download folder using the internal file manager, uninstall and install your version. I downloaded one 4 GB ZIM from within your version and deleted the ZIM from within the library.

It's gone from the file folder in the internal file manager. However the app's data remained 4GB. The trash bin in the file manager is empty as well.

Is there anything else I could check?

**Comment by sunsero** [comment] 2024-04-01 15:30
PS There's a notification 'Analyzing Heap Dump' from Kiwix. It's telling 'Finding paths to retained objects' and a progress bar at about 30%. Not sure if the progress bar is increasing or stuck.

**Comment by MohitMaliFtechiz** [comment] 2024-04-02 05:34
> PS There's a notification 'Analyzing Heap Dump' from Kiwix. It's telling 'Finding paths to retained objects' and a progress bar at about 30%. Not sure if the progress bar is increasing or stuck.

That was for checking the memory leak if any occur, we are checking this in our CI, but sometimes it shows on some devices due to their internal implementation.

> It's gone from the file folder in the internal file manager. However the app's data remained 4GB. The trash bin in the file manager is empty as well.

Seems very strange to me as well, if the file is deleted from the device and it is not in the bin so why your device is keeping the data of application. Have you checked after a few minutes whether the storage is freed up or not? Sometimes system does not immediately free up the storage due to its caching mechanism.

> Is there anything else I could check?

Is this behaviour same for other apps too? can you please check after deleting the file it remains in the app-specific directory or not? This might be the possible reason that the file is not properly deleted that's why the storage is not freed up.

**Comment by sunsero** [comment] 2024-04-02 05:47
Not sure when this happened (not after a few minutes) but the storage is freed up now. In the meanwhile I had rebooted the phone for another reason and just noticed the storage is freed up right now.

The file had no more been visible in the data directory while the storage had not been freed up yet.

Thank you very much for the support.

**Closed** 2024-04-02 05:47 UTC
Labels: question

**Comment by MohitMaliFtechiz** [comment] 2024-04-02 05:52
@sunsero Glad to know that the problem is fixed.
