### ISSUE TITLE
Ressource doesn't load when the page is a redirection

### ISSUE THREAD

**Issue by dattaz** [kiwix/kiwix-android#69] opened 2017-04-03 09:24 UTC
Step to reproduce : 
Download this zim file  [redirection_fail_base.zim.zip](https://github.com/kiwix/kiwix-android/files/889527/redirection_fail_base.zim.zip) un-compress, open in kiwix app

Open a page (which is a redirection) : click a tag and then on a question , you will see html without image or css
Open a page (which is not a redirection) : made a search for a question 

You should probably inject a <base> tag like is done kiwix-lib (see in kiwix-serve for example)

**Comment by kelson42** [comment] 2017-07-19 20:10
This is a duplicate of https://github.com/kiwix/kiwix-lib/issues/70

**Closed by kelson42** 2017-07-19 20:10 UTC
Labels: bug
