### ISSUE TITLE
Search need to show a message that the requested keyword is not found.

### ISSUE THREAD

**Issue by AkashAli506** [kiwix/kiwix-android#1070] opened 2019-03-09 12:42 UTC
**Describe the bug**
When you search a keyword like "Akash", it doesn't show anything.

**Expected behavior**
search need to show a message that "the requested keyword is not found" or "try another keyword".

**Steps to reproduce the behavior:**
1. When you type some keyword in the search.
2. If keyword is not found it doesn't show any message.

**Environment**
- Version of Kiwix Android : 2.4
- Device : Huawei Mate 10 lite
- OS version :  8.0.0

**Comment by abdulwd** [comment] 2019-03-09 12:46
@AkashAli506 Please follow the issue template while creating an issue.

**Comment by AkashAli506** [comment] 2019-03-09 13:19
@abdulwd I have changed the template.

**Comment by abdulwd** [comment] 2019-03-09 14:05
@AkashAli506 If you want to work on this issue you can otherwise any of our contributors can. This is similar to #1010.

**Comment by AkashAli506** [comment] 2019-03-09 14:49
@abdulwd I want to work on this issue but I am facing errors in gradle building. Can you please help me building this project?

**Comment by iadeelzafar** [comment] 2019-03-09 14:55
@AkashAli506 Can you share the screenshots of the error?

**Comment by iadeelzafar** [comment] 2019-03-09 14:58
@AkashAli506  Follow this [Build Solution](https://github.com/kiwix/kiwix-android/pull/974#issuecomment-463157239)

**Comment by AkashAli506** [comment] 2019-03-09 14:58
![Screen Shot 03-09-19 at 07 57 PM](https://user-images.githubusercontent.com/45498607/54073161-afeb9600-42a5-11e9-83ad-a5fc894b69e7.PNG)

**Comment by AkashAli506** [comment] 2019-03-09 14:58
@iadeelzafar Thanks for help.

**Comment by waahm7** [comment] 2019-03-10 11:47
@AkashAli506  I faced build issues too when building in Android Studio 3.3.2. Error was AndroidManifest not found. I resolved it by using latest Android Studio 3.5 canary preview. Update your Android Studio if you are facing similar issue.

**Comment by AkashAli506** [comment] 2019-03-11 18:46
Thanks, @waahm7.

**Comment by kelson42** [comment] 2019-12-26 22:38
Im not sure is this is a good idea... Should we display a toat with this message?

**Comment by iadeelzafar** [comment] 2019-12-27 18:54
@kelson42 An empty view would be a better choice.

**Comment by macgills** [comment] 2020-02-27 09:02
So we have `No Results` displaying but perhaps we could also have a loading state, there have been some complaints of lengthy loading

**Comment by soCallmeAdityaKumar** [comment] 2023-01-15 04:32
can i work on this issue

**Comment by soCallmeAdityaKumar** [comment] 2023-01-17 06:19
@kelson42  is this only occurring in the 
Version of Kiwix Android : 2.4
Device : Huawei Mate 10 lite
OS version : 8.0.0 
or in every version .
because in my its showing no results

**Comment by kelson42** [comment] 2023-01-26 19:04
We should check with latest dev version indeed. @MohitMaliDeveloper Might that be this bug has already been fixed, can you please verify?

**Comment by MohitMaliFtechiz** [comment] 2023-02-03 09:49
@kelson42 , 
I have tested it and unable to reproduce this bug. it's seems already fixed in any PR. I'm attaching a video sample.

https://user-images.githubusercontent.com/34593983/216568095-c5ebb0f2-7c72-4e5e-974a-cdb55f38032e.mp4

**Comment by kelson42** [comment] 2023-02-03 10:12
@MohitMaliFtechiz Thanks for the clear feedback. Closing the ticket as implemented.

**Closed by kelson42** 2023-02-03 10:12 UTC
Labels: enhancement, search, good first issue
