### ISSUE TITLE
Cannot open zimaa files from my sdcard

### ISSUE THREAD

**Issue by elPatrixF** [kiwix/kiwix-android#3691] opened 2024-02-01 15:21 UTC
I have tried multiple versions and I cannot see the split zimaa files on my sdcard.
The normal zim files are accessible in the latest nightly version, but not the split files.

I'm using gnu split to split the files, and it used to work with older zim files and in version 3.7.1

Am I doing something wrong or is this an error?

**Comment by MohitMaliFtechiz** [comment] 2024-02-02 10:08
@elPatrixF We have facing this issue with splited ZIM files with the latest version. However, version `3.7.1` is still working with splited ZIM files. We already have an ticket for this issue https://github.com/kiwix/kiwix-android/issues/3605.

**Comment by MohitMaliFtechiz** [comment] 2024-02-02 10:14
Duplicate of #3605.

**Closed by MohitMaliFtechiz** 2024-02-02 10:14 UTC
Labels: duplicate
