### ISSUE TITLE
Cannot get beyond "Grant access to access all storage"

### ISSUE THREAD

**Issue by JensKorte** [kiwix/kiwix-android#3458] opened 2023-07-22 10:14 UTC
## Fairphone 3, kiwix 3.6

Using kiwix I finally get the message "To use content offline you need to grant access to the storage" (translated from "Um auf Offlineinhalt zuzugreifen, müssen wir auf Ihren Speicher zugreifen"). I granted all the rights: 1. Android preferences -> Apps -> Kiwix -> Permissions (allowed all: device next to you, location) 2. Android preferences -> Apps -> Special App-access -> Access on all files (kiwix allowed).

Rebooting doesn't change anything.

In comparison to 3.6: 2.4 works

## Environments

- Version of Kiwix Android : 2.4 from F-Droid
- Device : Fairphone 3
- OS version : LineageOS 20-20230704-microG-FP3 (this is the LOS from microG, not the original one!)

- Version of Kiwix Android : 3.6 from IzzyOnDroid
- Device : Fairphone 3
- OS version : LineageOS 20-20230704-microG-FP3 (this is the LOS from microG, not the original one!)

I recognized this bug while reporting #3457 .

**Comment by kelson42** [comment] 2023-07-22 10:44
@JensKorte Can you please test with latest version 3.7.1 available on download.kiwix.org?

**Comment by JensKorte** [comment] 2023-07-23 21:53
With 3.7.1 I get the message (translated from german) "Your filesystem doesn't support files >4GB".
I guess that's it.

**Comment by MohitMaliFtechiz** [comment] 2023-08-04 10:03
@JensKorte Thanks for reporting the bug.

> Using kiwix I finally get the message "To use content offline you need to grant access to the storage" (translated from "Um auf Offlineinhalt zuzugreifen, müssen wir auf Ihren Speicher zugreifen"). I granted all the rights: 1. Android preferences -> Apps -> Kiwix -> Permissions (allowed all: device next to you, location) 2. Android preferences -> Apps -> Special App-access -> Access on all files (kiwix allowed).

This message is shown when there is no storage access. I have tested it with `3.6.0` and after giving the storage access this message does not show. But @JensKorte facing this issue it is probably the issue which we have fixed in https://github.com/kiwix/kiwix-android/pull/3233.

> With 3.7.1 I get the message (translated from german) "Your filesystem doesn't support files >4GB".
I guess that's it.

* @JensKorte in this version of `kiwix` have you faced the storage permission issue?

> "Your filesystem doesn't support files >4GB"
* If you have a `fat32` sd card and try to download zim file over 4GB then this message appears because we can not create over 4GB files in `fat32` filesystem.

**Comment by JensKorte** [comment] 2023-08-04 10:36
> > "Your filesystem doesn't support files >4GB"
> 
>     * If you have a `fat32` sd card and try to download zim file over 4GB then this message appears because we can not create over 4GB files in `fat32` filesystem.

It would be nice, if the user gets a hint to the "only <4GB on FAT32" problem since locating the problem would be much more easier. I can think of 2 solutions:

Solution A: Give a different message, if the problem occurs on a FAT32 fs
Solution B: Extend the message "To use content offline you need to grant access to the storage" to 
"To use content offline you need to grant access to the storage. Sometime this bug appears with files >4GB on a FAT32 filesystem"

**Comment by MohitMaliFtechiz** [comment] 2023-08-04 12:42
> It would be nice, if the user gets a hint to the "only <4GB on FAT32" problem since locating the problem would be much more easier. I can think of 2 solutions:
Solution A: Give a different message, if the problem occurs on a FAT32 fs
Solution B: Extend the message "To use content offline you need to grant access to the storage" to
"To use content offline you need to grant access to the storage. Sometime this bug appears with files >4GB on a FAT32 filesystem"

@JensKorte both are different here.
1) To use content offline you need to grant access to the storage
     This is for if the application does have not the access to devices filesystem to download the zim file.
2) "Your filesystem doesn't support files >4GB"
    This is shown when the file system does not support downloading files over 4GB.

So it is not ideal to show different error messages for one scenario, the user will be confused about which error is causing the problem.

> Solution A: Give a different message, if the problem occurs on a FAT32 fs.
   Good point, It will be helpful for the user if they know the exact error, @kelson42, @gouri-panda  what do you think?

**Comment by kelson42** [comment] 2023-08-27 05:00
@MohitMaliFtechiz I'm not sure what is going on here, as you are testing with basically 3 different versions of Kiwix Android. Please don't do that. What is sure is that: if the problem is a permission problem, please report accordingly. Reporting a fat32 problem is this is only a permission problem is a bug. So what is the status: do we have still a bug here or not?

**Comment by MohitMaliFtechiz** [comment] 2023-08-28 11:50
> What is sure is that: if the problem is a permission problem, please report accordingly.

@kelson42 We had some permission-related problems in `3.6.0` but permission related problem reported by @JensKorte was solved in https://github.com/kiwix/kiwix-android/pull/3233 and we are limiting the downloading zim files over 4Gb on `fat32` file systems since we are not able to write files in this filesystem and this message is appearing when @JensKorte tries to download the zim file. So here it is not a bug this limitation is put by us for this file system.

We have 2 file systems that do not support files over 4GB (`fat32` and `vfat`), so IMO the message shown to the user is good here.

**Comment by kelson42** [comment] 2023-08-29 02:25
@JensKorte Hope latest version (nightly) works in an appropriate way for you as well. Otherwise, please reactivate the discussion.

**Closed** 2023-08-29 02:25 UTC
Labels: bug, question
