### ISSUE TITLE
Last 3.12.0 destroy all libraries?!

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#4132] opened 2024-12-10 16:40 UTC
Claims a user:
![Image](https://github.com/user-attachments/assets/ea647607-8c67-4662-a92d-e55f576d2bbd)

Can you please confirm this is not the case?

**Comment by kelson42** [comment] 2024-12-10 16:40
@MohitMaliFtechiz ... and please give a feedback to the user.

**Comment by MohitMaliFtechiz** [comment] 2024-12-11 09:51
@kelson42 I have tested this and can confirm that it is not destroying the ZIM files. However, the previously added ZIM files do not initially appear on the LocalLibraryScreen. If we refresh by swiping down, all the previously added ZIM files reappear on the library screen.

Upon further investigation, I discovered the root cause of this behavior. It seems that the file path is missing from the book entity, and our validation logic checks if the file exists before displaying it on the local library screen. If the file path is invalid or missing, the ZIM files are excluded from the list.

This issue appears to be related to an automated change in the `default.json` file during the implementation of #3624. Specifically, the [ID of the file property was updated here](https://github.com/kiwix/kiwix-android/pull/3624/files#diff-96c5cfb8192b8c46e410a7f42bbecd759775556e9eed118b3a17cbb05f11a521L17) due an automated change, which inadvertently caused changes to our database. Due to this, previously saved file paths are now empty, leading to these files being filtered out during validation.

**Comment by kelson42** [comment] 2024-12-11 10:08
@MohitMaliFtechiz Can you please make a fix to fix this bad behaviour?

**Comment by MohitMaliFtechiz** [comment] 2024-12-11 10:12
@kelson42 Yes, I am placing a fix for this issue, but unfortunately it will not work for those users who have already updated their app since the database of those users has already been updated.

**Comment by kelson42** [comment] 2024-12-13 05:17
This is a pretty dramatic error. please put counter measure to avoid this happens again. I would at least put a heavy comment in the json around that ID to explain that this Id should bot change.

**Closed** 2024-12-13 06:07 UTC
Labels: bug, question
