### ISSUE TITLE
Kwix on F-Droid only goes up to version 2.4 and has not been updated since 2018-09-21

### ISSUE THREAD

**Issue by novellus** [kiwix/kiwix-android#3097] opened 2022-09-30 18:58 UTC
Kwix on F-Droid only goes up to version 2.4 and has not been updated since 2018-09-21.
Expected: F-Droid should host the latest builds

https://f-droid.org/packages/org.kiwix.kiwixmobile/

**Comment by kelson42** [comment] 2022-09-30 19:10
@novellus I discovered the problem 30 mn ago. I guess the problem is directly a consequence of #3091. To be confirmed.

**Comment by kelson42** [comment] 2022-10-05 06:45
Duplicate of #3091

**Closed by kelson42** 2022-10-05 06:45 UTC
Labels: bug, duplicate
