### ISSUE TITLE
Search results with non Latin letters are displayed with html tags 

### ISSUE THREAD

**Issue by maksbotan** [kiwix/kiwix-android#3831] opened 2024-05-09 08:16 UTC
**Describe the bug**
When using Wiktionary ZIM file and searching for words with non-latin (for example Cyrillic or extended Latin) letters, results are displayed with some HTML tags. 

**Expected behavior**

Results are displayed correctly without any garbage. 

**Steps to reproduce the behavior:**
1. Download Wiktionary (English) file through the app 
2. Open search 
3. Type "привет" or "księga" 

**Screenshots**

![Screenshot_20240509_110643_Kiwix](https://github.com/kiwix/kiwix-android/assets/275614/b37c2555-9f00-442a-bb13-ee35533ede9d)

**Environment**
- Version of Kiwix Android : 3.10.0 build 7231000
- Device : Samsung galaxy S22+
- OS version : Android 14

**Comment by kelson42** [comment] 2024-05-09 08:20
This a topic for mwoffliner, will move the issue. But issue is known and either fixed or upstream

**Comment by maksbotan** [comment] 2024-05-09 08:26
Thanks for the quick response!

Is there a way to test nightly build to see of the issue is fixed?

**Comment by MohitMaliFtechiz** [comment] 2024-05-10 10:34
@maksbotan You can test the latest nightly from here https://download.kiwix.org/nightly/

**Comment by kelson42** [comment] 2024-05-10 10:59
It's a duplicate of https://github.com/openzim/mwoffliner/issues/1797

**Closed by kelson42** 2024-05-10 10:59 UTC
