### ISSUE TITLE
Feature enhancement adding bookmark button, as in new version it is not available

### ISSUE THREAD

**Issue by gptshubham595** [kiwix/kiwix-android#1143] opened 2019-04-03 10:55 UTC
New version adding bookmark button is not available
![Screenshot_2019-04-03-16-24-07-48](https://user-images.githubusercontent.com/24877361/55473749-135eae80-562d-11e9-93a9-b87faad316dd.png)
![Screenshot_2019-04-03-16-24-10-55](https://user-images.githubusercontent.com/24877361/55473771-16f23580-562d-11e9-82cc-1c1b99afdb16.png)
![Screenshot_2019-04-03-16-24-16-56](https://user-images.githubusercontent.com/24877361/55473780-1c4f8000-562d-11e9-8374-9c8a8e86bc4e.png)

**Comment by gptshubham595** [comment] 2019-04-03 13:50
@mhutti1 @abdulwd

**Comment by mhutti1** [comment] 2019-04-03 18:45
I think this is a duplicate of https://github.com/kiwix/kiwix-android/issues/973

**Closed by mhutti1** 2019-04-03 18:45 UTC

**Comment by gptshubham595** [comment] 2019-04-04 10:32
Earlier it was there but in new version of kiwix after the tabs feature update bookmark feature is not there
