### ISSUE TITLE
Convert Project to Kotlin

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1826] opened 2020-02-27 09:42 UTC
**Is your feature request related to a problem? Please describe.**
Kotlin is our primary language but 40% of the codebase is still in java, this ticket aims to get that number to 0%. If you want to contribute to the project but are finding it diffcult to find a suitable ticket of a manageable size then this is for you!

**Describe the solution you'd like**
Comment here that you want to convert a class (I recommend starting with small ones) with the class name to claim it. Then make a ticket and start working on it. Use `ctrl+alt+shift+k` to automatically convert the file and then improve it to be more idiomatic kotlin.

**Additional context**
If you have never worked in kotlin before the [koans](https://kotlinlang.org/docs/tutorials/koans.html) (and the kotlin docs in general) are a good way to get used to the features. There is also support from kiwix members if you want to open a PR in draft

**Comment by AjayThakur12** [comment] 2020-02-27 17:48
@macgills  @kelson42  can I work on this issue.
I will start converting file from intro folder

**Comment by kelson42** [comment] 2020-02-27 18:11
@AjayThakur12 Yes, but do piece by piece. Module by module.

**Comment by rohanprasadofficial** [comment] 2020-02-27 19:43
@macgills @kelson42 can i convert the local_file_transfer folder to kotlin ?

**Comment by macgills** [comment] 2020-02-28 08:25
@AjayThakur12 a module is a bit larger than my original intention but `intro`s classes are quite small

@rohanprasadofficial I would say LocalFileTransfer is too large to tackle all as one ticket. Try WifiDirectManager, that is over 400 lines, probaby more than the entire `intro` module.

Both of you please make specific tickets `Convert X to kotlin`

**Comment by rohanprasadofficial** [comment] 2020-02-28 08:30
@macgills  okay great , thanks i will do WifiDirectManager

**Comment by thelosergeek** [comment] 2020-03-11 21:56
@macgills can i work on this?

**Comment by kelson42** [comment] 2020-03-12 07:12
@thelosergeek Yes, Please open a ticket with the part you want to move to Kotlin.

**Comment by Dalakoti07** [comment] 2020-03-12 13:53
@macgills @kelson42, I also want to contribute to the project, is there any class which is not assigned to anyone, I can convert to kotlin.

**Comment by macgills** [comment] 2020-03-12 16:16
> Comment here that you want to convert a class (I recommend starting with small ones) with the class name to claim it. Then make a ticket and start working on it. 

Everyone should follow the directions of this ticket.

@Dalakoti07 go looking for a class (over 40% of the project is still in java), find one you like, comment its name here and make sure nobody else has already commented then make a ticket and get to work.

This ticket is meant to be a haven of autonomy mostly because my time is a bit limited right now and also I love seeing classes converted to kotlin.

**Comment by yash1ts** [comment] 2020-03-13 15:15
I want to convert HelpActivity.

**Comment by macgills** [comment] 2020-03-13 15:52
@yash1ts make a ticket

**Comment by yash1ts** [comment] 2020-03-13 17:24
You mean I need to make a new issue and mention this issue there right?

**Comment by kelson42** [comment] 2020-03-13 17:31
> You mean I need to make a new issue and mention this issue there right?

Yes, and you make the corresponding PR with the "fix"

**Comment by jonggeunpark** [comment] 2020-04-27 03:58
can i work on this?

**Comment by kelson42** [comment] 2020-04-27 06:33
@jonggeunpark yes, open a ticket and then a PR with the piece of code you want to convert.

**Comment by s-ayush2903** [comment] 2020-06-21 14:22
I would like to convert `KiwixWifiP2pBroadcastReceiver.java` class to Kotlin

**Comment by s-ayush2903** [comment] 2020-07-10 17:23
I would like to convert `SharedPreferenceUtil.java` class to Kotlin

**Comment by ritvikmahajan17** [comment] 2020-08-04 05:13
I would like to convert 

- [ ] LocalFileTransferTransferActivity.java class to Kotlin

**Comment by ritvikmahajan17** [comment] 2020-08-04 05:19
@kelson42 I would Like to convert `LocaleFileTransferActivity.java` file into kotlin

**Comment by prayutsu** [comment] 2020-08-18 08:22
I want to convert ErrorActivity.java into Kotlin file

**Comment by macgills** [comment] 2020-08-18 08:30
@prayutsu great, please make that ticket

**Comment by gouri-panda** [comment] 2020-08-20 06:00
@macgills I want to convert FileReader.java to kotlin.

**Comment by gouri-panda** [comment] 2020-09-04 18:42
I would like to convert `KiwixWebView.java` class to Kotlin

**Comment by yyprince334** [comment] 2021-03-16 18:01
I want to contribute on it.

**Comment by yyprince334** [comment] 2021-03-16 18:02
I want to contribute on it.

**Comment by simonnepinto** [comment] 2021-03-28 03:08
I would like to convert LibraryViewCallback.java to Kotlin

**Comment by gouri-panda** [comment] 2021-03-28 06:10
@simonnepinto please go ahead! But first creat a ticket for that class.

**Comment by Rishavgupta12345** [comment] 2021-09-22 06:11
i think this issue is already solved 

if not then please tell me what changes can I do?

**Comment by kelson42** [comment] 2021-09-22 08:17
Do we have a list of modules which still need to be converted?

**Comment by Rishavgupta12345** [comment] 2021-09-28 05:53
@kelson42 @gouri-panda  WHENEVER I AM DOING A COMMIT ON YOUR  CLONED PROJECT I AM GETTING "commit failed with error" and the commit is failing . CAN YOU PLEASE HELP ME OUT ?

DESCRIPTION OF ERROR :

Running lint... Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details > Task :buildSrc:compileKotlin FAILED FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':buildSrc:compileKotlin'. > Kotlin could not find the required JDK tools in the Java installation 'C:\Program Files\Java\jre1.8.0_301' used by Gradle. Make sure Gradle is running on a JDK, not JRE. * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. * Get more help at https://help.gradle.org BUILD FAILED in 10s > Task :buildSrc:compileKotlin FAILED FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':buildSrc:compileKotlin'. > Kotlin could not find the required JDK tools in the Java installation 'C:\Program Files\Java\jre1.8.0_301' used by Gradle. Make sure Gradle is running on a JDK, not JRE. * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. * Get more help at https://help.gradle.org BUILD FAILED in 2s Static analysis found violations and attempted to autofix, please commit these autoformat changes

**Comment by gouri-panda** [comment] 2021-09-28 18:01
@Rishavgupta12345 It's complaining that you are using a  greater version of JDK 8 when your gradle is only compatible up to a JDK  8version.  You need Java 8 or above JDK and not just JRE. Let me know if you still got errors.

**Comment by Rishavgupta12345** [comment] 2021-09-29 06:53
@gouri-panda  yes I did the following changes which you asked but things are not committing yet. but the error has changed from before 

description of error:-
Starting a Gradle Daemon, 1 incompatible and 4 stopped Daemons could not be reused, use --status for details FAILURE: Build failed with an exception. * What went wrong: Unable to start the daemon process. This problem might be caused by incorrect configuration of the daemon. For example, an unrecognized jvm option is used. Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/6.2/userguide/gradle_daemon.html Process command line: C:\Program Files\Java\jdk1.8.0_301\bin\java.exe -Xmx4096m -Dfile.encoding=windows-1252 -Duser.country=IN -Duser.language=en -Duser.variant -cp C:\Users\risha\.gradle\wrapper\dists\gradle-6.2-all\dvufqs6kielxeao781pmk5huj\gradle-6.2\lib\gradle-launcher-6.2.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.2 Please read the following process output to find out more: ----------------------- * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. * Get more help at https://help.gradle.org FAILURE: Build failed with an exception. * What went wrong: java.net.BindException: Address already in use: Cannot bind * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. * Get more help at https://help.gradle.org Static analysis found violations and attempted to autofix, please commit these autoformat changes

**Comment by gouri-panda** [comment] 2021-09-29 07:02
@Rishavgupta12345 You can ask these questions on our slacks Android channel. We can discuss over there. Ask in Android channel and I'll get back to you :)

**Comment by cdhiraj40** [comment] 2021-10-20 05:58
hey, @gouri-panda I would like to convert matcher.java to matcher.kt, and can you explain to me what does it mean by ``` first create a ticket for that class. ``` Thanks :)

**Comment by gouri-panda** [comment] 2021-10-20 09:32
@cdhiraj40 Github Issues let you track your work on GitHub. If you create an issue then you want to solve this issue, then the issue can assign to you. That's how anyone's work doesn't conflict with each other. If you want to convert a java class file to kotlin then you need to create an issue first if it isn't created yet. In this way, It'll keep track of which files are underway from java to kotlin, and also other contributors will know that if someone is working or not if they are interested in this class to convert java to kotlin.

**Comment by Im-Kunal-13** [comment] 2021-11-29 03:39
I want to contribute on this issue. Are there any classes left on which I can work ?

**Comment by cdhiraj40** [comment] 2021-11-29 03:53
> I want to contribute on this issue. Are there any classes left on which I can work ?

yes there are, here checkout https://github.com/search?p=5&q=repo%3Akiwix%2Fkiwix-android+language%3AJava&type=Code (for some PRs have been created so do check first :)

**Comment by cdhiraj40** [comment] 2021-12-10 12:54
I would like to convert Datasource.java and KiwixIdlingResource.java

**Comment by aneeshgupta25** [comment] 2022-01-31 16:20
Can I work on this issue?

**Comment by the-illuminatus** [comment] 2022-02-04 15:58
if there are still issues left then I would like to contribute to this one.

**Comment by cdhiraj40** [comment] 2022-02-04 17:38
hello @aneeshgupta25 and @the-illuminatus pick any java file from here https://github.com/search?p=5&q=repo%3Akiwix%2Fkiwix-android+language%3AJava&type=Code
and convert it to kotlin and make a PR!
Don't forget to check if PR for some file has already been created and if not then do create an issue for your file :)

**Comment by aneeshgupta25** [comment] 2022-02-04 21:41
@cdhiraj40 Thanks.. Will definitely work on it.. :)

**Comment by aneeshgupta25** [comment] 2022-02-05 08:18
@cdhiraj40 I am working on the templates.java file but there's this variable _"CUSTOM_APP_HAS_EMBEDDED_ZIM "_ and is initialized to  **~embed_zim~** I am not able to figure out what's **~** symbol in JAVA and about embed_zim. Can you plz guide me about this..?

**Comment by kelson42** [comment] 2022-08-26 05:05
@MohitMaliFtechiz @gouri-panda How much work is left here? I’m not really wanting to keep sucha ticket far more longer open.

**Comment by kelson42** [comment] 2022-11-07 10:36
@gouri-panda @MohitMaliFtechiz So, looks like we are almost done. How can we sure we don't have forgotten something. How do you check this?

**Comment by gouri-panda** [comment] 2022-11-07 10:44
@kelson42 We can see this in the project overview's main page or we can search [this](https://github.com/kiwix/kiwix-android/search?l=java).

**Comment by kelson42** [comment] 2022-11-07 10:46
@gouri-panda OK, so lets merge the two PR left and look to what is left

**Comment by kelson42** [comment] 2022-11-10 10:52
@gouri-panda @MohitMaliFtechiz It seems we have no PR to convert https://github.com/kiwix/kiwix-android/blob/19a70529f481909ff78ab7c879d9c85ceaeed304/templates/Constants.java to Kotlin! The rest seems handled by currently open PRs.

**Comment by MohitMaliFtechiz** [comment] 2022-11-10 10:59
> @gouri-panda @MohitMaliFtechiz It seems we have no PR to convert https://github.com/kiwix/kiwix-android/blob/19a70529f481909ff78ab7c879d9c85ceaeed304/templates/Constants.java to Kotlin! The rest seems handled by currently open PRs.

yes this has been left let me create PR for this.

**Comment by gouri-panda** [comment] 2022-11-10 11:05
@kelson42 Ok. https://github.com/kiwix/kiwix-android/blob/19a70529f481909ff78ab7c879d9c85ceaeed304/templates/Constants.java this is a very small java file indeed.

**Comment by kelson42** [comment] 2022-12-03 12:14
Finally done! Thank you to all participants to this effort.

**Closed by kelson42** 2022-12-03 12:14 UTC
Labels: enhancement, good first issue
