### ISSUE TITLE
Touch up README

### ISSUE THREAD

**Issue by EladKeyshawn** [kiwix/kiwix-android#95] opened 2017-04-08 21:25 UTC
We should  update the readme to readme.md and enhance the format to be more readable and look better

**Comment by EladKeyshawn** [comment] 2017-04-23 08:51
@kelson42 @mhutti1 Can I switch the readme to use markdown (.md)?

**Comment by kelson42** [comment] 2017-04-23 08:52
@EladKeyshawn OK to me.

**Comment by kelson42** [comment] 2018-01-18 11:12
This seems to be a duplicate of #112 which provides over more information. So I will close it.

**Closed by kelson42** 2018-01-18 11:12 UTC
Labels: duplicate, enhancement
