### ISSUE TITLE
Archive test/static analysis(/apks?) output on github actions

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2060] opened 2020-05-01 13:29 UTC
**Is your feature request related to a problem? Please describe.**
We currently rely on console output which can be difficult to parse.

**Describe the solution you'd like**
[UploadArtifact](https://github.com/actions/upload-artifact) hit v2 and is now much friendlier to use, we should use it to have easily accessible lint/detekt/unit&instrumentation results

**Comment by s-ayush2903** [comment] 2020-12-02 23:20
Can this be closed via #2487 & #2506

**Comment by kelson42** [comment] 2020-12-03 07:37
@s-ayush2903 This is a question? A fact? The problem is solved?

**Comment by s-ayush2903** [comment] 2020-12-03 07:39
I believe this can be close via two PRs mentioned above, after their merge, we are uploading lints, detekt, and all tests' reports to GH-Actions, which was demanded in this issue(as per the issue description)

**Comment by kelson42** [comment] 2020-12-03 07:43
@s-ayush2903 Ok, letting @macgills deciding about that.

**Comment by s-ayush2903** [comment] 2020-12-03 08:07
Okay fine, no worries.

**Closed** 2020-12-03 10:57 UTC
Labels: enhancement, testing
