### ISSUE TITLE
Onboarding Fragment

### ISSUE THREAD

**Issue by GeVic** [kiwix/kiwix-android#651] opened 2018-03-22 06:59 UTC
# It is a 
- [ ]  Bug Report
- [x]  Feature Request

#### Feature Description
I am suggesting this feature to show first-time users how to get most from our app. As our app aims to disseminate and increase offline reach of our users, So It's important to draw users attention to noteworthy features in our app.

@mhutti1 @kelson42 @rashiq  Any suggestions? Should I go ahead with it?

**Comment by harshvardhan-takawale** [comment] 2018-03-22 09:25
@GeVic This issue has already been brought up(#421). I have also created a PR for the same with basic design.

**Comment by mhutti1** [comment] 2018-03-22 14:18
Close as duplicate of #421

**Closed by mhutti1** 2018-03-22 14:18 UTC

**Comment by GeVic** [comment] 2018-03-22 14:30
@harshvardhan-takawale @mhutti1 I wasn't aware of the same.
