### ISSUE TITLE
Quick Review of App 

### ISSUE THREAD

**Issue by Wajahat-Khan** [kiwix/kiwix-android#1146] opened 2019-04-06 06:17 UTC
As, kiwix has to download a large data for it to be available for users, can we add a feature that it shows a quick demo or review of the data before downloading, so that it can help users to check if they are getting what they really want.

**Comment by sonusourav** [comment] 2019-04-06 12:22
Duplicate of #1087 . Always check if the issue you are opening is already opened.

**Closed** 2019-04-07 13:17 UTC
