### ISSUE TITLE
[UI] Cancel button of "Delete this file? "dialog is broken.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-android#828] opened 2018-07-30 14:06 UTC
The "Cancel" button is wrongly displayed.

- long press a zim
- "Delete this file?" dialog appears
- "Cancel" button is wrongly displayed.

![screen_cancel](https://user-images.githubusercontent.com/86161/43402210-833e585a-9412-11e8-8b45-3866b05a2c37.png)

**Comment by mgautierfr** [comment] 2018-07-30 14:08
My kiwix application language in english, so it is not the translation string that is wrong.
Setting kiwix application to french, the "Cancel" button is correctly displayed in french ("annuler")

**Comment by RajaVamsi11** [comment] 2018-10-01 19:27
@mhutti1 @mgautierfr Can I start working on this issue?

**Comment by mgautierfr** [comment] 2018-10-02 08:15
I'm not working on it.
Note that I'm pretty sure that the issue appears also for other texts.

**Comment by mhutti1** [comment] 2018-10-02 09:02
@RajaVamsi11 Sure.

**Comment by RajaVamsi11** [comment] 2018-11-03 05:54
[
![screenshot_2018-11-03-11-19-27](https://user-images.githubusercontent.com/30550059/47948649-c467fc80-df5a-11e8-9492-5af3b0fa1740.png)
](url)
@mgautierfr @mhutti1 There is no issue with my device.whai i have to do now?

**Comment by mhutti1** [comment] 2018-11-03 21:42
@RajaVamsi11 this is an issue where most of the issue would be reproducing it I feel.

**Comment by kelson42** [comment] 2019-06-17 19:11
FYI this looks like burmese language, which might have a special font handling in the app. I suspect the Burmese font to be packaged with the app itself.

**Comment by macgills** [comment] 2019-06-21 11:15
![image](https://user-images.githubusercontent.com/3358282/59918874-e5179080-941d-11e9-88bb-7bee1f2810ef.png)
The string has been changed to No since this tickets creation and I see no issues with the translation nor any special handling of Burmese. Closing this ticket

**Closed by macgills** 2019-06-21 11:15 UTC
Labels: bug
