### ISSUE TITLE
The text is collapsed

### ISSUE THREAD

**Issue by vivadavid** [kiwix/kiwix-android#2560] opened 2020-12-15 19:55 UTC
Hi,

As a beta tester, I'm currently using Kiwix for Android version 3.4.3 build 6230403. I first noticed on version 3.4.2 the following behaviour: when I'm on a particular entry and I click on a section on the table of contents, I would expect to be taken to this particular section with the text visible, so I can read it without having to scroll or click again. What currently happens is that the text of the entry stays in compact mode, stays collapsed. Even when I click on a subsection, I'm only taken to the heading of the main section, and as a result, I need to click several times and manually find the subsection I want to read.

I've also noticed that, in fact, regardless the table of contents, when you go to a particular entry, all the text is collapsed. I wonder if it would more useful if all the text was visible.

In particular, I've tested this on Wikipedia Spanish all nopic 2020-11 and Wiktionary Spanish all maxi 2020-12. 

English isn't my mother tongue and I hope I explained things correctly.

Thanks! 

- Version of Kiwix Android: 3.4.3 build 6230403.
- Device: Xiaomi Mi 9T Pro.
- OS version: Android 10.0.

**Comment by s-ayush2903** [comment] 2020-12-17 21:31
Hi @vivadavid Thanks for the report, as per my comprehension from the description provided it looks to me a duplicate of #2166

**Comment by vivadavid** [comment] 2020-12-17 21:48
Hi, @s-ayush2903,

Thank you for your message. The thread you mention isn't exactly about the same issue, but it's very similar and the cause is probably the same.

Should I copy and paste my report in that thread and close this one?

**Comment by s-ayush2903** [comment] 2020-12-17 22:37
Thanks @vivadavid for making me look into the issue again. Now that I've analysed it again, I understand this issue is about the "collapsed" nature of sections and subsections of the article when a click on same is triggered from the table of contents. This issue and the one that I mentioned ain't completely related. You needn't close it, let it be open as it is.

**Comment by vivadavid** [comment] 2020-12-18 07:40
Thank you, @s-ayush2903! Let me know if I can provide more information.

**Comment by s-ayush2903** [comment] 2020-12-18 10:45
I'll give this a shot.

**Comment by vivadavid** [comment] 2021-04-29 17:39
Hi,

On Kiwix for Android 3.4.4, things got worse. In the past, the app would take me to the main section (not to the required subsection) without collapsing the text. This is what happens now.

Steps:

1. I press on the Table of Contents.
2. I press on a particular section or subsection.
3. Nothing happens.

Tested with the full Spanish Wikipedia (Feb 2021).

**Comment by gouri-panda** [comment] 2021-04-29 18:19
Hi @vivadavid , thank you for the report. I can successfully  produce the subsection of bug(step 2) if I tap the subsection. but I can't reproduce the bug if I click the section. Can you tell me how? Thanks!

**Comment by kelson42** [comment] 2021-04-29 18:26
It is important we can sort out this ticket before releasing 3.4.4. It is true that the section does not uncollapse properly when clicked on it in the TOC. This is an old bug impossible to fix properly in kiwix android only, see #309. But all the rest seems to work fine to me.

**Comment by vivadavid** [comment] 2021-04-29 20:55
Thank you for pointing me to bug 309, whose title is far more descriptive than mine. I keep my fingers crossed for a future solution to this problem.

**Closed** 2021-04-30 03:51 UTC
Labels: bug, duplicate
