### ISSUE TITLE
Requested URL cannot be loaded as service workers are not supported here.

### ISSUE THREAD

**Issue by samuk** [kiwix/kiwix-android#2789] opened 2022-03-08 08:20 UTC
**Describe the bug**
This error appears requested URL cannot be loaded as service workers are not supported here.
**Expected behavior**
View https://twitter.com/KiwixOffline/status/1500761820818194437 resource
**Steps to reproduce the behavior:**
1. install kiwix android
2. Download Military medicine'
3. Try to open file in Kiwix Android

**Environment**
- Version of Kiwix Android : 
- Device : Samsung Galaxy 9
- OS version : Android 10

**Comment by MohitMaliFtechiz** [comment] 2022-08-09 12:22
hi @samuk ,

This is issue with the webview related to chrome , please update the chrome and it will disappear.

**Comment by kelson42** [comment] 2022-08-10 06:54
It's not a bug, but a limitation and It won't work better with newest Chrome IMO. Read https://github.com/openzim/zimit/issues/106#issuecomment-1068907042 and https://github.com/kiwix/kiwix-tools/issues/416

**Comment by kelson42** [comment] 2022-08-10 06:56
I think there is really nothing we can do more here. Closing the ticket.

**Closed** 2022-08-10 06:56 UTC
Labels: question
