### ISSUE TITLE
App Freezes when storage permission denied

### ISSUE THREAD

**Issue by criticalAY** [kiwix/kiwix-android#3251] opened 2023-02-26 15:24 UTC
**Describe the bug**

When we Storage permission is denied by user the application freezes in a loop showing toast endlessly 

**Expected behavior**

If user denies permission then the user is taken to the app setting to allow for permission and shouldn't be allowed to access library if denied storage access

**Steps to reproduce the behavior:**
1. Deny Storage permissions
2. enless toast

**Screenshots**

https://user-images.githubusercontent.com/48384865/221419867-78540be6-248e-41ef-b216-8c56731903ba.mp4

**Environment**
- Version of Kiwix Android : 3.6.0
- Device : Oneplus Nord ce
- OS version : 12

**Logs**

**Comment by kelson42** [comment] 2023-02-26 20:08
Duplicate of #3229

**Closed by kelson42** 2023-02-26 20:08 UTC

**Comment by criticalAY** [comment] 2023-02-26 20:13
Oh my bad sorry didn't realise there is already open PR
