### ISSUE TITLE
North Frisian Wiki only allows/appears in the Amrum dialect

### ISSUE THREAD

**Issue by limey75** [kiwix/kiwix-android#2583] opened 2021-01-20 19:24 UTC
Hi,

At present, the North Frisian language version of Wikipedia (Nordfriisk Wikipedia) only allows access to the Amrum dialect version of the wiki. But it is on the website available in several dialects (Sölring, Fering, Halunder, Frasch, etc.). On the Wiki website, you have the option of the changing which dialect Wiki will be displayed in. I want to read Wikipedia in (Mooringer) Frasch, actually the dominant North Frisian dialect. But Kiwix does not allow this. It is not possible to specify the browsing dialect, the links at the top of the homepage do not work. Only the Amrum dialect (Öömrang) is available from the North Frisian Wikpedia homepage.

Would it be possible to also get access to Frasch (and the other dialects)? Otherwise, the North Frisian Wikipedia is severely limited in scope.

**Environment**
- Version of Kiwix Android : 3.4.3 Build 6230403
- Device : Android tablet
- OS version : 10

Thanks!

**Comment by kelson42** [comment] 2021-01-24 14:50
To me a duplicate of https://github.com/openzim/mwoffliner/issues/840. We don’t handle that so far.

**Closed by kelson42** 2021-01-24 14:50 UTC
Labels: question
