### ISSUE TITLE
Kiwix doesn't pick up local connection

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#263] opened 2017-09-27 06:05 UTC
See image: I'm connected to my wi-fi network but Kiwix won't pick it up and connect to the library. Restarting the app won't improve things, however it is not constant: if I try again 10-20 minutes later it may work again (without me having done anything else).

![screenshot_2017-09-27-08-01-07](https://user-images.githubusercontent.com/21675885/30898224-7a03abfe-a35a-11e7-805a-e9d6ea1327e6.png)

**Comment by kelson42** [comment] 2017-09-27 06:13
Looks like a bug even if only sporadic... and difficult to reproduce.

**Comment by julianharty** [comment] 2017-10-04 13:59
At the moment we display a single error message regardless of the cause of the network problem or error. How about we add some additional information to help at least technical users make better sense of what's going wrong? I'd like to also improve the information displayed for all users, however we'd need to add extra strings and have them translated which put me off doing so at the time.

**Comment by kelson42** [comment] 2018-01-20 22:11
@julianharty @mhutti1 @divadsn I would like your feedback about that issue please. Does the fixes done since the opening (in particular #323 fixing) should let us consider this ticket to as "fixed"?

**Comment by mhutti1** [comment] 2018-01-20 22:28
It shouldn't do as imo it has no relation to the bug reported by @Albert221 with permissions.

**Comment by divadsn** [comment] 2018-01-21 00:26
IMO this looks rather to be related with #323 when the connection is being intercepted by the network.

**Comment by Popolechien** [comment] 2018-01-21 11:07
Maybe a way to reproduce: I had a similar event when both Wikimed and Kiwix were open. Closing both and reopening Kiwix alone solved the issue.

**Comment by julianharty** [comment] 2018-01-23 00:11
@Popolechien do you have the ability to extract the Android log from the device? e.g. using the `adb logcat` command from the Android SDK... If so, the OkHttp requests and responses should be logged, IIRC. Perhaps there'll be some clues in the log too? Thanks for reporting the problem and that you'd noticed it might appear when two instances of Kixix were running. That may help us hone in on what's going wrong.

**Comment by macgills** [comment] 2019-05-27 10:50
Fixed in #1170

**Closed by macgills** 2019-05-27 10:50 UTC
Labels: bug
