### ISSUE TITLE
Opening contents by swiping right on main page shows "No content headers found"

### ISSUE THREAD

**Issue by arpank10** [kiwix/kiwix-android#620] opened 2018-03-11 13:08 UTC
### Environment
  * version of the software you use : Version 2.3 Build 55
  * device / operating system : Android 7.1.1
  
### The Bug:

  * What do you obtain? A copy of the error message or a screenshot is always useful.
![whatsapp image 2018-03-11 at 6 33 50 pm](https://user-images.githubusercontent.com/24573296/37253694-1151946c-255b-11e8-864d-e18c61868b6c.jpeg)
![whatsapp image 2018-03-11 at 6 33 50 pm 1](https://user-images.githubusercontent.com/24573296/37253697-174014ac-255b-11e8-950f-d74e1bf763c2.jpeg)

#### Steps to reproduce:

  1. Open a zim file
  2. Swipe right to open content headers on main page of Zim file.
  3. It shows "No content headers found" followed by the content headers.
  
  * What should be the behaviour from your point of view? How do you expect the service to work?
"No content headers found" should not be displayed when content headers are present.

**Comment by kelson42** [comment] 2018-03-11 16:01
The title of the page should be displayed... I have here a recent version of Kiwix which seems to work... so I suspect this bug has been introduced recently or this is depending of the content currently loaded.

**Comment by mhutti1** [comment] 2018-03-11 23:25
@kelson42 likely content dependent which ZIM file is this?

**Comment by arpank10** [comment] 2018-03-12 12:39
@mhutti1 Wikipedia Maths(122 MB) and Wiktionary(5.7 MB)

**Comment by arpank10** [comment] 2018-03-12 12:39
I will check for few other Zim files.

**Comment by Raghav-intrigue** [comment] 2018-03-23 13:57
Can I get assigned to this?

**Comment by arpank10** [comment] 2018-03-23 13:58
Sure.

**Comment by julianharty** [comment] 2018-04-11 17:04
This message seems to be overloaded i.e. used in several circumstances. In my view it's not always the bests choice. In tandem we can choose to add headers to content that doesn't currently have any so this message isn't displayed - valid content headings are instead (since this is used when the content lacks a **_title_** which is gleaned from the content when the content has a valid HTML `<H1>` tag.

I'll list these first then add the screenshots so you can see the effects. I'll add some additional observations on editing the content in another comment as this one will be massive once I've added the screenshots.

Ray Charles (one of our often used ZIMs for testing)
- Homepage has a single heading, but no H1 heading.
- "I'm Moving On" page has several headings, but no H1 heading

Bollywood ZIM (one I use quite a bit for testing as it's fairly small but not as plain as the Ray Charles layouts, etc.
- Homepage looks like it should have a H1 heading because the initial text is massive, but it's marked up using a large font etc instead
- Nagarpuram has well-structured headings and is the only one here that actually has the article name in the title section of the right drawer navigation menu

And finally for these examples, our very own Kiwix Help page. This is generated from an XML layout and used as HTML content, effectively becoming a 1-page 'article' in the app.

<H2>Ray Charles examples</H2>

![raycharleszim_homepage_has_onesection](https://user-images.githubusercontent.com/785891/38631358-765e9580-3db1-11e8-92dc-a57f1883c5dc.png)

![raycharleszim_has_sections_butnoh1](https://user-images.githubusercontent.com/785891/38631379-8177bc26-3db1-11e8-935c-a3d6a42e8120.png)

<H2> Bollywood examples </H2>

![bollywoodzimhomepage_hassections_noh1](https://user-images.githubusercontent.com/785891/38631706-66e85f5e-3db2-11e8-8ce4-3bd173c7bacd.png)

![bollywoodzimhomepage_hassections_noh1_menu](https://user-images.githubusercontent.com/785891/38631742-86ec6b42-3db2-11e8-9da1-5026e2cb1673.png)

<H2> Kiwix Help example </H2>

![kiwix_help_lacks_headings](https://user-images.githubusercontent.com/785891/38631763-98b6b472-3db2-11e8-9b10-b212bdffb497.png)

**Comment by julianharty** [comment] 2018-04-11 17:15
As promised here are some additional comments and observations. 

At least for Bollywood, I've found what seems to be the source page. https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Film/Offline_Bollywood 
I notice this was edited by one of the project team. 

Perhaps other ZIM files also have their 'homepage' online where they can be edited.

For the Bollywood homepage, switching to [edit](https://en.wikipedia.org/w/index.php?title=Wikipedia:WikiProject_Film/Offline_Bollywood&action=edit) mode reveals how the layout was constructed:
```
<div style="font-size:185%;">Welcome to Bollywood</div>
<div style="font-size:135%;">All Wikipedia articles about Bollywood and beyond, from Wikipedia, powered by Kiwix.</div>
``` 
rather than using the markup for a H1. It's easy to edit this page to use the markup to make the first line into a H1 heading but replacing the `div`s with = e.g. 
`=Welcome to Bollywood=`
The HTML that's generated converts the wiki markup of `=` to HTML markup of `<H1>` etc. And the Kiwix Android app converts the H1 text into the title of the article and the section title in the right-drawer.

I've saved this change BTW so when you visit the page you'll need to review the edit history. 

So my first observation is we may be able to fix the source article(s) to add what will become the title. I'll add others as additional comments here.

**Comment by julianharty** [comment] 2018-04-11 19:03
Next suggestion... 
The current message only seems pertinent when there are **no section headings**, it seems confusing in all other circumstances. So if there are any section headings (which are generated by Kiwix parsing the HTML of the article) then I suggest we don't use the current message. Instead we could either put nothing (no text / a blank or empty string) or - if we can obtain it the title of the article, (perhaps based on parsing the link used in the ZIM file?)

**Comment by julianharty** [comment] 2018-04-11 20:40
@RohanBh I'd reached a similar conclusion of what happens in the code. I did find it odd that the Android view is added as a child of the WebView but on balance - why not, they are both Views after all...

I do like your simple, clean suggestion to add `<H1>` tags to the current minuscule help.html source. However, how about adding a H1 as well as the current title (which is in the head element of the HTML rather than the body)? As you say, at least the right drawer will then say 'Help' rather than the current unhelpful message.

Here's a mock up of adding an H1 rather than changing the current title to be the H1:

```
./app/src/main/assets/help.html

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8"/>
    <title>Help</title>
</head>
<body>
<h1>Help</h1>
</html>
```

One consideration I expect you understand well is the aspect of localisation of the contents of the help. The English term 'Help' is probably quite well recognised globally but not by all our users, I expect. Perhaps we have to be a little cleverer in finding a solution that localises the text that gets displayed that doesn't get affected when displaying any articles that happen to have Help as their H1 heading e.g. https://en.wikipedia.org/wiki/Help and the translated equivalents that refer to the Beatles, etc.

**Comment by RohanBh** [comment] 2018-04-11 21:13
Yes, I agree. What I suggested wasn't even going to work (not a regular web coder here).
I never considered the problems of having a large userbase. It is important that a user sees everything in the app in his/her local language.
We need not worry about other articles here, as many articles come in different languages and Kiwix lets you download them in your language. So, this problem won't occur for popular articles that are available in many languages.
Although, I am not sure how to provide a similar solution for the help page. With the current solution, the help page itself will get converted to the local language (because each language specific string resource will be used), but the content header will always show "help".
We could probably handle the specific case of help page by adding an XML string resource with help value. Then loading the language specific string at runtime in the [parse() method](https://github.com/kiwix/kiwix-android/blob/master/app/src/main/java/org/kiwix/kiwixmobile/utils/DocumentParser.java#L50) like this:
```Java
if (title.equals("Help")) {
    title = getResources().getString(R.string.help_text);
}
```

**Comment by macgills** [comment] 2019-09-09 13:14
I think there is nothing to do on this ticket. I cannot reproduce the original issue, it seems the zim files have been correctly updated so they have sections/h1 headings. @kelson42 recommend closing.

**Closed** 2019-09-09 14:36 UTC
Labels: bug, good first issue
