### ISSUE TITLE
Android: make Kiwix react to Wikipedia links in other apps

### ISSUE THREAD

**Issue by mbe57** [kiwix/kiwix-android#817] opened 2018-07-22 11:40 UTC
Other than Aard2, opening a Wikipedia link in another app, Kiwix is not offered as serving App.
I.e. in Android you can have a link that "points" to a Wikipedia entry. Android has a number of Apps registered that serve such links. Web browser (Chrome e.g.), or Aard2, are both offered. The Kiwix App is not offered, although it can handle Wikis and Wikipedia.
Just "tell" Android that Kiwix is "interested" in this type of Wikipedia links.
TXs and cheers
Michael

Migrated fromhttps://sourceforge.net/p/kiwix/feature-requests/1005/

**Comment by mhutti1** [comment] 2018-07-23 21:07
Thanks for reporting. Duplicate of #731

**Closed by mhutti1** 2018-07-23 21:07 UTC
Labels: enhancement
