### ISSUE TITLE
[Bug] On Android, video fullscreen is not possible [sf#884]

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#44] opened 2017-03-18 12:32 UTC
_From @rashiq on June 8, 2016 13:7_

**Reported by kelson42 on 2015-06-04 09:35 UTC**
Steps to reproduce:
- Download a TED ZIM file
- Start to play a video
- Click on the fullscreen buton

Nothing happens, this seems to be related to a security limitation of Android, but there is a workaround in javascript which should be implemented.

Using [this](https://github.com/cprcrack/VideoEnabledWebView) should fix the problem.

_Copied from original issue: kiwix/kiwix#206_

**Comment by mhutti1** [comment] 2017-03-18 12:32
_From @kelson42 on December 3, 2016 16:58_

@mhutti1 Do you have an opinion about this? How much work would be necessary?

**Comment by mhutti1** [comment] 2017-03-18 12:32
@kelson42 I will look into it but don't know at the moment.

**Comment by kelson42** [comment] 2018-01-17 16:20
For that file we use the javascript tool video.js from videojs.com. At the bottom of the videojs.com welcome page we have a few examples which seem to work fine with the Android integrated browser. The problem is that with Kiwix, it looks like nothing about this special video player UI is displayed.

**Comment by kelson42** [comment] 2019-09-18 09:30
@macgills Sorry to make this part of 3.0 at the last time, but would be really have this working regarding the big effort made by @rgaudin to get the video based ZIM file working fine everywhere. This should be fixed against http://tmp.kiwix.org/youtube-playlist-PLdUM7Ji5ZffmPyZBFv-c3ExBWi3G-TaVn_fr_all_HD.zim

**Closed** 2019-09-23 08:29 UTC
Labels: bug
