### ISSUE TITLE
Fix Checkstyle issues

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#100] opened 2017-04-10 12:54 UTC
There are approximately 800 checkstyle warnings. We need to fix the issues or in some cases update rules.

**Comment by kelson42** [comment] 2018-01-18 10:51
@mhutti1 Could you please share here the command to get the list?

**Comment by RajaVamsi11** [comment] 2018-02-26 16:58
@mhutti1 How can we get list of checkstyle warnings?

**Comment by mhutti1** [comment] 2018-02-27 23:56
Download the checkstyle plugin for android studio and configure it with https://github.com/kiwix/kiwix-android/blob/master/config/checkstyle/checkstyle.xml

**Comment by kelson42** [comment] 2018-03-02 17:31
The implementation of this ticket seems really important to save a lot of reviewers time.

**Comment by kelson42** [comment] 2019-07-17 12:15
@macgills What the current situation and feeling about this ticket?

**Comment by macgills** [comment] 2019-07-17 12:18
https://docs.gradle.org/current/userguide/checkstyle_plugin.html we can add it

**Comment by macgills** [comment] 2020-01-22 14:34
@kelson42 rather than supporting checkstyle which is java only we would probably be more suited to switching this ticket to "integrate [detekt](https://github.com/arturbosch/detekt)" and view remaining java code as "should be rewritten in kotlin"

**Comment by kelson42** [comment] 2020-01-22 15:13
@macgills "detekt" is not run by https://www.codefactor.io ?

**Comment by macgills** [comment] 2020-01-22 15:38
If codefactor is running detekt it is running a very lenient or much earlier version

**Comment by macgills** [comment] 2020-02-12 11:49
@kelson42 is this ticket now "Integrate detekt and fix issues" or "Fix checkstyle issues"?

**Comment by kelson42** [comment] 2020-02-12 13:52
@macgills Both.

**Comment by kelson42** [comment] 2020-02-13 13:05
Just to be surw, this ticket is not a duplicate of #1274?

**Comment by macgills** [comment] 2020-02-13 13:26
totally different

**Comment by macgills** [comment] 2020-02-20 16:17
@kelson42 I had forgotten checkstyle was only a format checker and didn't actually check for any bugs at all.

I don't think it is worth our time integrating it for the dwindling 43% of the code that remains in java when our formatter is already in source control and ktlint runs on our kotlin and automatically formats it.

Checkstyle does not support autofixes beyond what we already have so I don't think its integration will be particularly useful.

**Comment by macgills** [comment] 2020-02-21 09:21
@kelson42 there is still a PR that integrates detect so I am reopening this and will move that Pr from draft to Ready for Review

**Closed** 2020-02-24 10:09 UTC
Labels: enhancement, good first issue
