### ISSUE TITLE
Advanced library search : Option to display only selected label(Vid,Pic,Text...)

### ISSUE THREAD

**Issue by Mitia99** [kiwix/kiwix-android#2446] opened 2020-10-16 15:16 UTC
**Describe the solution you'd like**
Option to only display "pic zim,vid zim,text only zim..."when doing a content search

**Additional context**
![AddText_10-16-06.03.33.jpg](https://user-images.githubusercontent.com/56766778/96276448-b0005b80-0fdb-11eb-975b-53e7414d53b5.jpg)

**Comment by macgills** [comment] 2020-10-19 09:56
I would consider this a dupe of #1077 , thank you for the report, closing

**Closed** 2020-10-19 10:00 UTC
