### ISSUE TITLE
Kiwix 3.3.0 Build 6230300 crashes with wikipedia_en_all_novid_2018-06.zim

### ISSUE THREAD

**Issue by Wikinaut** [kiwix/kiwix-android#2041] opened 2020-04-27 17:05 UTC
**Describe the bug**

**Expected behavior**

**Steps to reproduce the behavior:**
1. When selecting that ZIM file  wikipedia_en_all_novid_2018-06.zim (Kiwix shows 77,2 GB, Android filemanager shows 37,02 GB) which md5sum is okay, Kiwix shortly shows the start page, then crashes.
2. Works with (for example) wikipedia_de_all_maxi_novid_2019-08.zim (Kiwix shows 34,5 GB, Android filemanager shows 82,93 GB)

**Screenshots**

**Environment**
- Version of Kiwix Android : 3.3.0 Build 6230300
- Device : HUAWEI P Smart 2019 (POT-LX1)
- OS version : Android 10

**Logs**

**Comment by macgills** [comment] 2020-04-28 14:16
@Wikinaut are these files downloaded outside of the kiwix app?

**Comment by Wikinaut** [comment] 2020-04-28 16:59
@macgills Yes, they were loaded outside kiwix app and then placed into the Kiwix ZIM folder.

Today, I downloaded the last available, newer version.: wikipedia_en_all_maxi_2018-10.zim This works, i.e. no crashes, however images are missing in some articles (like "Prince (musician)" and "Apollo 13". I will investigate and report in a different issue.

**Comment by macgills** [comment] 2020-04-29 09:27
#2046 boils down to "trouble with loading svgs" and a fix has been implemented so that could be a duplicate of your "missing images" problem

As for this crash I am monitoring our crash dashboard, it could be a problem with mimetype reading and that is also fixed but I have no way of confirming they are the same.

I will try and repro soon, the download process takes some time

**Comment by macgills** [comment] 2020-05-01 08:28
I have confirmed this is due to failing to load the mimetype for a php resource.

I have also confirmed it is fixed on latest develop, a new beta will be released shortly

**Closed by macgills** 2020-05-01 08:28 UTC

**Comment by kelson42** [comment] 2020-05-01 14:03
@Wikinaut @macgills `wikipedia_en_all_maxi_2018-10.zim` has many (but not everywhere) missing pictures. This is well known.

**Comment by Wikinaut** [comment] 2020-05-01 14:31
Yes, I already reported here: https://github.com/openzim/mwoffliner/issues/1008
