### ISSUE TITLE
Checkbox always visible to user in Wifi Hotspot

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3219] opened 2023-01-27 10:21 UTC
According to _Originally posted by @kelson42 in https://github.com/kiwix/kiwix-android/issues/2537#issuecomment-1406235556_ in ```Wifi Hotspot``` checbox should always visible to user and if someone change (adding or removing a book) while service is running, then service is restarted.

**Comment by kelson42** [comment] 2023-01-27 18:17
Duplicate of #2537

**Closed by kelson42** 2023-01-27 18:17 UTC
Labels: enhancement, Hotspot
