### ISSUE TITLE
Kiwix Android full version in conflict with Playstore version

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#3839] opened 2024-05-13 06:27 UTC
A user reports:

> I have downloaded the full version Kiwix from official link as it allows me to access the ZIM Files stored in SD card.
> However I keep getting update notification from playstore to update the app to the latest version, if I do update it I loose access to the ZIM Files I have stored on the SD Card.
> Kindly clarify:
> 1. If there is a way to stop seeing KiwiX in app update section of playstore?
> 2. Or is there an Apk with a different signature so that it is not recognised by playstore?
> Problem in detail:
>The way I use playstore is by visiting the app update section, checking what new features the app updates have added and then hitting the update all button, hence you see this conflict poses a problem.

**Comment by kelson42** [comment] 2024-05-13 09:36
Do we have a duplicate of #3838 here?! Strange to get these two similar issue "together"!

**Comment by ThreeDeeJay** [comment] 2024-05-13 10:01
Looks like we have ourselves what we in the industry like to call a bit of a *coinkidink*.
Though this person is requesting APK with a *different* signatures to *block* updates while my request was about making it the *same* to *allow* updates.
But yeah, if the [play store version is missing some features](https://www.reddit.com/r/Kiwix/comments/119lwjl/why_isnt_the_play_store_up_to_date/j9pcnn9/), I wouldn't want it to replace the GitHub version either so perhaps each store/source could have its own signature to prevent updating to a different source, while using the same signature for all versions of each source so we can update them and kill 2 ~~birds~~ issues with one stone. 🤔

**Comment by MohitMaliFtechiz** [comment] 2024-05-14 05:58
> Do we have a duplicate of https://github.com/kiwix/kiwix-android/issues/3838 here?! Strange to get these two similar issue "together"!

@kelson42 No, it is not a duplicate of #3838.

> I have downloaded the full version Kiwix from official link as it allows me to access the ZIM Files stored in SD card.
However I keep getting update notification from playstore to update the app to the latest version, if I do update it I loose access to the ZIM Files I have stored on the SD Card.


 Here the user is facing the update issue if he already installed the website APK so playStore showing the update notification. It is because we are using the same keystore for generating the website and playStore APK that has the same signature that's why it is showing the update notification.

https://github.com/kiwix/kiwix-android/blob/2612cf83a8703f66e8ea1dc4c5e6c65312283579/.github/workflows/release.yml#L21-L65

**Comment by kelson42** [comment] 2024-05-14 06:15
@MohitMaliFtechiz Could we generate the APK (and nightly) and PlayStore with two different (but proper) key material?

**Comment by MohitMaliFtechiz** [comment] 2024-05-14 07:04
@kelson42 I have tested all the scenarios for this situation and we can not resolve this by changing the signature of this. 

Because there are some other things as well that Play Store now started checking along with the signature to show the update like `packageName`, and `versionCode`.
* First it checks the `packageName` of the installed application. However, the application has been generated with any signature whether it is debug or released no matter.
* Then it matches the `versionCode` of the installed application, and checks in its own database whether there is any bigger version is available or not for this `packageName`. If it finds the bigger version for that `packageName` it shows the update in "Update list" on playStore.

For example: 
I have installed the [kiwix-universal-2024-04-14.apk](https://download.kiwix.org/nightly/2024-04-14/kiwix-universal-2024-04-14.apk) that has the `3.10.0` versionCode(this apk was generated by the debug keyStore), and currently on playStore our application version is `3.10.1`. So still shows the kiwix app in "Update list" of playStore.

| Nightly APK(3.10.0) | Version | PlayStore showing update for this nightly APK |
| ------------- | ------------- | ------------- |
| ![Screenshot_20240514-120534](https://github.com/kiwix/kiwix-android/assets/34593983/495786cf-bcb8-44bc-ae9f-4ed3d767cee7) | ![Screenshot_20240514-120542](https://github.com/kiwix/kiwix-android/assets/34593983/cc6cd839-91bb-4206-ba33-e86d7acb79ff) | ![Screenshot_20240514-122717](https://github.com/kiwix/kiwix-android/assets/34593983/7910731f-5a4c-453b-a53f-86a4ca0a45e0) |


so even if we change the signature then also it will show the update for our application in the "Update list" on playStore.

**Comment by kelson42** [comment] 2024-05-14 07:24
I guess then, this will be a WONTFIX  @MohitMaliFtechiz Thank you for the detailed analysis and explanation.

**Comment by Popolechien** [comment] 2024-05-14 07:36
Wait - just to be clear: anyone installing the APK from our website is bound to get the Playstore update forced on them in the future?

**Comment by MohitMaliFtechiz** [comment] 2024-05-14 08:45
@Popolechien It will show the update on `playStore` for website APK, if there is a bigger version available on playStore, like mentioned above. but it will not force to update the APK from playStore(it will show the update in the "update list" on playStore).

**Comment by Popolechien** [comment] 2024-05-14 12:34
Ah ok I see that the playstore has 3.10.1 whereas the version available for download on kiwix.org is 3.9

**Closed** 2024-05-14 12:38 UTC
Labels: question
