### ISSUE TITLE
Swipe down to load more instead of loading at once

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#992] opened 2019-02-16 13:47 UTC
**Is your feature request related to a problem? Please describe.**
It requires more time and data of a user to get the list of Zim files all at once. The user may not have to scroll down the whole list which is being presented to him to find the one he/she is looking for. Further, due to the high data speed requirement for loading list of books at once, many times it is unable to display any Zim file.

**Describe the solution you'd like**
The Zim files should be loaded in batches and not at once. As the user reaches the end of recycler view, more files will continue to come up till he/she does not find what he/she is looking for. This way both the data and time of the user would be saved.

**Comment by abdulwd** [comment] 2019-02-16 14:45
Duplicate of #683.

**Closed by abdulwd** 2019-02-16 14:45 UTC
