### ISSUE TITLE
Articles containing "?" cannot be opened

### ISSUE THREAD

**Issue by Inbefortus** [kiwix/kiwix-android#2671] opened 2021-07-03 20:35 UTC
Kiwix Version: 3.4.4
ZIM: 2021-03 German and English Wikipedia

Articles that contain a "?" cannot be opened. You can only open them by opening them in a new tab, as demonstrated in the videos below:

https://user-images.githubusercontent.com/71934042/124366295-f58ab480-dc4e-11eb-93b7-cdb7edb5d0ea.mp4

https://user-images.githubusercontent.com/71934042/124366296-f6bbe180-dc4e-11eb-861b-1a7330a44a96.mp4

**Comment by ibrahim1520** [comment] 2021-08-08 17:28
Hello !
Can I fix it?

**Comment by kelson42** [comment] 2021-08-08 17:44
@ibrahim1520 Yes, but first, what is your analysis of the problem? How would look like your solution?

**Comment by puranjayK** [comment] 2022-01-18 19:14
Hi @kelson42 , I would like to work on this issue. However I'm a newbie here so could you guide me with this issue?

**Comment by kelson42** [comment] 2022-01-18 19:33
@puranjayK OK, but what isnthe root cause? How do you plan to fix the problem?

**Comment by puranjayK** [comment] 2022-01-19 07:30
> @puranjayK OK, but what isnthe root cause? How do you plan to fix the problem?

@kelson42 I'm a newbie, so i don't have much idea what about this. Could u guide me where I need to start from and if I should even take this issue?

**Comment by kelson42** [comment] 2022-01-19 07:36
@puranjayK This is not a programming lesson here. Either you have a clue how to fix it and you take it and if you have technical questions we might then help. But you need to know first what you have to do. All the necessary information should be available in the `README.md` to start with.

**Comment by puranjayK** [comment] 2022-01-19 13:05
@kelson42  I might have come out wrong but I wasn't asking for progamming lessons. 
I meant I'm new to this org so can you help me from where I should begin for this issue?

**Comment by airpods69** [comment] 2022-01-23 18:26
well I'd like to work on this issue 
might take 2-3 days cause i still need to look at the source code (downloaded it and got graddle working but its kinda late here for now and i got some classes) 

also its funny (Varenyam Bhardwaj here)

**Comment by airpods69** [comment] 2022-01-23 22:12
![image](https://user-images.githubusercontent.com/65490150/150699707-1723201e-0396-4682-a622-3fa405bb4242.png)
Seems like the "?" does something weird and messes up the URL for some reason

**Comment by airpods69** [comment] 2022-01-23 22:14
also im so sorry @puranjayK I totally ignored the fact that you wanted to work on this issue!

**Comment by cdhiraj40** [comment] 2022-01-24 08:13
> ![image](https://user-images.githubusercontent.com/65490150/150699707-1723201e-0396-4682-a622-3fa405bb4242.png) Seems like the "?" does something weird and messes up the URL for some reason well atleast this is what i could tell from the logs

@airpods69 could you tell me where you got the article which had this  ``?``so that I can reproduce and see if I get something :)

**Comment by airpods69** [comment] 2022-01-24 08:23
> > ![image](https://user-images.githubusercontent.com/65490150/150699707-1723201e-0396-4682-a622-3fa405bb4242.png) Seems like the "?" does something weird and messes up the URL for some reason well atleast this is what i could tell from the logs
> 
> @airpods69 could you tell me where you got the article which had this `?`so that I can reproduce and see if I get something :)

found it in the wikipedia (the simplified english one i forgot the name ;-;) 
search for rihana then scroll down and look for the loud album
open it and you should find the article with a "?" in it

**Comment by cdhiraj40** [comment] 2022-01-24 09:05
Thanks @airpods69 telling me the file name. @kelson42 seems like the content doesn't exist in the kiwix library itself so it can't find it which results in not opening the next article
for eg: 
http://library.kiwix.org/wikipedia_en_simple_all_maxi_2022-01/A/What's_My_Name?
I don't think so if the issue is with our app

**Comment by airpods69** [comment] 2022-01-24 09:11
maybe it is an issue with link if you ask me (just a hunch tbh)
![image](https://user-images.githubusercontent.com/65490150/150753628-b5c3711a-90c3-43ce-be77-bb83956543c5.png)
but looking at the links it doesnt allow or even consider "?" while looking for it 

and also i used the simplified wikipedia because it had a smaller download size 
the person who opened the issue must have been using the complete version of wikipedia

**Comment by cdhiraj40** [comment] 2022-01-24 09:19
> maybe it is an issue with a link if you ask me,  but looking at the links it doesn't allow or even consider "?" while looking for it
you are correct but I have noticed many times that the link with the ``?`` mark in end doesn't matter it will go to the same link 
try: [link1](https://www.kiwix.org/en/support-us/code?)[link2](https://www.primevideo.com?)

> and also I used the simplified Wikipedia because it had a smaller download size the person who opened the issue must have been using the complete version of Wikipedia

I checked in complete version only that is https://download.kiwix.org/zim/wikipedia/wikipedia_en_simple_all_maxi_2022-01.zim

**Comment by airpods69** [comment] 2022-01-24 09:26
well no thats not the issue here 

"whats my name?" does exist 
instead of "?" it goes to %3F

so it doesnt exist cause its the wrong link which we are going to

replacing "?" with "%3F" should solve the issue while looking up for the link

we are looking for:
http://library.kiwix.org/wikipedia_en_simple_all_maxi_2022-01/A/What's_My_Name?

when we should be looking for:
http://library.kiwix.org/wikipedia_en_simple_all_maxi_2022-01/A/What's_My_Name%3F

**Comment by cdhiraj40** [comment] 2022-01-24 09:28
> well no thats not the issue here
> 
> "whats my name?" does exist instead of "?" it goes to %3F
> 
> so it doesnt exist cause its the wrong link which we are going to
> 
> replacing "?" with "%3F" should solve the issue while looking up for the link
> 
> we are looking for: http://library.kiwix.org/wikipedia_en_simple_all_maxi_2022-01/A/What's_My_Name?
> 
> when we should be looking for: http://library.kiwix.org/wikipedia_en_simple_all_maxi_2022-01/A/What's_My_Name%3F
> 
> so there you go the issue should be easy to solve just need to change how the link thingy works

okay yeah, that does solve the thing, I thought the link didn't exist. Thanks for the info ;)

**Comment by airpods69** [comment] 2022-01-24 09:30
yep that seems to be the case for rihana but lemme just check with the german one

**Comment by airpods69** [comment] 2022-01-24 09:36
actually that doesnt explain one thing

if it doesnt redirect then why does it work when the link is opened in a new tab 
so that means its not a library issue right?

**Comment by airpods69** [comment] 2022-01-24 09:38
I am not sure how libraries work but replacing "?" with "%3F" at all occurrences when loading the URL should fix it without changing everything in the library

**Comment by airpods69** [comment] 2022-01-24 14:58
me and @cdhiraj40 discussed this but i thought putting it up here also would make sense so that everyone knows 


![IMG_20220124_153357~2.jpg](https://user-images.githubusercontent.com/65490150/150806748-59634fd3-a250-45ea-bca1-3755a2ff4798.jpg)

something interesting that i found

**Comment by Jaifroid** [comment] 2022-01-26 22:00
Hi all, this is an issue we also had in Kiwix JS. Please see https://github.com/kiwix/kiwix-js/issues/806 and the PR that fixes it https://github.com/kiwix/kiwix-js/pull/807. The issue is simply that the URL needs to have any querystrings and anchors removed BEFORE it is decoded.

A URL in a ZIM article is URI-encoded by default, but it may have additionally have a querystring, or an anchor (and that question mark and hash, if any, are not encoded). Usually a reader will have a function that removes any querysting and anchor before then decoding the URI and sending it to the backend for reading from the ZIM.

However, if the URI is decoded first and then querystrings are removed, then of course the question mark will be interpreted as a querystring and it and everything after will be removed.

You shouldn't substitute all question marks for %3F in the backend, or else you will introduce more problems than you solve! You should use a proper `decodeURIComponent` function _after_ you have removed any querystring or hash anchor from the encoded URL in the article's HTML.

**Comment by bip7686** [comment] 2022-03-09 17:56
org.kiwix.kiwixmobile.core.main.CoreWebViewClient in line 143 the url "https://kiwix.app/A/What's_My_Name?" is not encoded. So that would mean that the url is decoded somewhere else? I was not able to find the place where the actual request is done.

**Comment by kelson42** [comment] 2022-07-28 12:54
@Inbefortus Maybe this big is already fixed in 3.6.0, but otherwise we will fic it in 3.7.0.

**Comment by kelson42** [comment] 2022-12-01 10:45
@MohitMaliFtechiz Not a duplicate of #2847

**Comment by MohitMaliFtechiz** [comment] 2022-12-01 12:17
> @MohitMaliFtechiz Not a duplicate of #2847

hi @kelson42 , Both Issue are different. since #2847 is related to new tab(webview is not giving proper url to handle) and #2671 is for article contains ? not opening. but i have placed a fix for both issues in #2968.

**Comment by MohitMaliFtechiz** [comment] 2023-07-10 08:02
@kelson42, We already fixed this issue in https://github.com/kiwix/kiwix-android/pull/2968

**Comment by kelson42** [comment] 2023-07-10 08:06
@Inbefortus I will close the ticket but woukd be glad to get your feedback to confirm this is fixed in 3.7.

**Closed** 2023-07-10 08:06 UTC
Labels: bug, good first issue

**Comment by Inbefortus** [comment] 2023-07-10 09:24
@kelson42 Yes, I can confirm that this issue has been eliminated 👍

![Screen_Recording_20230710-111040_One UI Home_1](https://github.com/kiwix/kiwix-android/assets/71934042/6b41f9b6-cd1d-4a22-a3ae-92677dc8f294)
