### ISSUE TITLE
F-droid app is out of date

### ISSUE THREAD

**Issue by avidseeker** [kiwix/kiwix-android#3376] opened 2023-05-30 20:05 UTC
[Kiwix F-droid](https://f-droid.org/en/packages/org.kiwix.kiwixmobile/) app version is 2.4 (2018-09-21). This is causing the app to break (keeps prompting storage permissions), and it needs to be updated.

**Comment by licaon-kter** [comment] 2023-05-31 06:50
https://github.com/kiwix/kiwix-android/issues/3091 is still not fixed afaik

/close as duplicate of many issues

**Comment by kelson42** [comment] 2023-05-31 06:59
Yes, we have many tickets to remove ObjectBox and this is an ongoing effort.

**Closed** 2023-05-31 06:59 UTC
Labels: duplicate
