### ISSUE TITLE
Search bar not restored after exiting full screen

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#3744] opened 2024-03-11 15:41 UTC
Report from a user (note: I was not able to reproduce on Nothing Phone 2 phone running the same version, might be a tablet thing?):

I use KiwiX on a Samsung Galaxy Tab S9 Ultra running Android 14. I'm running version 3.9.1 build 7230901 from the app store (with Wikipedia of about 109gb downloaded via the app).

When I first open Wikipedia in KiwiX, there is the very helpful menu section in the third top line on the right - Search/Windows/Random/Dots.

If I go to fullscreen, all the top menu lines disappear (as they should). However, when I "Exit fullscreen", the all-important third top line (Search/Windows/Random/Dots) is not restored, so it is no longer possible to search. The only way to restore the third-top line is to exit KiwiX and then restart it, or to go to Split-screen (second-top line on the right) and then go back to Single-screen.

Would it be possible to make the third top line (Search/Windows/Random/Dots) visible below the second line after "Exit Full-screen"?

**Comment by kelson42** [comment] 2024-03-14 06:26
@MohitMaliFtechiz You confirm?

**Comment by MohitMaliFtechiz** [comment] 2024-03-14 09:52
@kelson42 No, I have tested this scenario on both mobile and tablet with different scenarios(Rotating the screen after opening the full-screen mode, etc), but I am unable to reproduce it all the menu items are showing after closing the `Full-screen mode`. However, I am wondering because we have not put any code that hides the menu when closing the full-screen mode.

![Screenshot from 2024-03-14 14-58-09](https://github.com/kiwix/kiwix-android/assets/34593983/e8b9e3a5-c88c-465f-a893-6a980bf6e24e)


We are only hiding menu items when the loaded URL is invalid (There is no URL for loading in the webview). But here, this case is not applicable because the user can able to to see these options when he closes and reopens the application so it means the previously loaded URL is valid.

https://github.com/kiwix/kiwix-android/blob/f7a34c1b42fbe2a109952c9f9324464a8ea879a6/core/src/main/java/org/kiwix/kiwixmobile/core/main/MainMenu.kt#L113

**Comment by Popolechien** [comment] 2024-03-14 10:03
Ok should we close the issue then?

**Comment by MohitMaliFtechiz** [comment] 2024-03-14 10:22
@Popolechien We can close this issue as we are not able to reproduce this, and programmatically we do not hiding these menu items, if any zim file is showing in the reader.

**Closed** 2024-03-14 10:30 UTC
Labels: bug, question
