### ISSUE TITLE
Come up with a set of devices we want to test on

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#110] opened 2017-04-20 11:17 UTC

**Comment by kelson42** [comment] 2017-05-12 11:20
@mhutti1 What is the status on this? I think you made a first choice. This might be improve lately but this ticket seems to be implemented.

**Comment by mhutti1** [comment] 2017-05-12 20:43
Yes we have an initial set of devices. We can close this ticket if you want but we will need to revisit it in the future.

**Comment by mhutti1** [comment] 2017-05-13 12:15
We need to ensure that we test on devices popular with our users and ensure
we also test on a cross section of Android devices. Currently I have simply
picked 3 devices with different versions that are popular.

**Comment by julianharty** [comment] 2018-04-13 17:14
I've been thinking about which devices we'd like to run our tests on as part of each commit. My impression is we'll want to know, via running the automated tests, whether the changes in *this* commit have caused any new problems. 

Separately we may want to run additional heavier-duty tests and/or our current tests on additional devices in order to focus on _existing flaws in our code_ so we can identify these flaws and then address them. 

Based on these premises we'll want to pick devices where our app seldom crashes in the field to run the CI tests and devices where our app often crashes for the second type of bug-reproduction tests.

Google Play Console has a section called Android vitals. In the Overview we can sort devices by their % of crash-free sessions. The 2 most reliable devices are the Samsung S6 and S7 models. 
```
Device             | Impacted sessions | Crash-free sessions | Number of sessions | Bottom quartile |  
Samsung Galaxy S6 Edge (zerolte)       | 0.25% | 99.75% | ~400 | 0.68% | CRASHES
Samsung Galaxy S7 (heroqltevzw)        | 0.38% | 99.62% | ~300 | 0.70% | CRASHES
Samsung Galaxy S7 Edge (hero2qltetmo)  | 0.46% | 99.54% | ~200 | 0.73% | CRASHES
Samsung Galaxy S6 (zerofltespr)        | 0.54% | 99.46% | ~400 | 0.80% | CRASHES
Samsung Galaxy S6 (zeroflte)           | 0.55% | 99.45% | ~500 | 0.62% | CRASHES
```

The least reliable models are:
``` 
Device | Impacted sessions | Crash-free sessions | Number of sessions | Bottom quartile
Samsung Galaxy Note8 (greatlte) 7.44%	92.56%	~100	0.92%	
Huawei P9 lite (HWVNS-H)         4.27%	95.73%	~200	0.61%	
OnePlus OnePlus3 (OnePlus3)     4.15%	95.85%	~200	0.81%	
Samsung Galaxy S6 (zerofltevzw) 3.64%	96.36%	~300	0.74%	
OnePlus OnePlus3T (OnePlus3T)    3.64%	96.36%	~200	0.84%	
```
(Sorry I've not quite got the formatting right, I hope the tables are clear enough to understand). We can see the S6 appears in different guises in both the most reliable and least reliable extremes. Different models with the same brand name, it seems.

When the crash rate is sorted by number of sessions (an indication of popularity of the devices) Samsung have 16 of the top 20 places in the table (see screenshot)

<img width="741" alt="screen shot 2018-04-13 at 18 06 43" src="https://user-images.githubusercontent.com/785891/38748316-a1fa9d2a-3f45-11e8-88af-d530c34774b9.png">

On this basis alone I'd recommend we test on Samsung S6 and S7 devices as part of the CI.
Filtering the crashes by Android OS version shows the most common Android versions are 8.0 and 7.0 

**So for our Travis-CI and Testdroid integration let's pick a permutation of S6 and S7 one running Android 7.0 and the other Android 8.0.** The actual permutation will depend on which devices are easily available in Birbar's Testdroid service.

We may want to revise the devices in a month or so depending on the relative popularity of Android OS versions. Note: the oldest Android OS version in the filters is 6.0.

**Comment by kelson42** [comment] 2018-04-14 15:34
@julianharty All of this seems to make sense. Now it is important to implement the change, test and close the ticket. If someone has an improvement on this he can then make next iterative improvement.

**Comment by julianharty** [comment] 2018-05-21 21:13
A quick update. I've added a Xiaomi Android 4.4 device and re-run one of the current open merge requests. One test failed on that device. I don't know exactly why yet the error message is:
```
Test failed to run to completion. Reason: 'Instrumentation run failed due to 'Native crash''. Check device logcat for details
```
I'll investigate in the morning. Perhaps another batch of tests will have been run overnight on this device which may help indicate whether the issue is related to the device or something else.

**Comment by julianharty** [comment] 2018-05-22 13:17
I'll close this issue as we've now got a useful set of 4 devices for CI testing. They are:

1. Samsung Galaxy S7 Edge, Android 6.0.1
2. Samsung Galaxy S6, Android 7.0
3. OnePlus Two A2001, Android 6.0.1
4. Lenovo Lemon K3, Android 4.4.4

![android devices for testing in the ci 22 may 2018](https://user-images.githubusercontent.com/785891/40364591-a3067466-5dca-11e8-83b4-66e28df19ce9.png)

They are a mix of the most popular devices and one that runs KitKat and our tests successfully.

**Comment by mhutti1** [comment] 2019-03-03 21:44
Reopening as s7 is dropping out a lot.

**Comment by mhutti1** [comment] 2019-03-03 21:45
I have removed it from the list for now.

**Comment by kelson42** [comment] 2019-06-14 08:54
@mhutti1 @macgills @julianharty Can we close that ticket?

**Comment by macgills** [comment] 2019-06-14 09:21
Right now bitbar is running one device so I think that we should add more as now it is our early warning system for device specific crashes

**Comment by julianharty** [comment] 2019-06-14 09:36
I agree with @macgills that we should add several more devices to help increase the chances of catching both device-specific bugs and detecting transient issues that cause the tests to fail - if the tests fail so might the app for end-users. That said, perhaps it'd also be worth enhancing the tests so they detect some of the most relevant failure conditions e.g. download server not available.

**Comment by kelson42** [comment] 2019-06-16 06:32
@mhutti1 @macgills @julianharty I don't understand: this ticket is 1 year old and the choice of devices (which is probably the most time intensive work) has been made. Why BitBar has still only one device configured? Where is the documentation explaining how to add/remove a device?

**Comment by mhutti1** [comment] 2019-06-16 16:06
The most recent issues were that we were testing on devices that were taking hours to become available. Ideally we would want to specify a subset of devices say 10 and then take the first 5 we can run on and use those to test so If some arn't available things don't go wrong.

**Comment by kelson42** [comment] 2019-06-16 16:29
@mhutti1 What happens if the chosen devices are not available? Do the CI wait? Is that handle in the CI itself (with a loop) or does testdroid just takes hours to give a feedback?

**Comment by mhutti1** [comment] 2019-06-16 16:52
We timeout after ~30 mins I think and CI marks it as a failure.

**Comment by kelson42** [comment] 2019-06-23 17:03
@macgills  Something needs to be done here, maybe by following Isaac's advice, to achieve to test on a good set of devices.

**Comment by macgills** [comment] 2019-06-24 07:31
I re-added the devices mentioned by this ticket, will monitor their progress

**Comment by kelson42** [comment] 2019-06-24 07:39
@macgills Thx, I propose to close that ticket. The purpose if this ticket has been reached. If the CI is not reliable because of any weakness in the device farm mgmt (devices not always available on time?) then a new ticket should be IMO open.

**Comment by macgills** [comment] 2019-06-24 07:40
Agreed

**Closed by macgills** 2019-06-24 07:40 UTC
Labels: enhancement
