### ISSUE TITLE
Add pagination in Download section

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#2626] opened 2021-04-01 18:58 UTC
**Is your feature request related to a problem? Please describe.**
Now all the zim files are downloading at once, which may be what the user wants or not. Pagination will load and display small chunks of data at a time(i.e zim files). Loading partial data on-demand reduces the usage of network bandwidth and system resources.

**Describe the solution you'd like**
Add pagination and show a small chunk of data at a time. After the user goes to the end or nearly end we will ask another chunk of data to load. This will dramatically decrease the user's bandwidth and loading time.

**Describe alternatives you've considered**
Nothing yet.

**Comment by s-ayush2903** [comment] 2021-04-01 19:00
Dupe of #683, see #1203 for more info. Closing

**Closed** 2021-04-01 19:01 UTC
Labels: enhancement, question

**Comment by gouri-panda** [comment] 2021-04-01 19:17
I thought pagination will solve this problem untill OPDS came. We just have to refactor some code a little bit.
