### ISSUE TITLE
Blank pages on Webview Chrome 76 in latest zim files

### ISSUE THREAD

**Issue by JPRO89-Cu** [kiwix/kiwix-android#1339] opened 2019-08-08 23:17 UTC
I tried android >= 7. With wiki all_nopic_ES  zim file from june (latest). Devices  that uses Chrome as default webview (not tried default webview v76 but is the same), but in v76 (maybe v7*) kiwix displays a blank page in all articles with the latest zim file of wikipedia. I tried old zim files and worked. But to work with the latest zim file I have to downgrade chrome to v66

**Comment by JPRO89-Cu** [comment] 2019-08-09 03:47
Found this on logcat opening wikipedia no pics june spanish where Wikipedia:Portada is the article to search
ContentResolver: Failed to get type for: content://org.kiwix.kiwixmobile.zim.base/A/Wikipedia:Portada (Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference)

**Comment by kelson42** [comment] 2019-08-09 05:32
Quite sure this is a duplicate of #1294

**Closed by kelson42** 2019-08-09 05:32 UTC
