### ISSUE TITLE
List item not visible on KeepToolbarVisible option Off

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#894] opened 2018-11-13 21:01 UTC
**Describe the bug**

When you keep toggle off the settings' KeepToolbarVisible button, the last list item is not completely visible. Again if you toggle on the switch, it behaves properly. This happens upon the second time, not in the first time.
Similar to #566 but bit different. It does not happen in the first time but in the second or third time.

**Expected behavior**

All the list items should be visible properly.

**Steps to reproduce the behavior:**
1. Toggle on the KeepToolbarVisble switch.
2. Go back to the main page.
3. Repeat step 1 and step 2 and probably by second-time issue is visible.

**Screenshots**

![kiwix crash 7 gif](https://user-images.githubusercontent.com/34706326/48442327-ead83400-e7b3-11e8-856b-40b703807c85.gif)

**Environment**
- Version of Kiwix Android: Build 2.4
- Device : Redmi 4
- OS version : Android 7.1

**Comment by prajurock** [comment] 2019-02-14 23:04
@sonusourav Are you working on this issue??

**Comment by prajurock** [comment] 2019-02-15 05:12
@abdulwd Can i work on this issue .This issue was created many days ago.

**Comment by sonusourav** [comment] 2019-02-15 12:30
@prajurock  I am working on this issue.

**Comment by prajurock** [comment] 2019-02-15 12:50
Ok @sonusourav proceed.Good Luck.

**Comment by kelson42** [comment] 2019-12-26 22:32
This needs to be re-confirmed with 3.1.2

**Comment by macgills** [comment] 2020-01-08 13:46
Confirmed I believe, I opened #1611 and it appears to be a duplicate of this

**Comment by kelson42** [comment] 2020-01-08 16:43
Duplicate of #1611

**Comment by kelson42** [comment] 2020-02-24 12:50
@macgills To me it looks like this bug has not been fixed properly. The last item is still hidden by the bottom bar on my Android 10 Google Pixel2.

**Comment by macgills** [comment] 2020-02-24 12:56
@kelson42 see #1611

**Closed by macgills** 2020-02-24 12:56 UTC
Labels: bug, duplicate

**Comment by kelson42** [comment] 2020-02-24 13:03
@macgills oops, sorry.
