### ISSUE TITLE
App Crashes when tap the Notification Bar

### ISSUE THREAD

**Issue by Achintya999** [kiwix/kiwix-android#668] opened 2018-03-25 19:15 UTC
Bug Report

Are you ready to report?

-Yes

Environment

    version of the software you use: Latest master
    device / operating system: One Plus 5/ Android 8.0

The Bug:

When in no internet range, and we close the app while downloading we can see the downloading in the notification and if we tap the notification the app crashes.
Similar to Issue number #600 but its when we close the app.

**Comment by kelson42** [comment] 2018-03-26 09:17
Yes to me, pretty much a duplicate of #600

**Comment by Achintya999** [comment] 2018-03-26 11:56
Yes but this is when the app is closed and the downloading continues we can see it in the notification panel and then the app crashes.

**Comment by hjoshi123** [comment] 2018-03-26 12:27
@Achintya999 Can you explicitly tell me when the crash occurred because in PR  https://github.com/kiwix/kiwix-android/pull/652 I fixed the unregisterReceiver issue that crashed the app when you closed it. So please tell me so when you are getting this error. I will try and if its still there I will make a PR as soon as possible.

**Comment by macgills** [comment] 2019-05-27 10:57
Fixed in #1170

**Closed by macgills** 2019-05-27 10:57 UTC
