### ISSUE TITLE
Exit from Kiwix when typing a search

### ISSUE THREAD

**Issue by Beater34** [kiwix/kiwix-android#3606] opened 2023-12-16 02:43 UTC
I am using a Moto g54 phone running Android 13 and I have a problem with Kiwix android version 3.8.1 build 7230801. I am a beta tester of Kiwix (but with no coding expertise). I am using English wikipedia_en_all_maxi_2023-10.zim downloaded on 1st Dec 2023. 

When I type in the Kiwix search field at normal speed, after typing 3-5 characters, I am returned to the previous screen (e.g. the home screen if I started Kiwix from there); the app remains open, but the search field is empty if I return to Kiwix. 

I can get around the problem by typing very slowly in the search field, so that the search is finished for each letter or combination of letters before I enter the next letter – for example, if I type ‘w’, I wait for that search to finish; then ‘i’, I wait for the ‘wi’ search to finish; then ‘k’, I wait for the ‘wik’ search to finish all the way to ‘wikipedia’. The problem persists after stopping Kiwix, and after restarting the phone.

**Comment by kelson42** [comment] 2023-12-16 08:22
@Beater34 Thank you for your bug report. Pretty sure this is a duplicate of #3581 which is fixed in [nightly](https://download.kiwix.org/nightly/) and version `3.9.0` (to be release later today). If not please reopen and we would be glad to further investigate.

**Closed by kelson42** 2023-12-16 08:22 UTC
