### ISSUE TITLE
Can't load wikisource content 

### ISSUE THREAD

**Issue by nicosims** [kiwix/kiwix-android#3479] opened 2023-09-12 04:17 UTC
Using the android app, downloaded both the text only and pictures versions of wikisource available, the issue persists with both. While you can navigate the website, as soon as you try to read a chapter or article, rather than just the table of contents or authors page, nothing loads. There is not text or anything else there, not even an error message.

**Comment by kelson42** [comment] 2023-09-19 05:43
@MohitMaliFtechiz Can you reproduce this problem? I guess this is wikisource in english.

**Comment by MohitMaliFtechiz** [comment] 2023-09-19 08:51
@kelson42 I have tested 3 Wikisource files (English, Dansk, Latin) with the develop branch and I am unable to reproduce the error. @nicosims can you please try with [latest nightly APK](https://download.kiwix.org/nightly/2023-09-19/kiwix-universal-2023-09-19.apk) or with the develop branch is this issue still exists at your end?

**Comment by kelson42** [comment] 2023-09-26 10:23
no feedback. likely fixed on dev. closinh

**Closed by kelson42** 2023-09-26 10:23 UTC
Labels: question
