### ISSUE TITLE
Heading does not change in App bar when Help is opened.

### ISSUE THREAD

**Issue by arpank10** [kiwix/kiwix-android#619] opened 2018-03-11 12:59 UTC
### Environment
  * version of the software you use : Version 2.3 build 55
  * device / operating system : Android 7.1.1
  
### The Bug:

  * What do you obtain? A copy of the error message or a screenshot is always useful.
 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24573296/37253603-e7e171c0-2559-11e8-8087-3a38e481d30f.gif)

#### Steps to reproduce:

  1. Open any zim file.
  2. Open help from options.
  3. Heading does not change.

  
  * What should be the behaviour from your point of view? How do you expect the service to work?

 Heading should change to "Help" when help is opened.

**Comment by RajaVamsi11** [comment] 2018-03-11 16:04
@arpank10  Can i work on this issue?

**Comment by arpank10** [comment] 2018-03-11 16:17
@RajaVamsi11  Sure, go ahead.

**Comment by mhutti1** [comment] 2018-03-11 23:27
Duplicate of #540 please search before opening issues.

**Closed by mhutti1** 2018-03-11 23:27 UTC
Labels: good first issue
