### ISSUE TITLE
Storage permissions are unnecessarily required

### ISSUE THREAD

**Issue by danielzgtg** [kiwix/kiwix-android#3265] opened 2023-03-14 00:31 UTC
**Describe the bug**

Whenever an app refuses to work unless I give it storage permissions, I always give it a 1-star review on Google Play. Open source apps I compile from source are an exception, but I still don't like that. This is a privacy concern after one of my apps scanned my entire storage and tried to upload everything. Storage permissions are unnecessary for reading user-selected files on modern Android.

**Expected behavior**

Kiwix-android should not:
- ask for
- declare in AndroidManifest.xml
- mention in any documentation
- require
- use

any storage permissions.

When I'm using the app, it shouldn't even make me think of storage permissions. Please use modern Android APIs like SAF and `Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION`. I know this is possible because my own apps never ask for storage permissions. An example of an app I ported to SAF is https://github.com/danielzgtg/DeepSpeech-examples/blob/33f58a39a5f1005ac1e7e1a6efb685c0dce12d2d/android_mic_streaming/app/src/main/java/org/deepspeechdemo/LoadFilesActivity.kt .

**Steps to reproduce the behavior:**
1. Install Kiwix
2. Open Android Settings
3. Open "Privacy"
4. Open "Permissions manager"
5. Open "Files"
6. Open "See more apps that can access all files"
7. Tap "Kiwix"
8. Notice that this page exists

**Screenshots**

This screen shouldn't exist:

![Screenshot_20230313-202753_Settings](https://user-images.githubusercontent.com/25646384/224861707-e7054d7b-6ae6-482a-9518-3b8d11bab63e.png)

**Environment**
- Version of Kiwix Android : 3.6.0
- Device : OnePlus 7 Pro
- OS version : Android 13 crDroid 9.2

**Comment by danielzgtg** [comment] 2023-03-14 00:32
I would like to work on this once I find the time to.

**Comment by kelson42** [comment] 2023-03-14 05:10
@danielzgtg We should agree first before starting any code.
@MohitMaliFtechiz Is that ticket not a duplicate?

**Comment by MohitMaliFtechiz** [comment] 2023-03-14 12:45
@kelson42 , We have try like this in https://github.com/kiwix/kiwix-android/issues/2890 . 
* We have used ```ACTION_OPEN_DOCUMENT_TREE``` (to take access of a directory, which we are using in non playstore build) and ```Storage Access Framework``` to access file from storage but above android 11 when we are accessing files which is downloaded outside from our app like from chrome , we are unable to read that file in our app without ```MANAGE_EXTERNAL_STORAGE``` permission.
* we also try some library code like https://github.com/braver-tool/Android11FilePicker , but they copy files from storage and access into there application. But this is not the use case for app to copy GB files and access into our application.

**Comment by danielzgtg** [comment] 2023-03-14 13:10
> we are unable to read that file in our app without MANAGE_EXTERNAL_STORAGE permission.

This is false, as demonstrated by my PR.

I will not tolerate any ~~rationales~~ excuses made by apps. Microsoft Teams did this and I gave it a 1-star review. Discord implemented it properly. I was trying to share pictures downloaded through SAF. I ended up refusing to grant the permission and used the Microsoft Teams webapp instead.

> library code

It shouldn't take a whole library. It's 10 lines of code to access the file.

That took me like only an hour or two. I just quickly deleted every file mentioning "storage," cascaded the delete, then changed `File` to `Uri`, imported my code from my other app, and cascaded the type change. The rest of the work would be updating the rest of the app to accept `Uri`s instead of `File`s.

> `ACTION_OPEN_DOCUMENT_TREE`

This isn't nice but it is somewhat tolerable. I would prefer to select a file instead of a directory.

> above android 11

Good point, I didn't consider anything below Android 11

**Comment by kelson42** [comment] 2023-03-18 14:55
@danielzgtg Your PR implies so far so many regressions, that I guess we can not really consider it... or I miss something?

**Comment by danielzgtg** [comment] 2023-03-18 16:41
@kelson42 I marked that PR as draft. I listed what work still needs to be started, and said that it will take 2 months. It should not be merged any time soon as that will cause regressions.

It's only there to demonstrate that the core idea is possible, and how the File to FileDescriptor transition can be achieved. I have reached my goal of removing the permissions while keeping the features I use working. I pushed the code just so that other people can take a look, without suggesting it be merged until further work starts.

What needs to be done is to do the same work to bring back every single feature that deals with files, with individual particularities for each. We now have a map with one way of reaching this goal for the other features. However, actually getting there will be lots of tedious work.

**Comment by Jaifroid** [comment] 2023-06-03 17:46
I'm not sure how version 3.7.0 will deal with file access permissions, but I continue to believe strongly that including a file picker is a must. Ideally both a file and a directory picker, but I'd be OK with a file picker. The fact that the PWA app can pick virtually any file on Android, on an SD card or anywhere else available to a file picker, strongly suggests this is a possibility. Given that we are often dealing with multi-GB files in Kiwix, it seems like a primary use-case for files that have been transferred to an SD card from a PC, or that have been downloaded outside the app, without requiring system-wide file-scanning capabilities (which will definitely put a lot of people off in our security-conscious age).

Maybe the app could operate in two modes. In a "simple" (default) mode it would simply have a file picker, and also of course have access to files it downloads itself into internal storage. But in settings a user who trusts the app fully could enable wider file permissions (if permitted by the Store the app was obtained from), and these would only be requested when the user turns the option on.

The "simple" version could be the only one available in the Play Store, enabling the app to pass certification there (or is this now fixed for v3.7.0?).

**Comment by Jaifroid** [comment] 2023-06-03 17:48
Edited to change version number to 3.7.1.

**Comment by vb0** [comment] 2023-06-17 06:45
I confirm the PWA works on external USB with the file picker (and SAF?) and the Pixel. This is important because Pixels don't expose the external storage as mount points to apps and to my knowledge there's no way to make them work with the regular Kiwix Android app without copying the file, which is usually no-go for multi-tens-of-GBs files. For better or worse the Pixels are the reference Android devices and if the app is in practice unusable with the large (and most interesting) archives this should be taken care of with quite a high priority.   

In the meantime there should be more prominently advertised somehow that **there is a PWA app that actually works with files from USB**. I spend more than one year looking for any kind of workarounds.   

As far as performance goes - as SAF is usually known to be a killer there is a slight lag in opening each article, like one would be on a sub-optimal internet connection but it's PERFECTLY acceptable. Everything works well, search, pictures, etc. - with the largest 90GB+ English Wikipedia. I turned off internet to confirm everything is coming locally.   

Also now that I double checked the PWA appears on kiwix.org under "Browser Extensions" which is misleading when one looks for Android software, as mobile browsers don't support extensions (well, some do with some serious limitations and pains, but this isn't widely known or even clear that it would help here).

**Comment by Jaifroid** [comment] 2023-06-17 08:35
As the lead dev on the PWA version, I can say that the app does not require any permissions and doesn't use SAF. Its ability to pick files probably comes from the underlying permissions that the browser has, given that the browser is privileged.

One limitation of the PWA currently is that, due to the crippled performance of Android file access at least from external storage, full-text search is currently disabled. It takes way too long to initiate (at least on full English Wikipedia), and too long for results to be returned. It can be experimentally turned on with the option under Expert Settings -> Troubleshooting and Development -> Force use of libzim... for reading full-text index (use dropdown and select WASM). However, on my device I found that frankly unusable. Some other users of high-end Galaxy devices have said that it works for them.

The other limitation is having to pick the file each time (lack of persistent permissions). This is simply due to the fact that Google devs have so-far declined to implement the File System Access API on Chrom(ium) Mobile.

It should also be stated that the PWA on Android requires Chrome or Chromium-derived browsers. Firefox for Android appears at first to be much faster, but it achieves this by copying the whole file into its internal storage (or possibly into RAM), which of course only works with small archives, and fails spectacularly with anything larger than 2GB.

**Comment by kelson42** [comment] 2023-06-23 11:55
@MohitMaliFtechiz have we already considrr to use https://github.com/anggrayudi/SimpleStorage ?

**Comment by MohitMaliFtechiz** [comment] 2023-06-30 13:14
@kelson42, No, we are not currently considering using `SimpleStorage`. Instead, we are attempting to access files for different API levels without relying on any library. However, it might be worth giving this library a try since it already handles all API levels.

**Comment by Jaifroid** [comment] 2023-08-17 06:51
Although #3414 provides info in README about the Play Store restrictions, it doesn't address users' legitimate security concerns since it simply tells users to sideload the unrestricted version with full file-scanning capabilities, i.e. to circumvent the security restrictions that are there to protect users.

While of course I personally trust Kiwix, it doesn't seem to me that the app should simply circumvent policies that have been put in place to prevent malicious activity. In fact, the README doesn't address security concerns at all,. Are we 100% sure we're immune to hacking? Are we sure that one of our myriad dependencies will never get compromised without our knowledge, as has happened even to big well-funded development outfits? This is the reason for the Play Store restrictions, they haven't just been put in because Google likes to make devs' lives hard.

@danielzgtg has demonstrated that it is possible to pick archives with a different API without requiring system-wide permissions. You only request permissions for the file (or potentially the folder) that is picked (and you cache that permission so it can be re-used). This ensures users have control over their own data.

Therefore, after the upcoming release, ISTM that changing the file access model along these lines should be a real priority.

**Comment by kelson42** [comment] 2023-08-17 07:05
@MohitMaliFtechiz so you confirm that the theoritical plus practical approach of @danielzgtg draft PR is invalid? It does not help post android10 versions to access zim files without requesting permissions and therefore is not a valid approach? If "yes", please explain why.

**Comment by Jaifroid** [comment] 2023-08-17 07:55
@kelson42 The approach is not "accessing ZIM files without requesting permissions". It is "requesting permissions at the point of first access" and not expecting the user to grant wide-ranging permissions to all storage on the device in advance.

**Comment by Jaifroid** [comment] 2023-08-17 17:28
I copiled @danielzgtg's PR in Android studio, but unfortunately any ZIM I try to open with this PR version is reported by the app as not being a valid ZIM file. So I am unable to reproduced the success that @danielzgtg reported and demonstrated in the screen cast.

**Comment by kelson42** [comment] 2023-08-17 23:46
> @MohitMaliFtechiz Thanks for investigating this, it's such a crucial issue for Kiwix Android.

Allow me to be preciser: its not at all a problem with Android, its a problem with the Play Store. Considering that a large majority of our Android users download from the Playstore, we can take the thoughs shortcut, but we should not forget about the reality.

**Comment by MohitMaliFtechiz** [comment] 2023-08-18 07:08
> Where were the files you were attempting to open? I assume it's not possible to open files that are in another app's specific directory, as those are restricted.

Yes, I am not opening files from another app's specific directory.

>  But a file downloaded to a public directory such as Downloads, or in a user-created (rather than app-created) directory should be accessible.

I am opening zim files from the download folder but am unable to read those files with @danielzgtg PR.

> I compiled @danielzgtg's PR in Android studio, but unfortunately any ZIM I try to open with this PR version is reported by the app as not being a valid ZIM file. So I am unable to reproduced the success that @danielzgtg reported and demonstrated in the screen cast.

So as you try but the application shows zim file is not valid it is because @danielzgtg remove those checks in his PR which checks whether we can read that file or not before opening the zim file so because of this we are directly opening the zim file with `FileDescriptor`, and `libkiwix` unable to read that file because there is no read permission as I have shown on the above image, As a result `not a valid zim file` message shown because we have placed this condition here https://github.com/kiwix/kiwix-android/blob/b628d7c46c2bb08aadeac11fa8b8d6625a25e14d/core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt#L1449. 

```
val zimFileReader = zimReaderContainer.zimFileReader
      zimFileReader?.let { zimFileReader ->
        mainMenu?.onFileOpened(urlIsValid())
        openArticle(zimFileReader.mainPage)
        safeDispose()
        bookmarkingDisposable = Flowable.combineLatest(
          newBookmarksDao?.bookmarkUrlsForCurrentBook(zimFileReader),
          webUrlsProcessor,
          List<String?>::contains
        )
          .observeOn(AndroidSchedulers.mainThread())
          .subscribe({ isBookmarked: Boolean ->
            this.isBookmarked = isBookmarked
            bottomToolbarBookmark?.setImageResource(
              if (isBookmarked) R.drawable.ic_bookmark_24dp else R.drawable.ic_bookmark_border_24dp
            )
          }, Throwable::printStackTrace)
        updateUrlProcessor()
      } ?: kotlin.run {
        requireActivity().toast(R.string.error_file_invalid, Toast.LENGTH_LONG)
      }
    }
```

>  @danielzgtg reported and demonstrated in the screen cast.

But I really wondered how he opened the zim file without any storage permission from outside the app's specific directory because we need storage permission to read those files which are not created by the app itself.

**Comment by Jaifroid** [comment] 2023-08-18 07:37
> Allow me to be preciser: its not at all a problem with Android, its a problem with the Play Store. Considering that a large majority of our Android users download from the Playstore, we can take the thoughs shortcut, but we should not forget about the reality.

While I agree, my point is that the Play Store has imposed these restrictions for security reasons and the current workaround is to ask users to circumvent the security restrictions for full functionality. I wouldn't be surprised if F-Droid ramps up security soon as well.

We come back to the fact that after the next release I believe the app needs some re-engineering so that it can use the Storage Access Framework with content URIs rather than direct access to files when opening files from shared storage. It can continue to use the current direct access when dealing with its own files in its own scoped storage. A hybrid model like this would provide the ideal solution IMHO, and then you could eliminate the fragmentation (Play Store, F-Droid, direct APK) which is confusing for the average user and off-putting for the security-conscious.

**Comment by Jaifroid** [comment] 2023-08-18 07:41
@MohitMaliFtechiz Thank you again. It's very puzzling...

**Comment by kevinmcmurtrie** [comment] 2023-08-18 08:11
>
> While I agree, my point is that the Play Store has imposed these restrictions for security reasons and the current workaround is to ask users to circumvent the security restrictions for full functionality. I wouldn't be surprised if F-Droid ramps up security soon as well.
>

That won't happen.  F-Droid has preferences to warn for certain types of features but it does not prohibit them.

SAF is _intentionally_ bad to force users and developers into paid Google Cloud storage.  It replaced far better permission models in OEM and open source ROMs.  It's so bad that some phone makers still have a bypass trick - something easy but hidden enough to pass Google's certification.

F-Droid exists for all the developers who were forced out of Google Play but have not yet abandoned Android.  Offline maps, BitTorrent clients, photo editors, developer tools, Termux, file managers, and pretty much anything powerful/interesting has to come from F-Droid.

**Comment by kelson42** [comment] 2023-08-18 09:09
> > Allow me to be preciser: its not at all a problem with Android, its a problem with the Play Store. Considering that a large majority of our Android users download from the Playstore, we can take the thoughs shortcut, but we should not forget about the reality.
> 
> While I agree, my point is that the Play Store has imposed these restrictions for security reasons

It's not always easy to decide, as a software/system designer, what you should allow or forbid to do to your users. You move in a grey zone most of the time and you have to make hard choices. Security related measures belong to this category.

But this is not because you have a security concern that you have to decide in place of the users, in place of the developers. Same: it's not because you have a security concern around a feature that you have to forbid its usage to 99% of the apps and allow only a few exceptions on hidden criterias. 

But I'm not here to discut if Google is right or not, I think that Google is definitly abusing is dominant position in the field of android app store, but that does not change anything.

What is important is that this is specific to the Play Store and not Android.

**Comment by Jaifroid** [comment] 2023-08-18 09:52
I'm no fan of Google, and I'm sure they abuse "security" concerns in order to push their own solutions. But the fact is that the system-wide permissions that MANAGE_EXTERNAL_STORAGE requires are increasingly unacceptable to security-minded users (actually a significant Kiwix userbase), and that's what this issue is about: exploring the alternatives.

To give one example: I used to be very annoyed by the fact that, without my knowledge, the Kiwix Android app would write a 4GB file to the root of my microSD card **_every time I opened it_**.  This was to test whether the card had exFAT support or not. But that behaviour damages flash memory very quickly.

IMHO the default assumption of Kiwix apps should be read-only access to files or folders that users have explicitly picked, with settings and state, bookmarks, etc., stored in its own internal storage to which it always has access. To achieve this will take some re-engineering it seems.

**Comment by kelson42** [comment] 2023-08-27 05:40
If the proposed way does not do the job, no reason to keep this ticket open.

**Closed by kelson42** 2023-08-27 05:40 UTC
Labels: question

**Comment by Jaifroid** [comment] 2023-08-27 06:43
Personally I would say that this issue remains an important one that has not been resolved. The proposed solution is not currently reproducible for unknown reasons, though a video demo of it working was provided. Of course the issue can always be re-opened if OP can provide more info regarding his solution.
