### ISSUE TITLE
Greetings message hindered

### ISSUE THREAD

**Issue by harsh-2711** [kiwix/kiwix-android#516] opened 2018-02-25 11:21 UTC
Feature Request

 What is your environment?

Latest Version available. Tested on One Plus 5T
Android
  
Describe the problem:

 Th greeting message that appears at the bottom of the main page gets hindered by the default navigation bar of the mobile.

Steps to reproduce:

1. More space can be added at the bottom so that the message is clearly visible.

2. Or the location of the message should be shifted elsewhere.
 
Feature Description

To enhance the visibility of greeting message on the main page

Want to work on the issue?

Yes

**Comment by srv-twry** [comment] 2018-02-25 13:36
@harsh-2711 Please attach a screenshot.

**Comment by kelson42** [comment] 2018-02-25 15:27
Duplicate of https://github.com/kiwix/kiwix-android/issues/442 ?

**Comment by MayankChuriwal** [comment] 2018-02-25 16:49
I guess he means to say that the help text gets hindered by the on screen navigation button in phones with 18:9 display right? Phones which do not have physical navigation buttons. @harsh-2711 @kelson42

**Comment by mhutti1** [comment] 2018-02-25 20:46
Duplicate of #442.

**Closed by mhutti1** 2018-02-25 20:46 UTC

**Comment by harsh-2711** [comment] 2018-02-26 10:05
@MayankChuriwal Yes
