### ISSUE TITLE
Problem with translations in Kiwix for Android

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-android#109] opened 2017-04-18 16:39 UTC
(This is a copy of https://github.com/kiwix/kiwix/issues/482, a android bug reported by @l2212 on kiwix repository)

Every time I close and open Kiwix (2.2) again from my phone the language switches back from the one I choose to the system language (in my case, Italian). If I open the list of languages the one who's selected is the correct one, but I have to click on it again to change the language of the app.

**Comment by kelson42** [comment] 2017-11-30 19:04
@asereze I'm not able to reproduce the problem.

**Comment by asereze** [comment] 2017-11-30 19:56
@kelson42 Yes, the UI language. I've set the app in Sardinian, but it switches back to Italian every time.

**Comment by kelson42** [comment] 2017-11-30 20:01
@asereze Could you just installed our last version http://download.kiwix.org/bin/android/2.3/kiwix-2.3_armeabi.apk and try again please?

**Comment by asereze** [comment] 2017-11-30 20:19
@kelson42 I've installed it now, but it seems that nothing changed. If I close and re-open the app the language changes back again.

**Comment by kelson42** [comment] 2017-11-30 20:27
@asereze I'm quite clueless as I can not reproduce the problem. Here is my procedure:
1 - Launch Kiwix
2 - Go to setting, and change to "Sardinian". Verify this is selected properly.
3 - Close all running apps through the dedicated Android button.
4 - Restart the app and go to settings.
5 - the "language" settings is still called "Limba", so "Sardinian" language apply properly.

You confirm this is what you do too?

**Comment by asereze** [comment] 2017-11-30 20:45
@kelson42 Yes, that's what I did. But I get the settings in Italian and the language is set to Italian, even if, if I open that setting, "sardo" (Sardinian) is selected. I have to click on it again to get the right language.

![photo_2017-11-30_21-40-04](https://user-images.githubusercontent.com/11271324/33453760-1ea49ada-d617-11e7-8c55-6ebef5be44b1.jpg)
![photo_2017-11-30_21-40-02](https://user-images.githubusercontent.com/11271324/33453772-27549b94-d617-11e7-89ee-47a8e202d72d.jpg)
![photo_2017-11-30_21-43-48](https://user-images.githubusercontent.com/11271324/33453929-9ba6a406-d617-11e7-8fa2-e17b045f5936.jpg)

**Comment by kelson42** [comment] 2017-11-30 20:49
@asereze Thanks for all the information
@mhutti1 Quite clueless honestly...

**Comment by asereze** [comment] 2017-11-30 21:14
@kelson42 No problem, thank you for your work. Anyway, in case it could be useful, my phone is a Xiaomi Redmi Note 4X with Android 7.1.2 (Lineage OS 14.1) on it.

**Comment by mhutti1** [comment] 2017-11-30 21:39
We have discussed this bug before and its quite a difficult one to crack. I think it might require a rewrite of most of our Locale code. It might be in the scope of GCI/dividable to be in the scope but I am not sure.

**Comment by kelson42** [comment] 2017-11-30 21:44
@mhutti1 OK, you have an other bug we can link to that one?

**Comment by mhutti1** [comment] 2017-11-30 21:44
@kelson42 I think that this was that bug.

**Comment by asereze** [comment] 2018-07-20 16:08
Hello,
I asked to gsantner, a developer that worked for a lot of open source projects for Android, what was his solution for having a working language selection menu, and he told me to check out the code that he wrote here:

https://github.com/gsantner/opoc/blob/12445a8996f142be483b1b05f077e8b73ce553e7/android/java/net/gsantner/opoc/preference/LanguagePreferenceCompat.java

https://github.com/gsantner/opoc/blob/7eb344487f7e49d01566fadeeda5a52279b40f90/android/java/net/gsantner/opoc/util/ContextUtils.java

This works without any problem for more than 10 apps right now (as I can see on my phone when I use Stringlate and Dandelion), could it be used to fix this issue on Kiwix as well?

**Comment by mhutti1** [comment] 2018-07-20 16:45
Hi @asereze I think its possible we have fixed this in version 2.4 which we are rolling out now. If not then I will have a look again. Thanks for the links 👍

**Comment by asereze** [comment] 2018-07-24 13:05
@mhutti1 Ok, I will wait for the new version, then! You are welcome, thank you for your work!

**Comment by macgills** [comment] 2020-01-22 14:40
I can not reproduce this issue
@asereze can you confirm the language selection now works as expected after app restarts?

**Comment by kelson42** [comment] 2020-01-28 12:20
I close this issue, the report is pretty old and I don't have heard anything recently about this problem.

**Closed by kelson42** 2020-01-28 12:20 UTC
Labels: help wanted, i18n
