### ISSUE TITLE
Full screen bug

### ISSUE THREAD

**Issue by MayankChuriwal** [kiwix/kiwix-android#476] opened 2018-02-20 14:32 UTC
**Is it a ?**

- [ ✔️] Bug Report

- [ ] Feature Request

### Step 1: Are you ready to report ?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - [ ✔️] I have test with the last (dev) version of the software?  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2 : What is your environment ?
  * browser / app : app
  * version of the software you use : android studio 3.0.1 
                                                           android 6.0
  * device / operating system : Xiaomi Redmi 3s Prime / android
  
### Step 3: Describe the problem:

After I switch to the full screen mode and pressing the back button the app crashes.

  * What do you obtain? A copy of the error message or a screenshot is always useful

The app crashes totally.

  * When does this occur? 

After switching to the full screen mode.

#### Steps to reproduce:

  1. Go to menu and select Full Screen
  2. Press back option
  3. The app crashes totally
  ...
  
  * What should be the behavior from your point of view? How do you expect the service to work?

Pressing back the app must take you back to the main layout or maybe close the app but start it from main activity.

### Step 4 (optional) : Other Comments:
  * What is the context of this ticket? If not obvious, explain why you need to do this.
 
  * If you have an idea about the technical background of the ticket, please share it.
  
  
#### Feature Description

Please describe the feature you want to add to the project.

**Comment by mhutti1** [comment] 2018-02-20 23:44
Could you please provide a stacktrace.

**Comment by arpank10** [comment] 2018-02-21 10:05
In my case pressing the back button when on fullscreen mode closes the app. But as soon as I try to reopen it, it crashes. Doesn't open unless I clear data. Will provide stack trace as soon as I can.

**Comment by arpank10** [comment] 2018-02-21 10:15
The stacktrace:
`                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{org.kiwix.kiwixmobile/org.kiwix.kiwixmobile.KiwixMobileActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setVisible(boolean)' on a null object reference
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2756)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2825)
                                                                           at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                           at android.os.Looper.loop(Looper.java:203)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6343)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
                                                                        Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setVisible(boolean)' on a null object reference
                                                                           at org.kiwix.kiwixmobile.KiwixMobileActivity.openFullScreen(KiwixMobileActivity.java:892)
                                                                           at org.kiwix.kiwixmobile.KiwixMobileActivity.loadPrefs(KiwixMobileActivity.java:1647)
                                                                           at org.kiwix.kiwixmobile.KiwixMobileActivity.selectTab(KiwixMobileActivity.java:791)
                                                                           at org.kiwix.kiwixmobile.KiwixMobileActivity.newTab(KiwixMobileActivity.java:730)
                                                                           at org.kiwix.kiwixmobile.KiwixMobileActivity.newTab(KiwixMobileActivity.java:724)
                                                                           at org.kiwix.kiwixmobile.KiwixMobileActivity.getCurrentWebView(KiwixMobileActivity.java:803)
                                                                           at org.kiwix.kiwixmobile.KiwixMobileActivity.openArticle(KiwixMobileActivity.java:1341)
                                                                           at org.kiwix.kiwixmobile.KiwixMobileActivity.openMainPage(KiwixMobileActivity.java:1355)
                                                                           at org.kiwix.kiwixmobile.KiwixMobileActivity.openZimFile(KiwixMobileActivity.java:1011)
                                                                           at org.kiwix.kiwixmobile.KiwixMobileActivity.restoreTabStates(KiwixMobileActivity.java:1709)
                                                                           at org.kiwix.kiwixmobile.KiwixMobileActivity.manageExternalLaunchAndRestoringViewState(KiwixMobileActivity.java:1748)
                                                                           at org.kiwix.kiwixmobile.KiwixMobileActivity.onCreate(KiwixMobileActivity.java:454)
                                                                           at android.app.Activity.performCreate(Activity.java:6689)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2709)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2825) 
                                                                           at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                           at android.os.Looper.loop(Looper.java:203) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6343) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945) 
`

**Comment by MayankChuriwal** [comment] 2018-02-21 12:03
I am working on the bug will be soon be making a PR @mhutti1

**Comment by brijeshshah13** [comment] 2018-02-22 12:31
Taking into consideration that the bug has been solved, I'm closing this issue.

**Closed** 2018-02-22 12:31 UTC
Labels: bug, good first issue
