### ISSUE TITLE
Check if the space is really freed correctly avec (custom) app uninstall

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#14] opened 2017-03-02 06:31 UTC
A user complained it's not.

**Comment by mhutti1** [comment] 2017-03-02 12:38
@kelson42 I am not too sure what you mean by this. We don't have hooks too install / uninstall events and expansion files should be cleaned up by Google Play. There's really nothing we can do about this.

**Comment by mhutti1** [comment] 2017-04-18 15:36
I'm closing this isn't an issue with our app and there really is nothing we can do to solve it, its up to Android/Google Play.

**Comment by kelson42** [comment] 2017-04-20 06:30
@mhutti1 In theory you are right, but the problem is what really happens. Can we check that we do not leave things?

**Comment by mhutti1** [comment] 2017-04-20 07:52
@kelson42 No, not really. Its google play services that controls this, you can't really automate downloading an app from the app store (at least not on a service like testdroid). And the point is that even if we could we couldn't fix anything... I just checked on my device everything works entirely as intended, this is not a problem with our app.

**Comment by mhutti1** [comment] 2017-04-20 07:58
If the user can tell us what exactly gets "left behind" then we can confirm this beyond all doubt but until then we just have to assume its entirely a Google Play services issue.

**Comment by kelson42** [comment] 2017-04-20 07:58
@mhutti1 OK. Thank for the explanation, and the stuff we "unpack" on the fly, like the ICU data file? Is that also removed correctly?

**Comment by mhutti1** [comment] 2017-04-20 08:02
@kelson42 We copy the file to our local directory. This should be cleaned up on uninstall but again its not done by us and we have no control over this at all.

**Closed** 2017-04-20 08:11 UTC
Labels: question
