### ISSUE TITLE
Text in Content Manager Screen should be center aligned

### ISSUE THREAD

**Issue by siddharth2010** [kiwix/kiwix-android#393] opened 2018-02-15 10:23 UTC
The text in the center of the screen should also be center aligned

![screenshot_20180215-155059](https://user-images.githubusercontent.com/32238400/36251672-e1336f46-1239-11e8-8b89-2b58cb40b690.png)

**Comment by kelson42** [comment] 2018-02-15 10:25
@siddharth2010 Thank you for your bug report but this is a duplicate of #390

**Closed by kelson42** 2018-02-15 10:25 UTC
Labels: duplicate
