### ISSUE TITLE
UI fails to AutoConnect in the CI

### ISSUE THREAD

**Issue by gouri-panda** [kiwix/kiwix-android#2958] opened 2022-08-17 07:59 UTC
<del> Using 1.4.0 libraries and </del>  In espresso 3.4.0, I occasionally run into the following RuntimeException with a simple call to getInstance(InstrumentationRegistry.getInstrumentation())
>org.kiwix.kiwixmobile.intro.IntroFragmentTest > viewIsSwipeableAndNavigatesToMain[test(AVD) - 5.0.2] FAILED 
	java.lang.RuntimeException: Error while connecting UiAutomation
	at android.app.UiAutomation.connect(UiAutomation.java:210)

No tests particularly at this point. It fails sometimes on CI emulation at the start in both API 21 & API 30.
**More Context:**
https://issuetracker.google.com/issues/233914320

**Comment by kelson42** [comment] 2022-08-30 03:54
@gouri-panda What is "1.4.0 libraries", which library you talk about exactly?

**Comment by gouri-panda** [comment] 2022-08-30 10:11
@kelson42 Sorry! That was a typo! I have updated the description.

**Comment by gouri-panda** [comment] 2022-08-31 21:03
@kelson42 @MohitMaliFtechiz In the meanwhile we should try not use this method `getInstance(InstrumentationRegistry.getInstrumentation())`.That's the only solution i can think of it now.

**Comment by kelson42** [comment] 2022-09-01 04:01
@gouri-panda What is the purpose of this function? Could we avoid to use it at all?

**Comment by gouri-panda** [comment] 2022-09-01 14:50
@kelson42 It gets the `UiDevice` instance by `InstrumentationRegistry`. 
>Could we avoid to use it at all?

We should try an alternative way to find the `UIDevice` instance for the moment.

**Comment by gouri-panda** [comment] 2022-09-01 15:43
@kelson42 @MohitMaliFtechiz I'm closing this issue unless we see this problem in our existing code.

**Comment by kelson42** [comment] 2022-09-01 17:14
@gouri-panda problems should be trackef somrwhere in the repo.... even if root cause os outside

**Comment by kelson42** [comment] 2022-09-03 09:05
@gouri-panda I think to better understand this ticket, we shoudl update it with information allowing to answer the following questions:
* Which test fails exactly? Is that always the same?
* Does it always fail at the same place?
* How often does it fails?
* Does it fail only with emulator? Only with emulator in Github? 
* Does it fail always with the same API level (seems to always be a problem with API 21)?
* Since when do we have the problem? What what the trigger?

**Comment by kelson42** [comment] 2022-09-09 04:45
@gouri-panda Any update/answer in view?

**Comment by gouri-panda** [comment] 2022-09-09 07:29
@kelson42 Not yet

**Comment by gouri-panda** [comment] 2022-09-13 11:06
>Which test fails exactly? Is that always the same?

There are no tests in particular. It doesn't fail in same test case.
>Does it always fail at the same place?How often does it fails?

Some times
>Does it fail only with emulator? Only with emulator in Github?

Only with the emulator in Github
>Does it fail always with the same API level (seems to always be a problem with API 21)?

No
>Since when do we have the problem? What what the trigger?

I don't know when it was started

**Comment by kelson42** [comment] 2022-12-30 08:06
@MohitMaliFtechiz Would be great of you could fix this CI instability

**Comment by MohitMaliFtechiz** [comment] 2023-01-11 13:15
hi @kelson42 ,
This should be automatically fixed in https://github.com/kiwix/kiwix-android/pull/3203.

**Closed** 2023-01-11 13:19 UTC
Labels: bug
