### ISSUE TITLE
Kiwix Display Problem

### ISSUE THREAD

**Issue by RickAust** [kiwix/kiwix-android#1539] opened 2019-10-01 02:59 UTC
Hi.
I don't know if anyone can help me but most of my phone's Kiwix pages are no longer displaying accurately. 
I have Wikivoyage on my SD card, which seems to be working fine. However when I go to use Wikipedia (split into 4 files on my SD card), variations of the attached page appear (once I leave the homepage). The particular page shown below is what appears when I use the "Wikimedia Foundation" link. Similar pages are revealed when I use other links. The homepage itself appears normal.

This is the first time I've ever experienced this problem, having used the Kiwix app for many years. The specific zim files have also been used for years, again without problems.
![Screenshot_2019-10-01-11-45-47-645_org kiwix kiwixmobile](https://user-images.githubusercontent.com/56009454/65930915-e9a30a80-e44a-11e9-8796-3867a51d0839.png)
The files work normally when I use them on my laptop.
Note that I have reinstalled Kiwix and the zim files, without resolution of the issues.
Any ideas? 🙂
Rick (Australia)
PS This is my first entry on your forum. I hope I've presented things appropriately.

**Environment**
- Version of Kiwix Android : 3.0.3
- Device : Redmi 4X
- MIUI version : 10.3.1
- Android version: 7.1.2

**Comment by kelson42** [comment] 2019-10-01 06:22
@RickAust What is the exact ZIM file name and the article name impacted by this problem? Could you please try without splitting the ZIM file?

**Comment by RickAust** [comment] 2019-10-01 07:18
Hi Kelson42.
The file names are: Wikipedia (nopic 2012-01).zimaa, Wikipedia (nopic 2012-01).zimab, Wikipedia (nopic 2012-01).zimac, & Wikipedia (nopic 2012-01).zimad
The article names are numerous. I think just about every link is affected. The screenshot was Wikimedia Foundation but also happens with Reference Work, Volunteers, Larry Sanger etc. These are just the first few I tried.
Re splitting, I think I only split the original file because of the fat32 - NTFS issue. It has worked beautifully for several years up until about two days ago. I guess I could try and merge them somehow but it's a little tricky to download the whole file again (I'm really restricted data-wise).
Thanks so much for getting back to me so quickly. 🙂

**Comment by kelson42** [comment] 2019-10-01 07:19
@macgills Could you please have a look to that one? I don't think we still provide that file online, but it clearly looks like a regression... and we had similar tickets fixed relatively recently.

**Comment by RickAust** [comment] 2019-10-01 07:22
Do you mean to try just one non-split zim? Just clarifying.

**Comment by macgills** [comment] 2019-10-01 09:06
@RickAust the kiwix app no longer supports the splitting of zim files itself though it should still be able to read them.
If it is possible for you to download the entire file I would recommend it (though it sounds like it isn't) as that will ensure the best behaviour from Kiwix. 
@kelson42 from what resource can I get these split zim files for repro-ing this bug?

**Comment by kelson42** [comment] 2019-10-01 09:12
@macgills Looks like the original file has been renamed and even if I would have it, I'm pretty sure we don't distribute anymore.
@RickAust Without the file, no reproduction case... and not obvious solution to that problem appears for now. If you can not upload the file or download a new version of that file, it looks like it will be complicated for us to fix this problem. As a workaround you could downgrade your Kiwix version to an older version from https://download.kiwix.org/release/kiwix-android/

**Comment by RickAust** [comment] 2019-10-01 10:16
I think I understand all the advice. Thanks everyone for all the very
prompt feedback. Will see what I can manage at my end...

**Comment by RickAust** [comment] 2019-10-01 10:26
Re your gratefully received advice...

I think I used FFSJ to split the original downloaded zim file. It was
several years ago however, so the memory is not so fresh in my mind.
http://www.fastfilejoiner.com/
https://wiki.kiwix.org/wiki/FAQ

I might be a little stuck with the split zims as I need to utilise a
microSD card for zim storage on my phone. I seem to recall the card
wouldn't accept a >4GB file. Will give it another go.

Many thanks once again. 🙂

**Comment by RickAust** [comment] 2019-10-01 10:32
And just to make clear. I didn't originally download the split zim files. I
downloaded a single unsplit zim file (2012 no-pic English-language
Wikipedia) from the main Kiwix.org website, then split it myself on my
laptop.
Thanks to all of you.

**Comment by kelson42** [comment] 2019-10-01 11:00
@RickAust To be a bit more clear, I suspect the problem does not come from the split ZIM file (even if this might be something to check). I mostly suspect that this quite old ZIM file had not proper mime-types associated with the article and that we have now a libzim which is a bit more strict than it was. As a consequence the reader just does not recognised that it is HTML content anymore.

**Comment by kelson42** [comment] 2019-10-01 11:01
@RickAust I'll close the ticket as there is nothing more we can really do for now on our side. Please open a new ticket if one of the solutions/workarounds provided still fails or just add a small comment if you finally achieved to get back your beloved Wikipedia Encyclopedia :)

**Comment by RickAust** [comment] 2019-10-01 11:06
OK. I'm a little slow with some of the technical concepts but you've
explained things really well. Time to update my zim files (for a variety of
reasons!)...

**Comment by RickAust** [comment] 2019-10-01 11:06
Thanks again 🙂🙂🙂

**Comment by macgills** [comment] 2019-10-01 12:06
Or if you can upload the zimaa-zimXX to someplace I can download them (google drive/etc) then I can try to reproduce the error if that is a viable path for you

**Comment by RickAust** [comment] 2019-10-01 12:10
Hi Sean.
Thanks but I'll try a newer zim version first and get back to you guys if
I'm still stuck.
This is way overdue anyhow... 🙂

**Comment by RickAust** [comment] 2019-12-30 01:48
I've shared an item with you:

ZIM Files
https://drive.google.com/drive/folders/1uFaqqR1CF-rlskSTwKIZAIzLuh0FGBqu?usp=sharing&ts=5e09576e

It's not an attachment -- it's stored online. To open this item, just click  
the link above.

Hi Sean.  Not sure if you remember me but I emailed you two or three months  
back re some problems I was having reading some old Wikipedia zims on my  
Android phone. I've since accessed Wikipedia 2018.9.10. Kiwix is now  
working but is really, really slow. I assume this is because of the  
increased file size (single 34.8GB file vs. combined total of 9.7GB). Kiwix  
isn't slow when I'm reading my Wikivoyage zim, which is <1GB.  Last time we  
communicated, you said you might be able to further assess what's happening  
if I uploaded the files to the cloud. Have finally managed to do this.  
Would this analysis still be possible? I guess I just long for the days  
(only a few months back) when Wikipedia access was instant and flawless.  
Seasons Greetings, Erik (Australia). P.S. I also tried an unsplit version  
of the 9.7GB Wikipedia. Sadly, there were just the same problems as the  
split version.

**Comment by macgills** [comment] 2020-01-06 09:37
I'll run an investigation when the time permits, hopefully in the coming days

**Comment by RickAust** [comment] 2020-01-06 23:27
Many thanks Sean :-)

**Comment by macgills** [comment] 2020-01-07 10:36
No problem, stay safe and not on fire

**Comment by macgills** [comment] 2020-01-07 13:25
@kelson42 this is a strange one, the old zim file is returning improper redirect urls.
The app tries to read
`content://org.kiwix.kiwixmobile.zim.base/A/Internet%20encyclopedia.html`
and JniKiwixReader.checkUrl() returns the non encoded
`content://org.kiwix.kiwixmobile.zim.base/A/Internet encyclopedia.html`

and because these 2 urls are different we report that we should do a redirect and then use the second incorrect url.

**Comment by kelson42** [comment] 2020-01-07 13:40
@macgills Then the ZIM was wrong. Sorry for the hassle. I will close this ticket as newer ZIM files should not have this problem.

**Closed by kelson42** 2020-01-07 13:40 UTC
Labels: bug

**Comment by macgills** [comment] 2020-01-07 13:51
@RickAust the last app version that did not support redirects was [2.5.1](https://github.com/kiwix/kiwix-android/releases/tag/2.5.1). If you were content with the previous behaviour of your application then I would say this is the version you should install.

@kelson42 The bigger problem is the performance issue rick is experiencing. We could open some tickets to try and improve performance? Our ANR rate tends to be very good so it would require some detective work to identify bottlenecks.
I was trying to see if I could get any slowdown on wikipedia 10.3GB 2019-09-16 but to no avail. The landing page for it is a broken redirect though

**Comment by kelson42** [comment] 2020-01-07 14:09
@macgills @RickAust The problem here is that we have a ticket with at least two different topics which make it difficult to handle. I would recommend to open an other one regarding this other problem with last ZIM and last version of Android. The only thing which could be a bit slow, is the suggestion system, see #1676 (was assuming a bit quickly we had a duplicate here).

**Comment by RickAust** [comment] 2020-01-21 00:13
Thank you everyone for their work on this. Sorry about the late reply -
have been away for a while.
Cheers,
Erik (Australia)
