### ISSUE TITLE
Can't open zim from external download

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1447] opened 2019-09-06 14:14 UTC
**Describe the bug**
When you click open on a download of a zim it says "error can't open zim file"

**Expected behavior**
The zim file should open

**Steps to reproduce the behavior:**
1. click on [this](https://download.kiwix.org/zim/stack_exchange/dsp.stackexchange.com_en_all_2019-01.zim ) in chrome
2. click "open" after download completes
3. See error

**Environment**
- Version of Kiwix Android : develop/3.0
- Device : Nexus 5X
- OS version : 8.1.0

**Logs**
```
2019-09-06 15:02:36.192 22182-22397/org.kiwix.kiwixmobile E/kiwix: Exception reading article null from zim file
    java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] org.kiwix.kiwixlib.JNIKiwixReader.getContent(org.kiwix.kiwixlib.JNIKiwixString, org.kiwix.kiwixlib.JNIKiwixString, org.kiwix.kiwixlib.JNIKiwixString, org.kiwix.kiwixlib.JNIKiwixInt)' on a null object reference
        at org.kiwix.kiwixmobile.data.ZimContentProvider$TransferThread.run(ZimContentProvider.java:486)
```

**Comment by kelson42** [comment] 2019-09-09 02:01
@macgills Sounds to be a duplicate of #1312 to me

**Comment by macgills** [comment] 2019-09-09 08:22
No, very different. This launches the app and then fails to open it

**Comment by macgills** [comment] 2019-10-25 14:33
If we support inputStreams/FileDescriptors #56 this gets a hell of a lot easier. The underlying issue is that we get returned "Content Uris" and mapping them to "File Uris" is not easy. We have existing code that makes an attempt but every new FileProvider (chrome/firefox/etc) needs custom dedicated code from what I can surmise.

As a short term solution: the content uri is something like `content:///blah/blah.Provider/zimFileName.zim` so we could run a fileScan, filter based on the file name and open that, will take slightly longer than just opening a file but feasible. It is fighting the framework a bit.

**Comment by kelson42** [comment] 2019-10-27 10:07
@macgills Moving to 3.3

**Comment by kelson42** [comment] 2020-05-01 13:32
@macgills Just to confirm I understand properly. Clicking on a browser download notification opens kiwix properly bus does not share the ZIM file path, but instead a cryptic content URI which does not allow to know where is the ZIM file it represents. If you confirm, I wonder for what is this URI usefull and how you could get a filedescriptor of it?

**Comment by macgills** [comment] 2020-05-01 14:12
You can create an InputStream from it or get a AssetFileDescriptor but we can't get a filename as `content` uris might not even be a local file.  [ContentResolver](https://developer.android.com/reference/android/content/ContentResolver) is what we need to use to get access to the underlying data but kiwixlib would have to support the data in this format

**Comment by macgills** [comment] 2020-05-01 14:31
[Here](https://stackoverflow.com/a/20559418/12225251) is an example of a dirty hack that we can in no way guarantee will work consistently. It is pretty hideous.

**Comment by kelson42** [comment] 2020-05-01 15:05
@macgills I think we can affort a proper fix here :)

**Comment by macgills** [comment] 2020-07-08 10:29
As this is pending a potentially difficult kiwixlib update I'll move this out of the milestone

**Comment by s-ayush2903** [comment] 2020-10-14 12:40
@macgills Is this issue specific to a particular zim file only, as I'm now unable to reproduce it, when I download a zim externally and click from browser to open it, it leaves on the libraryFragment(to be specific the screen where downloaded books are present) of kiwix-android but does not open the file in the reader anyways.

PS: The Url of zim given in the issue description no longer exists and tried this with [this zim](https://download.kiwix.org/zim/stack_exchange/conlang.stackexchange.com_en_all_2020-07.zim).

**Comment by macgills** [comment] 2020-10-15 08:21
it should open in the reader so the issue still exists. This ticket is awaiting an update in kiwixlib that I believe has been prioritised as it relates to a few app features

**Comment by kelson42** [comment] 2020-11-11 09:13
Here the libkiwix related feature request: https://github.com/kiwix/kiwix-lib/issues/423

**Comment by virtadpt** [comment] 2021-02-07 04:36
Hi, has there been any progress on this bug?  So far it's been a total dealbreaker for me.  I'm in a bandwidth constrained area so I have another machine elsewhere download .zim files for me, and when I'm physically near it I copy them onto a microSD card to use on my phone or tablet (both Samsung, phone is a SM-G965U, tablet is a SM-T290, both are running v3.4.3 build 623403 from the Google Play store).  Doesn't even show up on the Library screen.

**Comment by kelson42** [comment] 2021-02-07 04:44
@virtadpt Can you please open an other ticket?

**Comment by virtadpt** [comment] 2021-02-07 22:24
Will-do.  Sorry 'bout that, I've not been sleeping a whole lot lately.

**Comment by virtadpt** [comment] 2021-02-08 01:13
Done - #2592.

**Comment by kelson42** [comment] 2022-07-02 06:38
@MohitMaliFtechiz Once we benefit of the new libkiwix binding, please have a look to this ticket.

**Comment by kelson42** [comment] 2023-02-16 16:34
@MohitMaliFtechiz Now that we use libkiwix10, this should actually been possible to fixt this ticket. Can you do that?

**Comment by MohitMaliFtechiz** [comment] 2023-02-17 09:55
@kelson42 , i have tested it , this is uri scheme issue. we are using a extension function ```toFile()``` of ```Uri class``` it needs scheme of uri as file.
https://github.com/kiwix/kiwix-android/blob/ec0c4a1fa45146c9f016359945f3cf6640137b89/app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt#L307
 but when we are opening zim file from chrome it is returing ```content://media/external/downloads/1000020683``` this uri. it's scheme is not the file type that's(it's scheme is ```content``` type) why this error message showing.

**Comment by kelson42** [comment] 2023-02-17 10:00
@MohitMaliDeveloper What abput the pr already open?

**Comment by MohitMaliFtechiz** [comment] 2023-02-17 12:15
@kelson42 , 
* since it is very old PR and we changed many things in our project (i think this code is outdated according to new android version let me test on newer version of android if this code is working or not).
* i have checked the PR,  i found there we are using ```FileDescriptor``` for opening files(and changes according the FileDescriptor) and this code is not directly working in android 11 and above. we need storage access framework for access files which is not our app specific(which downloaded outside the application). for that we are using a file picker in our app.
* we have a method for getting files from path by uri which is working perfectly (it will return file path by provided uri for every scheme type)
 https://github.com/kiwix/kiwix-android/blob/ec0c4a1fa45146c9f016359945f3cf6640137b89/core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt#L107

so should we use this existing method?(it need less code to fix this problem) @gouri-panda what do you think ?

**Comment by kelson42** [comment] 2023-02-17 13:02
@MohitMaliFtechiz 
* i don't want any extra file picker onviously
* does that mean previous analysis of the problem and solution are wrong? Deprecated?
* does that mean you don't need anymore access via filehandler developed specificaly for this bug in libkiwix10?

**Comment by MohitMaliFtechiz** [comment] 2023-02-17 13:17
@kelson42 ,

> does that mean previous analysis of the problem and solution are wrong? Deprecated?

* Actually not, previous analysis is true but on latest android versions this solution is not working. i have tested it on android 12 and it failed to open ZIM file from chrome. i'm attaching a video

> does that mean you don't need anymore access via filehandler developed specificaly for this bug in libkiwix10?

* if we will use this method  then we don't need the file handler specifically for opening ZIM files from storage(library method works perfectly below android 11).
 https://github.com/kiwix/kiwix-android/blob/ec0c4a1fa45146c9f016359945f3cf6640137b89/core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt#L107


https://user-images.githubusercontent.com/34593983/219661392-5ddd342e-e440-4bbb-8951-b49a2a5bbe0a.mp4

**Comment by MohitMaliFtechiz** [comment] 2023-02-20 10:24
@kelson42 ,

I have debug it, why it's failed to open externally download ZIM file. I have found it's Uri issue chrome downloaded Uri is ```content://media/external/downloads/1000020681``` and JNI failed to open this Uri so i have use ```getLocalFilePathByUri``` method of ```FileUtils``` class to get actual path of this uri (which i have propose to use in my above comment) after converting this path JNI able to read this ZIM file(in this scenario i have use ```MANAGE_EXTERNAL_PERMISSION``` without this permission it's throwing access denied error because we can not access files without this permission from whole storage). i'm attaching a video. 


https://user-images.githubusercontent.com/34593983/220078469-5abf8cc5-fc1f-4e0a-a686-b9b53eafd8fa.mp4

**Comment by kelson42** [comment] 2023-02-23 11:43
@MohitMaliFtechiz To make a decision we need pro/con for each part of the alternative. Here I don't have these info!

**Comment by gouri-panda** [comment] 2023-03-03 14:05
@MohitMaliFtechiz I may have an idea. Maybe we recognize the intent of which file it is. If it is a zim file we can modify the file scheme to open in our app. What do you think?

**Comment by kelson42** [comment] 2023-03-03 14:23
> @MohitMaliFtechiz I may have an idea. Maybe we recognize the intent of which file it is. If it is a zim file we can modify the file scheme to open in our app. What do you think?

Can we have please a clear pro/con for any proposed solution? I really need this to move forward this ticket.

**Comment by MohitMaliFtechiz** [comment] 2023-03-09 09:38
# FileDescriptor

**Pros:**
* A FileDescriptor is a low-level representation of an open file, and it provides more direct access to the file's underlying data. This can be useful for certain types of file operations, such as reading or writing large files.
* Using a FileDescriptor can be more efficient than using the normal method of opening a file, especially if you need to perform multiple operations on the same file (For example, you may need to read data from a file, process it, and then write the results back to the same file.).

**Cons:**
* A FileDescriptor can only be used with certain types of file operations, and it may not be suitable for all use cases.
**Like:-**
      **Text file operations:** FileDescriptor is a low-level abstraction of file operations and may not be ideal for text file operations 
        where you need to read or write specific data.
      **Filesystem monitoring:** If you need to monitor a directory for file system changes, such as file creation or deletion, you 
        may not be able to do this using a FileDescriptor.
      **Network file operations:** FileDescriptor is not suitable for network file operations, such as downloading files from a remote 
        server over HTTP or FTP.

# getLocalFilePathByUri

**Pros.**

* The normal method of opening a file from a path is easy to use and can be used for most file operations(read,write,delete).
* This method provides a higher-level abstraction of file operations.

**Cons.**
* This method may be less efficient than using a FileDescriptor, especially if you need to perform multiple operations on the same file

**Comment by kelson42** [comment] 2023-03-11 10:07
@mhutti1 Your answer is not helpful. I know what is a filedescriptor, and if I don't know i can read wikipedia. What i need are pro and cons in the context of kiwix-android:
* how much implementation effort is needed?
* can we still acess the xapian indexes?
* can we still get filehandlers for the direct reading of videos?
* what is the impact on memory? On execution time?
* any kind of user visible impact? Differences?

**Comment by MohitMaliFtechiz** [comment] 2023-04-11 12:32
@kelson42 , Sorry my previous answer was not helpful , I have re-accessed all of your points and here is my finding.

> how much implementation effort is needed?

It needs lots of refactoring as we will now load the Zim file with file descriptor, but we are already doing the refactoring in https://github.com/kiwix/kiwix-android/pull/2548 so it takes less time, but it needs to be tested properly.

> can we still access the xapian indexes?

I have tested and the search is working like earlier.

> can we still get filehandlers for the direct reading of videos?

I have tested with https://github.com/kiwix/kiwix-android/pull/2548 and we are able to watch videos with this PR.

> what is the impact on memory? On execution time?

As per our application scenario we are opening file from ```filePath``` in kiwixlib, so execution time depends on kiwixlib. As it takes some time for reading and resolving the Zim file from filePath , i believe it will do the same for file descriptor. On other hand if we are seeing this in android side then file descriptor execution time is less as compare to loading file by there filePath. Because file descriptor provides a more direct interface to the operating system's file system.



> any kind of user visible impact? Differences?

While testing https://github.com/kiwix/kiwix-android/pull/2548 PR, I have not seeing any visible difference, but this PR have some broken changes (we have to fix them) which i believe we had not done that time. Like while we are opening the bookmark then it crashes.

> what about older android versions?

In older android version we can use file descriptor. But as lower device comes with limited system resources, so we need to carefully use file descriptors efficiently in lower devices. 


Please let me know if my answer make sense to you.

**Comment by kelson42** [comment] 2023-11-04 06:53
@MohitMaliFtechiz Does #3518 or #3516 fixes this ticket? Otherwise what is left to do? Could we do it now?

**Comment by kelson42** [comment] 2023-11-07 20:18
@MohitMaliFtechiz ???

**Comment by MohitMaliFtechiz** [comment] 2023-11-08 06:59
> @MohitMaliFtechiz Does https://github.com/kiwix/kiwix-android/pull/3518 or https://github.com/kiwix/kiwix-android/pull/3516 fixes this ticket? Otherwise, what is left to do? Could we do it now?

@kelson42, no these PRs can not fix this problem, it is a different problem as you can see here https://github.com/kiwix/kiwix-android/issues/1447#issuecomment-1434401214.
1) https://github.com/kiwix/kiwix-android/pull/3518 => This is for the `File picker` issue in Android 13.
2) https://github.com/kiwix/kiwix-android/pull/3516  => This does not directly fix the problem as we can not get the `fd` from uri. 
 
Here I have two solutions:
1) Check the incoming data scheme here if it is the `content` type.
https://github.com/kiwix/kiwix-android/blob/ec0c4a1fa45146c9f016359945f3cf6640137b89/app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt#L307

then get the actual path from it via the `getLocalFilePathByUri` method and load this file via libzim.

https://github.com/kiwix/kiwix-android/blob/ec0c4a1fa45146c9f016359945f3cf6640137b89/core/src/main/java/org/kiwix/kiwixmobile/core/utils/files/FileUtils.kt#L107

2) We can load it by `fd` for this we need to get the `inputStream` of incoming uri with `ContentResolver` then get the `fd` from it(as @macgills mentioned https://github.com/kiwix/kiwix-android/issues/1447#issuecomment-622404276), and load it in libzim like we are doing in #3516.

**Comment by kelson42** [comment] 2023-11-08 07:12
From the historical point of view only solution #2 seems to be able to work.... so I would go for that one.

**Comment by MohitMaliFtechiz** [comment] 2023-11-08 07:32
> From the historical point of view only solution https://github.com/kiwix/kiwix-android/issues/2 seems to be able to work.... so I would go for that one.

Okay, i am placing a fix for it.

**Comment by MohitMaliFtechiz** [comment] 2023-11-08 14:40
@kelson42 I have placed a fix for it in https://github.com/kiwix/kiwix-android/pull/3527

**Closed** 2023-11-16 12:58 UTC
Labels: bug
