### ISSUE TITLE
Convert LibraryViewCallback.java to Kotlin

### ISSUE THREAD

**Issue by simonnepinto** [kiwix/kiwix-android#2620] opened 2021-03-28 08:00 UTC
#### What changes you have made:

Converted Java file to Kotlin

**Comment by s-ayush2903** [comment] 2021-04-01 19:05
The issue won't be closed until we have the aforementioned file written in kotlin, in `kiwix/develop`. Reopening.

**Comment by s-ayush2903** [comment] 2021-04-01 19:08
@simonnepinto Feel free to ask via commenting here for getting this ticket assigned to you. Any other person(preferably, the one who hasn't made any good contributions to kiwix) interested in pushing a fix can also comment here to work on the issue.

**Comment by simonnepinto** [comment] 2021-04-02 02:44
The static analysis keeps failing every time. Can you guide me on what does the static analysis check in this project?

**Comment by s-ayush2903** [comment] 2021-04-02 07:53
StaticAnalysis is the lint check that runs on each and every PR and commit that you make locally(in your pc). Lint means the code formatting(e.g., indentation, max chars in a line) of the file, if written code doesn't match with the ideals we have defined, then staticAnalysis fails. You should be able to fix it via auto-formatting the code in studio using the keybinding `Ctrl + Alt + L`, and this should solve the issue. 

And by the report you attached here, on giving a look to the file which is mentioned in the report, I can see that there isn't a new line where copyright license ends and the package name begins, adding a new line will fix this problem; but there seem to be more issues to me related to formatting in the newly added kotlin file in your PR, use auto-formatting and it'll be fixed.

Also, you shouldn't worry much if checks fail on your PR, it is totally fine, you needn't close the PR, this is how you'll learn. On failing checks your aim should be to correctly assess the failing report(s), find the problem and then fix it, obviously you can use internet for the errors which you don't know about.

**Comment by kelson42** [comment] 2021-05-02 09:33
What is the status here?

**Comment by anamansari062** [comment] 2021-11-29 09:56
If it is not resolved yet, I would like to work on it.

**Comment by gouri-panda** [comment] 2021-11-29 10:00
@anamansari062  You are assigned!

**Comment by tom635** [comment] 2021-12-13 09:42
@gouri-panda I would like to resolve this issue #2758 . and confirmed by running the code on my local system.

**Comment by cdhiraj40** [comment] 2021-12-13 12:30
> @gouri-panda I would like to resolve this issue #2758 and confirm by running the code on my local system.

hey @tom635, as you can see from assignees @anamansari062 has already been assigned and she has made a PR too,
i would suggest you to find an issue which is stale(no activity in some time) :)

**Comment by tom635** [comment] 2021-12-13 12:40
@cdhiraj40 ok Sir .And  one more doubt the interface LibraryViewCallback is still in java why so?

**Comment by cdhiraj40** [comment] 2021-12-13 12:43
> @cdhiraj40 ok Sir 

im not a sir, just another contributor :)

> one more doubt the interface LibI'mryViewCallback is still in java why so?

because PR is still under review and it has not been merged. once merged you will be able to see the kotlin file.

**Closed** 2022-07-26 16:07 UTC
Labels: enhancement
