### ISSUE TITLE
Titles in the book index are not completely visible

### ISSUE THREAD

**Issue by yashk2000** [kiwix/kiwix-android#1903] opened 2020-03-16 10:59 UTC
**Describe the bug**
The titles in the book index are not completely visible when they are too long.

**Expected behavior**
The titles should be completely visible. The entire index should be horizontally scrollable in order for the text views to be completely visible. Or the individual text views can also be made scrollable.  

**Steps to reproduce the behavior:**
1.Open the book index.
2. If the name of the component is too long, it won't be completely visible. 

**Screenshots**

![photo_2020-03-16_16-29-02](https://user-images.githubusercontent.com/41234408/76749885-44cf7c00-67a3-11ea-89c2-5fe83f6e7208.jpg)

**Environment**
- Version of Kiwix Android : 3.2.1
- Device : Redmi K20
- OS version : Android 10

**Addition Context**
I would like to work on this issue.

**Comment by kelson42** [comment] 2020-03-16 17:08
@abdulwd @macgills @mhutti1 I'm not sure we have a bug here honestly.... Not convince horizontal scrollable view would be really user friendly...

**Comment by abdulwd** [comment] 2020-03-16 19:46
I would say it's not a bug.

**Comment by yashk2000** [comment] 2020-03-17 06:44
It's not a bug, the UI was designed that way. 

But shouldn't it be improved so that the user can properly see the titles? Maybe make those views fit in multiple lines so that the titles are completely visible.

**Comment by abdulwd** [comment] 2020-03-17 09:22
There are things on which we need to compromise because of screen size. The user can click on the title to go to that heading.

**Comment by yashk2000** [comment] 2020-03-17 09:46
Yes, screen size is the reason the text gets cut out. 

Should I close this issue then?

**Comment by abdulwd** [comment] 2020-03-17 10:11
@kelson42 Can we close this?

**Closed** 2020-03-17 10:12 UTC
Labels: UI, enhancement, question
