### ISSUE TITLE
Largefiletest.txt procedure causes crash

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#1662] opened 2019-12-19 08:58 UTC
User feedback via email (feel free to close as I'm not sure it's entirely relevant):
"I use your Kiwix App 2.4 and everything works fine,but after the Upgrade 2.51 there's a large Problem with this App.
Everytime i open the App and want to choose f.e.a new zim File ,the app generates a largeFiletest.txt on my SDCard android/data/kiwixmobile/files ...sometimes the app initiates a Reboot of my Smartphone Xiaomi Redmi Note 4 Snapdragon Non Root Miui 10 stable Developer Rom.The Problem is that's happens everytime if i use the get content Button and the largefiletest.txt procedure happens also in the newest version 3.1.1 and furthermore i think the  app has a background request loop in the get content section.
The battery drain in 3.1 is much higher than in 2.4."

**Comment by kelson42** [comment] 2019-12-19 09:02
@Popolechien We are not really interested in any bug report now which is not on 3.1. For 3.1, I'm not sure reading the bug report about what is the problem?

**Comment by macgills** [comment] 2019-12-19 09:23
largefiletest.txt is what we use to assess if the storage is capable of handling files above 4GB.
On phones using some sd cards the entire file must be written which can be quite costly. There are other tickets about this but we can use this as an excuse to try a new supplemental system for detecting filesystems

**Comment by macgills** [comment] 2019-12-19 09:27
We could also introduce a cache. I didn't bother originally because I had no idea the operation (which always executed in under a second for me) would take upwards of 1min

**Comment by kelson42** [comment] 2019-12-19 09:32
I'll close this ticket as the system works as intended.

**Closed by kelson42** 2019-12-19 09:32 UTC
Labels: bug, question
