### ISSUE TITLE
Bookmarks show duplicates

### ISSUE THREAD

**Issue by A3148475824** [kiwix/kiwix-android#3913] opened 2024-06-29 03:46 UTC
Version 3.11.1 unexpectedly appeared, two identical bookmarks, NVIDIA, I searched for NVIDIA and added a bookmark, I searched for Intel, and then saw information about semiconductors in Intel's interface, clicked in and saw a well-known chip manufacturer, then I checked a few companies, saw NVIDIA and found that it was not added to the bookmark, I clicked to add it again! Then I suddenly remembered that I had already added it! Then I went to the bookmark search and found that there were really two identical bookmarks, and the content was the same, I don't understand why

![Screenshot_20240629-112531_Kiwix](https://github.com/kiwix/kiwix-android/assets/70214970/6f320c64-cdeb-4978-9e14-73f73406ee5b)

**Comment by A3148475824** [comment] 2024-06-29 03:53
I have a guess. Remember #3890? The code in the file manager is always linked together! It should be fixed, but I don't know why multiple bookmarks are linked together! I think this is the problem! I went to /storage/emulated/0/Android/data/org.kiwix.kiwixmobile/files/Bookmarks and found that there was only one Nvidia bookmark, so I don't understand why there are two bookmarks in the bookmark manager.

**Comment by MohitMaliFtechiz** [comment] 2024-07-02 07:01
Duplicate of https://github.com/kiwix/kiwix-android/issues/3890. See https://github.com/kiwix/kiwix-android/issues/3890#issuecomment-2202106902.

**Closed by MohitMaliFtechiz** 2024-07-02 07:01 UTC
Labels: bug
