### ISSUE TITLE
The last zim file card in the starting library view is cut off when the list requires scrolling. 

### ISSUE THREAD

**Issue by Frans-Lukas** [kiwix/kiwix-android#1959] opened 2020-03-25 10:25 UTC
**Describe the bug**

When more zim files are downloaded than can be shown in one screen height, the last card is cut off. This looks out of place and some information is missing (content tags).  

**Expected behavior**

The last item should be displayed fully just like every other item in the zim file browser list. 

**Steps to reproduce the behavior:**
1. Download enough zim files to enable scrolling in the start library view. 
2. Scroll to the bottom of the start zim file explorer.
3. Notice that the content tags are missing from the last zim file. 
4. It is possible this only works if you have books from a single language as I can't reproduce this from my virtual phone with files from multiple languages.

**Screenshots**

![video-1585131786](https://user-images.githubusercontent.com/22193232/77526655-395b0f80-6e8b-11ea-95dd-518d01ea56d9.gif)

**Environment**
- Version of Kiwix Android : 3.2.1
- Device : Oneplus 5
- OS version : 9.0.11

I'd like to work on this.

**Comment by macgills** [comment] 2020-03-25 10:35
duplicate of #1611 , be wary

**Closed by macgills** 2020-03-25 10:35 UTC

**Comment by Frans-Lukas** [comment] 2020-03-25 10:43
oh, ok! sounds more difficult than I imagined.
