### ISSUE TITLE
Not always possible to cancel a ZIM while Downloading

### ISSUE THREAD

**Issue by Achintya999** [kiwix/kiwix-android#670] opened 2018-03-25 21:31 UTC
Bug Report

**Environment**

version of the software you use: Latest master
device / operating system: One Plus 5/ Android 8.0

**The Bug**

When we start the download of the ZIM file and close the internet and opens the app again, no matter how many time we cancel the downloading it doesn't get cancelled it just remain there in the download section.

**Comment by kelson42** [comment] 2018-03-26 09:12
I can not reproduce the problem, but by playing around this (stopping randomly both Internet connection and app itself) and I have discover few other bugs:
* Downloads in the Android notifications list but not in the "Download" section
* It seems indeed difficult to stop them from the notification... at some point I have even achieved to make the app crash by trying this.

So I think there is a fundamental synchronisation problem here between what is displayed in both Notifications and Downlaod section and the "reality" of the download process in the app.

**Comment by kelson42** [comment] 2018-03-26 09:17
To me, pretty much a duplicate of #600

**Comment by Achintya999** [comment] 2018-03-26 11:57
@kelson42 assign this bug to me i will start working on it.

**Comment by mhutti1** [comment] 2018-03-31 22:25
I think this is when the download service crashes but the notification gets left and is non dismissable. If we can we should clean up notifications when we crash.

**Comment by Achintya999** [comment] 2018-03-31 22:28
Sir assign this bug to me.I will work on it and try to fix it

**Comment by kelson42** [comment] 2019-06-14 12:51
We have removed the "pause" ability in 2.5.

**Closed by kelson42** 2019-06-14 12:51 UTC
Labels: bug
