### ISSUE TITLE
How Kiwix behaves with mobile data

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#136] opened 2017-05-18 07:21 UTC
I had a feedack from a user switching from wifi to mobile data... and he does not want to use data for content download (which was already started with wifi). I suspect here we need an option about which system is allowed to be used for download (or do we have a dialog box prompted)?

**Comment by mhutti1** [comment] 2017-05-18 07:38
Duplicate of #135

**Closed by mhutti1** 2017-05-18 07:38 UTC
Labels: question
