### ISSUE TITLE
Deleting Kiwix does not delete zim files (nor some preferences)

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#711] opened 2018-04-13 09:35 UTC
Should it not clean the whole thing (or at least ask?)

I suspect it also does not delete some preferences either : uninstalling and reinstalling Kiwix, it remembered that I wanted it set in Spanish (yet did open in French, as explained in #710). All other preferences and permissions where however reset to zero.

**Comment by kelson42** [comment] 2018-04-14 11:45
This is duplicate of #596

**Closed by kelson42** 2018-04-14 11:45 UTC
Labels: bug, duplicate
