### ISSUE TITLE
Snackbar appears over bottom toolbar

### ISSUE THREAD

**Issue by aryanagarwal15** [kiwix/kiwix-android#579] opened 2018-03-04 12:36 UTC
### Are you ready to report?
   - Your issue may already be reported! Please search on the [issue track](../) before creating one.
   - Ensure you have tested with the last (dev) version of the software.  (If not, and if possible, run your test again with the most recent version available.)

### Environment
  * version of the software you use : Android Studio 3.0.1
  * device / operating system : Nexus 5X / Android 8.1.0
  
### The Bug:

  * What do you obtain? A copy of the error message or a screenshot is always useful.

The snackbar appear over bottom navigation bar when we bookmark / remove bookmark any item.

<img src="https://preview.ibb.co/buU0Sn/Screenshot_1520165842.png" width="300">
<img src="https://preview.ibb.co/jQH9L7/Screenshot_1520165727.png" width="300">
<img src="https://preview.ibb.co/jTb3f7/Screenshot_1520165844.png" width="300">

  * When does this occur? 

#### Steps to reproduce:

  1. Go to setting and enable bottom toolbar.
  2. Now an the main page try bookmarking any article
  3. Try removing the bookmark also.
  ...
  
  * What should be the behaviour from your point of view? How do you expect the service to work?
As per the [Material UI guidelines](https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-specs) the snackbar should appear above the bottom navigation bar as shown in the screenshot below.
<img src="https://preview.ibb.co/nnGfSn/snackbar.png" width="300">

### Other Comments:
  Would like to work on it.

**Comment by brijeshshah13** [comment] 2018-03-05 05:45
@aryanagarwal15 Go ahead, fix it.

**Comment by dhirajj75** [comment] 2018-03-05 18:49
We can set the timer for the snackbar and make it disappear after specific time.

**Comment by aryanagarwal15** [comment] 2018-03-05 19:01
@dhirajj75 The timer is already there. I'm trying to solve this bug by using what google specifies in their material guidelines page. I'm trying to achieve what I've shown in the last screenshot in the issue.

**Comment by dhirajj75** [comment] 2018-03-05 19:04
@aryanagarwal15  yes! It can be done.

**Comment by dhirajj75** [comment] 2018-03-05 19:05
Can I work on this?

**Comment by aryanagarwal15** [comment] 2018-03-05 19:16
@dhirajj75 I am already working on this.

**Comment by dhirajj75** [comment] 2018-03-06 03:49
@aryanagarwal15 okay!

**Comment by GeVic** [comment] 2018-03-09 10:38
@dhirajj75 If you are not currently working on this should i resolve the issue. Should i @mhutti1

**Comment by aryanagarwal15** [comment] 2018-03-09 11:04
@GeVic I am currently working on it.

**Comment by GeVic** [comment] 2018-03-09 11:37
@aryanagarwal15 Okay

**Comment by brijeshshah13** [comment] 2018-03-23 11:56
@aryanagarwal15 What is the status of this issue?

**Comment by ritik2017** [comment] 2018-10-02 19:44
what is the status of the issue? Shall I work to resolve it?

**Comment by mhutti1** [comment] 2018-10-03 09:38
I think this is still an issue if you want to give it a shot.

**Comment by kelson42** [comment] 2018-10-06 14:38
@panvica10 good :)

**Comment by kanupriyaa** [comment] 2019-06-25 10:58
Why is this issue still open when a PR was accepted? @mhutti1

**Comment by macgills** [comment] 2019-06-25 11:06
@kanupriyaa see conversation here https://github.com/kiwix/kiwix-android/pull/1210
This seems to be a branching error, the branch called 2.5 never wound up being used in the 2.5 release.
I will begin the process of getting this added to 3.0

**Comment by macgills** [comment] 2019-06-25 11:29
Confirmed bug still present, moving to 3.0 milestone

**Closed** 2019-08-15 12:24 UTC
Labels: enhancement, good first issue
