### ISSUE TITLE
Bitbar not working with split APKs

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#1228] opened 2019-06-25 14:07 UTC
**Describe the bug**
Uploads to bitbar on travis are not functional on develop or any derived branches.
There is a possibility that with the advent of #1219 and the generation of a universal apk that bitbar will select it from the group of generated apks.

**Expected behavior**
Bitbar uploads happen without error

**Steps to reproduce the behavior:**
open a pull request into develop

**Logs**
```
> Task :app:[secure]testUploadKiwixDebugAndroidTest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:[secure]testUploadKiwixDebugAndroidTest'.
> Cannot handle split APKs
```

**Comment by mhutti1** [comment] 2019-06-26 20:17
I think we got this working before. I am not entirely sure though.

**Comment by mhutti1** [comment] 2019-06-30 16:52
@macgills Possibly. I am not sure. If there is an easier way to fix this it might be worthwile.

**Comment by macgills** [comment] 2019-07-15 09:29
The universal apk does not work, the testdroid plugin does not work.
I could open an issue on [their repo](https://github.com/bitbar/testdroid-gradle-plugin)?

**Comment by kelson42** [comment] 2019-07-15 14:32
@macgills Please try with https://download.kiwix.org/release/kiwix-android/kiwix-2.4.apk and let me know if it fails too.

**Comment by macgills** [comment] 2019-07-15 15:24
@kelson42 the issue is that 2.5 onward is a split apk.
The testdroid plugin does not allow -from what I can see- specifying the upload of a particular apk when splits are present.
2.4 would probably work but I would need to make 2.4 build on travis because that has the keys for uploading to bitbar and that seems like more trouble than it is worth

**Comment by kelson42** [comment] 2019-07-15 19:27
@macgills What I don't understand is why bitbar does not work with the 3.0 universal APK, because we can build it?
@julianharty Anyway you can help us on this?

**Comment by kelson42** [comment] 2020-02-09 15:36
@macgills @abdulwd Do we ever need Bitbar for automated testing?

**Comment by abdulwd** [comment] 2020-02-09 16:04
@macgills Can we try [BrowserStack](https://www.browserstack.com/app-automate) for automated testing? We can generate a universal apk that can be uploaded to BrowserStack & run tests on a small number of devices (say 4 devices) for every build.

Also, we can run all these tests once a day as a regression suite on all the devices that are offered by BrowserStack.

**Comment by kelson42** [comment] 2020-02-09 16:14
@abdulwd The fundamental problem with BrowserStack is that we can not really affort it.

**Comment by kelson42** [comment] 2020-02-09 16:21
Or maybe not https://www.browserstack.com/open-source?ref=pricing

**Comment by abdulwd** [comment] 2020-02-09 17:08
Yupp. It's free for open source.

**Comment by macgills** [comment] 2020-02-10 08:37
It is an option, we could see if it integrates into our flow. Seems trivial to start with their plugin, it gets slightly more irritating if the plugin doesn't support split apks

**Comment by kelson42** [comment] 2020-02-10 08:38
@macgills @abdulwd Before moving on this I would really appreciate a pro/con table with BitBar and and browserstack and myabe other (In this table should of course be listed the most important problem we today face with BitBar).

**Comment by macgills** [comment] 2020-02-10 09:19
We do already do a lot of automated testing on emulators. API levels 21-29 on nightly.

What these solutions add is physical devices and support for recording video if something goes wrong during a test.

The con is we have to have a complicated solution to integrate into our flow properly or at least this is how I understand it ie fail build if the tests fail. Both platforms have `callbackUrls` to fire back on when they complete their tests, I believe our previous solution when working with bitbar was to start a bash script and ping a status endpoint for 10 mins until success or fail the build. 
I don't see it being much different with browserStack though I have not used it.

Another problem we experienced with bitbar that could be an issue with browserstack is the split apks. To support uploading a singular apk we would have to stop using the plugin which gives us a gradle task to run eg `gradlew runBrowserStackTests`. Instead the manual process involves curl commands and other extraneous gradle tasks to support the inputs to the curl command.

**Comment by kelson42** [comment] 2020-02-18 14:14
@abdulwd Do you know if browserstack can deal with split APKs?

**Comment by abdulwd** [comment] 2020-02-18 14:28
I'm not sure I have to check.

**Comment by kelson42** [comment] 2020-04-18 10:17
@abdulwd Have you been able to check this?

**Comment by abdulwd** [comment] 2020-04-20 14:25
@kelson42 We have to upload the correct split apk for the given device.
@macgills Can we discuss this over a call?

**Comment by macgills** [comment] 2020-04-20 15:26
We also do have a universal apk? If you can just upload that then there is no worries.

I can be on a call next week 27th-1st

**Comment by abdulwd** [comment] 2020-04-20 21:07
Cool. Works for me.

**Comment by kelson42** [comment] 2020-04-21 06:41
@abdulwd @macgills OK, looks like we should better deal with BrowserStack then. I will close this ticket. If we go further in that direction, I believe we should implement a really simple/minimal/basic automated test using BS and see if this behaves stable during a month. But before that we need a clear ticket to scope the work.

**Closed** 2020-04-21 06:41 UTC
Labels: bug, testing
