### ISSUE TITLE
Saving bookmarks in the `zim-split` splitted ZIM files are crashing the application, when there is a 0 size extra zim chunk.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/kiwix-android#3861] opened 2024-06-03 09:01 UTC
**Describe the bug**
Saving bookmarks in the `zim-split` splitted ZIM files are crashing the application, when there is a 0 size extra zim chunk.

**Expected behavior**
It should not crash.

**Steps to reproduce the behavior:**
1. Try to open any splitted ZIM file in the reader.
2. Click on the bookmark icon at the bottom.
3. You will see the crash.

**Environment**
- Version of Kiwix Android : 3.10.1
- Device : Google pixel 7a
- OS version : Android 13

**Logs**
```kotlin
 Process: org.kiwix.kiwixmobile, PID: 17268
                                                                                                    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:562)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878) 
                                                                                                    Caused by: java.lang.Exception: Corrupted block detected
                                                                                                    	at org.kiwix.libkiwix.Book.update(Native Method)
                                                                                                    	at org.kiwix.kiwixmobile.core.main.CoreReaderFragment.toggleBookmark(CoreReaderFragment.kt:1758)
                                                                                                    	at org.kiwix.kiwixmobile.core.main.CoreReaderFragment_ViewBinding$6.doClick(CoreReaderFragment_ViewBinding.java:121)
                                                                                                    	at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:26)
                                                                                                    	at android.view.View.performClick(View.java:7729)
                                                                                                    	at android.view.View.performClickInternal(View.java:7706)
                                                                                                    	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
                                                                                                    	at android.view.View$PerformClick.run(View.java:30484)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8501)
```

https://github.com/kiwix/kiwix-android/assets/34593983/85176581-8617-4329-bd5a-4d11000b9648

**Comment by kelson42** [comment] 2024-06-03 09:03
@MohitMaliFtechiz With or without a trailing 0 sized chunk?

**Comment by MohitMaliFtechiz** [comment] 2024-06-03 09:06
> @MohitMaliFtechiz With or without a trailing 0 sized chunk?

@kelson42 With 0 size extra zim chunk.

**Comment by kelson42** [comment] 2024-06-03 09:07
@MohitMaliFtechiz If you remove it, then it works?

**Comment by MohitMaliFtechiz** [comment] 2024-06-03 09:07
@kelson42 Yes, if i remove the extra 0 size zim chunk then it starts saving the bookmark.

**Comment by kelson42** [comment] 2024-06-03 09:09
Then clear duplicate of #3827

**Comment by MohitMaliFtechiz** [comment] 2024-06-03 10:05
For the crashing scenario, I have placed a fix in https://github.com/kiwix/kiwix-android/pull/3862 so that application will not crash if libkiwix throw this type of errors, and updated the https://github.com/kiwix/kiwix-android/issues/3827 ticket description for this crash scenario.

**Closed** 2024-06-07 04:37 UTC
Labels: bug, duplicate
