### ISSUE TITLE
version on fdroid older then gp version

### ISSUE THREAD

**Issue by ilyapashuk** [kiwix/kiwix-android#2513] opened 2020-11-19 16:17 UTC
In fdroid, last package is 3.3.1, september 9, but in gp it is october 16

**Comment by kelson42** [comment] 2020-11-20 07:45
@macgills How reasonable it is to consider this as duplicate of #1682 (3.5)?

**Comment by macgills** [comment] 2020-11-20 09:20
I can do a manual release, the automation of the release is still not there, I don't think we have decided on where to host the file that fdroid needs to read?

**Comment by macgills** [comment] 2020-11-20 10:34
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7753 up to fdroid maintainers now

**Comment by kelson42** [comment] 2020-12-10 06:57
3.4.1 has been put in prod. Thx.

**Closed by kelson42** 2020-12-10 06:57 UTC
Labels: question
