### ISSUE TITLE
Custom apps should validate their expansion files and re-download if corrupt/missing

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#64] opened 2017-03-18 12:41 UTC
_From @mhutti1 on September 27, 2016 11:43_

https://developer.android.com/google/play/expansion-files.html#Downloading

This article suggests that we should implement Googles download library and create a simple UI to inform the user of our progress.

_Copied from original issue: kiwix/kiwix#331_

**Comment by mhutti1** [comment] 2017-03-18 12:41
_From @kelson42 on December 11, 2016 15:59_

@mhutti1 I support the idea. Can we go ahead on this?

**Comment by mhutti1** [comment] 2017-03-18 12:41
So this either requires us implementing https://developer.android.com/google/play/licensing/index.html or using our own download method. We will need to work out which is the best option.

**Comment by RohanBh** [comment] 2018-03-09 22:34
@mhutti1 If we add the zim files as expansion files for the app, then the custom app's apk will no longer be a standalone apk. The apk size will reduce drastically but sharing of only the apk won't be enough to pass content between devices. 
You yourself told me 
> Because this is for the specific use case where distribution is offline.

**Comment by mhutti1** [comment] 2018-03-10 23:59
@RohanBh These are two different mechanisms. The .so mechanism is for pre packed standalone APK files for offline distribution. .obb files are Google Play store specific. They are different systems but at the end of the day you are still just reading a ZIM file.

**Comment by mhutti1** [comment] 2018-03-11 00:07
@RohanBh we do, other people might, anyone can. As an open source app it is important that we are not depended on the closed source nature of the Play Store to function.

**Comment by julianharty** [comment] 2019-09-03 20:14
Here are some thoughts on how we can design and implement support for obtaining the expansion file(s) on a device.

Firstly, Kiwix aims to support offline use - so there should be viable alternatives to obtain the content beyond (re-) downloading it from Google Play Store. For many users that won't be viable/desirable. As I've discovered, in some regions users share and sideload apps, including Kiwix apps and share content directly. I'd therefore suggest we design our custom apps so they can help these users understand what needs to be transferred and where the content needs to be placed in order for the custom app to find and use that content successfully.

As we're adding various forms of file sharing and content hosting into the core Android app one approach might integrate with these features for users who understand and are happy to use these instead of apps such as ShareIt.

Of course, the custom apps should also be able to download missing content directly from Google Play.

**Comment by macgills** [comment] 2019-10-22 10:25
My current thinking is that we do not need expansion files if we are just going to develop our own way of getting the zim files for a non-play store distribution of a non-embedded custom app. They add extra overhead/complication while giving us very little (user still has to download all this data) and limiting us (files cannot exceed 2GB).
This would entail the proposal of a new screen I would imagine, `CustomAppFileValidator` or the like potentially replacing the Intro screen as that has some slightly non relevant text eg `Download books and read wherever you are.`. @kelson42

**Comment by mhutti1** [comment] 2019-10-22 10:46
I disagree. Many of our custom app users don't want to go through additional steps and the main point of them is in my opinion the ability to install with one click.

**Comment by macgills** [comment] 2019-10-22 10:51
I think there is an acceptance that any app that provides significantly large data will have to go off and download it after install as many games do.
They still install with one click and most likely they launch us after installation (seeing as how the install is 15MB~) and we just start downloading and tell them "installing", in most scenarios it is just as convenient I'd hazard

**Comment by mhutti1** [comment] 2019-10-22 10:55
Sure. But if I downloaded an app that was 30MB I wouldn't expect it to start downloading 2GB of data. I think it would be annoying for a lot of people.

**Comment by macgills** [comment] 2019-10-22 10:59
They downloaded an app that has Wikipedia on it, there would have to be hefty delusion to think it is only 15MB though I guess that should not be underestimated.
[Hearthstone](https://play.google.com/store/apps/details?id=com.blizzard.wtcg.hearthstone&hl=en_IE) is 14MB.

**Comment by kelson42** [comment] 2019-10-22 11:44
> I disagree. Many of our custom app users don't want to go through additional steps and the main point of them is in my opinion the ability to install with one click.

I quite agree with that. We don't really consider to have ZIM files over 2GB and if we would need that, we would handle the with 2/3 extensions (splitted ZIM files). Having the ability to install custom apps is one click is a really important feature.

**Comment by macgills** [comment] 2019-10-22 11:55
It is still 1 click and we get to disentangle ourselves from the play store. Loads of apps do this because expansion files are incredibly limited.
Also many SD cards can support files over 2GB, it depends on the device. We can remove that limitation if we address FileSystem detection issues.
It also means we don't need to develop and maintain 2 separate systems for play distributed and other store front distributed

**Comment by mhutti1** [comment] 2019-10-22 12:25
In an ideal world I would have any stuff more than 2 GB be able to be downloaded as extra "modules" of content. I think we are in danger of seriously misleading users if we are not up front about the app size and I don't see a good way of conveying this on the play store without bundling the content with the app.

**Comment by macgills** [comment] 2019-10-22 12:36
Hearthstone has 10million+ downloads and nearly every game app does this. I would be shocked if Pokemon Go doesn't. Users should know this.
iOS doesn't even allow this, max app size is 4GB (not enough for many games) so they immediately go download off their own servers on launch.
This is an industry standard for serving large content across ecosystems.

**Comment by kelson42** [comment] 2019-10-22 12:37
@macgills We tend to do smaller ZIM custom apps, not bigger and what I mean with 1-click, is not only 1-click, it is atomic and transparent from the start how much size is needed. Basically I share the opinion of mhutti. I have to say that we also had this discussion in the past and the consensus was pretty much on how it works today. We can ping @Popolechien to get its opinion too.

**Comment by Popolechien** [comment] 2019-10-22 12:47
I get your point @macgills but the use case we are dealing with isn't as vertical (ie, connect to the store -> download from store) as in Northern markets. In many cases (Cuba, India, Eritrea are confirmed) people will buy the APK off the street or share it somehow from user to user - without ever connecting to the internet proper.

**Comment by macgills** [comment] 2019-10-22 12:53
@Popolechien that is not this scenario. Though my solution would probably help that scenario.
This is "online distributiont", in this scenario we have a guarantee that somebody has internet access and can download the app/data.
"Offline distribution" is why we have "embedded" apps, these are fat apps with the zim file baked in

**Comment by kelson42** [comment] 2019-10-22 13:03
@Popolechien This discussion started by @macgills is only about the online installation.

**Comment by macgills** [comment] 2019-10-30 15:30
The implementation of the official solution is even worse than first expected.
According to the docs we must download the modules from the sdkManager, which would be fine except those aren't the latest version.
The latest version is on [github](https://github.com/google/play-apk-expansion) and last updated 2 years ago. Neither of these versions are actually gradle projects.
The community comes to the rescue [with a fork](https://github.com/auxility/better-apk-expansion) the last release of which was 1 year 8 months ago so it has [issues](https://github.com/auxility/better-apk-expansion/issues/12)
>This library is outdated and cannot used on Android O.
startService() is no longer allowed to be called and startForegroundService() must be used instead (followed by startForeground())
Anyone facing the issue should update the code themselves or find an alternative.

>Myself, and likely many developers using .obb are currently praying that the increased .aab size of 1GB will become public soon (Google has teased this in an early preview via email: and not given us access...) so I think it's not worth putting extensive development into obb support at this time, sorry.
It is very much a 'keep it from breaking until we can finally cut it out and remove it fully'

>You know what, I might just switch to a plain old HTTP file download from Digital Ocean until this change blows over...I've been wondering how developers are coping with such a bizarre system.


I will see if this ridiculous command works 
```
android update project --path ~/Android/MyApp \
--library ~/android_sdk/extras/google/market_licensing \
--library ~/android_sdk/extras/google/market_apk_expansion/downloader_library
```
because the modules can not be imported in standard fashion.

And if that fails work on cloning/importing/fixing `better-apk-expansion`?

**Comment by macgills** [comment] 2019-10-31 11:25
I think it would be best to ignore the google download/licensing library, it is too old and unwieldly.
We can use a manual download of a `zim` in the case where we do not have an `obb` file installed a scenario which is when the app was sideloaded, magical install failure or user manually deleted the `obb` file.

I would propose an "installation verification" screen with a flow like

- has only obb file = valid
- has only zim = valid
- has zim and obb = delete zim, recheck
- has neither = start download, recheck on download completion

This maintains the requirement of atomic play store downloads and lends better support to other distribution platforms.

**Comment by mhutti1** [comment] 2019-10-31 13:25
Sounds good. I would ask the user if they want to delete the ZIM though. We also need to start mapping zim ids to obb files I think so we can verify they are the same.

**Comment by macgills** [comment] 2019-10-31 13:46
The scenario where a use has an obb and a zim at the same time would be if they sideloaded, later connected to the play store and updated to a newer version. Or perhaps google does some automatic downloading if they detect missing obbs, it is difficult to get a clear answer.
>To ensure proper behavior, you must not delete, move, or rename the expansion files. 

>If you must unpack the contents of your expansion files, do not delete the OBB expansion files afterwards and do not save the unpacked data in the same directory

>Do not delete or rename the .obb expansion file (unless you're performing an update). Doing so will cause Google Play (or your app itself) to repeatedly download the expansion file.

>However, in some cases Google Play cannot download the expansion files or the user might have deleted previously downloaded expansion files. To handle these situations, your app must be able to download the files itself when the main activity starts, using a URL provided by Google Play.

I think in that scenario to save disk space alone that deleting the zim is preferable if both are there.

We do need a way of identifying what zim to download, for obbs loading them into a ZimFileReader is enough to get id, etc

**Comment by kelson42** [comment] 2019-11-01 09:59
@macgills I'm suppportive

**Comment by macgills** [comment] 2019-11-01 10:19
@kelson42 then we would need a way of downloading the zimFile, how do we get a meta4 link from the json
```
"zim_file": "wikipedia_fr_test_2017-07.zim",
```
?

**Comment by mhutti1** [comment] 2019-11-01 13:29
I think we at one point at least included a download url in the the json schema.

**Comment by kelson42** [comment] 2019-11-01 13:48
@macgills if you look to #1218 (which is part of 3.1) milestone, you can see that I'm in favour of allowing an URL

> zim_url and zim_content should be merged (in zim?)

I'm in favour of having the `meta4` link directly in the JSON, like https://download.kiwix.org/zim/wikipedia_fr_all_maxi.zim.meta4

Be careful, such a permalink is a redirect.

**Comment by macgills** [comment] 2019-11-01 13:49
@mhutti1 ![image](https://user-images.githubusercontent.com/3358282/68029032-4134d000-fcae-11e9-9960-b9c8c5a32ace.png)
you are correct, it is just not in `customExample`

**Closed** 2019-11-11 13:05 UTC
Labels: challenge, custom apps, enhancement
