### ISSUE TITLE
Cannot resume download after pausing

### ISSUE THREAD

**Issue by cvzi** [kiwix/kiwix-android#2157] opened 2020-06-21 19:27 UTC
**Describe the bug**
There seems to be no way to resume a download, if you clicked on "Pause" in the notification

**Steps to reproduce the behavior:**
1. Start a download
2. Click "Pause" in the download notification -> the notification disappears
3. In the Library in the "Online" tab, there is only the black square to stop the download, but no way to resume it.

**Environment**
- Version of Kiwix Android : 3.3.1
- Device : Moto G7 Power
- OS version : Android 9

**Comment by kelson42** [comment] 2020-06-21 19:49
Somehow a duplicate of #2049 I believe. I wonder a bit we have a "pause" button in the notification @macgills. A bug ?

**Comment by macgills** [comment] 2020-06-22 14:44
When we migrated to fetch we regained the ability to pause notifications but did not add the functionality, we can either remove the pause button from the notification or support pausing/resuming in the UI

**Comment by kelson42** [comment] 2020-06-22 15:09
@macgills Could we hide please the "pause" button as long as the full feature is not brought back with  #2049  please ?

**Comment by macgills** [comment] 2020-06-22 15:26
@kelson42 #2049 has no relation to this, #2107 will entail an upgrade of fetch if there has actually been an update from the project maintainer, there wasn't last I checked

**Comment by kelson42** [comment] 2020-06-22 15:34
@macgills Sorry, I mean #2093. What is important for the moment is not to provide a button which has no proper handling behind. That is all what I want to emphasis.

**Comment by macgills** [comment] 2020-06-22 15:36
We can add this to 3.2.2 and I can probably get it done tomorrow? I don't think there are many other tickets left in 3.2.2 so I was hoping to get it to beta sooner rather than later

**Comment by kelson42** [comment] 2024-01-12 15:37
@Popolechien please open a new ticket. This one is too old.

**Comment by Popolechien** [comment] 2024-01-12 15:37
ok

**Closed by Popolechien** 2024-01-12 15:37 UTC
Labels: duplicate, enhancement, question
