### ISSUE TITLE
Logging (quantity and quality)

### ISSUE THREAD

**Issue by ISNIT0** [kiwix/kiwix-android#252] opened 2017-08-25 13:22 UTC
Having read:
https://www.javacodegeeks.com/2011/01/10-tips-proper-application-logging.html

@julianharty and I have been discussing what makes logging good/bad. This is based on:

- Quality of the message (appropriate tag/type, contents, contextual information, ease of understanding)
- Quantity/Location of Logs (near troublesome code, spread across the project)

I've generated a report about our logging at present:
[Kiwix.pdf](https://github.com/kiwix/kiwix-android/files/1251940/Kiwix.pdf)

Log Tag Naming Convention?
What do people think about "kiwix-{className}" or "kiwix-{fileName}"

**Comment by julianharty** [comment] 2017-10-04 14:02
Added logging of the OkHttp requests and responses https://github.com/kiwix/kiwix-android/commit/86f0da12c633400a87d40899b38bc7d7576d8271

**Comment by kelson42** [comment] 2020-02-09 14:11
@mhutti1 @macgills Do you have an idea how we could deal with that ticket?

**Comment by macgills** [comment] 2020-02-10 08:22
As part of #1270 I was looking to make a centralised logging class so we can have greater control over app logging and can comply with the conditional logging easily

**Comment by kelson42** [comment] 2023-04-16 14:13
Pretty much a duplicate of #1270. A ticket with such a formulation is as well pretty hard to implement.

**Comment by kelson42** [comment] 2024-03-11 06:38
@MohitMaliFtechiz Very old ticket I just have assigned tomyou. Not sure about this pertinence. What can you propose?

**Comment by kelson42** [comment] 2024-03-12 13:03
OK, so basicaly no clear actionable. Closing.

**Closed** 2024-03-12 13:04 UTC
Labels: enhancement
