### ISSUE TITLE
Search history suggestions are duplicated instead of reordered

### ISSUE THREAD

**Issue by danielzgtg** [kiwix/kiwix-android#1825] opened 2020-02-27 03:10 UTC
**Describe the bug**

Search history suggestions are duplicated instead of being moved to the top.

**Expected behavior**

To not see duplicate search suggestions.

**Steps to reproduce the behavior:**
1. Tap on the search icon
2. Type "wiki"
3. Tap on "wiki"
4. Repeat steps 1-3 for "kiwi"
5. Tap on the search icon
6. Tap on "wiki" (without typing anything)
7. Repeat steps 5-6 10 times

**Screenshots**

Expected behavior as in 3.1.3 ("wiki" is at the top, followed by "kiwi"):

![Screenshot_20200226-215905](https://user-images.githubusercontent.com/25646384/75408617-4f090380-58e4-11ea-88e5-52f1210f03e8.jpg)

Actual behavior (5 copies of "wiki" and no "kiwi"):

![Screenshot_20200226-220514](https://user-images.githubusercontent.com/25646384/75408682-7790fd80-58e4-11ea-9e31-e07b2372c36b.jpg)

**Environment**
- Version of Kiwix Android : 3.2.0
- Device : OnePlus 7 Pro
- OS version : OxygenOS Beta 9

**Comment by deborahlow97** [comment] 2020-02-27 08:15
Yea I feel that only unique searches should be shown to the users, and moved to the top if it's a duplicate search history. If this gets approved I'd like to work on this issue

**Comment by macgills** [comment] 2020-02-27 09:19
Yes I confirm this is an issue. Unless @danielzgtg wants to work on this you are next in line @deborahlow97

**Comment by danielzgtg** [comment] 2020-02-27 14:09
Unless danielzgtg wants to work on this […]

No, I can't contribute code until May, so go ahead

**Comment by macgills** [comment] 2020-02-27 14:10
You are assigned @deborahlow97

**Comment by kelson42** [comment] 2020-02-27 14:12
@macgills I believe this is a duplicate of https://github.com/openzim/libzim/issues/276. Should not be handle in Kiwix for Android.

**Closed** 2020-03-16 15:50 UTC
Labels: UI, bug, enhancement, good first issue, search
