### ISSUE TITLE
Inability to switch between different libraries

### ISSUE THREAD

**Issue by paologarcia002** [kiwix/kiwix-android#521] opened 2018-02-25 21:24 UTC
## Bug Report

- [Y] I have tested with the last (dev) version of the software. 

### Step 2: What is your environment?
  * version of the software you use : AVD of Pixel 2 with API 27, Ted Business, Tedx 2014
  
### Step 3: Describe the problem: 
When I was trying to reproduce the issue #344, instead of rendering correctly or with a mix of the two different ted libraries like in the issue, it only renders one library, despite switching to the other library (for example going from tedx to ted business, I would get only tedx like I never left)

#### Steps to reproduce:

  * Download the two Zim files: Ted Business and Tedx 2014 from the get content page
  * Once the files are downloaded, go to the Tedx library
  * Now switch from tedx to ted business through the get content menu
  * Tedx along with all its content appears on screen instead of Ted Business
  ...
  
As mentioned by Kelson in issue #344, it might be the cache is not cleared when the library changes.

**Comment by arpank10** [comment] 2018-02-27 08:50
See issue #236 , also take a look at the PR #481

**Comment by kelson42** [comment] 2018-04-11 17:15
@paologarcia002 Could you please recompile the last master HEAD and check that you still have this bug? It should be fixed.

**Comment by mhutti1** [comment] 2018-05-27 21:30
Closing as am pretty sure this is a duplicate of #344

**Closed by mhutti1** 2018-05-27 21:30 UTC
Labels: bug
