### ISSUE TITLE
Crash after update to 2.3

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#285] opened 2017-11-13 07:33 UTC
From the OTRS feedback queue.
"I have two zim files on SD card but  Kiwix can't find any of them. When I tap Get Content, it tries to get online or show "scanning for downloadable content message" but crashes immediately. the update rendered the app useless.
Cleaning the cache and data didn't fix anything."
Version 2.3 Build 173130

**Comment by mhutti1** [comment] 2017-11-13 18:28
Duplicate of #240

**Closed by mhutti1** 2017-11-13 18:28 UTC
Labels: bug
