### ISSUE TITLE
Split screen crashes secondary app

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#265] opened 2017-09-27 12:18 UTC
Feel free to ask questions, I'm only parroting from OTRS ticket service and will get back to the user if needed:

Problem is on Android 7.1: user says that it "breaks the app" when he tries to do split screen. Here's a small screencap animation that the user sent.

https://drive.google.com/file/d/0B9KLZQhlTuPvRXlnYWY4MVVNaW8/view

This issue is not dependent on which app Kiwix shares the screen with, it only seems to happen when the user resizes the secondary app window to its smallest size.

The issue does not occur when user opens Kiwix as the secondary app.

**Comment by kelson42** [comment] 2017-09-28 06:17
@Popolechien I do not have a device with Android 7.0, so I can not even try to reproduce that problem. @rashiq @EladKeyshawn @borisfba @mhutti1 @ISNIT0 @julianharty Anyone to confirm?

**Comment by julianharty** [comment] 2017-09-28 07:06
I've got devices with android 6 and 8, I should manage to get a device with
7 and will try to reproduce this in the coming days.

**Comment by EladKeyshawn** [comment] 2017-09-28 07:35
@kelson42 I've have Android 7 i'll try to reproduce

**Comment by kelson42** [comment] 2019-07-18 05:14
@macgills @EladKeyshawn @abdulwd @siddharth2010 Can someone reproduce that bug? Otherwise I would like to close it.

**Comment by siddharth2010** [comment] 2019-07-18 13:25
I have a Galaxy S6 running Android 7.1. Will test it tonight!

**Comment by macgills** [comment] 2019-07-18 13:31
I have not been able to replicate this, tested on an emulator running 7.0, android device 8.0. Recommend closing

**Comment by kelson42** [comment] 2019-07-18 13:46
Closing the ticket. @siddharth2010 Please test it and reopen the ticket if you see a problem.

**Closed by kelson42** 2019-07-18 13:46 UTC
Labels: bug, good first issue

**Comment by siddharth2010** [comment] 2019-07-18 13:47
@kelson42 , I just tested it. It seems to be working perfectly fine on 7.1 as well.
