### ISSUE TITLE
"Unknown file system error" when downloading

### ISSUE THREAD

**Issue by DoS007** [kiwix/kiwix-android#1382] opened 2019-08-15 17:27 UTC
**Describe the bug**
Getting content I want to download the in the online tab listed things, e.g. wiktionary or wikipedia. When I click to download in download tab i see "Paused: Waiting to retry". After a few minutes after attempting download it says "Unknown file system error". 

**Expected behavior**
It should just download e.g. "wiktionary".

**Steps to reproduce the behavior:**
See "Describe the bug". I use an sd card and chose "Extern" in kiwix options.

**Environment**
- Version of Kiwix Android : Newest in store, 2.5.2
- Device : Note 8
- OS version : Stock Android 9/Pie

**Logs**
Don't know where to get. Clicking on help on three dots main menu doesn't do anything.

**Comment by macgills** [comment] 2019-08-16 08:33
Is the problem persistent? We use an android component called the DownloadManager which has a known problem with blockada #1304 .
If you were updating a lot of apps from the playstore this could cause congestion on your device and prevent a download for a while.
We should detect if there is enough free space when you click on an item but perhaps make some space on the sd card? Or if you can try another sd card to see if the problem persists then it might help in diagnosing the problem.
If you select internal storage does the download fail?
Thank you for the report.

**Comment by DoS007** [comment] 2019-08-16 13:04
Yes, the problem remains.

I no nothing/don't use of blockada.

I didn't update a lot of apps.

The sd card has plenty of space (i have an 400gb sandisk extreme; i have more than 200gb space). I cannot test another sd card.

When i switch to internal storage, the download directly begins.

Oh and now the app crashed after switchting to extern. I now manually added the storage path, but the problem like described on top remains.

Thank you for your answer :).

**Comment by macgills** [comment] 2019-08-16 13:14
Are you using your sd card as internal storage or external storage? If you go to storage in your phone's settings it should let you know or there should be an option to format it as removable/internal. Kiwix works better with an sd card that is formatted as internal storage, if that is an option for you it may be helpful in the short term

If you got to a file explorer there should be a folder `Kiwix` at the root of your device storage, inside should be a file `logcat.txt` and that may have something useful in it

**Comment by DoS007** [comment] 2019-08-16 13:25
I use the sd card as external. Internal is for various reasons not an option for me.

Logs:
Maybe this part helps?

> 08-16 15:00:37.297  1425  1521 D kiwix   : Retrieving: content://org.kiwix.kiwixmobile.zim.base/null
> 08-16 15:00:37.298  1425  2100 E kiwix   : Exception reading article null from zim file
> 08-16 15:00:37.298  1425  2100 E kiwix   : java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] org.kiwix.kiwixlib.JNIKiwixReader.getContent(java.lang.String, org.kiwix.kiwixlib.JNIKiwixString, org.kiwix.kiwixlib.JNIKiwixString, org.kiwix.kiwixlib.JNIKiwixInt)' on a null object reference
> 08-16 15:00:37.298  1425  2100 E kiwix   : 	at org.kiwix.kiwixmobile.ZimContentProvider$TransferThread.run(ZimContentProvider.java:477)
> 08-16 15:00:37.300  1425  1425 I kiwix   : Intent data: null
> 08-16 15:00:37.301  1425  1425 D kiwix   : actionnull

[logcat.txt](https://github.com/kiwix/kiwix-android/files/3509773/logcat.txt)

**Comment by macgills** [comment] 2019-08-16 14:02
I am afraid that doesn't help.
This is a bit more to ask of you but if you can install this [development version of kiwix](https://download.kiwix.org/nightly/2019-08-16/2958-kiwix-universal-debug.apk
) and see if the problem persists? You will have to uninstall your current version of kiwix.

You could also try downloading the zim file to internal and then copying over to external? This may produce a bug where the file will be listed twice in the device tab, that won't happen on this dev version but will on your current version.

**Comment by DoS007** [comment] 2019-08-16 15:05
Ok, i tried it: I removed the current version, downloaded the versionfrom the link, switched to extern and tried downloading german wiktionary. The same problem appears (first "Paused: Waiting to retry" and after that "unknown file system error"). Logcat.txt seems to be empty?

Downloading internal and copy to external is not a real option for me, because i want to use big wiki with photos.

**Comment by MidUK** [comment] 2019-08-17 11:28
I also have this exact same problem.

I thought it might be because my SD card is FAT32 formatted and the file is being downloaded as a massive file (>4GB).

I tried switching to the internal storage and downloading. This works fine but because I need the internal storage for other things, this also isn't an option for me but it seems the file size could be a problem.

One additional thing to note, when I went I looked at the app permissions, I needed to authorise the storage permission. It didnt fix anything but it might be worthwhile other users checking and seeing if it works for them.

**Comment by DoS007** [comment] 2019-08-17 12:39
I looked up the permission setting in android, and kiwix as storage access. 

I tested big file, copied ~5,4 GB file from computer to sd card no problem.  So the 4GB limit should be no problem. But anyways the problem also appeared with wiktionary which is only 1GB. So storage limit shouldn't be the cause.

**Comment by MidUK** [comment] 2019-08-17 13:06
You're right - I've just checked with small downloads in Kiwix and they have the same problem.

Reading about another issue on here, it looks like it could be an Android Pie problem and the way permissions are requested.

**Comment by kelson42** [comment] 2019-08-17 13:52
@MidUK @DoS007 Even if the problem is not reproducible on our end, we don't exclude of course a weakness/bug in Kiwix. But might it be that you have a problem with this special SD cards. Does it fail in the same way with an other SD card?

**Comment by DoS007** [comment] 2019-08-17 14:22
I use Samsung Note 8 on Stock Android Pie. I use as SD Card: "SanDisk Extreme 400GB microSDXC Memory Card + SD Adapter with A2 App Performance, up to 160MB/s, Class 10, UHS-I, U3, V30" which works flawlessly with every other app.

I currently cannot try another sd card.

Is there any other information which could help: E.g. path to memory card or trying another kiwix modified version with other loglevel?

**Comment by MidUK** [comment] 2019-08-17 14:37
I'm using a Sandisk 128 Ultra SD card.

I've just tried with a Samsung Pro and it had the same problems.

Likewise there are no problems using other apps. All my apps use external storage.

**Comment by macgills** [comment] 2019-08-19 08:38
#1385 this is an issue we will be addressing shortly. Thank you for the reports

**Comment by kelson42** [comment] 2019-08-19 16:57
@macgills If we understand the root cause of the symptoms our users reported and this is already treated in #1385, could we close that ticket as duplicate?

**Comment by macgills** [comment] 2019-08-20 09:43
Will do, closing as duplicate

**Closed** 2019-08-20 14:12 UTC
Labels: bug
