### ISSUE TITLE
Making Full-Text-Search avaible again

### ISSUE THREAD

**Issue by Inbefortus** [kiwix/kiwix-android#2662] opened 2021-05-28 19:42 UTC
For some reason, Full-text-search was disabled a while ago, but is still available on PC. What was the reason to get rid of it in the Android app? Full-text-search is fantastic and incredibly useful when used properly. It helps you go much, much deeper into Wikipedia. It's just fantastic. Can you make it available again in the options? I'm definitely not the only one who will make use of it. I can't think of any logical reason why it shouldn't be made available again.

**Comment by kelson42** [comment] 2021-07-19 04:45
Duplicate of #1324

**Closed by kelson42** 2021-07-19 04:45 UTC
