### ISSUE TITLE
ZIM download Notification Click

### ISSUE THREAD

**Issue by Sagar0-0** [kiwix/kiwix-android#3675] opened 2024-01-17 16:43 UTC
**Describe the bug**

Nothing happens on click of the notification after successful download of the ZIM file.

**Expected behavior**

If should Open the ZIM in reader.

**Steps to reproduce the behavior:**
1. Download a ZIM
2. See the notification
3. Click on it.
4. Nothing happens

**Screenshots**

https://github.com/kiwix/kiwix-android/assets/85388413/377e4ddb-e40e-4509-a3a6-18b2af186c17

**Environment**
- Version of Kiwix Android : 3.9.1
- Device : REALME GT
- OS version : 13

**Logs**

**Comment by MohitMaliFtechiz** [comment] 2024-01-19 12:30
@Sagar0-0 Thanks for opening the issue. I am assigning it to you.

**Comment by kelson42** [comment] 2024-01-19 18:15
Please clarify what should be the correct behaviour before starting the work. IMO, we face here a regression, correct behaviour should be: put ZIM in local library (if not already there) and open welcome page.

**Comment by Sagar0-0** [comment] 2024-01-20 04:22
IMO, it should open the ZIM in the Reader

**Comment by Sagar0-0** [comment] 2024-01-21 17:21
For this feature, we need to use PendingIntent.getActivity in FetchDownloaderNotificationManager and start the Reader with the given ZIM file, am I going the right way?

**Comment by MohitMaliFtechiz** [comment] 2024-01-22 11:29
@Sagar0-0 For your reference, we have implemented this feature to open the ZIm file in the reader.

Check the below links they would be helpful for you.

https://github.com/kiwix/kiwix-android/blob/3f19f55b99c83152d9f6be2d910894c9409c8637/core/src/main/java/org/kiwix/kiwixmobile/core/downloader/fetch/FetchDownloadNotificationManager.kt#L165

https://github.com/kiwix/kiwix-android/blob/3f19f55b99c83152d9f6be2d910894c9409c8637/core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt#L608

**Comment by MohitMaliFtechiz** [comment] 2024-01-25 13:42
@Sagar0-0 Are you working on this? or should I take it?

**Comment by Sagar0-0** [comment] 2024-01-25 13:45
I sm working on it, I'll update this today

**Comment by Sagar0-0** [comment] 2024-01-25 17:37
If I push a new commit, will It be added to my previous un-merged PR?

**Comment by kelson42** [comment] 2024-01-25 17:55
@Sagar0-0 There is no PRbso far linked to this issue.

**Comment by Sagar0-0** [comment] 2024-01-25 18:11
I am concerned for #3676

**Comment by MohitMaliFtechiz** [comment] 2024-01-26 06:07
> If I push a new commit, will It be added to my previous un-merged PR?

@Sagar0-0 This will not unless you are working on the same PR.

Please create another branch with the issue number place your fix in that branch and then push it.

**Comment by Sagar0-0** [comment] 2024-01-26 06:12
Got it, Thanks

**Comment by kelson42** [comment] 2024-01-26 06:38
@Sagar0-0 Thank you for reporting and fixing this issue, I have been impacted by it and glad you are on it.

**Comment by Sagar0-0** [comment] 2024-01-26 13:13
Right now, Inside KiwixMainActivity onNewIntent method... I am checking if it is a download notification and app is running, then I am navigating to the "readerFragmentResId". and then default code for calling onNewIntent for respective fragments. It is navigating to the reader but I think is now the right way and also showing unexpected behaviour. What can be the gap I am missing?

**Comment by MohitMaliFtechiz** [comment] 2024-01-26 13:37
> Right now, Inside KiwixMainActivity onNewIntent method... I am checking if it is a download notification and app is running, then I am navigating to the "readerFragmentResId". and then default code for calling onNewIntent for respective fragments. It is navigating to the reader but I think is now the right way and also showing unexpected behaviour. What can be the gap I am missing?

@Sagar0-0 have you removed this code from the `CoreReaderFragment` it is necessary to remove it if you are observing this on `KiwixMainActivity`.

 https://github.com/kiwix/kiwix-android/blob/3f19f55b99c83152d9f6be2d910894c9409c8637/core/src/main/java/org/kiwix/kiwixmobile/core/main/CoreReaderFragment.kt#L608

What is the unexpected behavior you are facing?

**Comment by Sagar0-0** [comment] 2024-01-26 13:53
The "handleNotificationIntent" function is linked to multiple functions and variables from CoreReaderFragment. Do I have to move/copy all the things to the KiwixMainActivity? Is there anything else possible? as it will lead to code duplication.

**Comment by MohitMaliFtechiz** [comment] 2024-01-26 13:55
@Sagar0-0 The "handleNotificationIntent" function is only used when the intent is received you can move this function to `KiwixMainActivity` it will do the same.

**Comment by Sagar0-0** [comment] 2024-01-26 14:14
After moving this, the related functions/variables used inside of handleNotificationintent method are missing, should I copy them also, as they are also used in other places from CoreReaderFragment.

**Comment by MohitMaliFtechiz** [comment] 2024-01-29 07:05
@Sagar0-0 You should not move the `openZimFile` function as it is mainly used for opening the ZIM files in `CoreReaderFragment`. You can use the `navigate` function of `CoreMainActivity` with bundle options and we have a function in `KiwixReaderFragment` which can open the ZIM file with bundle arguments.  You can move `NewBookDao` from `CoreReaderFragment` to `KiwixMainActivity` since it is mainly used for this function in `CoreReaderFragment`.

https://github.com/kiwix/kiwix-android/blob/3b4f58b229d2b12d27fb16babe9070542185b9de/app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt#L86

**Comment by MohitMaliFtechiz** [comment] 2024-01-29 07:05
Also please make a PR so that we can guide you according to your changes.

**Comment by Sagar0-0** [comment] 2024-01-29 18:24
> @Sagar0-0 You should not move the `openZimFile` function as it is mainly used for opening the ZIM files in `CoreReaderFragment`. You can use the `navigate` function of `CoreMainActivity` with bundle options and we have a function in `KiwixReaderFragment` which can open the ZIM file with bundle arguments. You can move `NewBookDao` from `CoreReaderFragment` to `KiwixMainActivity` since it is mainly used for this function in `CoreReaderFragment`.
> 
> https://github.com/kiwix/kiwix-android/blob/3b4f58b229d2b12d27fb16babe9070542185b9de/app/src/main/java/org/kiwix/kiwixmobile/nav/destination/reader/KiwixReaderFragment.kt#L86
> 
> > After moving this, the related functions/variables used inside of handleNotificationintent method are missing, should I copy them also, as they are also used in other places from CoreReaderFragment.
> 
> Please check the usage of the functions and variables before moving anything, and if you think you need to move this then you can do it we will review your PR and suggest the best. This process will take less time to fix the issues.

Thanks for clarification. I needed to be sure before moving the functions, I will open a PR and we'll discuss there for improvements.

**Closed** 2024-01-30 18:14 UTC
Labels: bug
