### ISSUE TITLE
Ask for confirmation before exiting the app

### ISSUE THREAD

**Issue by anamansari062** [kiwix/kiwix-android#2744] opened 2021-11-29 09:36 UTC
**Is your feature request related to a problem? Please describe.**
If we are pressing back button, the app closes without confirmation.

**Describe the solution you'd like**
The app should ask confirmation like "Are you sure you want to exit?" when back button is clicked.

**Comment by kelson42** [comment] 2021-11-29 09:42
Seems to be a duplicate of #2606.

**Closed by kelson42** 2021-11-29 09:42 UTC
Labels: bug, duplicate, good first issue

**Comment by cdhiraj40** [comment] 2021-11-29 09:45
> Seems to be a duplicate of #2606.

I don't think this is a duplicate of #2606 this seems like a new feature request, unlike the other one

**Comment by kelson42** [comment] 2021-11-29 09:46
I not in favour of confirmation of this kind anyway.

**Comment by gouri-panda** [comment] 2021-11-29 09:50
We don't do any heavy tasks or save input tasks from users. So it's unnecessary.
