### ISSUE TITLE
New content not opening from library.

### ISSUE THREAD

**Issue by arpank10** [kiwix/kiwix-android#410] opened 2018-02-15 18:19 UTC
I have downloaded two contents - Wikipedia Mathematics and Wiktionary.
When I start the app, wiktionary main page is displayed. Then if I open Wikipedia Mathematics, it opens fine. But after that, on trying to open wiktionary again, wikipedia mathematics gets reloaded.

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/24573296/36273439-881378f4-12aa-11e8-87fb-2178bfe8a4f1.gif)

**Would you like to work on it?**
Yes

**Comment by mhutti1** [comment] 2018-02-15 19:16
Duplicate of #236 Feel free to work on that one though.

**Closed by mhutti1** 2018-02-15 19:16 UTC

**Comment by arpank10** [comment] 2018-02-15 19:19
Sure
