### ISSUE TITLE
Search results don't lead anywhere in Stack exchange Zims

### ISSUE THREAD

**Issue by Spikegrant15** [kiwix/kiwix-android#3410] opened 2023-06-11 07:35 UTC
**Describe the bug**
Search function in Stack Exchange Zims brings up accurate article names, but trying to use the links doesn't seem to do anything.

**Expected behavior**
Tapping a search result should bring you to that article

**Steps to reproduce the behavior:**
1. Download any (?) stack exchange Zim. (I have tested both the Role-playing and Chemistry ones)
2. Search for any article
3. Try to access any result given
-->

**Environment**

- Version of Kiwix : Android 3.4.5 Build 7230405
- Device : Motorola Moto G7 Power
- OS version : Android version 10

https://github.com/kiwix/kiwix-android/assets/84546821/48977aef-3920-4cd4-a53c-f45c09f175ca

https://github.com/kiwix/kiwix-android/assets/84546821/26781a4d-1948-4a0b-bb29-b46962697460

**Comment by kelson42** [comment] 2023-06-11 07:47
thanks for the bug report, seems a duplicate of #3094

**Comment by Spikegrant15** [comment] 2023-06-11 07:56
I thought this was a different problem as this is for stack exchange and not wikihow. If it is a duplicate I apologize.

**Comment by MohitMaliFtechiz** [comment] 2023-07-24 13:40
@Spikegrant15, @kelson42, This issue will be fixed after we merged https://github.com/kiwix/kiwix-android/pull/3217.


https://github.com/kiwix/kiwix-android/assets/34593983/d2800e7d-65fa-498d-a777-a017129d1e93

**Closed** 2023-09-18 17:13 UTC
Labels: bug, duplicate
