### ISSUE TITLE
2.4 doesn't seem to be able to read "book"-type articles from Wikimed

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#717] opened 2018-04-17 09:02 UTC
When downloading the last en_wikimed zim files (25.03.2018; I tried with the no images and nodet versions), I get the normal landing page ([this one](https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Medicine/Open_Textbook_of_Medicine2) )
But clicking on any of the links returns a blank page.
The search function works and returns normal articles, so it must have to do with the Book format those pages are in.

I initially thought about an mwoffliner issue, but I've downloaded the zims and opened the pages with kiwix-JS - and had no problem whatsoever.

**Comment by kelson42** [comment] 2018-04-17 09:16
Duplicate of #633

**Closed by kelson42** 2018-04-17 09:16 UTC
Labels: bug, duplicate
