### ISSUE TITLE
Clicking on download notification should launch the app.

### ISSUE THREAD

**Issue by AnjayGoel** [kiwix/kiwix-android#1701] opened 2020-01-19 13:38 UTC
Currently, clicking on download notification does nothing. It would be better if clicking them launches the app.

**Platform:**
Coolpad note 3 lite
Custom ROM (Android 8.1)
App version: 3.1.3

**Comment by kelson42** [comment] 2020-01-19 13:41
Duplicate of #1312

**Closed by kelson42** 2020-01-19 13:41 UTC
