### ISSUE TITLE
Tabular text getting cropped by sideward shifting

### ISSUE THREAD

**Issue by venomousboxer** [kiwix/kiwix-android#506] opened 2018-02-24 16:12 UTC
**Is it a ?**

- [X] Bug Report

- [ ] Feature Request

### Step 1: Are you ready to report ?
   - Your issue may already be reported! Please search on the [issue track](https://github.com/kiwix/kiwix-android/issues) before creating one.
   - [x] I have test with the last (dev) version of the software?  ( If not, and if possible, run your test again with the most recent version available.)

### Step 2 : What is your environment ?
  * browser / app : app
  * version of the software you use : Android studio 3.0.1
  * device / operating system : Xiaomi Redmi 4 / android 7.1.2 N2G47H
  
### Step 3: Describe the problem:

  * Whenever there is any table (Data in tabular form) in the content of page of any encyclopedia
    it is not properly placed on the page and appears shifted leftwards.

  * It occurs whenever the displayed data is in tabular form

#### Steps to reproduce:

  1. Just download any random encyclopedia search for any country 
  (as data about countries usually contains something in tabular form)

  * What should be the behaviour from your point of view? How do you expect the service to work?

  Data should be streached instead of getting cropped by shifting sidewards

**Comment by kelson42** [comment] 2018-02-24 16:13
I do not have the screenthos, but this looks like a content issue, nothing which can be fixed within Kiwix.

**Comment by venomousboxer** [comment] 2018-02-24 16:15
I’ll just send you the screen shots

**Comment by venomousboxer** [comment] 2018-02-24 16:22
Here are some screenshots
![2fd3465d-eef2-41c0-814f-e9eb21e61b21](https://user-images.githubusercontent.com/31950172/36632461-d6eee61c-19ac-11e8-8fcb-ea7349356929.jpg)

![5dcd4b4e-da03-4061-810b-bbf368d6f266](https://user-images.githubusercontent.com/31950172/36632464-ded613dc-19ac-11e8-96e2-2727effbd245.jpg)

**Comment by kelson42** [comment] 2018-02-24 16:24
That confirms what I said. If there is a problem, this is in the HTML itself. So, not a bug with Kiwix...

**Comment by venomousboxer** [comment] 2018-02-24 16:25
Okay

**Comment by iadeelzafar** [comment] 2019-02-26 15:05
This can be closed too @abdulwd

**Closed** 2019-02-26 16:22 UTC
