### ISSUE TITLE
Double ScrollToTop buttons in Reader

### ISSUE THREAD

**Issue by Sagar0-0** [kiwix/kiwix-android#3671] opened 2024-01-15 17:00 UTC
**Describe the bug**

When I was reading, I can see two redundant/same buttons that perform scroll to top operation on clicked.

**Expected behavior**

There should be only 1 button.

**Steps to reproduce the behavior:**
1. Open a zim and go to reader

**Screenshots**

![photo_6138595481576651127_y](https://github.com/kiwix/kiwix-android/assets/85388413/9c94e2b5-d63c-4f57-b72b-115ccd49886d)

**Environment**
- Version of Kiwix Android : 3.9.1
- Device : REALME GT NEO 3T
- OS version : 13

**Logs**

**Comment by MohitMaliFtechiz** [comment] 2024-01-16 12:04
Hi @Sagar0-0 Thanks for opening the issue. This ZIM file has its own "scroll to the top" button that's why these two buttons are showing. Are these buttons showing on other ZIM files as well?

**Comment by MohitMaliFtechiz** [comment] 2024-01-16 13:30
@Sagar0-0, @kelson42 I confirm this is not showing twice on the other ZIM files so it is especially showing on those ZIM files which have their own "Scroll to Top" button.

**Comment by Sagar0-0** [comment] 2024-01-16 17:18
Is it possible, for us to check for the button in the ZIM so that we can prevent ours? I know this is not a big issue to deal with, but still small improvements matters IMO :>

**Comment by satvik2131** [comment] 2024-01-17 11:00
Hi @Sagar0-0 , can I work on this issue , I understand the scenario and I think I can check on it ?

**Comment by Sagar0-0** [comment] 2024-01-17 11:04
Sure you can go ahead if you got the clarity

**Comment by MohitMaliFtechiz** [comment] 2024-01-17 11:23
@satvik2131, @Sagar0-0  all the content is inside the ZIM file in web pages form. The ID of the "Scroll to top" button might be different in other zim files or might be the same for other views in the zim file. So there is not a good way to properly Implement this for every zim file until we don't get clarity about this(hiding our button on behalf of Zim's "Scroll to top" ID). Might be @kelson42 better know about this.

**Comment by satvik2131** [comment] 2024-01-17 11:24
yes @MohitMaliFtechiz  , I agree with you , the issue is device specific I guess because I am unable to see the issue in my device 
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwi74tGlpOSDAxUCzDgGHdTlA38QFnoECBIQAQ&url=https%3A%2F%2Fwiki.openzim.org%2Fwiki%2FZIM_file_format&usg=AOvVaw2aAdbknBIm6cLNaSGkPN-2&opi=89978449

**Comment by MohitMaliFtechiz** [comment] 2024-01-17 11:29
@satvik2131 no it's not the device-specific issue I am also able to reproduce it.

have you enabled the "Back to Top" setting from the settings screen? are you using the Budding Author ZIm file? For now, this zim file has the "Scroll to top" button.

**Comment by satvik2131** [comment] 2024-01-17 11:33
> @satvik2131 no it's not the device-specific issue I am also able to reproduce it.
> 
> 
> 
> have you enabled the "Back to Top" setting from the settings screen? are you using the Budding Author ZIm file? For now, this zim file has the "Scroll to top" button.

Yes got it , able to reproduce now , thanks

**Comment by Sagar0-0** [comment] 2024-01-21 17:26
@satvik2131 did you find any easier way to solve this? If not, then IG we should close this issue as not planned.

**Comment by satvik2131** [comment] 2024-01-23 15:03
@Sagar0-0 yes , we can close it , I didn't find any other way to solve it .

**Closed** 2024-01-23 15:57 UTC
