### ISSUE TITLE
"Get content" launcher icon shortcut is broken

### ISSUE THREAD

**Issue by Fs00** [kiwix/kiwix-android#2728] opened 2021-11-02 21:00 UTC
**Describe the bug**
When tapping on the "Get content" launcher shortcut, no app activity is launched and instead the "App not installed" error toast is shown.
This is because [the shortcut points to an activity](https://github.com/kiwix/kiwix-android/blob/19a70529f481909ff78ab7c879d9c85ceaeed304/app/src/main/res/xml-v25/shortcuts.xml#L24) (`ZimManageActivity`) that doesn't exist anymore.

**Expected behavior**
The app should be opened (I suppose that the shortcut should bring the user to the Downloads section?)

**Steps to reproduce the behavior:**
1. Long press on the app icon in the launcher
2. Click on "Get content" shortcut
3. Observe the "App not installed" error toast

**Environment**
- Version of Kiwix Android: 3.4.5
- Device: any
- OS version: any

**Comment by kelson42** [comment] 2021-11-03 07:24
Bug confirmed!

**Comment by Fs00** [comment] 2021-11-03 07:53
What would be the intended fix for this? Removing the shortcut entirely or making it launch the app directly to Downloads section?

**Comment by gouri-panda** [comment] 2021-11-03 08:27
I'm not sure why we removed it `ZimManageActivity` class  from  [there](https://github.com/kiwix/kiwix-android/pull/2209/commits/567939b52007cad9e85637ae35a140bedece2251).

**Comment by kelson42** [comment] 2021-11-03 08:30
@gouri-panda You mean we have this bug since more than a year!?

**Comment by gouri-panda** [comment] 2021-11-03 08:31
Yes, @kelson42 I'm surprised too.

**Comment by gouri-panda** [comment] 2021-11-03 09:05
@kelson42 It isn't working with 3.4.1. Maybe earlier versions too! Maybe that's why we removed them.

**Comment by kelson42** [comment] 2021-11-03 09:43
Wow, what would the fix strategy? Make the link working? Remove the link?

**Comment by gouri-panda** [comment] 2021-11-03 09:53
We don't have enough options for new shortcuts now. If we wanna keep them then we can revert the appropriate classes and try to fix the bug from there.

**Comment by jhbiggs** [comment] 2021-11-26 16:16
@gouri-panda @kelson42 I would be happy to take out the shortcut or send it over to the main activity and send a commit.

**Comment by kelson42** [comment] 2021-11-26 16:49
@jhbiggs Great!

**Comment by kelson42** [comment] 2021-11-29 09:20
Shorcut has been introduced by @abdulwd with https://github.com/kiwix/kiwix-android/issues/688

**Comment by tom635** [comment] 2021-12-13 07:01
@kelson42 how can I contribute to this issue

**Comment by kelson42** [comment] 2021-12-13 07:09
@jhbiggs works already on it, right?

**Comment by tom635** [comment] 2021-12-13 08:36
@kelson42 could you assign me an issue on which I can contribute.

**Comment by kelson42** [comment] 2021-12-13 08:38
@Fs00 You have to pick one yourself (which is not already assigned), please read https://kiwix.org/code

**Comment by AayushSolanki** [comment] 2021-12-16 05:37
Is the issue resolved or not?

**Comment by cdhiraj40** [comment] 2021-12-16 06:55
> Is the issue resolved or not?

hey, @AayushSolanki it's not resolved yet, but @jhbiggs is already assigned and has made PR. I guess let's wait for some more days till then you can take some other issue that is not assigned yet :)

**Comment by kelson42** [comment] 2022-01-03 20:50
Fixed with #2743

**Closed by kelson42** 2022-01-03 20:50 UTC
Labels: bug, good first issue
