### ISSUE TITLE
Unable to open ZIM files that Kiwix for Android did not download.

### ISSUE THREAD

**Issue by virtadpt** [kiwix/kiwix-android#2592] opened 2021-02-08 01:10 UTC
**Describe the bug**
BLUF: It seems like it should be possible for Kiwix for Android to open .zim files that it did not download.  It can't.

Background: I live in a very bandwidth contstrained location; it is feasible for me to use Kiwix to download smaller .zim files (e.g., InstallGentoo Wiki - 2019-09-18 - 9MB) but not to download larger ones (wikipedia_en_all_maxi_2020-12.zim - 73.9 GB).  So, my workaround is to take a flash drive to work, plug it into my machine there, and have it download .zim files with wget.  Then the next time I'm in the area I pick up the flash drive, plug it into my laptop, plug my phone or tablet's microSD card into my laptop, and copy the .zim file over.

The thing is, this doesn't actually work.  Only files that Kiwix for Android has downloaded are in the Kiwix Library.

If I use my file manager to open the .zim file (Open With -> Kiwix) the Kiwix app open and very briefly the "loading" indicator shows at the top, but the .zim file is not added to the Library.

On all of my devices I have Kiwix configured to use my phone's microSD card as its source of truth (sandwich menu -> Settings -> Storage -> External).

**Expected behavior**
If a new .zim file is in the storage location Kiwix is configured for: By opening the Kiwix app's Library screen the new .zim file should be present and I should be able to open and read through or search it just like .zim files that Kiwix downloaded on its own.

If a new .zim file has been copied onto the storage location Kiwix is configured for: I should be able to open the file's "do stuf" menu, tap on "Open with", select Kiwix, and Kiwix should add that file to its Library screen and let me read through or search it.

**Steps to reproduce the behavior:**
1. Download a .zim file, but not with Kiwix.  Use a web browser, or copy a .zim file onto the Android device's storage somehow (say, by copying the file with a file manager)
2. Open Kiwix
3. Tap the Library icon
4. The .zim file is not present

Alternatively, trying to open the file with "Open with"
1. Download a .zim file, but not with Kiwix.  Use a web browser, or copy a .zim file onto the Android device's storage somehow (say, by copying the file with a file manager)
2. Open the Android device's file manager.
3. Navigate to where the new .zim file is stored (on my devices, that is my phone's microSD card -> Android -> Data -> org.kiwix.kiwixmobile -> Files -> Kiwix)
4. Tap on the "do stuff with this file" menu icon for the file (for me it's a kebab menu icon)
5. "Open with"
6. Select Kiwix
7. The .zim fie does not open.  The .zim file is also not in the Library.

**Screenshots**
Can supply screenshots upon request.

**Environment**
- Version of Kiwix Android : v3.4.3 build 623403 from the Google Play store on both devices
- Device : 
    - Samsung SM-G965U phone
    - Samsung SM-T290 tablet
- OS version : Both are running Android 10, unmodified

**Logs**
* Phone: https://drive.google.com/file/d/1umINHzLqnYJwWGFbjT-P2DH1BmehB48J/view?usp=sharing
* Tablet: https://drive.google.com/file/d/1YaJRE4gjD64iSNtzqSflIk_TVdSR8ciC/view?usp=sharing

**Comment by shambu2k** [comment] 2021-02-08 06:55
Seems like a duplicate of #1447. I also see an existing draft PR for this issue #2548.
Can anyone else confirm?

**Comment by kelson42** [comment] 2021-02-10 09:54
@virtadpt Thank you very much for your quality bug report. This should indeed just work. We have a detection system which is definitly buggy and fails to detect your SD card I guess. @mhutti1 You had worked on this and @BBT-SeanMacGillicuddy had afterward incorporated/modified your code. Do you see here what is going wrong?

**Comment by mhutti1** [comment] 2021-02-17 20:20
I think the not opening with the library is an issue I have seen on my Samsung device, the way the file is passed into Kiwix is not being handled correctly. It's tricky becuase each device maker often has their own file browser with its own way of passing files. I havn't looked at Android file search in  a while but when I did the main issue was again it is up to device manufactures and often there is no way to know where sd cardsare mounted.

**Comment by kelson42** [comment] 2021-02-21 08:24
@mhutti1 What I don’t understand is that this is the same kind of explanation that I heard from you 4-5 years ago. Many tickets have been closed meanwhile, jus an example about a recent one https://github.com/kiwix/kiwix-android/issues/2354.

**Comment by kelson42** [comment] 2021-02-26 16:26
@mhutti1 I have a few questions which I believe their answers would help to bring clarity and fix the bug:
* This tickets reports two different bugs (1) the new ZIM file is not automatically detected in the Kiwix local library (2) The user can not open from the "file browser". The real problem I want to treat is that the (1), one time fixed we could look like to (2).
* What is the current approach to detect automatically new content in the local library? I believe it would be good to create a wiki page just for this and briefly explain the approach and its weaknesses.
* Does the diagnostic - uploaded by @virtadpt and created via Kiwix - allows us to know the mouting point of the SD cards and why Kiwix fails to identify the new content?
* Since a few versions, we have revamped the SD card detection algorithm which is used in the settings to populate the Settings Storage list of devices. My experience is that this feature works fine now. Do we know if the SD card detection has worked fine there (from the diagnostic)? Are somehow two things related? If the SD card detection works fine, why not just ask to scan the SD card if there is one?

**Comment by virtadpt** [comment] 2021-02-26 19:22
@kelson42 
- Yeah, I was wondering about that... what does having no File -> Open menu have to do with an Android misfeature?
- How about adding a File -> Open menu so we can select ones that Kiwix doesn't already know about?  Kiwix is great for making wikis available offline, but it's missing the "download files so they can be added offline" use case.
- When reading through the diagnostic dump I sent, I saw some stuff about "zim files in the database" but nothing about "zim files not in the database."  I spent some time poking around looking for said SQLite database so I could add the file manually, but didn't find it.
- It worked fine, because it located the .zim archives that I was able to download through Kiwix (by browsing the Kiwix library) but not the ones that I downloaded some other way.  It doesn't, for example, detect any .zim files that I download with Firefox on my phone or tablet (that I move into the Kiwix .zip library directory) that are small enough for me to grab in an hour or less at home.

**Comment by mhutti1** [comment] 2021-02-28 00:22
- We do have a file open menu for some apps, its not an easy thing to do for everything as you have to tell apps that you support opening certain file types but different apps want you to tell them in different ways. It is a constant battle to update what we tell apps we can open as they for no apparent reason change how they want us to tell them.
- I can have a look into creating a wiki on what we currently do.
- We can try scan the SD card but as I said we might not find the sd cards root directory correctly. If we can't find that we have issues. This also is device specific.

**Comment by shapeshifter910** [comment] 2021-03-01 18:24
So what's the point of having the download from our repository link in your FAQ. Because anybody that downloads files that way will not be able to use them in Kiwix.
The whole point of this app is to have wiki files and being able to open them on various devices OFFLINE.
Your app has it's core functionality BROKEN!
It's relatively easy to use a tablet of phone when being offgrid and recharging them using solar panels or power banks unlike using laptops which need Inverter to recharge.
And trying to get me to download 80GB over wifi to my tablet is no a good idea.
So if you truly want to provide an offline wikipedia for people, the android and ios apps are far more important than the computer applications.
You should find some qualified android developers. There are some out there for sure because I have some quality apps on my android tablet that have no problems with anything at all - external storage or internal, doesn't matter, open anything from anywhere.

**Comment by virtadpt** [comment] 2021-03-01 19:23
@shapeshifter910 This.  So much this.  I'm pretty much at the point of building a PiPhone to run Kiwix Desktop because I can open open .zim files that I download at home (the tiny ones).

**Comment by mhutti1** [comment] 2021-03-07 18:41
I understand the frustration. We are 100% volunteers working on the Android app at the moment. I assure you it does work on some devices but device manufacturers keep changing their file browser specs underneath us so we have to be constantly playing catchup. 

The underlying issue is that ZIM files don't have a mimetype we can query for. This is what allows other apps to open word documents etc and it is trivial for apps to open these types of file as you elude. Unfortunately without an identifiable mimetype it is much much harder.

**Comment by mhutti1** [comment] 2021-03-07 18:53
The issue is the code here: https://github.com/kiwix/kiwix-android/blob/develop/app/src/main/AndroidManifest.xml#L46 I have spent many hours trying various additional path configurations but none work with for example the samasung file browser. We are telling the browser we accept the file. It is not listening though...

**Comment by mhutti1** [comment] 2021-03-07 19:07
https://github.com/kiwix/kiwix-android/wiki/Finding-Files-In-Android

**Comment by Moranic** [comment] 2021-04-25 22:06
I'm currently facing this same issue. Externally downloaded zim files simply do not show on my Oneplus 9. Your link mentions a deprecated method of loading .zim files by path; perhaps that could be reïntroduced as a workaround?

**Comment by R2RT** [comment] 2021-05-24 10:13
Sorry about not full report, but I am currently in travel. Anyway, I think there is an issue with extension recognition for files with dots in their names. E.g. bicycles.stackexchange.com_en_all_2021-04.zim could not be found either on internal nor external storage. I've renamed it into bicyclesstackexchangecom_en_all_2021-04.zim and it was finally found.

Samsung Galaxy A71, SM-A715/DS, Android 11, One UI 3.1

**Comment by kelson42** [comment] 2021-05-24 11:07
I believe the last comment explains clearly what is the problem?!

**Comment by gouri-panda** [comment] 2021-05-24 11:12
>I'm currently facing this same issue. Externally downloaded zim files simply do not show on my Oneplus 9. Your link mentions a deprecated method of loading .zim files by path; perhaps that could be reïntroduced as a workaround?

@Moranic Is there any chance your phone running on Android 11? because android changes the android's file setting on android 11.

**Comment by Moranic** [comment] 2021-05-24 11:24
Yes, OP9 ships with Android 11. Then perhaps that is my issue.

**Comment by ElectroXexual** [comment] 2021-06-03 05:56
Why not implement your own file picker so you won't have to rely on how samsung file browser or any other file managers work? Just add a button in library that opens file browser where you pick a zim file. If you pick a wrong file type that's on you, no need to bother with mimetype either.

**Comment by shapeshifter910** [comment] 2021-06-03 07:56
> Why not implement your own file picker so you won't have to rely on how samsung file browser or any other file managers works? Just add a button in library that opens file browser where you pick a zim file. If you pick a wrong file type that's on you, no need to bother with mimetype either.

I think I know. For the same reason they expect people to download a 90GB file to a phone. They are clueless.
Certainly have no clue how to code and how software and hardware works.

**Comment by virtadpt** [comment] 2021-06-03 20:25
> Why not implement your own file picker so you won't have to rely on how samsung file browser or any other file managers works? Just add a button in library that opens file browser where you pick a zim file. If you pick a wrong file type that's on you, no need to bother with mimetype either.

There is no shortage of open source file managers for Android that could be examined to see how they did it.

**Comment by virtadpt** [comment] 2021-06-03 20:26
> I think I know. For the same reason they expect people to download a 90GB file to a phone. They are clueless.

In some respects, you are correct.  The whole point of Kiwix is to make Wikipedia (all 90-some gigabytes of it) available in areas where accessing Wikipedia or downloading a mirror of it are infeasible or just not possible.  That this very use case isn't attainable unless one can get their phone to reliably download a mirror of Wikipedia is just... b0rken.  So broken it breaks the word 'broken'.

**Comment by virtadpt** [comment] 2021-06-03 20:29
? https://github.com/zhanghai/MaterialFiles/blob/master/app/src/main/java/me/zhanghai/android/files/filelist/OpenFileActivity.kt

**Comment by virtadpt** [comment] 2021-06-03 20:31
? https://developer.android.com/guide/topics/providers/document-provider

**Comment by mhutti1** [comment] 2021-06-05 20:03
We can't use the storage access framework as we need to get a native file descriptor and last time I checked it won't provide one unfortunately. We  have some work that might let us work around this but it is not ready yet.

**Comment by mhutti1** [comment] 2021-06-05 20:04
> > Why not implement your own file picker so you won't have to rely on how samsung file browser or any other file managers works? Just add a button in library that opens file browser where you pick a zim file. If you pick a wrong file type that's on you, no need to bother with mimetype either.
> 
> I think I know. For the same reason they expect people to download a 90GB file to a phone. They are clueless.
> Certainly have no clue how to code and how software and hardware works.

At the moment all the developers on the Android project are volunteers, with limited time. This is an open source project so if you feel you understand a solution please make the pull request with the fix.

**Comment by l-one1** [comment] 2021-07-16 20:59
Just found this thread off Reddit.  Can confirm issue happens to me with the following data:

Kiwix 3.4.4 Build: 6230404 on Android 11, Kernel 4.14.113, June 1 2021 security patch level / Samsung Galaxy XCover Pro SM-G715U1.

My experience with this bug:

After having my download fail for the ~82GB Wikipedia Maxi file I downloaded it on my computer with Bittorrent instead.  I found the directory the other ZIM files are stored on my MicroSD card (android/data/org.kiwix.kiwixmobile/files/kiwix) and copied the main Wikipedia ZIM file there (wikipedia_en_all_maxi_2021-03.zim).

Kiwix fails to see the new ZIM file.

I can open Kiwix and go to 'Library' and see the other ZIMs I downloaded through the Kiwix app download section.  I also can swipe down (while in 'Library') and see about 5 seconds of the circling icon indicating it is trying to refresh the library - but main Wikipedia won't show up.  Storage location is set to 'External'.

...

Also, regarding R2RT's comment:
> Sorry about not full report, but I am currently in travel. Anyway, I think there is an issue with extension recognition for files with dots in their names. E.g. bicycles.stackexchange.com_en_all_2021-04.zim could not be found either on internal nor external storage. I've renamed it into bicyclesstackexchangecom_en_all_2021-04.zim and it was finally found.

Given the file I am working with (wikipedia_en_all_maxi_2021-03.zim) has no dots in the filename this does not appear to be the cause, at least in how the bug presents in my case.

**Comment by kevinmcmurtrie** [comment] 2021-10-14 18:14
Same problem with 3.4.5 beta on a new Android 11 phone.  I set external storage, downloaded a tiny zimfile in Kiwix, then added my big zimfiles in the same directory as the Kiwix download.  The app brings up a spinner for a long time in the library view but it can't see anything other than its own download.
I see other apps completely avoiding app storage for microSD cards because Google's API file is so utterly slow and broken.  (And then they're moving out of Play Store so that ability isn't lost in Android 12)

**Comment by kelson42** [comment] 2021-10-15 06:40
Yes, the problem is still there. I really do my best so we can fix this (or at least improve the situation) in the version 3.4.6.

**Comment by Ryonez** [comment] 2021-12-25 11:50
I'm really regretting deleting my old wiki zim to replace it with the update.
I've copied an 89 GB file twice and it refuses to see the file next to the other 2 it can see. I had a look at downloading it on the app, and it's guessing it'll take 17 hours. That's almost 8 times longer than it takes me to copy it from my computer over wifi. And the app has to be active for the download to continue. If it's in the background to long, it stops.

Using 3.4.5 7230405

**Comment by kelson42** [comment] 2021-12-25 12:58
@Ryonez Does latest development version solves your problem? http://download.kiwix.org/nightly/2021-12-25/

**Comment by mcmordie** [comment] 2021-12-27 22:07
@kelson42  Had the same issue and your 12-25 nightly build worked for me.  Do you have a non-debug version?

**Comment by kelson42** [comment] 2021-12-28 06:35
@mcmordie soon

**Comment by Moosss88** [comment] 2022-01-08 23:24
I know the answer is not that good but 
I tried many things 
What worked for me is to download the old version 
kiwix-2-5-3.apk
From other site but you have to delete the not working one first then click on the left 3 dots then the + downthere then you will see your file

**Comment by mbe57** [comment] 2022-02-28 11:13
2.5.3 does not help on my Huawei M5 tablet - Android 9.
And 3.4.5 sucks, too.
There is a busy icon circling for hours, but not finding 3 HUUUGE ZIMs in /extSD/Kiwix. 
I have sent error reports via Kiwix App.

**Comment by LookinR** [comment] 2022-04-05 21:47
I have the same problem with Kiwix on my Xiaomi Redmi 9 with Android 11, MIUI 12.5.4 - this is really very unpleasant bug, because the list of downloable zim files for my native language (czech) is very short, also for my purposes are many files missing (i. e. JavaDoc) or outdated. This makes Kiwix useful only for offline Wikipedia...

I downloaded my own zim file on SD card and also copied it on internal memory in different locations. On Library page rotates the "loading symbol" for very long time, but my zim file is never found. Filemanager gives no option to open zim file in Kiwix, so I tried to open it directly in AirDroid application. Kiwix opens last shown page, but nothing is done with new zim file. There is also no accessible "Kiwix" folder neither on internal memory, nor sd card, as was found on some web pages...

I found only this nasty workaround:
1. Install some random zim file with "Download page" in Kiwix, which zou don't want to read.
2. Connect your phone with USB cable in developer mode to computer.
3. Open folder "SD card"/data/Android/data/org.kiwix.kiwixmobile/files/Kiwix (it maybe works also with internal storage, I have in my setting external storage as default)
4. You find there your downloaded random zim file. Copy its name to clipboard and delete it.
5. Copy our own zim file and name it after deleted one (you have the name in clipboard).
6. et voilà - you have in your Library still old name, but at least you can open it and there are new data from your zim file...

**Comment by virtadpt** [comment] 2022-04-09 19:02
I just gave the latest version a try on my tablet, using a copy of the 2021-03 .ZIM file of Wikipedia, and it seems to work now.  I was able to run a few searches and read wiki articles normally.

**Comment by mhjackson123** [comment] 2022-04-21 22:18
I have tried many ways to get the 90GB full wikipedia file onto my S22Ultra with no success. I tried the renaming trick suggested above with no luck. I was able to share the file via the app from a phone running Android 9 but it did not show up... I will keep trying but there must be a way to get Kiwix Android to find files stored on the phone...

**Comment by Jaifroid** [comment] 2022-04-22 14:15
OK, I see #2800 might fix this. I'll be happy to test a nightly on my Android once merged.

**Comment by Jaifroid** [comment] 2022-04-28 15:18
@LTVA1 It looks like a fix is in #2800, but that PR hasn't been merged yet, so nightly will still have the old File Access code. (I'm only a user of this app, not a developer of it, so I don't have any special insight here.)

**Comment by LTVA1** [comment] 2022-04-28 15:43
Upd3: after several reloads this long pagevloading diappears and all works perfect!

Although it is still nightly build, so I look forward to seeing at least this way to load custom zim files in play market app version.

**Comment by LTVA1** [comment] 2022-04-28 17:00
Search doesn't work — it gives the results, but when I tap any of them it just reloads current page

**Closed** 2022-04-29 18:04 UTC
Labels: bug

**Comment by bartash** [comment] 2022-05-08 17:42
Just got a new phone and added a .zim of wikipedia on an sd card, but can't get kiwix to use it
Do we need to wait for a new android release to get the bug fix?

**Comment by Llantha** [comment] 2022-08-19 15:52
I downgraded to kiwix 2.1.
https://m.apkpure.com/kiwix-offline/org.kiwix.kiwixmobile/download/45-APK (pick the right one)
I manually put the files in <my computer's name>\<my pixel 6 pro's name>\Internal shared storage\Android\data\org.kiwix.kiwixmobile\files\Kiwix
Profit.

**Comment by traverseda** [comment] 2022-09-23 15:45
I can confirm that this doesn't work with my samsung galaxy note 10 and kiwix 3.4.5, which is very unfortunate as we're about to be hit by a large storm in Nova Scotia and I may be without power for a week plus if things go really poorly.

**Comment by erayd** [comment] 2022-09-23 22:58
@traverseda The version you are using is out of date. v3.5.0 and v3.6.0 both work fine.

Note that you'll need to fetch it from f-droid or directly from the kiwix website. The version in the play store hasn't been updated for about a year.

**Comment by traverseda** [comment] 2022-09-24 17:00
Noted, thanks!

**Comment by zackmentz** [comment] 2023-02-11 21:49
> @traverseda The version you are using is out of date. v3.5.0 and v3.6.0 both work fine.
> 
> Note that you'll need to fetch it from f-droid or directly from the kiwix website. The version in the play store hasn't been updated for about a year.

THIS RIGHT HERE SOLVED MY ISSUE -- THE GOOGLE PLAY'S STORE APP IS OUTDATED WHILE THE KIWIX WEBSITE LATEST VERSION FINDS THE ZIMS NO PROBLEM.  I just created this account to comment this.  Kudos for saving me a ton of time!

**Comment by Ryonez** [comment] 2023-02-11 22:05
> @traverseda The version you are using is out of date. v3.5.0 and v3.6.0 both work fine.
> 
> Note that you'll need to fetch it from f-droid or directly from the kiwix website. The version in the play store hasn't been updated for about a year.

f-droid isn't being updated either...

**Comment by SuperUserNameMan** [comment] 2023-03-10 09:25
glad to know it is fixed on v3.5 and v3.6, unfortunately none of them want to install on my Android 4.1.2 tablet :-(

**Comment by kelson42** [comment] 2023-03-10 09:27
@SuperUserNameMan Please open a new tickets with all the details. Without details we won't be able to help you much

**Comment by Jaifroid** [comment] 2023-03-10 13:04
@SuperUserNameMan If you're installing from sources other than the Play Store, you may need to change a setting on your Android device. Under Settings search for something like "Install unknown apps".

**Comment by SuperUserNameMan** [comment] 2023-03-10 16:46
> @SuperUserNameMan If you're installing from sources other than the Play Store, you may need to change a setting on your Android device. Under Settings search for something like "Install unknown apps".

This setting was already enabled. 
Kiwix 3.2.1 is the most recent that can install.
I opened a ticket (#3259), and @kelson42  replied my android version is no more supported ... :-(

Sad, because it could be a smart way to recycle some old devices.

**Comment by SuperUserNameMan** [comment] 2023-03-10 17:36
@Jaifroid : it works ! thank you !  You've just extended the life of a 10 year old outdated slug with broken glass and cracked paint !

It can't run better than Firefox 68.8.0 on it, but it is enough to install and run your PWA as an App, download ZIM from web and open the ZIM files already present on the sdcard.

Note to whoever encounter this issue : when you click on the browse button to select the ZIM, if the popup dialog does not let you open a file browser to select the ZIM, you might want to install an other file-browser (like "OI File Manager") and try again (its icon should appear into the popup dialog box and let you pick the ZIM wherever it is on your sdcard)

Thanks again @Jaifroid !

**Comment by Jaifroid** [comment] 2023-03-10 17:46
@SuperUserNameMan The only issue with using Firefox is that, at least on a modern Android, it has a bug whereby it loads the whole ZIM file into memory. While this works with smaller ZIMs, it is not much good with a large ZIM, as the memory fills up and it can crash. However, older Firefox may not have this issue, in which case you're good to go. For a more app-like feel on Firefox, you can try setting the app to Full Screen (setting in Configuration).

**Comment by lfreidin** [comment] 2023-04-30 11:20
On my Samsung Galaxy S23+ only version 3.5 works normally with manually copied file. Neither 3.4.5 from Google Play can download files but does not open files copied manully, version 3.6 from kiwix.org can't open any files, because can't obtain storage permissions.

**Comment by Jaifroid** [comment] 2023-04-30 11:29
@lfreidin Due to tightening of restrictions for file access, you need to use the version in the F-Droid store, not the Play Store. That means enabling ability to load apps from other sources in your phone.

**Comment by erayd** [comment] 2023-05-01 10:57
> Neither 3.4.5 from Google Play can download files but does not open files copied manully...

v3.4.5 is very out-of-date, and predates the fix that addressed this issue.

> ...version 3.6 from kiwix.org can't open any files, because can't obtain storage permissions.

This is incorrect. v3.6 from kiwix.org can open files just fine. If you are experiencing permissions problems, it's likely that the necessary permission was requested and denied at some point, or the permission was removed for non-use (Samsung's flavour of Android does this).

**Comment by TomNCatz** [comment] 2023-08-24 16:54
Is there a reason the app hasn't been updated on the play store for two years at this point? That seems like a long time for it to be the difference between a bleeding edge version and an LTS version. Not to mention that 3.4.5 to 3.6.0 is a large version gap.

**Comment by Jaifroid** [comment] 2023-08-24 17:04
> Is there a reason the app hasn't been updated on the play store for two years at this point? That seems like a long time for it to be the difference between a bleeding edge version and an LTS version. Not to mention that 3.4.5 to 3.6.0 is a large version gap.

Google blocked the latest version due to it using the MANAGE_EXTERNAL_STORAGE api which is now banned. Something similar happened with F-Droid, though not exactly the same issue. A new version is nearly ready that should overcome these issues, though at the cost of not being able to pick archives from shared folders in the Play Store version. Current recommendation is to sideload the APK direct from Kiwix.org for the full functionality of the app.

**Comment by TomNCatz** [comment] 2023-08-24 17:37
This app probably doesn't need MANAGE_EXTERNAL_STORAGE does it?  READ_EXTERNAL_STORAGE should cover most of it's needs and if not there is the storage access framework. I guess I haven't looked at the code so maybe there is a use case I'm not thinking of.

**Comment by virtadpt** [comment] 2023-08-24 17:42
MANAGE_EXTERNAL_STORAGE might be necessary for the "use Kiwix to download the .zim files" functionality.  READ_EXTERNAL_STORAGE would be needed for actually opening and using the .zim files.

**Comment by progtw** [comment] 2023-10-22 18:25
I am late to this thread, but had the same problem and additional solution hint. 
After reading this thread, I installed Kiwix 3.7 apk directly from kiwix.org. 

In addition, I needed to go "Hamburger menu/Einstellungen/Berechtigungen" (probably "Settings/Rights" in English) and allow "Zulassen, dass ZIM-Dateien auf der SD-Karte gelesen und geschrieben werden" bevor I could add other ZIMs to the library.

**Comment by kelson42** [comment] 2023-10-22 18:42
We will release `3.8.0`, feel free to check the latest nightly and share feedbacks https://download.kiwix.org/nightly/

**Comment by madunist** [comment] 2025-04-28 15:37
Hello, I wanted to share this method in the hope that maybe it can help someone having same issue. I just downloaded the "es file manager" and choose the zim file. I received the attached warning and app can now see the kiwix zim file. Enjoy. 

![Image](https://github.com/user-attachments/assets/9146516d-9699-4977-8d63-b1dc515739a4)
