### ISSUE TITLE
Icon of custom zim file is not shown in the app

### ISSUE THREAD

**Issue by LTVA1** [kiwix/kiwix-android#2811] opened 2022-04-29 13:37 UTC
**Describe the bug**
I made a zim file with zimwriterfs on Windows 10. When I open the kiwix desktop app and navigate to my zim file (1.9 gb), it displays its icon. However, when I put zim file to root directory of my xiaomi mi note 8 pro (Android 11, MIUI 12) and use android app nightly build from 28.04.2022, it shows up in the list without the icon.

**Expected behavior**
Obviously, I expected the icon to be displayed, since it is 48x48 .png (no transparency) file.

**Steps to reproduce the behavior:**
1. Create .zim file with the command ```docker run --mount type=bind,source=C:/Users/%User%/Desktop/site,target=/home/docker/zimwriterfs/data openzim/zim-tools zimwriterfs -w index.html -I icon.png -l rus -t "Фонд SCP" -d "Русскоязычный сайт коллективного литературного творчества" -c "SCP Foundation" -p "LTVA" //home/docker/zimwriterfs/data/test //home/docker/zimwriterfs/data/scp-wiki-ru-05-2022-maxi.zim -x -i``` using Docker desktop on Windows 10. Make sure you included some visible icon and have some pages with external links in your root html folder.
2. Check if zim file works correctly and displays the icon in kiwix desktop app.
3. Use nightly build mentioned above to open the zim file you previously put into root directory of your smartphone internal storage. You should see no icon.

**Environment**
- Version of Kiwix Android : nightly build 28.04.2022.
- Device : xiaomi mi note 8 pro
- OS version : Android 11, MIUI 12

**Comment by LTVA1** [comment] 2022-04-29 13:44
P.S. I tried to manually move one of the zim files downloaded by kiwix (iirc some Wikipedia articles selection) into root folder and it successfully displays the icon.

**Comment by kelson42** [comment] 2022-06-21 18:51
@LTVA1 Do you see the icon in kiwix-serve? Are you able to share your ZIM file somewhere so we can check it? I suspect `icon.png` is not at the root of `C:/Users/%User%/Desktop/site`.

**Comment by kelson42** [comment] 2022-08-26 05:00
@MohitMaliFtechiz Pretty sure this will be fixed automatically when you will use latest version of libkiwix.

**Comment by kelson42** [comment] 2022-09-28 07:34
Pretty much a duplicate of #2772 IMO. @LTVA1 Please check with nightly if your bug is fixed https://download.kiwix.org/nightly/ and reopen the ticket please if not.

**Closed by kelson42** 2022-09-28 07:34 UTC
Labels: bug, question, UI
