### ISSUE TITLE
Replace exit full screen icon with material design icon

### ISSUE THREAD

**Issue by pprathameshmore** [kiwix/kiwix-android#407] opened 2018-02-15 16:33 UTC
I am replacing exit full screen icon with new material design icon from Google.

![ic_fullscreen_exit_black_24dp](https://user-images.githubusercontent.com/17108186/36268223-fd833ffc-129b-11e8-8d9c-66972c03d8dd.png)

**Comment by pprathameshmore** [comment] 2018-02-15 16:33
I am working on this.

**Comment by pprathameshmore** [comment] 2018-02-15 16:36
@kelson42 Please help me!
I am added this feature. But I don't how to commit to main repo.
Should I create new branch or commit to master?

**Comment by pprathameshmore** [comment] 2018-02-15 16:37
![repo](https://user-images.githubusercontent.com/17108186/36268483-9b9f2d68-129c-11e8-9414-84ebf15e6d0f.JPG)

**Comment by srv-twry** [comment] 2018-02-15 17:35
@pprathameshmore Please create a new branch and open the PR to the master. 

Side note: I would suggest learning some version control specially using the terminal/command line. 
[Here](https://www.youtube.com/watch?v=xAAmje1H9YM&list=PLeo1K3hjS3usJuxZZUBdjAcilgfQHkRzW) is good lecture series that i would recommend for learning git although you can learn from other sources also.

**Comment by srv-twry** [comment] 2018-02-15 17:38
@pprathameshmore Another advise. I think you've created a duplicate issue. This is already being done in #403 . You were told by the issue creator that he is already working on it but still you have created this issue which is not recommended to do. Please close this and avoid doing it in the future.

**Comment by mhutti1** [comment] 2018-02-15 18:50
Duplicate of #403

**Closed by mhutti1** 2018-02-15 18:50 UTC
