### ISSUE TITLE
Crash after update to 2.3

### ISSUE THREAD

**Issue by Popolechien** [kiwix/kiwix-android#286] opened 2017-11-13 07:38 UTC
From the OTRS feedback queue
"The search function does not work anymore - it wouldn't show any article.
 
I have these two files, both on external SD card:
wikipedia_de_all_nopic_2016-08.zimaa
wikipedia_de_all_nopic_2016-08.zimab
 
here's my configuration:
 
Internal 6,1 GB / 11 GB
External 24,9 GB / 29,8 GB
/ „empty no text“
 
The last line with „/“ is empty."

**Comment by mhutti1** [comment] 2017-11-13 18:28
Duplicate of #240

**Closed by mhutti1** 2017-11-13 18:28 UTC
Labels: bug
