### ISSUE TITLE
CrashReport 3.3.1: java.lang.NullPointerException FileUtils.contentQuery

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-android#2104] opened 2020-05-21 15:48 UTC
```
Caused by: java.lang.NullPointerException: 

 
  at android.os.Parcel.createException (Parcel.java:1956)

 
  at android.os.Parcel.readException (Parcel.java:1918)

 
  at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:183)

 
  at android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:135)

 
  at android.content.ContentProviderProxy.query (ContentProviderProxy.java:418)

 
  at android.content.ContentResolver.query (ContentResolver.java:809)

 
  at android.content.ContentResolver.query (ContentResolver.java:758)

 
  at android.content.ContentResolver.query (ContentResolver.java:716)

 
  at org.kiwix.kiwixmobile.core.utils.files.FileUtils.contentQuery (FileUtils.java:141)

 
  at org.kiwix.kiwixmobile.core.utils.files.FileUtils.getLocalFilePathByUri (FileUtils.java:114)

 
  at org.kiwix.kiwixmobile.main.KiwixMainActivity.manageExternalLaunchAndRestoringViewState (KiwixMainActivity.java:73)

 
  at org.kiwix.kiwixmobile.main.KiwixMainActivity.onCreate (KiwixMainActivity.java:54)
```

**Comment by s-ayush2903** [comment] 2020-06-18 22:45
@macgills Can you please mention reproducing the crash?

**Comment by macgills** [comment] 2020-06-19 14:09
@s-ayush2903 this is taken from a crash report on the google play console, this is about all the information we have

**Comment by s-ayush2903** [comment] 2020-06-19 14:37
Sir, don't we have the device information like buildVersion or stuff like that on which the crash took place?
If we get that, it may prove somewhat useful in making the simulations and hence trace the crash

**Comment by macgills** [comment] 2020-06-19 14:50
`3.3.1` is the version this crash happened on, there is a tag on git. I don't have easy access to the original report anymore, google's UI has made it somewhat unfindable

`FileUtils.contentQuery (FileUtils.java:141)`

We have a line number in our codebase, that is plenty to at least slap a bandaid on this

**Comment by kelson42** [comment] 2020-07-11 13:48
@macgills Do we have any hints that this bug still occur with 3.3.3?

**Comment by macgills** [comment] 2020-07-13 08:30
No report yet

**Comment by kelson42** [comment] 2020-07-13 08:52
I propose to close it.

I really believe we should treat seriously the crash reports but:
* With borken ZIM files around these last months... I'm afraid of investigating time for nothing
* We need to have the handling to deliver the information necessary for a proper treatment.

IMO we should focus on https://github.com/kiwix/kiwix-android/issues/62, close that one and reopen it if it happens again.

**Comment by macgills** [comment] 2020-07-13 09:27
This is more an issue of stopping the app crashing with opening a zim file from some external location, that is the code path here, no JNI at all

**Comment by kelson42** [comment] 2020-07-13 09:32
@macgills OK, yes I got confused.

**Comment by julianharty** [comment] 2020-07-13 14:52
Here are a couple of screenshots of the error as reported in Google Play Console:
![Screen Shot 2020-07-13 at 15 50 54](https://user-images.githubusercontent.com/785891/87318836-c56b7280-c520-11ea-85d5-c7ecca1b9a9e.png)
![Screen Shot 2020-07-13 at 15 51 10](https://user-images.githubusercontent.com/785891/87318856-cc928080-c520-11ea-89f9-c4d8b69f798b.png)

@macgills Here's the link to the crash cluster https://play.google.com/apps/publish/?account=9116215767541857492#AndroidMetricsErrorsPlace:p=org.kiwix.kiwixmobile&appid=4975184706939091905&appVersion&lastReportedRange=LAST_60_DAYS&clusterName=apps/org.kiwix.kiwixmobile/clusters/63b3eb0c&detailsAppVersion (at least it works for me at the moment...) I hope it's useful.

**Comment by julianharty** [comment] 2020-07-13 14:59
@s-ayush2903 As the screenshots show:

- The crash happens on at least Android 9 and Android 10, it happens in various versions of our app, so it's probably an old bug.

Version|Count|Percent
-- | -- | --
53 |	78|51.7%
182160|45|29.8%
1182160|10|6.6%
6220501|10|6.6%
45|4|2.6%
6220502|3|2.0%
5220501|1|0.7%

- It's happening on various device models.


Liquid S1 (a10) | 22 | 14.6%
-- | -- | --
Galaxy A40 (a40) | 16 | 10.6%
CAMON 12 Air (TECNO-CC6) | 15 | 9.9%
S15 Pro(VISION) (itel-L6002P) | 8 | 5.3%
SPARK 4 (TECNO-KC8) | 6 | 4.0%
Galaxy A10s (a10s) | 5 | 3.3%
Galaxy A50 (a50) | 5 | 3.3%
LT | 5 | 3.3%
Galaxy A20 (a20) | 5 | 3.3%
SPARK 3 (TECNO-KB7j) | 5 | 3.3%
Galaxy S8 (dreamqltecan) | 5 | 3.3%
Smart 3 Plus (Infinix-X627STU) | 4 | 2.6%
Galaxy Note8 (greatqltechn) | 4 | 2.6%
Galaxy S8+ (dream2lte) | 3 | 2.0%
HUAWEI P smart+ 2019 (HWPOT-H) | 3 | 2.0%
Galaxy A50s (a50s) | 3 | 2.0%
Galaxy A60 (a60q) | 3 | 2.0%
Galaxy Note8 (greatlte) | 3 | 2.0%
S15 (itel-W6002E) | 2 | 1.3%
A3_Pro (A3_Pro) | 2 | 1.3%
Others | 27 | 17.9%

Here's an example of the most recent crash's stack trace (the rest are virtually identical)

```
Jul 11, 11:09 PM on app version 53
Tecno CAMON 12 (TECNO-CC7), 3840MB RAM, Android 9
Report 1

java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3013)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3148)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:78)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1861)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:193)
  at android.app.ActivityThread.main (ActivityThread.java:6819)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:497)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:912)
Caused by: java.lang.IllegalArgumentException: 
  at android.database.AbstractCursor.getColumnIndexOrThrow (AbstractCursor.java:340)
  at android.database.CursorWrapper.getColumnIndexOrThrow (CursorWrapper.java:87)
  at org.kiwix.kiwixmobile.utils.files.FileUtils.contentQuery (FileUtils.java:165)
  at org.kiwix.kiwixmobile.utils.files.FileUtils.getLocalFilePathByUri (FileUtils.java:150)
  at org.kiwix.kiwixmobile.KiwixMobileActivity.manageExternalLaunchAndRestoringViewState (KiwixMobileActivity.java:1561)
  at org.kiwix.kiwixmobile.KiwixMobileActivity.onCreate (KiwixMobileActivity.java:387)
  at android.app.Activity.performCreate (Activity.java:7136)
  at android.app.Activity.performCreate (Activity.java:7127)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1271)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2990)
```

**Comment by julianharty** [comment] 2020-07-13 15:04
One of the things that does change in the crash report is the line where the crash is triggered e.g. here it's `(FileUtils.java:144)` 

```
Jul 9, 10:32 PM on app version 182160
Infinix Smart 3 Plus (Infinix-X627STU), 2048MB RAM, Android 9
Report 6

java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2956)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3091)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:78)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1843)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:193)
  at android.app.ActivityThread.main (ActivityThread.java:6758)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:497)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:912)
Caused by: java.lang.IllegalArgumentException: 
  at android.database.AbstractCursor.getColumnIndexOrThrow (AbstractCursor.java:340)
  at android.database.CursorWrapper.getColumnIndexOrThrow (CursorWrapper.java:87)
  at org.kiwix.kiwixmobile.utils.files.FileUtils.contentQuery (FileUtils.java:159)
  at org.kiwix.kiwixmobile.utils.files.FileUtils.getLocalFilePathByUri (FileUtils.java:144)
  at org.kiwix.kiwixmobile.KiwixMobileActivity.manageExternalLaunchAndRestoringViewState (KiwixMobileActivity.java:1771)
  at org.kiwix.kiwixmobile.KiwixMobileActivity.onCreate (KiwixMobileActivity.java:462)
  at android.app.Activity.performCreate (Activity.java:7136)
  at android.app.Activity.performCreate (Activity.java:7127)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1271)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2933)
```
I don't know if this is exactly the same crash as the original one reported, as it may depend on the line number and whether there are several similar lines of the code that could trigger a similar crash. It does *look* similar given `manageExternalLaunchAndRestoringViewState` is in the various crash traces.

**Comment by macgills** [comment] 2020-07-14 06:18
@julianharty none of those are the latest version of the app and that is not the correct crash, the code has changed massively and that IllegalArgumentException error has been fixed.

**Comment by julianharty** [comment] 2020-07-14 06:25
@macgills so is this issue fixed? I'll admit I'm a bit confused as the stack traces seem very similar.

**Comment by macgills** [comment] 2020-07-14 06:28
This issue is not fixed, neither I nor anyone else has opened a PR to fix it. It is a problem with very few reports which adds to the difficulty in finding it so not a major issue and there are tickets in the work that should render it redundant. A bandaid might be nice in the interim though so I might get around to this soon, higher priority tickets at the moment though

**Comment by s-ayush2903** [comment] 2020-08-16 09:44
@macgills The day i commented here and received your comment the same day, went to `3.3.1` version of the repo and searched for the loc(line of code) mentioned in the crash report it turned out that there exists no java class of `FileUtils.java` and instead we have the kotlin version of it, so i'm not sure how the report is created and filed here :shrug: .

**Comment by macgills** [comment] 2020-08-17 09:07
Definitely weird, maybe I accidentally got this report from a slightly older version? we can still find the offending line

```
  at android.content.ContentResolver.query (ContentResolver.java:716)

 
  at org.kiwix.kiwixmobile.core.utils.files.FileUtils.contentQuery (FileUtils.java:141)
```

somewhere in the `contentQuery` method we call `ContentResolver.query `

**Closed** 2020-09-10 11:02 UTC
Labels: bug
