### ISSUE TITLE
Can't run tests without changing the testBuildType to "debug"

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-android#886] opened 2018-10-29 00:30 UTC
**Describe the bug**
Tests fail to run

**Expected behavior**
Tests should run

**Steps to reproduce the behavior:**
Try to run tests

**Environment**
- Version of Kiwix Android : master
- Device : Galaxy S8
- OS version : 8.0.1

**Logs**
Can't get log back as can't reproduce once I fixed it but it is this error https://stackoverflow.com/questions/28659451/test-running-failed-permission-denial-starting-instrumentation-componentinfo

```
 testBuildType "debug"
```
fixes this issue

@julianharty any ideas

**Comment by julianharty** [comment] 2018-11-24 22:17
@mhutti1 I'm not sure of the cause; however I've discovered there are various inbuilt poorly described requirements to get the tests (and optionally the test coverage) to run. As standard, I believe (from when I last looked at this a couple of months ago) that tests only run for debug builds. Setting the `testBuildType` enables the tests to run for other build targets (which was how I managed to get unblocked with a build target for generating code coverage). I don't recall seeing a permission denial, I've seen plenty of refusals to run tests because no tests were found (even though they existed in the project).

I'm going to be doing some more testing of the app in the coming weeks so will keep an eye on whether anything similar goes wrong. Thanks for asking and sorry for the delay (I've been focusing on other work for the last 6 weeks).

**Comment by kelson42** [comment] 2019-05-23 11:39
@mhutti1 @julianharty What is the status of this ticket?

**Comment by mhutti1** [comment] 2019-05-27 22:01
I think @macgills had been working on a fix.

**Comment by macgills** [comment] 2019-05-28 08:39
As part of #1175 I deleted the coverage buildType and enabled coverage on the debug build so I would say the ticket status is obsolete @kelson42

**Comment by kelson42** [comment] 2019-05-28 08:57
@macgills Nice, do you have link to a documentation (CONTRIBUTING.md) where it is explained how it works now? So @mhutti1 @julianharty and other developers might be able to say if they are OK?

**Comment by kelson42** [comment] 2019-06-14 08:52
@macgills any update?

**Comment by macgills** [comment] 2019-06-14 09:09
Resolved by #1176 coverage buildtype is deleted along with `testBuildType` so the default behaviour of using debug is preserved, closing

**Comment by kelson42** [comment] 2019-06-14 09:10
@macgills I see nothing in https://github.com/kiwix/kiwix-android/blob/master/CONTRIBUTING.md about all of this? Where is the documentation?

**Comment by macgills** [comment] 2019-06-14 09:11
I will add a commit to 2.5 branch now

**Comment by kelson42** [comment] 2019-06-14 09:24
Here is a list of questions which should be IMO in a way or an other answer by the CONTRIBUTING:
* [LOCAL] As a newcomer how to build the app (it should be the default gradle buildtype, was the purpose of the ticket)?
* [LOCAL] What should I expect from this default build/buildtype, what is his name?
* [LOCAL] How to run the unit tests (and how to interpret the results, if this is not obvious)?
* [LOCAL] What are the e2e/UI automated tests? How does that work? Why I can not run them locally?
* [CI] How do the unit tests & e2e automated tests are integrated in travis CI? How to see/interpret the results?
* [LOCAL] Secure that code coverage does not run per default if you run locally unit tests.
* [LOCAL] How to run code coverage with unit tests? Where are the results? How to interpret them?
* [CI] How does code coverage works with unit/e2e automated test on Travis CI? How to see/analysis the results?

All of this should be IMO in the CONTRIBUTING.md file. Therefore:
* It should be relatively quick (don't go too much in details, just explains the key things, necessary for the global understanding)
* Audience are (new) developers, please explain the principles but don't forget the most pragmatic aspects to help them get the job done.

**Comment by macgills** [comment] 2019-06-14 12:28
#1199 added details in contributing.md, closing

**Closed by macgills** 2019-06-14 12:28 UTC
Labels: bug
