### ISSUE TITLE
Empty dialog box on clicking languageItem in getContent

### ISSUE THREAD

**Issue by arpank10** [kiwix/kiwix-android#389] opened 2018-02-15 05:54 UTC
**Description**
While content is still loading, pressing languageItem on top right displays an empty dialog box along with a toast "Content still loading". It should display only the toast instead.
![whatsapp image 2018-02-15 at 11 24 06 am](https://user-images.githubusercontent.com/24573296/36242585-cf87fe20-1242-11e8-9f31-3cbbb0562497.jpeg)

**Would you like to work on it?**
Yes

**Comment by kelson42** [comment] 2018-02-15 06:06
Quite a duplicate of #383 IMO.

**Comment by VANKINEENITAWRUN** [comment] 2018-02-15 11:19
can i work on this issue

**Closed** 2018-02-16 22:27 UTC
Labels: bug, good first issue
