### ISSUE TITLE
Systematic problem by opening and reponing N times the same file

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#859] opened 2018-09-17 08:07 UTC
If I try (with 2.4) to open and reopen N<10 times the same file in the local library the app at some point:
* Crash OR
* Says the ZIM file is invalid
[logcat.txt](https://github.com/kiwix/kiwix-android/files/2387705/logcat.txt)

**Comment by kelson42** [comment] 2019-08-31 19:54
I need to confirm or close that with 3.0

**Comment by macgills** [comment] 2019-09-05 11:29
Could not reproduce, closing

**Closed by macgills** 2019-09-05 11:29 UTC
Labels: bug
