### ISSUE TITLE
List is not refreshed automatically when you start a download and navigate back to the home screen

### ISSUE THREAD

**Issue by hamza-maqsood** [kiwix/kiwix-android#1950] opened 2020-03-24 03:16 UTC
**Describe the bug**

**Expected behavior**
When a download is started and the user navigates back to the home screen, the list is not updated when the download completes, even when the notification is clicked.

**Steps to reproduce the behavior:**
1. Starts a download in the ONLINE tab and navigate back to the home screen.

**Environment**
- Version of Kiwix Android : 7.1
- Device : LG G5
- OS version : 7.1

** Solution**
One solution can be to use Live Data from android jetpack or to use a callback.

**Comment by sonusourav** [comment] 2020-03-24 05:50
Duplicate of #1797

**Comment by macgills** [comment] 2020-03-24 15:08
I closed that other ticket as this is closer to something we should do, the list in KiwixMain should be observing the same data source as in the ZimFileSelectFragment. It is a bit annoying because the screen currently has no VIewModel

**Comment by grayhatdevelopers** [comment] 2020-03-25 17:34
@sonusourav  I saw the issue #1797 as you have mentioned, but my point is why the user needs to refresh the list, providing a refresh option even if nothing is being downloaded will simply be an overkill. The list only needs to be refreshed when something is added, so let the app do it itself

**Comment by hamza-maqsood** [comment] 2020-03-25 17:40
@sonusourav I saw the issue #1797 that you have mentioned, but my point is that the list only needs to be refreshed only when something is downloaded, the app should do it itself.

**Comment by kelson42** [comment] 2023-01-11 19:45
I will check if we still have the bug. Seems anyway easy to fix.

**Comment by kelson42** [comment] 2023-01-17 08:01
@MohitMaliFtechiz Can you please upfate the ticket?

**Comment by MohitMaliFtechiz** [comment] 2023-01-25 13:36
hi @kelson42 ,
i'm unable to reproduce this error. Since this issue is very old (As i recall, we changed the download screen UI). I understand home screen as Current ```local library fragment``` (Please tell me if i am understand ```home screen``` wrong).
I'm attaching a video 

https://user-images.githubusercontent.com/34593983/214577081-c0fec62d-2da4-4bc2-8f43-3d5d6406e4bb.mp4

**Closed** 2023-01-25 13:37 UTC
Labels: bug, good first issue
