### ISSUE TITLE
Positive search result in Wikimed fails to send user to corresponding article.

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-android#567] opened 2018-03-03 16:59 UTC
_From @Popolechien on March 3, 2018 13:0_

From OTRS:
I'm using the wikimed app. 
 Version : 2017-08
Buid : 1172141

Whenever I type gongylonema pulchrum , I get the search results but when I tap on it.. nothing happens... It doesn't direct me to the content.

_Copied from original issue: kiwix/kiwix-android-custom#17_

**Comment by kelson42** [comment] 2018-03-03 16:59
I confirm the bug... but this is more for the Kiwix repo.

**Comment by RohanBh** [comment] 2018-03-03 22:12
@kelson42 which search is this? For me, there is no problem with the global search. I am on the ArchWiki zim.

**Comment by kelson42** [comment] 2018-03-04 06:49
@RohanBh Read properly the ticket. It is not a problem with the archwiki zim. It is a problem with one article of the wikipedia en medical zim.

**Comment by RohanBh** [comment] 2018-03-05 14:47
@kelson42 Sorry for replying late, but I wasn't able to download WikiMed zim as there was some issue(which fixed randomly). All the links on its main page open a blank page. Is it same for you too?

**Comment by Popolechien** [comment] 2018-03-05 15:40
It seems to reproduce on every article that is in italics (same result with _Candida albicans_ and _New England Journal of Medicine_): the articles are not empty though because if they exist as links within the text they appear normally (e.g. from the Vaginal yeast infection and Haemophilia articles).

**Comment by RohanBh** [comment] 2018-03-06 21:56
@kelson42 I have fixed this issue. I will make a PR as soon as [this PR](https://github.com/kiwix/kiwix-android/pull/586)(which addresses the search activity crash) gets merged into master.

**Comment by RohanBh** [comment] 2018-03-06 21:58
Thanks @Popolechien for pointing out that. It helped a lot :smile:

**Closed** 2018-03-11 00:17 UTC
Labels: bug

**Comment by kelson42** [comment] 2018-03-18 17:14
@RohanBh Thank you for fixing this important bug.
