### ISSUE TITLE
Mathjax render doesn't work on android

### ISSUE THREAD

**Issue by dattaz** [kiwix/kiwix-android#152] opened 2017-06-09 13:32 UTC
For zim of stackexchange/stackoverlfow we use mathjax for rendering latex and math symbole.

It's work well on web browser (with kiwix server) but not in kiwx-android.

Issue for step to reproduice : https://github.com/openzim/sotoki/issues/63

**Comment by kelson42** [comment] 2017-06-11 09:25
@dattaz Do you have a concrete file/url + article name + screenshot to share here. That would help the developers to reproduce quickly the problem and maybe fix it.

**Comment by dattaz** [comment] 2017-06-11 09:52
Sure,
url : A/question/1443.html 
article name : Can one latexify formulae on Signal Processing meta?
zim : http://dattaz.fr/sotoki/meta.dsp.stackexchange.com_en_all_2017-06.zim
![fail_mathjax_android](https://user-images.githubusercontent.com/6572195/27010067-6ad462c6-4e9c-11e7-89ee-9b880e4e51ac.png)

**Comment by kelson42** [comment] 2017-06-11 09:55
@borisfba Would that be something you would volunteer to work on?

**Comment by kelson42** [comment] 2017-06-30 14:36
A working example (served by kiwix-serve) can be seen here http://download.kiwix.org:8080/meta.dsp.stackexchange.com_en_all_2017-06/A/question/1443.html

**Comment by kelson42** [comment] 2017-07-18 06:40
@EladKeyshawn @borisfba That would be really helpful if one of us could have a look to that bug.

**Comment by mhutti1** [comment] 2017-08-07 13:50
@kelson42 I think something has changed. I can no longer find the article to reproduce.

**Comment by kelson42** [comment] 2018-01-17 17:31
@mhutti1 As far as I can see the problem is still there with the last ZIM File. Just take the latest version. Have a look there for example http://library.kiwix.org/dsp.stackexchange.com_en_all_2017-10/A/question/1637/what-does-frequency-domain-denote-in-case-of-images.html

**Comment by Popolechien** [comment] 2018-08-30 13:14
Seems the problem is still here as well with the german wikipedia zim (wikipedia_de_all_novid_2018-06) whereas wikipedia_de_all_2017-06 worked fine. Here is the screenshot provided:
![40493939_687848854903836_8012107017894232064_n 1](https://user-images.githubusercontent.com/21675885/44853866-5c99ea80-ac67-11e8-8c90-8be55fd41f58.png)

**Comment by macgills** [comment] 2019-09-04 08:52
I am struggling to reproduce this as all links on this issue have expired but with the recent re-enabling of StackOverflow zims I say this should be re-tested

**Comment by kelson42** [comment] 2019-09-04 08:53
@macgills If you can reproduce the problem with the article "Signal Processing" and https://download.kiwix.org/zim/stack_exchange/dsp.stackexchange.com_en_all_2019-01.zim ... then I would recommend to close the ticket.

**Comment by macgills** [comment] 2019-09-04 09:11
tch, still broken
![image](https://user-images.githubusercontent.com/3358282/64241863-67333380-cefc-11e9-870f-c46347e2b7dd.png)

**Comment by macgills** [comment] 2019-09-06 14:37
```
2019-09-06 15:21:04.685 22182-23460/org.kiwix.kiwixmobile D/kiwix: reading  A/index.html(mime: text/html, size: 28416) finished.
2019-09-06 15:21:04.694 22182-22764/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/static/bootstrap/css/bootstrap.min.css
2019-09-06 15:21:04.698 22182-23459/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/static/bootstrap/css/bootstrap-theme.min.css
2019-09-06 15:21:04.699 22182-22764/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/static/main.css
2019-09-06 15:21:04.704 22182-23459/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/static/moment.js
2019-09-06 15:21:04.710 22182-22764/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/static/MathJax.js?config=TeX-AMS_HTML-full
2019-09-06 15:21:04.717 22182-23463/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/static/jquery-2.1.4.min.js
2019-09-06 15:21:04.718 22182-22294/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/static/bootstrap/css/bootstrap.min.css = text/css
2019-09-06 15:21:04.726 22182-23459/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/static/main.js
2019-09-06 15:21:04.732 22182-22294/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/static/bootstrap/css/bootstrap-theme.min.css = text/css
2019-09-06 15:21:04.740 22182-22294/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/static/main.css = text/css
2019-09-06 15:21:04.745 22182-23466/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/I/favicon.png
2019-09-06 15:21:04.759 22182-23471/org.kiwix.kiwixmobile E/kiwix: Unable to get content for url: -/static/MathJax.js?config=TeX-AMS_HTML-full
2019-09-06 15:21:04.759 22182-23471/org.kiwix.kiwixmobile E/kiwix: std::exception
2019-09-06 15:21:04.760 22182-22294/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/static/moment.js = application/javascript
2019-09-06 15:21:04.761 22182-23471/org.kiwix.kiwixmobile D/kiwix: reading  -/static/MathJax.js?config=TeX-AMS_HTML-full(mime: , size: 0) finished.
2019-09-06 15:21:04.765 22182-22294/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/static/jquery-2.1.4.min.js = application/javascript
2019-09-06 15:21:04.771 22182-22294/org.kiwix.kiwixmobile E/kiwix: Unable to get mime-type for url: -/static/MathJax.js?config=TeX-AMS_HTML-full
2019-09-06 15:21:04.771 22182-22294/org.kiwix.kiwixmobile E/kiwix: std::exception
```
So it seems that the app can't figure out from the extension `.js` that the mime type is `application/javascript`.
I added a quick mapping for that and still no luck with mathjax rendering
```
2019-09-06 15:29:28.987 23797-23884/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/static/MathJax.js?config=TeX-AMS_HTML-full = application/javascript
2019-09-06 15:29:28.988 23797-24122/org.kiwix.kiwixmobile E/kiwix: Unable to get content for url: -/static/MathJax.js?config=TeX-AMS_HTML-full
2019-09-06 15:29:28.989 23797-24122/org.kiwix.kiwixmobile E/kiwix: std::exception
2019-09-06 15:29:28.989 23797-24122/org.kiwix.kiwixmobile D/kiwix: reading  -/static/MathJax.js?config=TeX-AMS_HTML-full(mime: , size: 0) finished.
2019-09-06 15:29:28.997 23797-23884/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/static/moment.js = application/javascript
```

Once again completely stuck without some help. @mhutti1 @mgautierfr

**Comment by kelson42** [comment] 2019-09-06 16:19
@macgills There should be not assumption about the mime-type based on the extension. The mimetype is delivered by the libzim.

**Comment by mhutti1** [comment] 2019-09-08 21:57
I spent a considerable amount of time looking into this and couldn't come up with anything either.

**Comment by macgills** [comment] 2019-09-09 08:19
```
2019-09-06 15:29:28.989 23797-24122/org.kiwix.kiwixmobile E/kiwix: std::exception
```
Then it is up to @mgautierfr to decipher this line which I think is coming from JNI?



@kelson42 that is not how it works in the app
```
 @Override
  public String getType(Uri uri) {
    String mimeType;

    // This is the code which makes a guess based on the file extenstion
    String extension = MimeTypeMap.getFileExtensionFromUrl(uri.toString().toLowerCase());
    mimeType = MimeTypeMap.getSingleton().getMimeTypeFromExtension(extension);

    // This is the code which retrieve the mimeType from the libzim
    // "slow" and still bugyy
    if ("js".equals(extension)) {
      mimeType = "application/javascript";
    }
    if (mimeType == null || mimeType.isEmpty()) {
      String t = uri.toString();
      int pos = uri.toString().indexOf(CONTENT_URI.toString());
      if (pos != -1) {
        t = uri.toString().substring(
          CONTENT_URI.toString().length());
      }
      // Remove fragment (#...) as not supported by zimlib
      pos = t.indexOf("#");
      if (pos != -1) {
        t = t.substring(0, pos);
      }

      mimeType = currentJNIReader.getMimeType(t);

      // Truncate mime-type (everything after the first space
      mimeType = mimeType.replaceAll("^([^ ]+).*$", "$1");
    }

    Log.d(TAG_KIWIX, "Getting mime-type for " + uri.toString() + " = " + mimeType);
    return mimeType;
  }
```
We only ask kiwixlib if the `android.webkit.MimeTypeMap` has no satisfying answer. My mapping of js to a mimtetype was just a shot in the dark that has not been committed

**Comment by mgautierfr** [comment] 2019-09-09 14:01
@macgills What zim are you using ?

**Comment by macgills** [comment] 2019-09-09 14:06
https://download.kiwix.org/zim/stack_exchange/dsp.stackexchange.com_en_all_2019-01.zim this one and then I go to the article "why is the Fourier Transform so important"

**Comment by mgautierfr** [comment] 2019-09-09 16:15
There is no article `-/static/MathJax.js?config=TeX-AMS_HTML-full` but `-/static/MathJax.js` in this file.

**Comment by kelson42** [comment] 2019-09-09 16:20
@macgills Obviously the arguments of the URL should be removed before requisting the asset to the libzim.

**Comment by mgautierfr** [comment] 2019-09-09 16:55
Should it be also removed at zim file creation ?

**Closed** 2019-09-11 05:20 UTC
Labels: bug, help wanted
