### ISSUE TITLE
SVG can not be rendered properly (Images in zim file does not show up)

### ISSUE THREAD

**Issue by sonusourav** [kiwix/kiwix-android#1014] opened 2019-02-21 16:12 UTC
**Describe the bug**
Images in some Zim files do not show up. The case is with some files and not all.

**Expected behavior**
The images should load correctly and not have any broken link

**Steps to reproduce the behavior:**
1. Open WikEM (37.3 MB).
2. Scroll down to see.

**Screenshots**

![broken images](https://user-images.githubusercontent.com/34706326/53182424-7bc67300-361f-11e9-9800-79cb2c4300bb.jpeg)

**Environment**
- Version of Kiwix Android : 2.4 Build 55
- Device : Redmi 4
- OS version : Nougat 7.1

**Comment by kelson42** [comment] 2019-02-21 16:20
@sonusourav Please secure with `kiwix-serve` that this is not a problem with the ZIM file itself (missing image in the ZIM file)... And then give a concreate zim/page so we can reproduce the problem.

**Comment by sonusourav** [comment] 2019-02-21 17:56
@kelson42  I checked from kiwix-server, the zim file is fine there. 

![kiwix_desktop](https://user-images.githubusercontent.com/34706326/53190625-fd260180-362f-11e9-88ae-20d0aeb0f87a.png)

Even after I deleted the zim file from my mobile device and re-downloaded, the issue persists. 
Is anybody else getting the same problem? Here are the file details:
Project: WikEM
Size: 37.3
Lang: English (en)
Date created: 08-10-2018
Additional info: Contains pictures

**Comment by rajbohra10** [comment] 2019-04-11 15:19
![Screenshot_2019-04-11-20-25-52-34](https://user-images.githubusercontent.com/39001878/55968996-b2714f00-5c9a-11e9-8340-34f2084de991.png)

@sonusourav @kelson42 The images are not loading even when the device is connected to kiwix-server. I would like to work on this bug, is anyone else working on it?

**Comment by kelson42** [comment] 2019-07-25 08:49
I confirm the problem with 2.5 and recent version of WiKem homepage. I can also confirm that the problem is not with the ZIM.

**Comment by macgills** [comment] 2019-08-16 12:15
@mhutti1 would this have anything to do with the redirect problem being addressed in #1368 ?

**Comment by mhutti1** [comment] 2019-08-16 13:00
I guess it could theoretically. Will be interesting to see if it is fixed by it.

**Comment by macgills** [comment] 2019-09-06 13:19
```
2019-09-06 14:05:09.586 17627-19231/org.kiwix.kiwixmobile I/kiwix: Attempting to create reader with: /storage/emulated/0/Kiwix/wikem_en_all_novid_2019-05.zim
2019-09-06 14:05:09.586 17627-19231/org.kiwix.kiwixmobile I/kiwix: Opening ZIM file /storage/emulated/0/Kiwix/wikem_en_all_novid_2019-05.zim
2019-09-06 14:05:09.594 17627-19178/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/s/css_modules/ext.smw.style.css
2019-09-06 14:05:09.597 17627-19177/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/s/css_modules/ext.smw.tooltips.css
2019-09-06 14:05:09.601 17627-19177/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/s/css_modules/style.css
2019-09-06 14:05:09.601 17627-18938/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/s/css_modules/skins.minerva.base.reset%7Cskins.minerva.content.styles%7Cext.cite.style%7Cmobile.app.pagestyles.android%7Cmediawiki.page.gallery.styles%7Cmediawiki.skinning.content.parsoid.css
2019-09-06 14:05:09.602 17627-19175/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/s/css_modules/content.parsoid.css
2019-09-06 14:05:09.605 17627-19178/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/s/css_modules/inserted_style.css
2019-09-06 14:05:09.609 17627-19175/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/script.js
2019-09-06 14:05:09.613 17627-19178/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/masonry.min.js
2019-09-06 14:05:09.617 17627-19177/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/images_loaded.min.js
2019-09-06 14:05:09.619 17627-19180/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/details_polyfill.js
2019-09-06 14:05:09.621 17627-19182/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/I/m/Kaji-Title-v3-Print-COVER-AMAZON.jpg%3Fresize%3D232%2C348.svg
2019-09-06 14:05:09.627 17627-18938/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/article_list_home.js
2019-09-06 14:05:09.643 17627-19177/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/I/m/IMG_0323.png%3Fresize%3D169%2C300.svg
2019-09-06 14:05:09.649 17627-19180/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/jquery.js
2019-09-06 14:05:09.649 17627-19175/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/jsConfigVars.js
2019-09-06 14:05:09.650 17627-19182/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/mediawiki.js
2019-09-06 14:05:09.650 17627-19178/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/startup.js
2019-09-06 14:05:09.652 17627-18938/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/site.js
2019-09-06 14:05:09.670 17627-19178/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/ext.smw.style.js
2019-09-06 14:05:09.672 17627-17710/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/s/css_modules/ext.smw.style.css = text/css
2019-09-06 14:05:09.672 17627-18938/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/ext.smw.tooltips.js
2019-09-06 14:05:09.680 17627-17710/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/s/css_modules/ext.smw.tooltips.css = text/css
2019-09-06 14:05:09.686 17627-17710/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/s/css_modules/skins.minerva.base.reset%7Cskins.minerva.content.styles%7Cext.cite.style%7Cmobile.app.pagestyles.android%7Cmediawiki.page.gallery.styles%7Cmediawiki.skinning.content.parsoid.css = text/css
2019-09-06 14:05:09.705 17627-17710/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/s/css_modules/content.parsoid.css = text/css
2019-09-06 14:05:09.709 17627-17627/org.kiwix.kiwixmobile D/kiwix: TextToSpeech was initialized successfully.
2019-09-06 14:05:09.717 17627-17710/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/s/css_modules/inserted_style.css = text/css
2019-09-06 14:05:09.729 17627-17710/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/s/css_modules/style.css = text/css
2019-09-06 14:05:09.742 17627-17710/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/images_loaded.min.js = application/javascript
2019-09-06 14:05:09.753 17627-17710/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/script.js = application/javascript
2019-09-06 14:05:09.766 17627-17710/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/masonry.min.js = application/javascript
2019-09-06 14:05:09.783 17627-17710/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/details_polyfill.js = application/javascript
2019-09-06 14:05:09.789 17627-17710/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/I/m/Kaji-Title-v3-Print-COVER-AMAZON.jpg%3Fresize%3D232%2C348.svg = image/svg+xml
2019-09-06 14:05:09.795 17627-17710/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/article_list_home.js = application/javascript
2019-09-06 14:05:09.800 17627-17710/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/site.js = application/javascript
2019-09-06 14:05:09.806 17627-17710/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/startup.js = application/javascript
2019-09-06 14:05:09.817 17627-17710/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/mediawiki.js = application/javascript
2019-09-06 14:05:09.871 17627-17772/org.kiwix.kiwixmobile D/OpenGLRenderer: endAllActiveAnimators on 0x71c67f5c00 (RippleDrawable) with handle 0x71d2531100
2019-09-06 14:05:09.882 17627-17658/org.kiwix.kiwixmobile D/LeakCanary: Checking retained instances because Showing retained instance notification
2019-09-06 14:05:09.883 17627-17658/org.kiwix.kiwixmobile D/LeakCanary: No retained instances
2019-09-06 14:05:09.884 17627-17658/org.kiwix.kiwixmobile D/LeakCanary: Checking retained instances because Showing retained instance notification
2019-09-06 14:05:09.884 17627-17658/org.kiwix.kiwixmobile D/LeakCanary: No retained instances
2019-09-06 14:05:09.998 17627-19248/org.kiwix.kiwixmobile D/kiwix: reading  -/s/css_modules/ext.smw.tooltips.css(mime: text/css, size: 0) finished.
2019-09-06 14:05:10.182 17627-19261/org.kiwix.kiwixmobile D/kiwix: reading  -/j/js_modules/site.js(mime: application/javascript, size: 16409) finished.
2019-09-06 14:05:10.212 17627-19247/org.kiwix.kiwixmobile D/kiwix: reading  -/s/css_modules/ext.smw.style.css(mime: text/css, size: 24736) finished.
2019-09-06 14:05:10.253 17627-19250/org.kiwix.kiwixmobile D/kiwix: reading  -/s/css_modules/skins.minerva.base.reset%7Cskins.minerva.content.styles%7Cext.cite.style%7Cmobile.app.pagestyles.android%7Cmediawiki.page.gallery.styles%7Cmediawiki.skinning.content.parsoid.css(mime: text/css, size: 11412) finished.
2019-09-06 14:05:10.257 17627-19265/org.kiwix.kiwixmobile D/kiwix: reading  -/j/js_modules/ext.smw.style.js(mime: application/javascript, size: 44) finished.
2019-09-06 14:05:10.258 17627-19254/org.kiwix.kiwixmobile D/kiwix: reading  -/j/js_modules/images_loaded.min.js(mime: application/javascript, size: 6398) finished.
2019-09-06 14:05:10.272 17627-19255/org.kiwix.kiwixmobile D/kiwix: reading  -/j/js_modules/masonry.min.js(mime: application/javascript, size: 24103) finished.
2019-09-06 14:05:10.272 17627-19249/org.kiwix.kiwixmobile D/kiwix: reading  -/s/css_modules/style.css(mime: text/css, size: 2371) finished.
2019-09-06 14:05:10.278 17627-17710/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/jsConfigVars.js = application/javascript
2019-09-06 14:05:10.297 17627-19253/org.kiwix.kiwixmobile D/kiwix: reading  -/j/js_modules/script.js(mime: application/javascript, size: 443) finished.
2019-09-06 14:05:10.298 17627-19258/org.kiwix.kiwixmobile D/kiwix: reading  -/j/js_modules/article_list_home.js(mime: application/javascript, size: 714) finished.
2019-09-06 14:05:10.300 17627-19264/org.kiwix.kiwixmobile D/kiwix: reading  -/j/js_modules/jsConfigVars.js(mime: application/javascript, size: 1) finished.
2019-09-06 14:05:10.301 17627-19251/org.kiwix.kiwixmobile D/kiwix: reading  -/s/css_modules/content.parsoid.css(mime: text/css, size: 4453) finished.
2019-09-06 14:05:10.305 17627-19256/org.kiwix.kiwixmobile D/kiwix: reading  -/j/js_modules/details_polyfill.js(mime: application/javascript, size: 7664) finished.
2019-09-06 14:05:10.305 17627-17710/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/jquery.js = application/javascript
2019-09-06 14:05:10.311 17627-17710/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/I/m/IMG_0323.png%3Fresize%3D169%2C300.svg = image/svg+xml
2019-09-06 14:05:10.313 17627-19266/org.kiwix.kiwixmobile D/kiwix: reading  -/j/js_modules/ext.smw.tooltips.js(mime: application/javascript, size: 47) finished.
2019-09-06 14:05:10.315 17627-17710/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/ext.smw.style.js = application/javascript
2019-09-06 14:05:10.319 17627-17710/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/ext.smw.tooltips.js = application/javascript
2019-09-06 14:05:10.319 17627-19257/org.kiwix.kiwixmobile D/kiwix: reading  I/m/Kaji-Title-v3-Print-COVER-AMAZON.jpg%3Fresize%3D232%2C348.svg(mime: image/svg+xml, size: 8439) finished.
2019-09-06 14:05:10.320 17627-19259/org.kiwix.kiwixmobile D/kiwix: reading  I/m/IMG_0323.png%3Fresize%3D169%2C300.svg(mime: image/svg+xml, size: 4297) finished.
2019-09-06 14:05:10.330 17627-19252/org.kiwix.kiwixmobile D/kiwix: reading  -/s/css_modules/inserted_style.css(mime: text/css, size: 111686) finished.
2019-09-06 14:05:10.334 17627-19263/org.kiwix.kiwixmobile D/kiwix: reading  -/j/js_modules/mediawiki.js(mime: application/javascript, size: 27634) finished.
2019-09-06 14:05:10.336 17627-19260/org.kiwix.kiwixmobile D/kiwix: reading  -/j/js_modules/startup.js(mime: application/javascript, size: 22588) finished.
2019-09-06 14:05:10.345 17627-19262/org.kiwix.kiwixmobile D/kiwix: reading  -/j/js_modules/jquery.js(mime: application/javascript, size: 149043) finished.
2019-09-06 14:05:10.393 17627-17627/org.kiwix.kiwixmobile I/chromium: [INFO:CONSOLE(1)] "Uncaught SyntaxError: Unexpected end of input", source: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/jsConfigVars.js (1)
2019-09-06 14:05:10.408 17627-17627/org.kiwix.kiwixmobile I/chromium: [INFO:CONSOLE(139)] "JQMIGRATE: Migrate is installed with logging active, version 3.0.1", source: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/jquery.js (139)
2019-09-06 14:05:10.409 17627-17627/org.kiwix.kiwixmobile I/chromium: [INFO:CONSOLE(140)] "JQMIGRATE: jQuery is not compatible with Quirks Mode", source: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/jquery.js (140)
2019-09-06 14:05:10.417 17627-17627/org.kiwix.kiwixmobile I/chromium: [INFO:CONSOLE(4)] "Uncaught ReferenceError: addOnloadHook is not defined", source: content://org.kiwix.kiwixmobile.zim.base/-/j/js_modules/site.js (4)
2019-09-06 14:05:10.434 17627-17627/org.kiwix.kiwixmobile D/kiwix: Loaded URL: content://org.kiwix.kiwixmobile.zim.base/A/Main_Page
2019-09-06 14:05:10.434 17627-17627/org.kiwix.kiwixmobile D/kiwix: Loaded URL: content://org.kiwix.kiwixmobile.zim.base/A/Main_Page
```
I am completely unaware of how to diagnose this.
`2019-09-06 14:05:10.319 17627-19257/org.kiwix.kiwixmobile D/kiwix: reading  I/m/Kaji-Title-v3-Print-COVER-AMAZON.jpg%3Fresize%3D232%2C348.svg(mime: image/svg+xml, size: 8439) finished.
`
 this reading seems fine? is it a problem with svgs? If so will we have to detect the mime type and write out custom html at `ZimContentProvider.TransferThread.run()`? @mhutti1

**Comment by mhutti1** [comment] 2019-09-08 21:56
This could be todo with redirects (are you using the fixed version)? Otherwise it might be svgs?

**Comment by macgills** [comment] 2019-09-09 08:12
Using the fixed version. If there is any way I can debug further to get more info please let me know.The quickest way to patch up my knowledge on kiwix rendering is unfortunately to ask a lot of pestering questions

**Comment by kelson42** [comment] 2019-09-09 15:08
@macgills Have you checked the webView can display SVG properly?

**Comment by kelson42** [comment] 2019-09-09 15:19
@macgills I have uploaded a test ZIM with a SVG here http://tmp.kiwix.org/svg_test.zim... unfortunately I was not able to test it... because Kiwix crash at the time I try to open it!!!!

**Comment by macgills** [comment] 2019-09-09 15:20
that would be [this](https://github.com/kiwix/kiwix-android/pull/1446) issue that I fixed

**Comment by kelson42** [comment] 2019-09-09 15:23
OK, so my conclusion is WebView is not able to render properly SVG. This won't be a problem for which we can quickly find a solution.

**Comment by macgills** [comment] 2019-09-09 15:29
```
2019-09-09 16:26:28.038 28747-28923/org.kiwix.kiwixmobile E/kiwix: Unable to get content for url: I/SVG_logo.svg
2019-09-09 16:26:28.038 28747-28923/org.kiwix.kiwixmobile E/kiwix: std::exception
```
from that test file, aye. 
SVG support has been apart of Webviews in android since 3.0 though. I can navigate on my device browser to a Wikipedia article on svgs that has them there

**Comment by kelson42** [comment] 2019-09-09 15:31
@mgautierfr @macgills  Something special in the libkiwix JNI. Kiwix-Desktop and Kiwix-serve have no problem with it!

**Comment by kelson42** [comment] 2019-09-09 15:57
@macgills Hmm.. no it works for me on Android. Are you able to get the test file working... or it simply fails like I said first?

**Comment by macgills** [comment] 2019-09-10 07:45
@kelson42, after downloading it I can find it with the kiwix app and then open it and the image is not displaying

**Comment by macgills** [comment] 2019-09-10 08:52
I am not sure what was happening but on develop I can now open that test svg file and it displays
![image](https://user-images.githubusercontent.com/3358282/64599042-a5bf6700-d3b0-11e9-934b-caaaa81e3372.png)

**Comment by macgills** [comment] 2019-09-10 08:55
is WikEM full of broken links for anyone else? When I click `Kaji Review Volume 3` I get taken to a blank page because it tries to load nothing
```
2019-09-10 09:54:21.060 11564-12001/org.kiwix.kiwixmobile D/kiwix: Retrieving: content://org.kiwix.kiwixmobile.zim.base/
2019-09-10 09:54:21.065 11564-12004/org.kiwix.kiwixmobile D/kiwix: reading  (mime: text/html, size: 10303) finished.
2019-09-10 09:54:21.068 11564-12001/org.kiwix.kiwixmobile D/kiwix: Getting mime-type for content://org.kiwix.kiwixmobile.zim.base/ = text/html
2019-09-10 09:54:21.093 11564-11564/org.kiwix.kiwixmobile W/ContentUriUtils: Cannot open content uri: content://org.kiwix.kiwixmobile.zim.base/
```

**Comment by macgills** [comment] 2019-12-17 11:38
I think this file is lying about being an svg, I am not incredibly well versed on the formats but the byte difference is a lot
WikEM:
```
2019-12-17 11:19:28.771 E/BYTES:: ������JFIF����������������C��	
    
   
     ' .)10.)-,3:J>36F7,-@WAFLNRSR2>ZaZP`JQRO����C&&O5-5OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO����\���"���������������������������������������������������������������������V%P%P%P%P%P$�/��!%���������������o�(���ve��'w�O"�J�J�z��IR|ԠJ�n���M1�~=xL�|����@�����^[�9��95^a���1�=�߇^7�P�n}�y����������S��6󆍜�v)�:@K��q�`\�g���\9����F~��Q���f�Vӫ��{:ޫ�^���ǻ�ač��:;x�l���N]�|�Dtr��5i�56l�̽�9��~�椳�ěz�9~�����:�s�CI@ ��|ei����κ�T���Zf2�ɕ��ejFV�35I��%���J�J$"B��cn�1T�B�J$ J����������Z���WR��������@����������������������c.+���:��'W��E�iw��/,z����*�:T�=}[*�}����4
    !-�H��8�M"�YƊ|�>��),�:����@��(�%���(�>�m�^���o���&WXa����L���摤�J���`���ȭuVBȏ^m�u���"����6bIԯ���|�ݖ����'C�5m櫢��:�WO>A�8�@@�������������������������s���5��7f�[3�4�Q��a�r#uyGC�P��@P�����ē_�#T�o狩-���������(�(�(�(�(�(�/�@������������������Wg����P������������������������*����
    �������������� !"#023@14P`$��������F>��Q����V����6�m���DڻʅwN}�5�:� �q�±��ޒ6r�S�l�ǩP�V�a�d�0ĭ��㕣Ҵ��2�;H�<��Fc�� x�B�J��jG�cR|�^�%~�{L���#�:5;PҨ*q�Y�Z��`����D�����V@��E��0k��`�ԽZ(�.�n	h��7�An̯)&K/wX�q�ҩb�ȡQ��qѵg����I0��bAR����5���ʷ%��Ӳ��~{r���B�B�m�YE@x�n�󮎴����h��0��x�s>$���>�����8���̷�Y �;/���,}ܜwWQ��$��M�ʸ+"Hۻ����Cm.dR���cx|��zrMD�:Eo���ٺ3ў���?�N���q�B��׃����X�a�6�f�����	�!2t��^
    ��|�5S��F=#�����	#GJ�G+Q9f�����M�i�H�J;3���Բ�4`q#X��'p�;��ǂL�7&=ݐ6)�#�T���%ԩ�V?=��a�2̨hS2Ȋ h�\L�ȇ�m~+Od$��]+f��ߞ���r�$dnw�V�q+H��r4t������vn�&�&�,����r�,Δ�:#S�yB%a����1$��m����&�У,F�����ǮWXʊ��g^���[��:0�0�Kޑ{�����'�"nJ�M:�\t{��R����.̱3I����� �!
    �������^V�7�9;�+�@�����6Q sHv�]y�#>�%O�d�lǐc�>,W�C��a�:c�i�4�\�h�cUe���@!�e��7!	�(�Wq`�CU�˩1�#�5�Fk������ ����������������������!01a����?�B��^<�:A�O��SG��d������ ���M��HS�֊�4���P�4����/����%��������������������! 0Q12@"P`���?�p7۫�n rST�i�tt>�3;z~u�	�ĉ������m̚t[��|olLG
    �%>K�?r~%>�/.�ɬ���L��!�a��K&�Yn_1�c�1��i�\2gh�d�p�#"x!n���sc�1�[B�_�����6��������������!1"AQaq 02B�@P�R`b��#r����������?�����6$ߒ%��*E��A��s�
    wCH��yo�����&� !*�T�h	^G}���d@�t�d���$ڶ=@�T�����X��<��J�&T�Z")t�uO"Ӫ�,�R`�]��U{�`�=;�wE�����i��	�D[��K�@<gI;�t�D��� ���f��el,�|K*xS+z�o���W��"���F�0�p����A�*%K���
```
Test SVG:
```
2019-12-17 11:25:36.482 E/BYTES:: <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="100%" height="100%" viewBox="0 0 100 100">
    
      <title>SVG Logo</title>
    
      <a xlink:href="http://www.w3.org/Graphics/SVG/" target="_parent"
         xlink:title="W3C SVG Working Group home page">
    
        <rect
            id="background"
            fill="#FF9900"
            width="100"
            height="100"
            rx="4"
            ry="4"/>
    
        <rect
            id="top-left"
            fill="#FFB13B"
            width="50"
            height="50"
            rx="4"
            ry="4"/>
    
        <rect
            id="bottom-right"
            x="50"
            y="50"
            fill="#DE8500"
            width="50"
            height="50"
            rx="4"
            ry="4"/>
    
        <g id="circles" fill="#FF9900">
            <circle
                id="n"
                cx="50"
                cy="18.4"
                r="18.4"/>
    
            <circle
                id="ne"
                cx="72.4"
                cy="27.6"
                r="18.4"/>
    
            <circle
                id="e"
                cx="81.6"
                cy="50"
                r="18.4"/>
    
            <circle
                id="se"
                cx="72.4"
                cy="72.4"
                r="18.4"/>
    
            <circle
                id="s"
                cx="50"
                cy="81.6"
                r="18.4"/>
    
            <circle
                id="sw"
                cx="27.6"
                cy="72.4"
                r="18.4"/>
    
            <circle
                id="w"
                cx="18.4"
                cy="50"
                r="18.4"/>
    
            <circle
                id="nw"
                cx="27.6"
                cy="27.6"
                r="18.4"/>
        </g>
    
        <g id="stars">
            <path
                id="black-star"
                d="M  63.086, 18.385
                   c  0.000, -7.227  -5.859,-13.086 -13.100,-13.086
                   c -7.235,  0.000 -13.096,  5.859 -13.096, 13.086
                   c -5.100, -5.110 -13.395, -5.110 -18.497,  0.000
                   c -5.119,  5.120  -5.119, 13.408   0.000, 18.524
                   c -7.234,  0.000 -13.103,  5.859 -13.103, 13.085
                   c  0.000,  7.230   5.870, 13.098  13.103, 13.098
                   c -5.119,  5.110  -5.119, 13.395   0.000, 18.515
                   c  5.102,  5.104  13.397,  5.104  18.497,  0.000
                   c  0.000,  7.228   5.860, 13.083  13.096, 13.083
                   c  7.240,  0.000  13.100, -5.855  13.100,-13.083
                   c  5.118,  5.104  13.416,  5.104  18.513,  0.000
                   c  5.101, -5.120   5.101,-13.410   0.000,-18.515
                   c  7.216,  0.000  13.081, -5.869  13.081,-13.098
                   c  0.000, -7.227  -5.865,-13.085 -13.081,-13.085
                   c  5.101, -5.119   5.101,-13.406   0.000,-18.524
                   C 76.502, 13.275  68.206, 13.275  63.086, 18.385 z"/>
    
            <path
                id="white-star"
                fill="#FFFFFF"
                d="M 55.003, 23.405
                   v 14.488
                   L 65.260, 27.640
                   c  0.000, -1.812  0.691,-3.618   2.066, -5.005
                   c  2.780, -2.771  7.275,-2.771  10.024,  0.000
                   c  2.771,  2.766  2.771, 7.255   0.000, 10.027
                   c -1.377,  1.375 -3.195, 2.072  -5.015,  2.072
                   L 62.101, 44.982
                   H 76.590
                   c  1.290, -1.280  3.054,-2.076   5.011, -2.076
                   c  3.900,  0.000  7.078, 3.179   7.078,  7.087
                   c  0.000,  3.906 -3.178, 7.088  -7.078,  7.088
                   c -1.957,  0.000 -3.721,-0.798  -5.011, -2.072
                   H 62.100
                   l 10.229, 10.244
                   c  1.824,  0.000  3.642, 0.694   5.015,  2.086
                   c  2.774,  2.759  2.774, 7.250   0.000, 10.010
                   c -2.750,  2.774 -7.239, 2.774 -10.025,  0.000
                   c -1.372, -1.372 -2.064,-3.192  -2.064, -5.003
                   L 55.000, 62.094
                   v 14.499
                   c  1.271,  1.276  2.084, 3.054   2.084,  5.013
                   c  0.000,  3.906 -3.177, 7.077  -7.098,  7.077
                   c -3.919,  0.000 -7.094,
```

The WikEM seems to just be a jpeg/jfif? @kelson42  I would say if we recreated the zim file now this issue would disappear

**Comment by kelson42** [comment] 2019-12-17 13:58
OK, I close the ticket. Seems to work fine with proper SVG files.

**Closed by kelson42** 2019-12-17 13:58 UTC
Labels: bug
